src/audio.h File Reference - Paper Mario Documentation
audio.h File Reference
Data Structures
union UnkField
union X16
struct UnkAl1
struct UnkAl4
struct UnkLen18
struct UnkAl7C
struct UnkAl0
struct UnkAlA
struct UnkAlAC
struct UnkAl6CC
struct UnkAlC
struct UnkAl30
struct UnkAl48
struct UnkTemp2
struct UnkAl19E0Sub
struct UnkAl19E0Sub2
struct UnkAl19E0Sub3
struct UnkAl19E0
struct UnkAl60
struct UnkAl24
struct UnkAlA9C
union Q32
struct UnkAl8
struct UnkAl1E4
struct UnkAl834
Typedefs
typedef void(* UnkFuncAl) ()
Functions
void al_LoadBKHeaders (UnkAl19E0 *arg0, ALHeap *arg1)
void func_8004B440 (UnkAl6CC *, u8, u8, UnkAl19E0 *, u8)
void func_8004B62C (UnkAl6CC *)
void func_8004B698 (UnkAl6CC *)
void func_8004B6D8 (UnkAl6CC *, s32, s16, s16, u8)
void func_8004B748 (UnkAl6CC *)
s32 func_8004B9E4 (UnkAl6CC *, s32)
void func_8004BA54 (UnkAl6CC *, s32)
s16 func_8004C444 (UnkAl6CC *)
void func_8004D510 (UnkAlA9C *)
UnkAlA9C * func_8004D794 (s32)
s32 func_8004DA0C (s32)
void func_8004DAA8 (UnkAlA9C *)
void func_8004DFD4 (UnkAl19E0 *)
void func_8004E158 (UnkAlA9C *, s32, s32, UnkAl19E0 *)
void func_8004E3A4 (UnkAlA9C *)
void func_8004E444 (UnkAlA9C *)
s16 func_8004E4B8 (UnkAlA9C *)
void func_8004FBBC (UnkAlA9C *, UnkAl60 *)
s32 func_8004FC08 (UnkAlA9C *, u32)
void func_8004FCB4 (UnkAlA9C *, UnkAl60 *)
void func_8004FCE4 (UnkAlA9C *, UnkAl60 *)
void func_8004FD04 (UnkAlA9C *, UnkAl60 *)
void func_8004FD38 (UnkAlA9C *, UnkAl60 *)
void func_8004FD94 (UnkAlA9C *, UnkAl60 *)
void func_8004FE10 (UnkAlA9C *, UnkAl60 *)
void func_8004FE6C (UnkAlA9C *, UnkAl60 *)
void func_8004FEB0 (UnkAlA9C *, UnkAl60 *)
void func_8004FED0 (UnkAlA9C *, UnkAl60 *)
void func_8004FF3C (UnkAlA9C *, UnkAl60 *)
void func_8004FF58 (UnkAlA9C *, UnkAl60 *)
void func_8004FF70 (UnkAlA9C *, UnkAl60 *)
void func_8004FF88 (UnkAlA9C *, UnkAl60 *)
void func_8004FFA8 (UnkAlA9C *, UnkAl60 *)
void func_8004FFB4 (UnkAlA9C *, UnkAl60 *)
void func_8004FFC8 (UnkAlA9C *, UnkAl60 *)
void func_8004FFE4 (UnkAlA9C *, UnkAl60 *)
void func_8004FFF0 (UnkAlA9C *, UnkAl60 *)
void func_8004FFFC (UnkAlA9C *, UnkAl60 *)
void func_80050004 (UnkAlA9C *, UnkAl60 *)
void func_80050020 (UnkAlA9C *, UnkAl60 *)
void func_80050128 (UnkAlA9C *, UnkAl60 *)
void func_8005015C (UnkAlA9C *, UnkAl60 *)
void func_80050184 (UnkAlA9C *, UnkAl60 *)
void func_800501A8 (UnkAlA9C *, UnkAl60 *)
void func_800502F0 (UnkAlA9C *, UnkAl60 *)
void func_80050560 (UnkAlA9C *, UnkAl60 *)
s32 func_80056068 (s32, u8)
s32 func_800506C8 (s32, s32)
s32 func_80050C30 (u32)
void func_80050D50 (UnkAl1E4 *)
void func_800511BC (UnkAl834 *)
void func_80051334 (UnkAl834 *, UnkAl1E4 *)
void func_80051434 (UnkAl834 *, UnkAl1E4 *)
void func_800521E8 (UnkAl834 *, UnkAl1E4 *)
void func_800522A8 (UnkAl834 *, UnkAl1E4 *)
void func_8005232C (UnkAl834 *, UnkAl1E4 *)
void func_800525A0 (UnkAl19E0 *)
void func_80052614 (UnkAl19E0 *)
void func_80052660 (UnkAl19E0 *)
void func_80052B44 (UnkAl48 *)
void func_80052BF8 (UnkAl48 *, s32 *)
void func_800532F4 (UnkAl30 *)
void func_80053370 (UnkAlC *)
void func_800533A8 (UnkAl4 *)
void func_80053654 (UnkAl19E0 *)
void func_80053974 (UnkAl1 *, s32, s32, s16)
void func_80053A18 (UnkAl1 *)
void func_80053A28 (UnkAl1 *)
void func_80053A98 (u8, u16, s32)
void func_80053AEC (UnkAl1 *, s16)
void func_80053BA8 (UnkAl1 *)
s32 func_80053BE8 (UnkAl19E0 *, s32, s32, s32 *)
void func_80054CE0 (s32, s32)
void func_8005610C (void)
void func_80055110 (UnkAlA9C *)
s32 func_80055FF0 (s32, s32)
s32 func_8005600C (s32, s32)
s32 func_80056028 (s32, u8)
s32 func_80056044 (s32, u8)
void func_8005608C (s32 *, s32 *)
void func_800560A8 (void)
void func_80056144 (UnkFuncAl, s32)
void func_8005615C (void)
void func_80056180 (void)
void func_800561A4 (s32)
void func_800561C4 (s32)
void func_800561E4 (s32)
void func_80056204 (void)
void func_80056228 (void)
void func_80056D44 (s16)
s16 func_80056D50 (void)
void func_80056D78 (u8, u16)
void func_80056DCC (u8, u8)
void func_80056EC0 (u8, s8)
void func_80056EE8 (u8)
void func_80056FA4 (u8, u8, s32, f32, s16, u8, u8, s32)
void func_80057224 (u8, UnkAl30 *)
void func_80057344 (u8, f32)
void func_8005736C (u8, s16, s32, u8, u8)
void func_80057548 (u8, u8, u8)
void func_800576EC (u8, s32, s32)
void func_80057DC8 (s32)
void func_80057E08 (u8)
void func_80057E5C (u8)
void func_80057EB0 (void)
void func_80057ED0 (s16)
void al_LoadINIT (UnkAl19E0 *, s32, ALHeap *)
s32 al_CopyFileTableEntry (u16, s32, s32 *)
void al_LoadPER (UnkAl19E0 *, s32 *)
void al_LoadPRG (UnkAl19E0 *, s32 *)
void al_DmaCopy (s32, s32 *, s32)
void * alHeapAlloc (ALHeap *heap, s32 arg1, s32 size)
Variables
u8 D_80078181
s32 D_80078190
s32 D_800781D0
s32 D_80078290
s32 D_800782F8
s32 D_80078348
s32 D_80078320
s32 D_80078544
s32 D_800785A0
s32 D_80078DB0
u16 D_80078DB6
UnkAl0 * D_80078E50
UnkAl0 * D_80078E54
s8 D_80078E58
s16 D_80078E5A
s8 D_80078E5C
s32 * D_8007F1F8
UnkAl19E0 * D_8009A5C0
UnkAlA9C * D_8009A5CC
UnkAlA9C * D_8009A5FC
UnkFuncAl D_8009A5E8
UnkAl834 * D_8009A628
UnkAl6CC * D_8009A640
UnkAlA9C * D_8009A664
u16 D_800A0F50
s32 * D_800A3FE0
s32 * D_800A3FE4
s32 D_800A3FE8
s8 D_800A3FEC
s16 D_800A3FEE
s32 D_800A3FF0
Typedef Documentation
UnkFuncAl
typedef void(* UnkFuncAl) ()
Definition at line 9 of file audio.h.
Function Documentation
al_LoadBKHeaders()
void al_LoadBKHeaders (UnkAl19E0 * arg0, ALHeap * arg1)
Definition at line 18 of file code_303c0_len_3e10.c.
Referenced by func_80052E5C().
func_8004B440()
void func_8004B440 (UnkAl6CC * arg0, u8 arg1, u8 arg2, UnkAl19E0 * arg3, u8 arg4)
Definition at line 4 of file code_26840_len_20d0.c.
Referenced by func_80052E5C().
func_8004B62C()
void func_8004B62C (UnkAl6CC * arg0)
Definition at line 86 of file code_26840_len_20d0.c.
Referenced by func_80052E5C().
func_8004B698()
void func_8004B698 (UnkAl6CC * arg0)
Definition at line 88 of file code_26840_len_20d0.c.
Referenced by func_8004B440().
func_8004B6D8()
void func_8004B6D8 (UnkAl6CC * arg0, s32 arg1, s16 arg2, s16 arg3, u8 arg4)
Definition at line 105 of file code_26840_len_20d0.c.
Referenced by func_800551E0(), func_80055240(), func_800552D0(), func_80055330(), func_800553C0(), and func_80055408().
func_8004B748()
void func_8004B748 (UnkAl6CC * arg0)
Definition at line 132 of file code_26840_len_20d0.c.
Referenced by func_800535C0().
func_8004B9E4()
s32 func_8004B9E4 (UnkAl6CC * arg0, s32 arg1)
Definition at line 134 of file code_26840_len_20d0.c.
Referenced by func_8004B440(), and func_80054D74().
func_8004BA54()
void func_8004BA54 (UnkAl6CC * arg0, s32 arg1)
Definition at line 154 of file code_26840_len_20d0.c.
Referenced by func_8004B440(), func_80056204(), and func_80056228().
func_8004C444()
s16 func_8004C444 (UnkAl6CC * arg0)
Definition at line 176 of file code_26840_len_20d0.c.
Referenced by func_800533D0().
func_8004D510()
void func_8004D510 (UnkAlA9C * arg0)
Definition at line 3 of file code_28910_len_5090.c.
Referenced by func_800535C0().
func_8004D794()
UnkAlA9C* func_8004D794 (s32 arg0)
Definition at line 8 of file code_28910_len_5090.c.
Referenced by func_8004DA0C().
func_8004DA0C()
s32 func_8004DA0C (s32 arg0)
Definition at line 25 of file code_28910_len_5090.c.
Referenced by func_800559C4().
func_8004DAA8()
void func_8004DAA8 (UnkAlA9C * arg0)
Definition at line 52 of file code_28910_len_5090.c.
Referenced by func_8004DA0C(), and func_8004E3A4().
func_8004DFD4()
void func_8004DFD4 (UnkAl19E0 * arg0)
Definition at line 73 of file code_28910_len_5090.c.
Referenced by func_800533D0().
func_8004E158()
void func_8004E158 (UnkAlA9C * arg0, s32 arg1, s32 arg2, UnkAl19E0 * arg3)
Definition at line 77 of file code_28910_len_5090.c.
Referenced by func_80052E5C().
func_8004E3A4()
void func_8004E3A4 (UnkAlA9C * arg0)
Definition at line 158 of file code_28910_len_5090.c.
Referenced by func_800533D0().
func_8004E444()
void func_8004E444 (UnkAlA9C * arg0)
Definition at line 179 of file code_28910_len_5090.c.
Referenced by func_8004E3A4(), and func_800533D0().
func_8004E4B8()
s16 func_8004E4B8 (UnkAlA9C * arg0)
Definition at line 181 of file code_28910_len_5090.c.
Referenced by func_800533D0().
func_8004FBBC()
void func_8004FBBC (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 199 of file code_28910_len_5090.c.
func_8004FC08()
s32 func_8004FC08 (UnkAlA9C * arg0, u32 arg1)
Definition at line 212 of file code_28910_len_5090.c.
Referenced by func_8004FBBC(), and func_8004FD94().
func_8004FCB4()
void func_8004FCB4 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 227 of file code_28910_len_5090.c.
func_8004FCE4()
void func_8004FCE4 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 242 of file code_28910_len_5090.c.
func_8004FD04()
void func_8004FD04 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 246 of file code_28910_len_5090.c.
func_8004FD38()
void func_8004FD38 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 251 of file code_28910_len_5090.c.
func_8004FD94()
void func_8004FD94 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 264 of file code_28910_len_5090.c.
func_8004FE10()
void func_8004FE10 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 279 of file code_28910_len_5090.c.
func_8004FE6C()
void func_8004FE6C (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 301 of file code_28910_len_5090.c.
func_8004FEB0()
void func_8004FEB0 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 311 of file code_28910_len_5090.c.
func_8004FED0()
void func_8004FED0 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 324 of file code_28910_len_5090.c.
Referenced by func_8005083C().
func_8004FF3C()
void func_8004FF3C (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 350 of file code_28910_len_5090.c.
func_8004FF58()
void func_8004FF58 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 356 of file code_28910_len_5090.c.
func_8004FF70()
void func_8004FF70 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 361 of file code_28910_len_5090.c.
func_8004FF88()
void func_8004FF88 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 366 of file code_28910_len_5090.c.
func_8004FFA8()
void func_8004FFA8 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 370 of file code_28910_len_5090.c.
func_8004FFB4()
void func_8004FFB4 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 374 of file code_28910_len_5090.c.
func_8004FFC8()
void func_8004FFC8 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 379 of file code_28910_len_5090.c.
func_8004FFE4()
void func_8004FFE4 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 385 of file code_28910_len_5090.c.
func_8004FFF0()
void func_8004FFF0 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 389 of file code_28910_len_5090.c.
func_8004FFFC()
void func_8004FFFC (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 393 of file code_28910_len_5090.c.
func_80050004()
void func_80050004 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 397 of file code_28910_len_5090.c.
func_80050020()
void func_80050020 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 402 of file code_28910_len_5090.c.
func_80050128()
void func_80050128 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 404 of file code_28910_len_5090.c.
func_8005015C()
void func_8005015C (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 417 of file code_28910_len_5090.c.
func_80050184()
void func_80050184 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 424 of file code_28910_len_5090.c.
func_800501A8()
void func_800501A8 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 432 of file code_28910_len_5090.c.
func_800502F0()
void func_800502F0 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 434 of file code_28910_len_5090.c.
func_80050560()
void func_80050560 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 436 of file code_28910_len_5090.c.
func_80056068()
s32 func_80056068 (s32 arg0, u8 arg1)
Definition at line 410 of file code_303c0_len_3e10.c.
Referenced by func_8014AA54().
func_800506C8()
s32 func_800506C8 (s32 arg0, s32 arg1)
Definition at line 447 of file code_28910_len_5090.c.
Referenced by func_80056028(), func_80056044(), and func_80056068().
func_80050C30()
s32 func_80050C30 (u32 arg0)
Definition at line 473 of file code_28910_len_5090.c.
Referenced by func_80055464(), func_800554A4(), func_800554E8(), func_8005553C(), func_80055590(), func_800555E4(), func_80055618(), func_8005566C(), func_800556D0(), and func_80055718().
func_80050D50()
void func_80050D50 (UnkAl1E4 * arg0)
Definition at line 489 of file code_28910_len_5090.c.
Referenced by func_800511BC().
func_800511BC()
void func_800511BC (UnkAl834 * arg0)
Definition at line 507 of file code_28910_len_5090.c.
Referenced by func_800533D0().
func_80051334()
void func_80051334 (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 560 of file code_28910_len_5090.c.
Referenced by func_800511BC().
func_80051434()
void func_80051434 (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 562 of file code_28910_len_5090.c.
Referenced by func_800511BC().
func_800521E8()
void func_800521E8 (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 566 of file code_28910_len_5090.c.
Referenced by func_800511BC().
func_800522A8()
void func_800522A8 (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 568 of file code_28910_len_5090.c.
Referenced by func_800511BC().
func_8005232C()
void func_8005232C (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 570 of file code_28910_len_5090.c.
Referenced by func_800511BC().
func_800525A0()
void func_800525A0 (UnkAl19E0 * arg0)
Definition at line 4 of file code_2d9a0_len_890.c.
func_80052614()
void func_80052614 (UnkAl19E0 * arg0)
Definition at line 19 of file code_2d9a0_len_890.c.
Referenced by func_80052E5C().
func_80052660()
void func_80052660 (UnkAl19E0 * arg0)
Definition at line 37 of file code_2d9a0_len_890.c.
Referenced by func_800533D0().
func_80052B44()
void func_80052B44 (UnkAl48 * arg0)
Definition at line 39 of file code_2d9a0_len_890.c.
func_80052BF8()
void func_80052BF8 (UnkAl48 * arg0, s32 * arg1)
Definition at line 52 of file code_2d9a0_len_890.c.
Referenced by func_80053654().
func_800532F4()
void func_800532F4 (UnkAl30 * arg0)
Definition at line 142 of file code_2e230_len_2190.c.
Referenced by func_80052E5C().
func_80053370()
void func_80053370 (UnkAlC * arg0)
Definition at line 164 of file code_2e230_len_2190.c.
Referenced by func_80052E5C().
func_800533A8()
void func_800533A8 (UnkAl4 * arg0)
Definition at line 176 of file code_2e230_len_2190.c.
Referenced by func_80052E5C().
func_80053654()
void func_80053654 (UnkAl19E0 * arg0)
Definition at line 277 of file code_2e230_len_2190.c.
Referenced by func_800533D0().
func_80053974()
void func_80053974 (UnkAl1 * arg0, s32 arg1, s32 arg2, s16 arg3)
Definition at line 369 of file code_2e230_len_2190.c.
Referenced by func_8004B440().
func_80053A18()
void func_80053A18 (UnkAl1 * arg0)
Definition at line 371 of file code_2e230_len_2190.c.
Referenced by func_8004DAA8().
func_80053A28()
void func_80053A28 (UnkAl1 * arg0)
Definition at line 377 of file code_2e230_len_2190.c.
Referenced by func_800533D0().
func_80053A98()
void func_80053A98 (u8 arg0, u16 arg1, s32 arg2)
Definition at line 392 of file code_2e230_len_2190.c.
Referenced by func_8004B440(), and func_800533D0().
func_80053AEC()
void func_80053AEC (UnkAl1 * arg0, s16 arg1)
Definition at line 404 of file code_2e230_len_2190.c.
Referenced by func_8004E158().
func_80053BA8()
void func_80053BA8 (UnkAl1 * arg0)
Definition at line 428 of file code_2e230_len_2190.c.
Referenced by func_800533D0().
func_80053BE8()
s32 func_80053BE8 (UnkAl19E0 * arg0, s32 arg1, s32 arg2, s32 * arg3)
Definition at line 439 of file code_2e230_len_2190.c.
Referenced by func_8004FE6C().
func_80054CE0()
void func_80054CE0 (s32 arg0, s32 arg1)
Definition at line 496 of file code_2e230_len_2190.c.
Referenced by func_800561A4(), and func_800561C4().
func_8005610C()
void func_8005610C (void)
Definition at line 427 of file code_303c0_len_3e10.c.
Referenced by func_80052E5C(), and func_800535C0().
func_80055110()
void func_80055110 (UnkAlA9C * arg0)
Definition at line 27 of file code_303c0_len_3e10.c.
Referenced by func_8004E158().
func_80055FF0()
s32 func_80055FF0 (s32 arg0, s32 arg1)
Definition at line 394 of file code_303c0_len_3e10.c.
func_8005600C()
s32 func_8005600C (s32 arg0, s32 arg1)
Definition at line 398 of file code_303c0_len_3e10.c.
func_80056028()
s32 func_80056028 (s32 arg0, u8 arg1)
Definition at line 402 of file code_303c0_len_3e10.c.
Referenced by func_8014AA54().
func_80056044()
s32 func_80056044 (s32 arg0, u8 arg1)
Definition at line 406 of file code_303c0_len_3e10.c.
Referenced by func_8014AA54().
func_8005608C()
void func_8005608C (s32 * arg0, s32 * arg1)
Definition at line 414 of file code_303c0_len_3e10.c.
func_800560A8()
void func_800560A8 (void)
Definition at line 421 of file code_303c0_len_3e10.c.
func_80056144()
void func_80056144 (UnkFuncAl arg0, s32 arg1)
Definition at line 429 of file code_303c0_len_3e10.c.
func_8005615C()
void func_8005615C (void)
Definition at line 433 of file code_303c0_len_3e10.c.
Referenced by step_init_state().
func_80056180()
void func_80056180 (void)
Definition at line 438 of file code_303c0_len_3e10.c.
Referenced by step_init_state().
func_800561A4()
void func_800561A4 (s32 arg0)
Definition at line 443 of file code_303c0_len_3e10.c.
Referenced by func_8014A498().
func_800561C4()
void func_800561C4 (s32 arg0)
Definition at line 447 of file code_303c0_len_3e10.c.
func_800561E4()
void func_800561E4 (s32 arg0)
Definition at line 451 of file code_303c0_len_3e10.c.
func_80056204()
void func_80056204 (void)
Definition at line 455 of file code_303c0_len_3e10.c.
func_80056228()
void func_80056228 (void)
Definition at line 459 of file code_303c0_len_3e10.c.
Referenced by init_demo_data().
func_80056D44()
void func_80056D44 (s16 arg0)
Definition at line 32 of file code_31650.c.
Referenced by func_8004B328().
func_80056D50()
s16 func_80056D50 (void)
Definition at line 36 of file code_31650.c.
Referenced by func_8004B328().
func_80056D78()
void func_80056D78 (u8 arg0, u16 arg1)
Definition at line 49 of file code_31650.c.
Referenced by func_80053A98().
func_80056DCC()
void func_80056DCC (u8 arg0, u8 arg1)
Definition at line 61 of file code_31650.c.
Referenced by func_80053654().
func_80056EC0()
void func_80056EC0 (u8 arg0, s8 arg1)
Definition at line 71 of file code_31650.c.
Referenced by func_80052E5C().
func_80056EE8()
void func_80056EE8 (u8 arg0)
Definition at line 77 of file code_31650.c.
Referenced by func_800525A0(), and func_80053654().
func_80056FA4()
void func_80056FA4 (u8 arg0, u8 arg1, s32 arg2, f32 arg3, s16 arg4, u8 arg5, u8 arg6, s32 arg7)
Definition at line 86 of file code_31650.c.
Referenced by func_80053654().
func_80057224()
void func_80057224 (u8 arg0, UnkAl30 * arg1)
Definition at line 88 of file code_31650.c.
Referenced by func_80052E5C().
func_80057344()
void func_80057344 (u8 arg0, f32 arg1)
Definition at line 90 of file code_31650.c.
Referenced by func_80053654().
func_8005736C()
void func_8005736C (u8 arg0, s16 arg1, s32 arg2, u8 arg3, u8 arg4)
Definition at line 96 of file code_31650.c.
Referenced by func_80053654().
func_80057548()
void func_80057548 (u8 arg0, u8 arg1, u8 arg2)
Definition at line 98 of file code_31650.c.
Referenced by func_80053654().
func_800576EC()
void func_800576EC (u8 arg0, s32 arg1, s32 arg2)
Definition at line 100 of file code_31650.c.
Referenced by func_80053888(), and func_800538C4().
func_80057DC8()
void func_80057DC8 (s32 arg0)
Definition at line 146 of file code_31650.c.
Referenced by func_80053654().
func_80057E08()
void func_80057E08 (u8 arg0)
Definition at line 160 of file code_31650.c.
Referenced by func_80053654().
func_80057E5C()
void func_80057E5C (u8 arg0)
Definition at line 175 of file code_31650.c.
Referenced by func_80053654().
func_80057EB0()
void func_80057EB0 (void)
Definition at line 190 of file code_31650.c.
Referenced by func_80053654().
func_80057ED0()
void func_80057ED0 (s16 arg0)
Definition at line 196 of file code_31650.c.
Referenced by func_80052E5C().
al_LoadINIT()
void al_LoadINIT (UnkAl19E0 * arg0, s32 arg1, ALHeap * arg2)
Definition at line 471 of file code_2e230_len_2190.c.
Referenced by func_80052E5C().
al_CopyFileTableEntry()
s32 al_CopyFileTableEntry (u16 arg0, s32 arg1, s32 * arg2)
Definition at line 473 of file code_2e230_len_2190.c.
Referenced by func_80052E5C().
al_LoadPER()
void al_LoadPER (UnkAl19E0 * arg0, s32 * arg1)
Definition at line 475 of file code_2e230_len_2190.c.
Referenced by func_80052E5C().
al_LoadPRG()
void al_LoadPRG (UnkAl19E0 * arg0, s32 * arg1)
Definition at line 477 of file code_2e230_len_2190.c.
Referenced by func_80052E5C().
al_DmaCopy()
void al_DmaCopy (s32 arg0, s32 * arg1, s32 arg2)
Definition at line 507 of file code_2e230_len_2190.c.
Referenced by func_80052E5C().
alHeapAlloc()
void* alHeapAlloc (ALHeap * heap, s32 arg1, s32 size)
Definition at line 213 of file code_31650.c.
Referenced by func_80052E5C().
Variable Documentation
D_80078181
u8 D_80078181 extern
Definition at line 13 of file code_25f00_len_940.c.
Referenced by func_80056D5C().
D_80078190
s32 D_80078190 extern
Referenced by func_800532F4().
D_800781D0
s32 D_800781D0 extern
Referenced by func_800532F4().
D_80078290
s32 D_80078290 extern
Referenced by func_8004B440().
D_800782F8
s32 D_800782F8 extern
Referenced by func_8004B440().
D_80078348
s32 D_80078348 extern
Referenced by func_8004B440().
D_80078320
s32 D_80078320 extern
Referenced by func_8004B440().
D_80078544
s32 D_80078544 extern
Referenced by func_800532F4().
D_800785A0
s32 D_800785A0 extern
D_80078DB0
s32 D_80078DB0 extern
Definition at line 4 of file code_303c0_len_3e10.c.
Referenced by func_800533D0(), and func_80055050().
D_80078DB6
u16 D_80078DB6 extern
Definition at line 6 of file code_303c0_len_3e10.c.
Referenced by func_80055760(), func_800557CC(), and func_80055848().
D_80078E50
UnkAl0* D_80078E50 extern
Definition at line 4 of file code_31650.c.
Referenced by func_800565A4().
D_80078E54
UnkAl0* D_80078E54 extern
Definition at line 5 of file code_31650.c.
Referenced by func_80052E5C(), func_80056D78(), func_80056DA4(), func_80056DCC(), func_80056EC0(), func_80056F78(), func_80057344(), func_80057B64(), func_80057B8C(), func_80057BB4(), func_80057BDC(), func_80057C04(), and func_80057C2C().
D_80078E58
s8 D_80078E58 extern
Definition at line 6 of file code_31650.c.
Referenced by func_80056D34().
D_80078E5A
s16 D_80078E5A extern
Definition at line 7 of file code_31650.c.
Referenced by func_80056D44(), and func_80056D50().
D_80078E5C
s8 D_80078E5C extern
Definition at line 8 of file code_31650.c.
Referenced by func_80056D5C().
D_8007F1F8
s32* D_8007F1F8 extern
Referenced by func_8004B9E4().
D_8009A5C0
UnkAl19E0* D_8009A5C0 extern
Referenced by func_80052E30(), func_80052E5C(), func_800533D0(), func_800535C0(), func_80053F64(), func_80054C4C(), func_8005608C(), func_800560A8(), and func_80056144().
D_8009A5CC
UnkAlA9C* D_8009A5CC extern
Referenced by func_80052E5C().
D_8009A5FC
UnkAlA9C* D_8009A5FC extern
Referenced by func_8004D794(), func_80052E5C(), func_800533D0(), func_800535C0(), and func_80054248().
D_8009A5E8
UnkFuncAl D_8009A5E8 extern
Referenced by func_800535C0().
D_8009A628
UnkAl834* D_8009A628 extern
Referenced by func_80050C30(), func_80050C54(), func_80052E5C(), and func_800533D0().
D_8009A640
UnkAl6CC* D_8009A640 extern
Referenced by func_80052E5C(), func_800533D0(), func_800535C0(), func_80054248(), func_80054D74(), func_800551E0(), func_80055240(), func_800552D0(), func_80055330(), func_800553C0(), func_800553F4(), func_80055408(), func_80056204(), and func_80056228().
D_8009A664
UnkAlA9C* D_8009A664 extern
Referenced by func_8004D794(), func_80052E5C(), func_800533D0(), func_800535C0(), and func_80054248().
D_800A0F50
u16 D_800A0F50 extern
Referenced by func_8004B328().
D_800A3FE0
s32* D_800A3FE0 extern
Referenced by func_80057E08(), func_80057E5C(), and func_80057ED0().
D_800A3FE4
s32* D_800A3FE4 extern
Referenced by func_80057E08(), func_80057E5C(), and func_80057ED0().
D_800A3FE8
s32 D_800A3FE8 extern
Referenced by func_80057E08(), func_80057E5C(), func_80057EB0(), and func_80057ED0().
D_800A3FEC
s8 D_800A3FEC extern
Referenced by func_80057E08(), func_80057E5C(), func_80057EB0(), and func_80057ED0().
D_800A3FEE
s16 D_800A3FEE extern
Referenced by func_80057DC8(), func_80057E08(), func_80057E5C(), func_80057EB0(), and func_80057ED0().
D_800A3FF0
s32 D_800A3FF0 extern
Referenced by func_80057DC8().