src/code_fee30_len_2d60.c File Reference - Paper Mario Documentation
code_fee30_len_2d60.c File Reference
Functions
s32 func_802DBD40 ()
s32 func_802DBD8C ()
s32 func_802DBDBC ()
s32 func_802DBE78 ()
s32 func_802DBFC0 ()
s32 func_802DC008 ()
s32 spr_appendMDL_component ()
s32 spr_transform_point ()
s32 spr_draw_component ()
s32 _spr_sign_extend_12bit (u16 val)
s32 _spr_sign_extend_16bit (u16 val)
s32 update_component ()
s32 func_802DD634 ()
s32 func_802DD6DC ()
s32 func_802DD7B0 ()
s32 func_802DD820 ()
s32 set_anim_timescale ()
s32 func_802DD89C ()
s32 func_802DD8F8 ()
void func_802DDA60 (void)
s32 func_802DDA84 (void)
s32 func_802DDA8C ()
s32 render_sprite ()
s32 func_802DDEC4 ()
s32 func_802DDEE4 ()
s32 func_802DDFF8 ()
s32 func_802DE044 ()
s32 func_802DE0C0 ()
s32 func_802DE0EC ()
s32 func_802DE2AC ()
s32 func_802DE3D8 ()
s32 func_802DE5C8 ()
s32 func_802DE5E8 ()
s32 func_802DE748 ()
s32 func_802DE780 ()
s32 func_802DE894 ()
s32 func_802DE8DC ()
s32 func_802DE9D8 ()
s32 func_802DEA40 ()
s32 func_802DEA6C ()
Function Documentation
func_802DBD40()
s32 func_802DBD40 ()
Definition at line 3 of file code_fee30_len_2d60.c.
func_802DBD8C()
s32 func_802DBD8C ()
Definition at line 5 of file code_fee30_len_2d60.c.
func_802DBDBC()
s32 func_802DBDBC ()
Definition at line 7 of file code_fee30_len_2d60.c.
func_802DBE78()
s32 func_802DBE78 ()
Definition at line 9 of file code_fee30_len_2d60.c.
func_802DBFC0()
s32 func_802DBFC0 ()
Definition at line 11 of file code_fee30_len_2d60.c.
Referenced by func_802DDA60().
func_802DC008()
s32 func_802DC008 ()
Definition at line 13 of file code_fee30_len_2d60.c.
spr_appendMDL_component()
s32 spr_appendMDL_component ()
Definition at line 15 of file code_fee30_len_2d60.c.
spr_transform_point()
s32 spr_transform_point ()
Definition at line 17 of file code_fee30_len_2d60.c.
spr_draw_component()
s32 spr_draw_component ()
Definition at line 19 of file code_fee30_len_2d60.c.
_spr_sign_extend_12bit()
s32 _spr_sign_extend_12bit (u16 val)
Definition at line 21 of file code_fee30_len_2d60.c.
_spr_sign_extend_16bit()
s32 _spr_sign_extend_16bit (u16 val)
Definition at line 31 of file code_fee30_len_2d60.c.
update_component()
s32 update_component ()
Definition at line 41 of file code_fee30_len_2d60.c.
func_802DD634()
s32 func_802DD634 ()
Definition at line 43 of file code_fee30_len_2d60.c.
func_802DD6DC()
s32 func_802DD6DC ()
Definition at line 45 of file code_fee30_len_2d60.c.
func_802DD7B0()
s32 func_802DD7B0 ()
Definition at line 47 of file code_fee30_len_2d60.c.
func_802DD820()
s32 func_802DD820 ()
Definition at line 49 of file code_fee30_len_2d60.c.
set_anim_timescale()
s32 set_anim_timescale ()
Definition at line 51 of file code_fee30_len_2d60.c.
func_802DD89C()
s32 func_802DD89C ()
Definition at line 53 of file code_fee30_len_2d60.c.
func_802DD8F8()
s32 func_802DD8F8 ()
Definition at line 55 of file code_fee30_len_2d60.c.
Referenced by load_engine_data(), and step_init_state().
func_802DDA60()
void func_802DDA60 (void)
Definition at line 57 of file code_fee30_len_2d60.c.
func_802DDA84()
s32 func_802DDA84 (void)
Definition at line 62 of file code_fee30_len_2d60.c.
func_802DDA8C()
s32 func_802DDA8C ()
Definition at line 66 of file code_fee30_len_2d60.c.
render_sprite()
s32 render_sprite ()
Definition at line 68 of file code_fee30_len_2d60.c.
func_802DDEC4()
s32 func_802DDEC4 ()
Definition at line 70 of file code_fee30_len_2d60.c.
func_802DDEE4()
s32 func_802DDEE4 ()
Definition at line 72 of file code_fee30_len_2d60.c.
Referenced by func_800E6860().
func_802DDFF8()
s32 func_802DDFF8 ()
Definition at line 74 of file code_fee30_len_2d60.c.
Referenced by func_802E8D74(), and player_enter_blue_pipe().
func_802DE044()
s32 func_802DE044 ()
Definition at line 76 of file code_fee30_len_2d60.c.
func_802DE0C0()
s32 func_802DE0C0 ()
Definition at line 78 of file code_fee30_len_2d60.c.
func_802DE0EC()
s32 func_802DE0EC ()
Definition at line 80 of file code_fee30_len_2d60.c.
func_802DE2AC()
s32 func_802DE2AC ()
Definition at line 82 of file code_fee30_len_2d60.c.
func_802DE3D8()
s32 func_802DE3D8 ()
Definition at line 84 of file code_fee30_len_2d60.c.
func_802DE5C8()
s32 func_802DE5C8 ()
Definition at line 86 of file code_fee30_len_2d60.c.
func_802DE5E8()
s32 func_802DE5E8 ()
Definition at line 88 of file code_fee30_len_2d60.c.
func_802DE748()
s32 func_802DE748 ()
Definition at line 90 of file code_fee30_len_2d60.c.
func_802DE780()
s32 func_802DE780 ()
Definition at line 92 of file code_fee30_len_2d60.c.
func_802DE894()
s32 func_802DE894 ()
Definition at line 94 of file code_fee30_len_2d60.c.
Referenced by EnableActorGlow().
func_802DE8DC()
s32 func_802DE8DC ()
Definition at line 96 of file code_fee30_len_2d60.c.
func_802DE9D8()
s32 func_802DE9D8 ()
Definition at line 98 of file code_fee30_len_2d60.c.
func_802DEA40()
s32 func_802DEA40 ()
Definition at line 100 of file code_fee30_len_2d60.c.
func_802DEA6C()
s32 func_802DEA6C ()
Definition at line 102 of file code_fee30_len_2d60.c.