src/code_106EF0.c File Reference - Paper Mario Documentation
code_106EF0.c File Reference
Functions
f32 func_802E5670 (struct802E4B10 *arg0, s32 arg1)
void func_802E5690 (s32 entityIndex)
s32 func_802E56D0 (Entity *entity)
void func_802E56EC (Entity *entity)
void func_802E578C (Entity *entity)
void func_802E57E4 (Entity *entity)
void func_802E5800 (Entity *entity)
void func_802E581C (Entity *entity)
s32 func_802E586C ()
void func_802E5E50 (Entity *entity)
void func_802E5F50 (Entity *entity)
void func_802E5F7C (Entity *entity)
Variables
StaticEntityData D_802EA934
Function Documentation
func_802E5670()
f32 func_802E5670 (struct802E4B10 * arg0, s32 arg1)
Definition at line 3 of file code_106EF0.c.
func_802E5690()
void func_802E5690 (s32 entityIndex)
Definition at line 13 of file code_106EF0.c.
func_802E56D0()
s32 func_802E56D0 (Entity * entity)
Definition at line 28 of file code_106EF0.c.
func_802E56EC()
void func_802E56EC (Entity * entity)
Definition at line 34 of file code_106EF0.c.
func_802E578C()
void func_802E578C (Entity * entity)
Definition at line 54 of file code_106EF0.c.
Referenced by func_802E57E4(), and func_802E5800().
func_802E57E4()
void func_802E57E4 (Entity * entity)
Definition at line 64 of file code_106EF0.c.
func_802E5800()
void func_802E5800 (Entity * entity)
Definition at line 68 of file code_106EF0.c.
func_802E581C()
void func_802E581C (Entity * entity)
Definition at line 72 of file code_106EF0.c.
Referenced by func_802E5E50().
func_802E586C()
s32 func_802E586C ()
Definition at line 82 of file code_106EF0.c.
Referenced by func_802E5F50(), and func_802E5F7C().
func_802E5E50()
void func_802E5E50 (Entity * entity)
Definition at line 84 of file code_106EF0.c.
func_802E5F50()
void func_802E5F50 (Entity * entity)
Definition at line 110 of file code_106EF0.c.
func_802E5F7C()
void func_802E5F7C (Entity * entity)
Definition at line 119 of file code_106EF0.c.
Variable Documentation
D_802EA934
StaticEntityData D_802EA934 extern
Referenced by func_802E56EC().