src/code_111f0_len_860.c File Reference - Paper Mario Documentation
code_111f0_len_860.c File Reference
Functions
void func_80035E54 (void)
void func_80035DF0 (s16 arg0)
void func_80035E00 (void)
void func_80035E24 (void)
s32 func_80035EEC ()
void func_800360FC (void)
void func_80036130 (void)
s32 func_8003617C ()
void func_800363FC (void)
s32 func_80036430 (void)
s32 func_8003646C ()
void func_80036640 (void)
Function Documentation
func_80035E54()
void func_80035E54 (void)
Definition at line 22 of file code_111f0_len_860.c.
Referenced by func_80035E00(), and func_80035E24().
func_80035DF0()
void func_80035DF0 (s16 arg0)
Definition at line 5 of file code_111f0_len_860.c.
Referenced by func_80240000_9AE700().
func_80035E00()
void func_80035E00 (void)
Definition at line 11 of file code_111f0_len_860.c.
func_80035E24()
void func_80035E24 (void)
Definition at line 16 of file code_111f0_len_860.c.
func_80035EEC()
s32 func_80035EEC ()
Definition at line 38 of file code_111f0_len_860.c.
func_800360FC()
void func_800360FC (void)
Definition at line 40 of file code_111f0_len_860.c.
func_80036130()
void func_80036130 (void)
Definition at line 48 of file code_111f0_len_860.c.
func_8003617C()
s32 func_8003617C ()
Definition at line 63 of file code_111f0_len_860.c.
func_800363FC()
void func_800363FC (void)
Definition at line 65 of file code_111f0_len_860.c.
func_80036430()
s32 func_80036430 (void)
Definition at line 71 of file code_111f0_len_860.c.
func_8003646C()
s32 func_8003646C ()
Definition at line 83 of file code_111f0_len_860.c.
func_80036640()
void func_80036640 (void)
Definition at line 85 of file code_111f0_len_860.c.