src/code_ED510.c File Reference - Paper Mario Documentation
code_ED510.c File Reference
Functions
ApiStatus TranslateModel (ScriptInstance *script, s32 isInitialCall)
ApiStatus RotateModel (ScriptInstance *script, s32 isInitialCall)
ApiStatus ScaleModel (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetModelIndex (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802C8EE4 (ScriptInstance *script, s32 isInitialCall)
ApiStatus CloneModel (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetModelCenter (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetTexPanner (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetModelFlag10 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802C90FC (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802C91A4 (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableTexPanning (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableModel (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetGroupEnabled (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetTexPanOffset (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802C9428 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802C94A0 (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetModelFlags (ScriptInstance *script, s32 isInitialCall)
s32 func_802C95A0 ()
ApiStatus func_802C971C (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802C9748 (ScriptInstance *script, s32 isInitialCall)
s32 TranslateGroup (ScriptInstance *script, s32 isInitialCall)
s32 RotateGroup (ScriptInstance *script, s32 isInitialCall)
s32 ScaleGroup (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802C9B40 (ScriptInstance *script, s32 isInitialCall)
s32 EnableGroup (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802C9C70 (ScriptInstance *script, s32 isInitialCall)
s32 modify_collider_family_flags ()
s32 ModifyColliderFlags (ScriptInstance *script, s32 isInitialCall)
s32 ResetFromLava (ScriptInstance *script, s32 isInitialCall)
s32 func_802C9FD4 ()
ApiStatus GetColliderCenter (ScriptInstance *script, s32 initialCall)
ApiStatus ParentColliderToModel (ScriptInstance *script, s32 isInitialCall)
ApiStatus UpdateColliderTransform (ScriptInstance *script, s32 isInitialCall)
s32 set_zone_enabled ()
s32 SetZoneEnabled ()
s32 goto_map ()
ApiStatus GotoMap (ScriptInstance *script, s32 isInitialCall)
ApiStatus GotoMapSpecial (ScriptInstance *script, s32 isInitialCall)
ApiStatus GotoMapByID (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetEntryID (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetMapID (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetLoadType (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetRenderMode (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlaySoundAtModel (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlaySoundAtCollider (ScriptInstance *script, s32 isInitialCall)
Function Documentation
TranslateModel()
ApiStatus TranslateModel (ScriptInstance * script, s32 isInitialCall)
Definition at line 5 of file code_ED510.c.
Referenced by N().
RotateModel()
ApiStatus RotateModel (ScriptInstance * script, s32 isInitialCall)
Definition at line 30 of file code_ED510.c.
ScaleModel()
ApiStatus ScaleModel (ScriptInstance * script, s32 isInitialCall)
Definition at line 55 of file code_ED510.c.
GetModelIndex()
ApiStatus GetModelIndex (ScriptInstance * script, s32 isInitialCall)
Definition at line 80 of file code_ED510.c.
func_802C8EE4()
ApiStatus func_802C8EE4 (ScriptInstance * script, s32 isInitialCall)
Definition at line 89 of file code_ED510.c.
CloneModel()
ApiStatus CloneModel (ScriptInstance * script, s32 isInitialCall)
Definition at line 98 of file code_ED510.c.
GetModelCenter()
ApiStatus GetModelCenter (ScriptInstance * script, s32 isInitialCall)
Definition at line 107 of file code_ED510.c.
SetTexPanner()
ApiStatus SetTexPanner (ScriptInstance * script, s32 isInitialCall)
Definition at line 124 of file code_ED510.c.
SetModelFlag10()
ApiStatus SetModelFlag10 (ScriptInstance * script, s32 isInitialCall)
Definition at line 135 of file code_ED510.c.
func_802C90FC()
ApiStatus func_802C90FC (ScriptInstance * script, s32 isInitialCall)
Definition at line 150 of file code_ED510.c.
func_802C91A4()
ApiStatus func_802C91A4 (ScriptInstance * script, s32 isInitialCall)
Definition at line 167 of file code_ED510.c.
EnableTexPanning()
ApiStatus EnableTexPanning (ScriptInstance * script, s32 isInitialCall)
Definition at line 176 of file code_ED510.c.
EnableModel()
ApiStatus EnableModel (ScriptInstance * script, s32 isInitialCall)
Definition at line 190 of file code_ED510.c.
SetGroupEnabled()
ApiStatus SetGroupEnabled (ScriptInstance * script, s32 isInitialCall)
Definition at line 204 of file code_ED510.c.
SetTexPanOffset()
ApiStatus SetTexPanOffset (ScriptInstance * script, s32 isInitialCall)
Definition at line 213 of file code_ED510.c.
func_802C9428()
ApiStatus func_802C9428 (ScriptInstance * script, s32 isInitialCall)
Definition at line 231 of file code_ED510.c.
func_802C94A0()
ApiStatus func_802C94A0 (ScriptInstance * script, s32 isInitialCall)
Definition at line 241 of file code_ED510.c.
SetModelFlags()
ApiStatus SetModelFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 252 of file code_ED510.c.
func_802C95A0()
s32 func_802C95A0 ()
Definition at line 272 of file code_ED510.c.
func_802C971C()
ApiStatus func_802C971C (ScriptInstance * script, s32 isInitialCall)
Definition at line 274 of file code_ED510.c.
func_802C9748()
ApiStatus func_802C9748 (ScriptInstance * script, s32 isInitialCall)
Definition at line 279 of file code_ED510.c.
TranslateGroup()
s32 TranslateGroup (ScriptInstance * script, s32 isInitialCall)
Definition at line 292 of file code_ED510.c.
RotateGroup()
s32 RotateGroup (ScriptInstance * script, s32 isInitialCall)
Definition at line 294 of file code_ED510.c.
ScaleGroup()
s32 ScaleGroup (ScriptInstance * script, s32 isInitialCall)
Definition at line 296 of file code_ED510.c.
func_802C9B40()
ApiStatus func_802C9B40 (ScriptInstance * script, s32 isInitialCall)
Definition at line 298 of file code_ED510.c.
EnableGroup()
s32 EnableGroup (ScriptInstance * script, s32 isInitialCall)
Definition at line 307 of file code_ED510.c.
func_802C9C70()
ApiStatus func_802C9C70 (ScriptInstance * script, s32 isInitialCall)
Definition at line 309 of file code_ED510.c.
modify_collider_family_flags()
s32 modify_collider_family_flags ()
Definition at line 319 of file code_ED510.c.
ModifyColliderFlags()
s32 ModifyColliderFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 321 of file code_ED510.c.
Referenced by N().
ResetFromLava()
s32 ResetFromLava (ScriptInstance * script, s32 isInitialCall)
Definition at line 323 of file code_ED510.c.
func_802C9FD4()
s32 func_802C9FD4 ()
Definition at line 325 of file code_ED510.c.
GetColliderCenter()
ApiStatus GetColliderCenter (ScriptInstance * script, s32 initialCall)
Definition at line 327 of file code_ED510.c.
ParentColliderToModel()
ApiStatus ParentColliderToModel (ScriptInstance * script, s32 isInitialCall)
Definition at line 339 of file code_ED510.c.
UpdateColliderTransform()
ApiStatus UpdateColliderTransform (ScriptInstance * script, s32 isInitialCall)
Definition at line 349 of file code_ED510.c.
set_zone_enabled()
s32 set_zone_enabled ()
Definition at line 354 of file code_ED510.c.
SetZoneEnabled()
s32 SetZoneEnabled ()
Definition at line 356 of file code_ED510.c.
goto_map()
s32 goto_map ()
Definition at line 358 of file code_ED510.c.
Referenced by GotoMap(), GotoMapByID(), and GotoMapSpecial().
GotoMap()
ApiStatus GotoMap (ScriptInstance * script, s32 isInitialCall)
Definition at line 360 of file code_ED510.c.
Referenced by N().
GotoMapSpecial()
ApiStatus GotoMapSpecial (ScriptInstance * script, s32 isInitialCall)
Definition at line 365 of file code_ED510.c.
GotoMapByID()
ApiStatus GotoMapByID (ScriptInstance * script, s32 isInitialCall)
Definition at line 370 of file code_ED510.c.
GetEntryID()
ApiStatus GetEntryID (ScriptInstance * script, s32 isInitialCall)
Definition at line 375 of file code_ED510.c.
Referenced by N().
GetMapID()
ApiStatus GetMapID (ScriptInstance * script, s32 isInitialCall)
Definition at line 380 of file code_ED510.c.
GetLoadType()
ApiStatus GetLoadType (ScriptInstance * script, s32 isInitialCall)
Definition at line 385 of file code_ED510.c.
SetRenderMode()
ApiStatus SetRenderMode (ScriptInstance * script, s32 isInitialCall)
Definition at line 390 of file code_ED510.c.
PlaySoundAtModel()
ApiStatus PlaySoundAtModel (ScriptInstance * script, s32 isInitialCall)
Definition at line 400 of file code_ED510.c.
Referenced by N().
PlaySoundAtCollider()
ApiStatus PlaySoundAtCollider (ScriptInstance * script, s32 isInitialCall)
Definition at line 414 of file code_ED510.c.