src/code_2e230_len_2190.c File Reference - Paper Mario Documentation
code_2e230_len_2190.c File Reference
Functions
void func_80052E30 (u8 index)
void func_80052E5C (s32 arg0)
void func_800532F4 (UnkAl30 *arg0)
void func_80053370 (UnkAlC *arg0)
void func_800533A8 (UnkAl4 *arg0)
void func_800533D0 (void)
void func_800535C0 (void)
void func_80053654 (UnkAl19E0 *arg0)
void func_80053888 (UnkAl48 *arg0, s32 arg1)
void func_800538C4 (UnkAl48 *arg0, s32 arg1)
s32 func_800538F8 ()
void func_80053974 (UnkAl1 *arg0, s32 arg1, s32 arg2, s16 arg3)
void func_80053A18 (UnkAl1 *arg0)
void func_80053A28 (UnkAl1 *arg0)
void func_80053A98 (u8 arg0, u16 arg1, s32 arg2)
void func_80053AC8 (UnkAl1 *arg0)
void func_80053AEC (UnkAl1 *arg0, s16 arg1)
void func_80053B04 (UnkAl1 *arg0, u32 arg1, s16 arg2)
void func_80053BA8 (UnkAl1 *arg0)
s32 func_80053BE8 (UnkAl19E0 *arg0, s32 arg1, s32 arg2, s32 *arg3)
s32 func_80053C58 ()
s32 func_80053CB4 ()
s32 func_80053CF8 ()
s32 func_80053E58 ()
UnkAlA9C * func_80053F64 (s32 arg0)
s32 func_80053F80 ()
UnkAlA9C * func_80054248 (u8 arg0)
void al_LoadINIT (UnkAl19E0 *arg0, s32 arg1, ALHeap *arg2)
s32 al_CopyFileTableEntry (u16 arg0, s32 arg1, s32 *arg2)
void al_LoadPER (UnkAl19E0 *arg0, s32 *arg1)
void al_LoadPRG (UnkAl19E0 *arg0, s32 *arg1)
s32 func_8005465C ()
s32 func_80054744 ()
s32 al_LoadBank ()
s32 func_800549F8 ()
s32 func_80054AA0 ()
s32 func_80054C4C (s32 arg0, s32 arg1)
s32 func_80054C84 ()
void func_80054CE0 (s32 arg0, s32 arg1)
s32 func_80054D74 (s32 arg0, s32 arg1)
s32 func_80054DA8 ()
void al_DmaCopy (s32 arg0, s32 *arg1, s32 arg2)
s32 func_80054E90 ()
s32 func_80054F48 ()
void al_CopyWords (s32 *src, s32 *dst, s32 num)
Function Documentation
func_80052E30()
void func_80052E30 (u8 index)
Definition at line 3 of file code_2e230_len_2190.c.
func_80052E5C()
void func_80052E5C (s32 arg0)
Definition at line 10 of file code_2e230_len_2190.c.
func_800532F4()
void func_800532F4 (UnkAl30 * arg0)
Definition at line 142 of file code_2e230_len_2190.c.
Referenced by func_80052E5C().
func_80053370()
void func_80053370 (UnkAlC * arg0)
Definition at line 164 of file code_2e230_len_2190.c.
Referenced by func_80052E5C().
func_800533A8()
void func_800533A8 (UnkAl4 * arg0)
Definition at line 176 of file code_2e230_len_2190.c.
Referenced by func_80052E5C().
func_800533D0()
void func_800533D0 (void)
Definition at line 186 of file code_2e230_len_2190.c.
func_800535C0()
void func_800535C0 (void)
Definition at line 257 of file code_2e230_len_2190.c.
func_80053654()
void func_80053654 (UnkAl19E0 * arg0)
Definition at line 277 of file code_2e230_len_2190.c.
Referenced by func_800533D0().
func_80053888()
void func_80053888 (UnkAl48 * arg0, s32 arg1)
Definition at line 351 of file code_2e230_len_2190.c.
func_800538C4()
void func_800538C4 (UnkAl48 * arg0, s32 arg1)
Definition at line 360 of file code_2e230_len_2190.c.
func_800538F8()
s32 func_800538F8 ()
Definition at line 367 of file code_2e230_len_2190.c.
func_80053974()
void func_80053974 (UnkAl1 * arg0, s32 arg1, s32 arg2, s16 arg3)
Definition at line 369 of file code_2e230_len_2190.c.
Referenced by func_8004B440().
func_80053A18()
void func_80053A18 (UnkAl1 * arg0)
Definition at line 371 of file code_2e230_len_2190.c.
Referenced by func_8004DAA8().
func_80053A28()
void func_80053A28 (UnkAl1 * arg0)
Definition at line 377 of file code_2e230_len_2190.c.
Referenced by func_800533D0().
func_80053A98()
void func_80053A98 (u8 arg0, u16 arg1, s32 arg2)
Definition at line 392 of file code_2e230_len_2190.c.
Referenced by func_8004B440(), and func_800533D0().
func_80053AC8()
void func_80053AC8 (UnkAl1 * arg0)
Definition at line 396 of file code_2e230_len_2190.c.
func_80053AEC()
void func_80053AEC (UnkAl1 * arg0, s16 arg1)
Definition at line 404 of file code_2e230_len_2190.c.
Referenced by func_8004E158().
func_80053B04()
void func_80053B04 (UnkAl1 * arg0, u32 arg1, s16 arg2)
Definition at line 411 of file code_2e230_len_2190.c.
func_80053BA8()
void func_80053BA8 (UnkAl1 * arg0)
Definition at line 428 of file code_2e230_len_2190.c.
Referenced by func_800533D0().
func_80053BE8()
s32 func_80053BE8 (UnkAl19E0 * arg0, s32 arg1, s32 arg2, s32 * arg3)
Definition at line 439 of file code_2e230_len_2190.c.
Referenced by func_8004FE6C().
func_80053C58()
s32 func_80053C58 ()
Definition at line 441 of file code_2e230_len_2190.c.
func_80053CB4()
s32 func_80053CB4 ()
Definition at line 443 of file code_2e230_len_2190.c.
func_80053CF8()
s32 func_80053CF8 ()
Definition at line 445 of file code_2e230_len_2190.c.
func_80053E58()
s32 func_80053E58 ()
Definition at line 447 of file code_2e230_len_2190.c.
func_80053F64()
UnkAlA9C* func_80053F64 (s32 arg0)
Definition at line 449 of file code_2e230_len_2190.c.
func_80053F80()
s32 func_80053F80 ()
Definition at line 456 of file code_2e230_len_2190.c.
Referenced by func_80055448().
func_80054248()
UnkAlA9C* func_80054248 (u8 arg0)
Definition at line 458 of file code_2e230_len_2190.c.
al_LoadINIT()
void al_LoadINIT (UnkAl19E0 * arg0, s32 arg1, ALHeap * arg2)
Definition at line 471 of file code_2e230_len_2190.c.
Referenced by func_80052E5C().
al_CopyFileTableEntry()
s32 al_CopyFileTableEntry (u16 arg0, s32 arg1, s32 * arg2)
Definition at line 473 of file code_2e230_len_2190.c.
Referenced by func_80052E5C().
al_LoadPER()
void al_LoadPER (UnkAl19E0 * arg0, s32 * arg1)
Definition at line 475 of file code_2e230_len_2190.c.
Referenced by func_80052E5C().
al_LoadPRG()
void al_LoadPRG (UnkAl19E0 * arg0, s32 * arg1)
Definition at line 477 of file code_2e230_len_2190.c.
Referenced by func_80052E5C().
func_8005465C()
s32 func_8005465C ()
Definition at line 479 of file code_2e230_len_2190.c.
func_80054744()
s32 func_80054744 ()
Definition at line 481 of file code_2e230_len_2190.c.
al_LoadBank()
s32 al_LoadBank ()
Definition at line 483 of file code_2e230_len_2190.c.
Referenced by func_80054C4C().
func_800549F8()
s32 func_800549F8 ()
Definition at line 485 of file code_2e230_len_2190.c.
func_80054AA0()
s32 func_80054AA0 ()
Definition at line 487 of file code_2e230_len_2190.c.
func_80054C4C()
s32 func_80054C4C (s32 arg0, s32 arg1)
Definition at line 489 of file code_2e230_len_2190.c.
func_80054C84()
s32 func_80054C84 ()
Definition at line 494 of file code_2e230_len_2190.c.
func_80054CE0()
void func_80054CE0 (s32 arg0, s32 arg1)
Definition at line 496 of file code_2e230_len_2190.c.
Referenced by func_800561A4(), and func_800561C4().
func_80054D74()
s32 func_80054D74 (s32 arg0, s32 arg1)
Definition at line 498 of file code_2e230_len_2190.c.
Referenced by func_800561E4().
func_80054DA8()
s32 func_80054DA8 ()
Definition at line 505 of file code_2e230_len_2190.c.
Referenced by func_8005615C(), and func_80056180().
al_DmaCopy()
void al_DmaCopy (s32 arg0, s32 * arg1, s32 arg2)
Definition at line 507 of file code_2e230_len_2190.c.
Referenced by func_80052E5C().
func_80054E90()
s32 func_80054E90 ()
Definition at line 509 of file code_2e230_len_2190.c.
func_80054F48()
s32 func_80054F48 ()
Definition at line 511 of file code_2e230_len_2190.c.
al_CopyWords()
void al_CopyWords (s32 * src, s32 * dst, s32 num)
Definition at line 513 of file code_2e230_len_2190.c.