src/code_17D6A0.c File Reference - Paper Mario Documentation
code_17D6A0.c File Reference
Functions
s32 func_8024EDC0 ()
s32 func_8024EDEC ()
s32 func_8024EE48 ()
s32 func_8024EEA8 ()
s32 func_8024EF08 ()
s32 create_popup ()
s32 func_8024EFA4 ()
s32 func_8024EFE0 ()
s32 func_8024F394 ()
s32 func_8024F5AC ()
s32 func_8024F768 ()
s32 func_8024F7C8 ()
s32 func_8024F84C ()
s32 func_8024F940 ()
s32 show_battle_message ()
s32 show_variable_battle_message ()
s32 is_popup_displayed ()
s32 set_popup_duration ()
s32 func_8024FAE8 ()
s32 func_8024FAFC ()
s32 close_action_command_instruction_popup ()
s32 func_8024FB3C ()
s32 func_80250818 ()
s32 show_message_popup ()
s32 ShowMessageBox ()
s32 ShowVariableMessageBox ()
ApiStatus IsMessageBoxDisplayed (ScriptInstance *script, s32 isInitialCall)
ApiStatus WaitForMessageBoxDone (ScriptInstance *script, s32 isInitialCall)
s32 ForceCloseMessageBox ()
s32 SetMessageBoxDuration ()
s32 func_80251434 ()
s32 func_80251454 ()
s32 func_80251474 ()
Function Documentation
func_8024EDC0()
s32 func_8024EDC0 ()
Definition at line 3 of file code_17D6A0.c.
func_8024EDEC()
s32 func_8024EDEC ()
Definition at line 5 of file code_17D6A0.c.
func_8024EE48()
s32 func_8024EE48 ()
Definition at line 7 of file code_17D6A0.c.
func_8024EEA8()
s32 func_8024EEA8 ()
Definition at line 9 of file code_17D6A0.c.
func_8024EF08()
s32 func_8024EF08 ()
Definition at line 11 of file code_17D6A0.c.
create_popup()
s32 create_popup ()
Definition at line 13 of file code_17D6A0.c.
func_8024EFA4()
s32 func_8024EFA4 ()
Definition at line 15 of file code_17D6A0.c.
func_8024EFE0()
s32 func_8024EFE0 ()
Definition at line 17 of file code_17D6A0.c.
func_8024F394()
s32 func_8024F394 ()
Definition at line 19 of file code_17D6A0.c.
func_8024F5AC()
s32 func_8024F5AC ()
Definition at line 21 of file code_17D6A0.c.
func_8024F768()
s32 func_8024F768 ()
Definition at line 23 of file code_17D6A0.c.
func_8024F7C8()
s32 func_8024F7C8 ()
Definition at line 25 of file code_17D6A0.c.
func_8024F84C()
s32 func_8024F84C ()
Definition at line 27 of file code_17D6A0.c.
func_8024F940()
s32 func_8024F940 ()
Definition at line 29 of file code_17D6A0.c.
show_battle_message()
s32 show_battle_message ()
Definition at line 31 of file code_17D6A0.c.
Referenced by func_80260E38().
show_variable_battle_message()
s32 show_variable_battle_message ()
Definition at line 33 of file code_17D6A0.c.
is_popup_displayed()
s32 is_popup_displayed ()
Definition at line 35 of file code_17D6A0.c.
Referenced by IsMessageBoxDisplayed(), and WaitForMessageBoxDone().
set_popup_duration()
s32 set_popup_duration ()
Definition at line 37 of file code_17D6A0.c.
func_8024FAE8()
s32 func_8024FAE8 ()
Definition at line 39 of file code_17D6A0.c.
func_8024FAFC()
s32 func_8024FAFC ()
Definition at line 41 of file code_17D6A0.c.
close_action_command_instruction_popup()
s32 close_action_command_instruction_popup ()
Definition at line 43 of file code_17D6A0.c.
func_8024FB3C()
s32 func_8024FB3C ()
Definition at line 45 of file code_17D6A0.c.
func_80250818()
s32 func_80250818 ()
Definition at line 47 of file code_17D6A0.c.
show_message_popup()
s32 show_message_popup ()
Definition at line 49 of file code_17D6A0.c.
ShowMessageBox()
s32 ShowMessageBox ()
Definition at line 51 of file code_17D6A0.c.
ShowVariableMessageBox()
s32 ShowVariableMessageBox ()
Definition at line 53 of file code_17D6A0.c.
IsMessageBoxDisplayed()
ApiStatus IsMessageBoxDisplayed (ScriptInstance * script, s32 isInitialCall)
Definition at line 55 of file code_17D6A0.c.
WaitForMessageBoxDone()
ApiStatus WaitForMessageBoxDone (ScriptInstance * script, s32 isInitialCall)
Definition at line 63 of file code_17D6A0.c.
ForceCloseMessageBox()
s32 ForceCloseMessageBox ()
Definition at line 67 of file code_17D6A0.c.
SetMessageBoxDuration()
s32 SetMessageBoxDuration ()
Definition at line 69 of file code_17D6A0.c.
func_80251434()
s32 func_80251434 ()
Definition at line 71 of file code_17D6A0.c.
func_80251454()
s32 func_80251454 ()
Definition at line 73 of file code_17D6A0.c.
func_80251474()
s32 func_80251474 ()
Definition at line 75 of file code_17D6A0.c.
Referenced by ShowShockEffect().