src/code_316f30.c File Reference - Paper Mario Documentation
code_316f30.c File Reference
Functions
void func_80200000 (void)
void func_80200080 (void)
void func_802AE000 (void)
void func_802B2000 (void)
void func_802B203C (void)
void func_802B2078 (void)
void func_802B20B4 (void)
Variables
s32 D_003169F0
s32 D_00316A70
s32 D_00316C00
s32 D_00316D90
s32 D_00316F30
Function Documentation
func_80200000()
void func_80200000 (void)
Definition at line 3 of file code_3169f0.c.
Referenced by func_802B2000().
func_80200080()
void func_80200080 (void)
Definition at line 3 of file code_316a70.c.
Referenced by func_802B203C().
func_802AE000()
void func_802AE000 (void)
Definition at line 3 of file code_316d90.c.
Referenced by func_802B2078(), and func_802B20B4().
func_802B2000()
void func_802B2000 (void)
Definition at line 13 of file code_316f30.c.
Referenced by boot_main().
func_802B203C()
void func_802B203C (void)
Definition at line 18 of file code_316f30.c.
Referenced by boot_main().
func_802B2078()
void func_802B2078 (void)
Definition at line 23 of file code_316f30.c.
func_802B20B4()
void func_802B20B4 (void)
Definition at line 28 of file code_316f30.c.
Variable Documentation
D_003169F0
s32 D_003169F0 extern
Referenced by func_802B2000().
D_00316A70
s32 D_00316A70 extern
Referenced by func_802B2000(), and func_802B203C().
D_00316C00
s32 D_00316C00 extern
Referenced by func_802B203C(), and func_802B2078().
D_00316D90
s32 D_00316D90 extern
Referenced by func_802B2078(), and func_802B20B4().
D_00316F30
s32 D_00316F30 extern
Referenced by func_802B20B4().