src/code_838b0_len_5900.c File Reference - Paper Mario Documentation
code_838b0_len_5900.c File Reference
Functions
s32 use_consumable ()
void remove_consumable (void)
s32 func_800EA4B0 ()
s32 world_partner_can_use_ability_default (Npc *partner)
s32 world_partner_can_player_pause_default (Npc *partner)
s32 func_800EA52C ()
s32 is_current_partner_flying (void)
s32 func_800EA5B8 ()
s32 func_800EA5D0 ()
s32 func_800EA6A8 ()
s32 func_800EA6CC ()
s32 func_800EB168 (s32 arg0)
s32 func_800EB200 ()
s32 func_800EB2A4 ()
s32 partner_use_ability ()
s32 partner_player_can_pause ()
s32 partner_can_use_ability ()
s32 partner_reset_data ()
s32 partner_initialize_data ()
s32 partner_test_enemy_collision ()
s32 partner_get_ride_script ()
s32 partner_handle_before_battle ()
s32 partner_handle_after_battle ()
s32 partner_kill_ability_script ()
s32 partner_suspend_ability_script ()
s32 partner_resume_ability_script ()
void enable_partner_walking (Npc *partner, s32 val)
void func_800EBA3C (Npc *partner)
void func_800EBB40 (Npc *partner)
s32 func_800EBC74 ()
void enable_partner_flying (Npc *partner, s32 val)
void update_player_move_history (Npc *partner)
void func_800ED5D0 (Npc *partner)
s32 func_800ED9F8 ()
s32 func_800EE994 ()
s32 func_800EE9B8 ()
s32 func_800EECC4 ()
s32 func_800EECE8 ()
s32 func_800EF300 ()
s32 func_800EF314 ()
void enable_partner_ai (void)
s32 func_800EF394 (f32 arg0)
s32 func_800EF3A4 ()
s32 func_800EF3C0 ()
s32 func_800EF3D4 ()
s32 func_800EF3E4 ()
s32 func_800EF414 ()
s32 func_800EF43C ()
void clear_partner_move_history (Npc *partner)
s32 func_800EF4E0 ()
s32 func_800EF600 ()
s32 func_800EF628 ()
s32 func_800EF640 ()
s32 func_800EF82C ()
Function Documentation
use_consumable()
s32 use_consumable ()
Definition at line 3 of file code_838b0_len_5900.c.
remove_consumable()
void remove_consumable (void)
Definition at line 5 of file code_838b0_len_5900.c.
Referenced by func_802BD4E8().
func_800EA4B0()
s32 func_800EA4B0 ()
Definition at line 10 of file code_838b0_len_5900.c.
world_partner_can_use_ability_default()
s32 world_partner_can_use_ability_default (Npc * partner)
Definition at line 12 of file code_838b0_len_5900.c.
world_partner_can_player_pause_default()
s32 world_partner_can_player_pause_default (Npc * partner)
Definition at line 16 of file code_838b0_len_5900.c.
func_800EA52C()
s32 func_800EA52C ()
Definition at line 20 of file code_838b0_len_5900.c.
is_current_partner_flying()
s32 is_current_partner_flying (void)
Definition at line 22 of file code_838b0_len_5900.c.
Referenced by PartnerIsFlying(), and TeleportPartnerToPlayer().
func_800EA5B8()
s32 func_800EA5B8 ()
Definition at line 24 of file code_838b0_len_5900.c.
func_800EA5D0()
s32 func_800EA5D0 ()
Definition at line 26 of file code_838b0_len_5900.c.
func_800EA6A8()
s32 func_800EA6A8 ()
Definition at line 28 of file code_838b0_len_5900.c.
func_800EA6CC()
s32 func_800EA6CC ()
Definition at line 30 of file code_838b0_len_5900.c.
func_800EB168()
s32 func_800EB168 (s32 arg0)
Definition at line 32 of file code_838b0_len_5900.c.
Referenced by Call800EB168(), func_80240000_8C7F90(), func_80245440_805CC0(), and GetPartnerCall800EB168().
func_800EB200()
s32 func_800EB200 ()
Definition at line 34 of file code_838b0_len_5900.c.
func_800EB2A4()
s32 func_800EB2A4 ()
Definition at line 36 of file code_838b0_len_5900.c.
Referenced by func_80240000_8C7F90().
partner_use_ability()
s32 partner_use_ability ()
Definition at line 38 of file code_838b0_len_5900.c.
partner_player_can_pause()
s32 partner_player_can_pause ()
Definition at line 40 of file code_838b0_len_5900.c.
partner_can_use_ability()
s32 partner_can_use_ability ()
Definition at line 42 of file code_838b0_len_5900.c.
Referenced by PartnerCanUseAbility().
partner_reset_data()
s32 partner_reset_data ()
Definition at line 44 of file code_838b0_len_5900.c.
partner_initialize_data()
s32 partner_initialize_data ()
Definition at line 46 of file code_838b0_len_5900.c.
Referenced by step_init_state().
partner_test_enemy_collision()
s32 partner_test_enemy_collision ()
Definition at line 48 of file code_838b0_len_5900.c.
partner_get_ride_script()
s32 partner_get_ride_script ()
Definition at line 50 of file code_838b0_len_5900.c.
Referenced by func_80283810().
partner_handle_before_battle()
s32 partner_handle_before_battle ()
Definition at line 52 of file code_838b0_len_5900.c.
partner_handle_after_battle()
s32 partner_handle_after_battle ()
Definition at line 54 of file code_838b0_len_5900.c.
partner_kill_ability_script()
s32 partner_kill_ability_script ()
Definition at line 56 of file code_838b0_len_5900.c.
partner_suspend_ability_script()
s32 partner_suspend_ability_script ()
Definition at line 58 of file code_838b0_len_5900.c.
Referenced by PartnerSuspendAbilityScript().
partner_resume_ability_script()
s32 partner_resume_ability_script ()
Definition at line 60 of file code_838b0_len_5900.c.
Referenced by PartnerResumeAbilityScript().
enable_partner_walking()
void enable_partner_walking (Npc * partner, s32 val)
Definition at line 62 of file code_838b0_len_5900.c.
Referenced by GoombariaUpdate().
func_800EBA3C()
void func_800EBA3C (Npc * partner)
Definition at line 64 of file code_838b0_len_5900.c.
Referenced by GoombariaUpdate().
func_800EBB40()
void func_800EBB40 (Npc * partner)
Definition at line 66 of file code_838b0_len_5900.c.
Referenced by GoombariaUpdate().
func_800EBC74()
s32 func_800EBC74 ()
Definition at line 68 of file code_838b0_len_5900.c.
enable_partner_flying()
void enable_partner_flying (Npc * partner, s32 val)
Definition at line 70 of file code_838b0_len_5900.c.
Referenced by TwinkUpdate().
update_player_move_history()
void update_player_move_history (Npc * partner)
Definition at line 72 of file code_838b0_len_5900.c.
Referenced by TwinkUpdate().
func_800ED5D0()
void func_800ED5D0 (Npc * partner)
Definition at line 74 of file code_838b0_len_5900.c.
Referenced by TwinkUpdate().
func_800ED9F8()
s32 func_800ED9F8 ()
Definition at line 76 of file code_838b0_len_5900.c.
func_800EE994()
s32 func_800EE994 ()
Definition at line 78 of file code_838b0_len_5900.c.
Referenced by func_802BDB84(), func_802BE4E8(), func_802BE8D4(), GoombariaPutAway(), GoompaPutAway(), and TwinkPutAway().
func_800EE9B8()
s32 func_800EE9B8 ()
Definition at line 80 of file code_838b0_len_5900.c.
Referenced by func_802BDB84(), func_802BE4E8(), func_802BE8D4(), GoombariaPutAway(), GoompaPutAway(), and TwinkPutAway().
func_800EECC4()
s32 func_800EECC4 ()
Definition at line 82 of file code_838b0_len_5900.c.
Referenced by func_802BD148(), func_802BD300(), GoombariaTakeOut(), GoompaTakeOut(), and TwinkTakeOut().
func_800EECE8()
s32 func_800EECE8 ()
Definition at line 84 of file code_838b0_len_5900.c.
Referenced by func_802BD148(), func_802BD300(), GoombariaTakeOut(), GoompaTakeOut(), and TwinkTakeOut().
func_800EF300()
s32 func_800EF300 ()
Definition at line 86 of file code_838b0_len_5900.c.
Referenced by DisablePartnerAI().
func_800EF314()
s32 func_800EF314 ()
Definition at line 88 of file code_838b0_len_5900.c.
Referenced by DisablePartnerAI().
enable_partner_ai()
void enable_partner_ai (void)
Definition at line 90 of file code_838b0_len_5900.c.
Referenced by EnablePartnerAI(), and func_80283908().
func_800EF394()
s32 func_800EF394 (f32 arg0)
Definition at line 92 of file code_838b0_len_5900.c.
Referenced by func_80245504_805D84(), func_80281C20(), and func_80283B88().
func_800EF3A4()
s32 func_800EF3A4 ()
Definition at line 94 of file code_838b0_len_5900.c.
Referenced by func_8024552C_805DAC(), func_80281C84(), and func_80283BB0().
func_800EF3C0()
s32 func_800EF3C0 ()
Definition at line 96 of file code_838b0_len_5900.c.
func_800EF3D4()
s32 func_800EF3D4 ()
Definition at line 98 of file code_838b0_len_5900.c.
Referenced by func_8004309C(), and func_802CF56C().
func_800EF3E4()
s32 func_800EF3E4 ()
Definition at line 100 of file code_838b0_len_5900.c.
Referenced by func_80281C84(), and func_802CF56C().
func_800EF414()
s32 func_800EF414 ()
Definition at line 102 of file code_838b0_len_5900.c.
Referenced by func_80281C20().
func_800EF43C()
s32 func_800EF43C ()
Definition at line 104 of file code_838b0_len_5900.c.
Referenced by func_802CF54C().
clear_partner_move_history()
void clear_partner_move_history (Npc * partner)
Definition at line 106 of file code_838b0_len_5900.c.
Referenced by ClearPartnerMoveHistory(), func_80240000_8C7F90(), TeleportPartnerToPlayer(), and world_goombario_pre_battle().
func_800EF4E0()
s32 func_800EF4E0 ()
Definition at line 108 of file code_838b0_len_5900.c.
func_800EF600()
s32 func_800EF600 ()
Definition at line 110 of file code_838b0_len_5900.c.
Referenced by DisablePlayerInput(), func_8004309C(), and func_802D6954().
func_800EF628()
s32 func_800EF628 ()
Definition at line 112 of file code_838b0_len_5900.c.
Referenced by DisablePlayerInput().
func_800EF640()
s32 func_800EF640 ()
Definition at line 114 of file code_838b0_len_5900.c.
func_800EF82C()
s32 func_800EF82C ()
Definition at line 116 of file code_838b0_len_5900.c.