src/os/code_43200_len_7c0.c File Reference - Paper Mario Documentation
code_43200_len_7c0.c File Reference
Functions
s32 __osMotorAccess (OSPfs *pfs, s32 unk)
s32 osMotorInit (OSMesgQueue *queue, OSPfs *pfs, int unk)
s32 osPfsAllocateFile (OSPfs *pfs, u16 unk1, u32 unk2, u8 *unk3, u8 *unk4, int unk5, s32 *unk6)
s32 osPfsDeclearPage ()
Function Documentation
__osMotorAccess()
s32 __osMotorAccess (OSPfs * pfs, s32 unk)
Definition at line 3 of file code_43200_len_7c0.c.
osMotorInit()
s32 osMotorInit (OSMesgQueue * queue, OSPfs * pfs, int unk)
Definition at line 5 of file code_43200_len_7c0.c.
Referenced by contRmbCheckMesg(), contRmbControl(), and contRmbRetrace().
osPfsAllocateFile()
s32 osPfsAllocateFile (OSPfs * pfs, u16 unk1, u32 unk2, u8 * unk3, u8 * unk4, int unk5, s32 * unk6)
Definition at line 8 of file code_43200_len_7c0.c.
Referenced by contPakFileOpen().
osPfsDeclearPage()
s32 osPfsDeclearPage ()
Definition at line 10 of file code_43200_len_7c0.c.