src/os/code_3b910_len_410.c File Reference - Paper Mario Documentation
code_3b910_len_410.c File Reference
Functions
s32 nuContMgrInit ()
s32 nuContMgrRemove ()
s32 nuContDataClose ()
s32 nuContDataOpen ()
s32 contRetrace ()
s32 contReadData ()
s32 contReadNW ()
s32 contQuery ()
s32 nuContDataLock ()
s32 nuContDataUnLock ()
Function Documentation
nuContMgrInit()
s32 nuContMgrInit ()
Definition at line 3 of file code_3b910_len_410.c.
Referenced by nuContInit().
nuContMgrRemove()
s32 nuContMgrRemove ()
Definition at line 5 of file code_3b910_len_410.c.
nuContDataClose()
s32 nuContDataClose ()
Definition at line 7 of file code_3b910_len_410.c.
Referenced by nuContDataGet().
nuContDataOpen()
s32 nuContDataOpen ()
Definition at line 9 of file code_3b910_len_410.c.
Referenced by nuContDataGet().
contRetrace()
s32 contRetrace ()
Definition at line 11 of file code_3b910_len_410.c.
contReadData()
s32 contReadData ()
Definition at line 13 of file code_3b910_len_410.c.
contReadNW()
s32 contReadNW ()
Definition at line 15 of file code_3b910_len_410.c.
contQuery()
s32 contQuery ()
Definition at line 17 of file code_3b910_len_410.c.
nuContDataLock()
s32 nuContDataLock ()
Definition at line 19 of file code_3b910_len_410.c.
nuContDataUnLock()
s32 nuContDataUnLock ()
Definition at line 21 of file code_3b910_len_410.c.