src/code_1f580_len_1940.c File Reference - Paper Mario Documentation
code_1f580_len_1940.c File Reference
Functions
ApiStatus SetEncounterStatusFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_800441F0 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_80044238 (ScriptInstance *script, s32 isInitialCall)
ApiStatus LoadDemoBattle (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_80044290 (ScriptInstance *script, s32 isInitialCall)
ApiStatus MakeNpcs (ScriptInstance *script, s32 isInitialCall)
s32 RemoveNpc (ScriptInstance *script, s32 isInitialCall)
s32 RemoveEncounter (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetBattleOutcome (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_800445A8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_800445D4 (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetOwnerEncounterTrigger (ScriptInstance *script, s32 isInitialCall)
ApiStatus DoNpcDefeat (ScriptInstance *script, s32 isInitialCall)
s32 start_battle ()
ApiStatus StartBattle (ScriptInstance *script, s32 isInitialCall)
ApiStatus StartBattleWith (ScriptInstance *script, s32 isInitialCall)
s32 StartBossBattle (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetBattleMusic (ScriptInstance *script, s32 isInitialCall)
s32 BindNpcAI (ScriptInstance *script, s32 isInitialCall)
ApiStatus BindNpcIdle (ScriptInstance *script, s32 isInitialCall)
ApiStatus RestartNpcAI (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableNpcAI (ScriptInstance *script, s32 isInitialCall)
s32 SetNpcAux (ScriptInstance *script, s32 isInitialCall)
ApiStatus BindNpcAux (ScriptInstance *script, s32 isInitialCall)
ApiStatus RestartNpcAux (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableNpcAux (ScriptInstance *script, s32 isInitialCall)
ApiStatus BindNpcInteract (ScriptInstance *script, s32 isInitialCall)
ApiStatus BindNpcHit (ScriptInstance *script, s32 isInitialCall)
ApiStatus BindNpcDefeat (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetSelfVar (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetSelfVar (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcVar (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetNpcVar (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetSelfRotation (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetSelfEnemyFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetSelfEnemyFlagBits (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_80045580 (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetSelfNpcID (ScriptInstance *script, s32 isInitialCall)
ApiStatus ClearDefeatedEnemies (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetEnemyFlagBits (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8004572C (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetSelfAnimationFromTable (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_80045798 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_800457C4 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_800457F8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8004580C (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_80045838 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_800458CC (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_80045900 (ScriptInstance *script)
ApiStatus SetTattleString (ScriptInstance *script, s32 isInitialCall)
Function Documentation
SetEncounterStatusFlags()
ApiStatus SetEncounterStatusFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 4 of file code_1f580_len_1940.c.
func_800441F0()
ApiStatus func_800441F0 (ScriptInstance * script, s32 isInitialCall)
Definition at line 19 of file code_1f580_len_1940.c.
Referenced by N().
func_80044238()
ApiStatus func_80044238 (ScriptInstance * script, s32 isInitialCall)
Definition at line 26 of file code_1f580_len_1940.c.
LoadDemoBattle()
ApiStatus LoadDemoBattle (ScriptInstance * script, s32 isInitialCall)
Definition at line 31 of file code_1f580_len_1940.c.
func_80044290()
ApiStatus func_80044290 (ScriptInstance * script, s32 isInitialCall)
Definition at line 36 of file code_1f580_len_1940.c.
MakeNpcs()
ApiStatus MakeNpcs (ScriptInstance * script, s32 isInitialCall)
Definition at line 40 of file code_1f580_len_1940.c.
Referenced by N().
RemoveNpc()
s32 RemoveNpc (ScriptInstance * script, s32 isInitialCall)
Definition at line 61 of file code_1f580_len_1940.c.
RemoveEncounter()
s32 RemoveEncounter (ScriptInstance * script, s32 isInitialCall)
Definition at line 63 of file code_1f580_len_1940.c.
GetBattleOutcome()
ApiStatus GetBattleOutcome (ScriptInstance * script, s32 isInitialCall)
Definition at line 65 of file code_1f580_len_1940.c.
func_800445A8()
ApiStatus func_800445A8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 70 of file code_1f580_len_1940.c.
func_800445D4()
ApiStatus func_800445D4 (ScriptInstance * script, s32 isInitialCall)
Definition at line 75 of file code_1f580_len_1940.c.
GetOwnerEncounterTrigger()
ApiStatus GetOwnerEncounterTrigger (ScriptInstance * script, s32 isInitialCall)
Definition at line 80 of file code_1f580_len_1940.c.
Referenced by N().
DoNpcDefeat()
ApiStatus DoNpcDefeat (ScriptInstance * script, s32 isInitialCall)
Definition at line 85 of file code_1f580_len_1940.c.
start_battle()
s32 start_battle ()
Definition at line 102 of file code_1f580_len_1940.c.
Referenced by StartBattle(), and StartBattleWith().
StartBattle()
ApiStatus StartBattle (ScriptInstance * script, s32 isInitialCall)
Definition at line 104 of file code_1f580_len_1940.c.
StartBattleWith()
ApiStatus StartBattleWith (ScriptInstance * script, s32 isInitialCall)
Definition at line 109 of file code_1f580_len_1940.c.
StartBossBattle()
s32 StartBossBattle (ScriptInstance * script, s32 isInitialCall)
Definition at line 114 of file code_1f580_len_1940.c.
SetBattleMusic()
ApiStatus SetBattleMusic (ScriptInstance * script, s32 isInitialCall)
Definition at line 116 of file code_1f580_len_1940.c.
BindNpcAI()
s32 BindNpcAI (ScriptInstance * script, s32 isInitialCall)
Definition at line 126 of file code_1f580_len_1940.c.
Referenced by N().
BindNpcIdle()
ApiStatus BindNpcIdle (ScriptInstance * script, s32 isInitialCall)
Definition at line 128 of file code_1f580_len_1940.c.
Referenced by N().
RestartNpcAI()
ApiStatus RestartNpcAI (ScriptInstance * script, s32 isInitialCall)
Definition at line 144 of file code_1f580_len_1940.c.
EnableNpcAI()
ApiStatus EnableNpcAI (ScriptInstance * script, s32 isInitialCall)
Definition at line 178 of file code_1f580_len_1940.c.
Referenced by N().
SetNpcAux()
s32 SetNpcAux (ScriptInstance * script, s32 isInitialCall)
Definition at line 201 of file code_1f580_len_1940.c.
Referenced by N().
BindNpcAux()
ApiStatus BindNpcAux (ScriptInstance * script, s32 isInitialCall)
Definition at line 203 of file code_1f580_len_1940.c.
Referenced by N().
RestartNpcAux()
ApiStatus RestartNpcAux (ScriptInstance * script, s32 isInitialCall)
Definition at line 219 of file code_1f580_len_1940.c.
EnableNpcAux()
ApiStatus EnableNpcAux (ScriptInstance * script, s32 isInitialCall)
Definition at line 252 of file code_1f580_len_1940.c.
BindNpcInteract()
ApiStatus BindNpcInteract (ScriptInstance * script, s32 isInitialCall)
Definition at line 275 of file code_1f580_len_1940.c.
BindNpcHit()
ApiStatus BindNpcHit (ScriptInstance * script, s32 isInitialCall)
Definition at line 295 of file code_1f580_len_1940.c.
Referenced by N().
BindNpcDefeat()
ApiStatus BindNpcDefeat (ScriptInstance * script, s32 isInitialCall)
Definition at line 315 of file code_1f580_len_1940.c.
SetSelfVar()
ApiStatus SetSelfVar (ScriptInstance * script, s32 isInitialCall)
Definition at line 331 of file code_1f580_len_1940.c.
Referenced by N().
GetSelfVar()
ApiStatus GetSelfVar (ScriptInstance * script, s32 isInitialCall)
Definition at line 341 of file code_1f580_len_1940.c.
Referenced by N().
SetNpcVar()
ApiStatus SetNpcVar (ScriptInstance * script, s32 isInitialCall)
Definition at line 348 of file code_1f580_len_1940.c.
Referenced by N().
GetNpcVar()
ApiStatus GetNpcVar (ScriptInstance * script, s32 isInitialCall)
Definition at line 365 of file code_1f580_len_1940.c.
Referenced by N().
SetSelfRotation()
ApiStatus SetSelfRotation (ScriptInstance * script, s32 isInitialCall)
Definition at line 382 of file code_1f580_len_1940.c.
SetSelfEnemyFlags()
ApiStatus SetSelfEnemyFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 396 of file code_1f580_len_1940.c.
SetSelfEnemyFlagBits()
ApiStatus SetSelfEnemyFlagBits (ScriptInstance * script, s32 isInitialCall)
Definition at line 401 of file code_1f580_len_1940.c.
Referenced by N().
func_80045580()
ApiStatus func_80045580 (ScriptInstance * script, s32 isInitialCall)
Definition at line 414 of file code_1f580_len_1940.c.
GetSelfNpcID()
ApiStatus GetSelfNpcID (ScriptInstance * script, s32 isInitialCall)
Definition at line 427 of file code_1f580_len_1940.c.
ClearDefeatedEnemies()
ApiStatus ClearDefeatedEnemies (ScriptInstance * script, s32 isInitialCall)
Definition at line 432 of file code_1f580_len_1940.c.
Referenced by N().
SetEnemyFlagBits()
ApiStatus SetEnemyFlagBits (ScriptInstance * script, s32 isInitialCall)
Definition at line 445 of file code_1f580_len_1940.c.
func_8004572C()
ApiStatus func_8004572C (ScriptInstance * script, s32 isInitialCall)
Definition at line 467 of file code_1f580_len_1940.c.
GetSelfAnimationFromTable()
ApiStatus GetSelfAnimationFromTable (ScriptInstance * script, s32 isInitialCall)
Definition at line 471 of file code_1f580_len_1940.c.
func_80045798()
ApiStatus func_80045798 (ScriptInstance * script, s32 isInitialCall)
Definition at line 479 of file code_1f580_len_1940.c.
func_800457C4()
ApiStatus func_800457C4 (ScriptInstance * script, s32 isInitialCall)
Definition at line 484 of file code_1f580_len_1940.c.
func_800457F8()
ApiStatus func_800457F8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 491 of file code_1f580_len_1940.c.
func_8004580C()
ApiStatus func_8004580C (ScriptInstance * script, s32 isInitialCall)
Definition at line 496 of file code_1f580_len_1940.c.
func_80045838()
ApiStatus func_80045838 (ScriptInstance * script, s32 isInitialCall)
Definition at line 501 of file code_1f580_len_1940.c.
func_800458CC()
ApiStatus func_800458CC (ScriptInstance * script, s32 isInitialCall)
Definition at line 516 of file code_1f580_len_1940.c.
func_80045900()
ApiStatus func_80045900 (ScriptInstance * script)
Definition at line 521 of file code_1f580_len_1940.c.
SetTattleString()
ApiStatus SetTattleString (ScriptInstance * script, s32 isInitialCall)
Definition at line 555 of file code_1f580_len_1940.c.