src/code_16F740.c File Reference - Paper Mario Documentation
code_16F740.c File Reference
Functions
s32 func_80240E60 ()
s32 func_80240FDC ()
s32 func_80241190 ()
s32 begin_battle ()
s32 func_80241AB8 ()
s32 func_80241B14 ()
void func_8024201C (void)
s32 update_heroes_start_turn ()
void func_80242AC0 (void)
s32 switch_to_player ()
void func_80242BA8 (void)
s32 update_end_player_turn ()
void func_80242EF8 (void)
s32 switch_to_partner ()
void func_80242FD8 (void)
s32 func_80242FE0 ()
void func_80243910 (void)
s32 switch_order ()
void func_802439D0 (void)
s32 func_802439D8 ()
void func_80243FD4 (void)
void func_80243FDC (void)
void func_80244000 (void)
s32 func_80244008 ()
void func_80244708 (void)
s32 func_80244710 ()
void func_80244A48 (void)
s32 end_battle ()
s32 func_80244D90 ()
s32 func_80244E38 ()
void func_80244EF8 (void)
s32 update_run_away ()
void func_80245438 (void)
s32 func_80245440 ()
void func_802456B0 (void)
ApiStatus EnablePartnerBlur (ScriptInstance *script, s32 isInitialCall)
ApiStatus DisablePartnerBlur (ScriptInstance *script, s32 isInitialCall)
s32 update_swap_partner ()
void func_80245AC8 (void)
s32 update_player_action ()
void func_80246448 (void)
s32 update_player_change_turn ()
void func_80246B2C_code (void)
s32 update_partner_action ()
void func_80247214 (void)
s32 func_8024721C ()
void func_802472A4 (void)
s32 update_enemy_change_turn ()
void func_80247568 (void)
s32 update_enemy_action ()
void func_80247AFC (void)
s32 func_80247B04 ()
s32 func_802480F0 ()
s32 func_80248190 ()
s32 func_802485FC ()
s32 func_80248660 ()
s32 func_80248AA4 ()
s32 func_80248B08 ()
s32 func_80248D78 ()
Function Documentation
func_80240E60()
s32 func_80240E60 ()
Definition at line 3 of file code_16F740.c.
func_80240FDC()
s32 func_80240FDC ()
Definition at line 5 of file code_16F740.c.
func_80241190()
s32 func_80241190 ()
Definition at line 7 of file code_16F740.c.
Referenced by func_80243FDC(), func_80253FB0(), and func_8026E16C().
begin_battle()
s32 begin_battle ()
Definition at line 9 of file code_16F740.c.
func_80241AB8()
s32 func_80241AB8 ()
Definition at line 11 of file code_16F740.c.
func_80241B14()
s32 func_80241B14 ()
Definition at line 13 of file code_16F740.c.
func_8024201C()
void func_8024201C (void)
Definition at line 15 of file code_16F740.c.
update_heroes_start_turn()
s32 update_heroes_start_turn ()
Definition at line 18 of file code_16F740.c.
func_80242AC0()
void func_80242AC0 (void)
Definition at line 20 of file code_16F740.c.
switch_to_player()
s32 switch_to_player ()
Definition at line 23 of file code_16F740.c.
func_80242BA8()
void func_80242BA8 (void)
Definition at line 25 of file code_16F740.c.
update_end_player_turn()
s32 update_end_player_turn ()
Definition at line 28 of file code_16F740.c.
func_80242EF8()
void func_80242EF8 (void)
Definition at line 30 of file code_16F740.c.
switch_to_partner()
s32 switch_to_partner ()
Definition at line 33 of file code_16F740.c.
func_80242FD8()
void func_80242FD8 (void)
Definition at line 35 of file code_16F740.c.
func_80242FE0()
s32 func_80242FE0 ()
Definition at line 38 of file code_16F740.c.
func_80243910()
void func_80243910 (void)
Definition at line 40 of file code_16F740.c.
switch_order()
s32 switch_order ()
Definition at line 43 of file code_16F740.c.
func_802439D0()
void func_802439D0 (void)
Definition at line 45 of file code_16F740.c.
func_802439D8()
s32 func_802439D8 ()
Definition at line 48 of file code_16F740.c.
func_80243FD4()
void func_80243FD4 (void)
Definition at line 50 of file code_16F740.c.
func_80243FDC()
void func_80243FDC (void)
Definition at line 53 of file code_16F740.c.
func_80244000()
void func_80244000 (void)
Definition at line 58 of file code_16F740.c.
func_80244008()
s32 func_80244008 ()
Definition at line 61 of file code_16F740.c.
func_80244708()
void func_80244708 (void)
Definition at line 63 of file code_16F740.c.
func_80244710()
s32 func_80244710 ()
Definition at line 66 of file code_16F740.c.
func_80244A48()
void func_80244A48 (void)
Definition at line 68 of file code_16F740.c.
end_battle()
s32 end_battle ()
Definition at line 71 of file code_16F740.c.
func_80244D90()
s32 func_80244D90 ()
Definition at line 73 of file code_16F740.c.
func_80244E38()
s32 func_80244E38 ()
Definition at line 75 of file code_16F740.c.
func_80244EF8()
void func_80244EF8 (void)
Definition at line 77 of file code_16F740.c.
update_run_away()
s32 update_run_away ()
Definition at line 80 of file code_16F740.c.
func_80245438()
void func_80245438 (void)
Definition at line 82 of file code_16F740.c.
func_80245440()
s32 func_80245440 ()
Definition at line 85 of file code_16F740.c.
func_802456B0()
void func_802456B0 (void)
Definition at line 87 of file code_16F740.c.
EnablePartnerBlur()
ApiStatus EnablePartnerBlur (ScriptInstance * script, s32 isInitialCall)
Definition at line 90 of file code_16F740.c.
DisablePartnerBlur()
ApiStatus DisablePartnerBlur (ScriptInstance * script, s32 isInitialCall)
Definition at line 95 of file code_16F740.c.
update_swap_partner()
s32 update_swap_partner ()
Definition at line 100 of file code_16F740.c.
func_80245AC8()
void func_80245AC8 (void)
Definition at line 102 of file code_16F740.c.
update_player_action()
s32 update_player_action ()
Definition at line 105 of file code_16F740.c.
func_80246448()
void func_80246448 (void)
Definition at line 107 of file code_16F740.c.
update_player_change_turn()
s32 update_player_change_turn ()
Definition at line 110 of file code_16F740.c.
func_80246B2C_code()
void func_80246B2C_code (void)
Definition at line 112 of file code_16F740.c.
update_partner_action()
s32 update_partner_action ()
Definition at line 115 of file code_16F740.c.
func_80247214()
void func_80247214 (void)
Definition at line 117 of file code_16F740.c.
func_8024721C()
s32 func_8024721C ()
Definition at line 120 of file code_16F740.c.
func_802472A4()
void func_802472A4 (void)
Definition at line 122 of file code_16F740.c.
update_enemy_change_turn()
s32 update_enemy_change_turn ()
Definition at line 125 of file code_16F740.c.
func_80247568()
void func_80247568 (void)
Definition at line 127 of file code_16F740.c.
update_enemy_action()
s32 update_enemy_action ()
Definition at line 130 of file code_16F740.c.
func_80247AFC()
void func_80247AFC (void)
Definition at line 132 of file code_16F740.c.
func_80247B04()
s32 func_80247B04 ()
Definition at line 135 of file code_16F740.c.
func_802480F0()
s32 func_802480F0 ()
Definition at line 137 of file code_16F740.c.
func_80248190()
s32 func_80248190 ()
Definition at line 139 of file code_16F740.c.
func_802485FC()
s32 func_802485FC ()
Definition at line 141 of file code_16F740.c.
func_80248660()
s32 func_80248660 ()
Definition at line 143 of file code_16F740.c.
func_80248AA4()
s32 func_80248AA4 ()
Definition at line 145 of file code_16F740.c.
func_80248B08()
s32 func_80248B08 ()
Definition at line 147 of file code_16F740.c.
func_80248D78()
s32 func_80248D78 ()
Definition at line 149 of file code_16F740.c.