src/code_ddaf0_len_c50.c File Reference - Paper Mario Documentation
code_ddaf0_len_c50.c File Reference
Functions
void func_801473F0 (void)
s32 func_80147414 ()
s32 func_80147474 ()
s32 func_80147574 ()
s32 func_80147650 ()
s32 func_80147698 ()
s32 func_80147AC4 ()
s32 set_ui_panel_properties ()
s32 func_80147D70 ()
void func_80147E48 (s32 panelIndex, s8 arg1, s32 arg2)
void func_80147E7C (s32 panelIndex, s32 arg1)
s32 func_80147EC4 ()
s32 func_80147F30 ()
Function Documentation
func_801473F0()
void func_801473F0 (void)
Definition at line 4 of file code_ddaf0_len_c50.c.
Referenced by load_engine_data(), and step_init_state().
func_80147414()
s32 func_80147414 ()
Definition at line 13 of file code_ddaf0_len_c50.c.
func_80147474()
s32 func_80147474 ()
Definition at line 15 of file code_ddaf0_len_c50.c.
func_80147574()
s32 func_80147574 ()
Definition at line 17 of file code_ddaf0_len_c50.c.
func_80147650()
s32 func_80147650 ()
Definition at line 19 of file code_ddaf0_len_c50.c.
func_80147698()
s32 func_80147698 ()
Definition at line 21 of file code_ddaf0_len_c50.c.
func_80147AC4()
s32 func_80147AC4 ()
Definition at line 23 of file code_ddaf0_len_c50.c.
set_ui_panel_properties()
s32 set_ui_panel_properties ()
Definition at line 25 of file code_ddaf0_len_c50.c.
Referenced by show_coin_counter().
func_80147D70()
s32 func_80147D70 ()
Definition at line 27 of file code_ddaf0_len_c50.c.
func_80147E48()
void func_80147E48 (s32 panelIndex, s8 arg1, s32 arg2)
Definition at line 29 of file code_ddaf0_len_c50.c.
func_80147E7C()
void func_80147E7C (s32 panelIndex, s32 arg1)
Definition at line 39 of file code_ddaf0_len_c50.c.
Referenced by show_coin_counter(), and update_coin_counter().
func_80147EC4()
s32 func_80147EC4 ()
Definition at line 52 of file code_ddaf0_len_c50.c.
func_80147F30()
s32 func_80147F30 ()
Definition at line 54 of file code_ddaf0_len_c50.c.