src/code_F5750.c File Reference - Paper Mario Documentation
code_F5750.c File Reference
Functions
ApiStatus HidePlayerShadow (ScriptInstance *script, s32 isInitialCall)
ApiStatus DisablePlayerPhysics (ScriptInstance *script, s32 isInitialCall)
ApiStatus DisablePlayerInput (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerCollisionSize (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerSpeed (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerJumpscale (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerActionState (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerAnimationSpeed (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlayerMoveTo (ScriptInstance *script, s32 isInitialCall)
s32 func_802D1270 ()
s32 func_802D1380 ()
s32 player_jump ()
void PlayerJump (ScriptInstance *script, s32 isInitialCall)
void PlayerJump1 (ScriptInstance *script, s32 isInitialCall)
void PlayerJump2 (ScriptInstance *script, s32 isInitialCall)
ApiStatus InterpPlayerYaw (ScriptInstance *script, s32 isInitialCall)
s32 PlayerFaceNpc (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPlayerTargetYaw (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerFlagBits (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPlayerActionState (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPlayerPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPlayerAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus FullyRestoreHPandFP (ScriptInstance *script, s32 isInitialCall)
ApiStatus FullyRestoreSP (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnablePartner (ScriptInstance *script, s32 isInitialCall)
ApiStatus DisablePartner (ScriptInstance *script, s32 isInitialCall)
s32 UseEntryHeading ()
s32 func_802D2148 ()
s32 UseExitHeading ()
s32 func_802D23F8 ()
s32 func_802D244C ()
s32 func_802D2484 ()
ApiStatus func_802D249C (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D24F4 (ScriptInstance *script, s32 isInitialCall)
s32 func_802D2508 ()
s32 func_802D2520 ()
s32 func_802D286C ()
s32 func_802D2884 ()
ApiStatus DisablePulseStone (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCurrentPartner (ScriptInstance *script, s32 isInitialCall)
s32 func_802D2B50 ()
s32 func_802D2B6C ()
ApiStatus Disable8bitMario (ScriptInstance *script, s32 isInitialCall)
s32 func_802D2C14 ()
s32 func_802D2C40 ()
ApiStatus PlaySoundAtPlayer (ScriptInstance *script, s32 isInitialCall)
s32 func_802D2D30 ()
s32 func_802D2ED4 ()
s32 func_802D2F34 ()
s32 func_802D2FCC ()
s32 func_802D3028 ()
s32 func_802D31E0 ()
s32 func_802D3398 ()
s32 func_802D33D4 ()
s32 func_802D3474 ()
s32 func_802D354C ()
s32 func_802D3624 ()
s32 func_802D3674 ()
s32 func_802D36E0 ()
s32 func_802D378C ()
s32 func_802D3840 ()
s32 func_802D38EC ()
s32 func_802D3998 ()
s32 func_802D39FC ()
s32 func_802D3A60 ()
s32 func_802D3C58 ()
s32 func_802D3EB8 ()
s32 func_802D3F74 ()
s32 func_802D3FC8 ()
s32 func_802D4050 ()
s32 func_802D4164 ()
s32 func_802D417C ()
s32 func_802D420C ()
s32 func_802D42AC ()
s32 func_802D4364 ()
s32 func_802D43AC ()
s32 func_802D43D0 ()
s32 func_802D43F4 ()
s32 func_802D4434 ()
s32 func_802D4488 ()
s32 func_802D4560 ()
Function Documentation
HidePlayerShadow()
ApiStatus HidePlayerShadow (ScriptInstance * script, s32 isInitialCall)
Definition at line 3 of file code_F5750.c.
Referenced by N().
DisablePlayerPhysics()
ApiStatus DisablePlayerPhysics (ScriptInstance * script, s32 isInitialCall)
Definition at line 15 of file code_F5750.c.
Referenced by N().
DisablePlayerInput()
ApiStatus DisablePlayerInput (ScriptInstance * script, s32 isInitialCall)
Definition at line 27 of file code_F5750.c.
Referenced by N().
SetPlayerPos()
ApiStatus SetPlayerPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 51 of file code_F5750.c.
Referenced by N().
SetPlayerCollisionSize()
ApiStatus SetPlayerCollisionSize (ScriptInstance * script, s32 isInitialCall)
Definition at line 69 of file code_F5750.c.
SetPlayerSpeed()
ApiStatus SetPlayerSpeed (ScriptInstance * script, s32 isInitialCall)
Definition at line 85 of file code_F5750.c.
Referenced by N().
SetPlayerJumpscale()
ApiStatus SetPlayerJumpscale (ScriptInstance * script, s32 isInitialCall)
Definition at line 90 of file code_F5750.c.
Referenced by N().
SetPlayerAnimation()
ApiStatus SetPlayerAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 96 of file code_F5750.c.
Referenced by N().
SetPlayerActionState()
ApiStatus SetPlayerActionState (ScriptInstance * script, s32 isInitialCall)
Definition at line 115 of file code_F5750.c.
SetPlayerAnimationSpeed()
ApiStatus SetPlayerAnimationSpeed (ScriptInstance * script, s32 isInitialCall)
Definition at line 120 of file code_F5750.c.
PlayerMoveTo()
ApiStatus PlayerMoveTo (ScriptInstance * script, s32 isInitialCall)
Definition at line 125 of file code_F5750.c.
Referenced by N().
func_802D1270()
s32 func_802D1270 ()
Definition at line 152 of file code_F5750.c.
func_802D1380()
s32 func_802D1380 ()
Definition at line 154 of file code_F5750.c.
player_jump()
s32 player_jump ()
Definition at line 156 of file code_F5750.c.
Referenced by PlayerJump(), PlayerJump1(), and PlayerJump2().
PlayerJump()
void PlayerJump (ScriptInstance * script, s32 isInitialCall)
Definition at line 158 of file code_F5750.c.
Referenced by N().
PlayerJump1()
void PlayerJump1 (ScriptInstance * script, s32 isInitialCall)
Definition at line 162 of file code_F5750.c.
PlayerJump2()
void PlayerJump2 (ScriptInstance * script, s32 isInitialCall)
Definition at line 166 of file code_F5750.c.
InterpPlayerYaw()
ApiStatus InterpPlayerYaw (ScriptInstance * script, s32 isInitialCall)
Definition at line 170 of file code_F5750.c.
Referenced by N().
PlayerFaceNpc()
s32 PlayerFaceNpc (ScriptInstance * script, s32 isInitialCall)
Definition at line 214 of file code_F5750.c.
Referenced by N().
GetPlayerTargetYaw()
ApiStatus GetPlayerTargetYaw (ScriptInstance * script, s32 isInitialCall)
Definition at line 216 of file code_F5750.c.
SetPlayerFlagBits()
ApiStatus SetPlayerFlagBits (ScriptInstance * script, s32 isInitialCall)
Definition at line 221 of file code_F5750.c.
GetPlayerActionState()
ApiStatus GetPlayerActionState (ScriptInstance * script, s32 isInitialCall)
Definition at line 237 of file code_F5750.c.
GetPlayerPos()
ApiStatus GetPlayerPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 243 of file code_F5750.c.
Referenced by N().
GetPlayerAnimation()
ApiStatus GetPlayerAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 256 of file code_F5750.c.
FullyRestoreHPandFP()
ApiStatus FullyRestoreHPandFP (ScriptInstance * script, s32 isInitialCall)
Definition at line 263 of file code_F5750.c.
FullyRestoreSP()
ApiStatus FullyRestoreSP (ScriptInstance * script, s32 isInitialCall)
Definition at line 271 of file code_F5750.c.
EnablePartner()
ApiStatus EnablePartner (ScriptInstance * script, s32 isInitialCall)
Definition at line 278 of file code_F5750.c.
DisablePartner()
ApiStatus DisablePartner (ScriptInstance * script, s32 isInitialCall)
Definition at line 286 of file code_F5750.c.
UseEntryHeading()
s32 UseEntryHeading ()
Definition at line 294 of file code_F5750.c.
func_802D2148()
s32 func_802D2148 ()
Definition at line 296 of file code_F5750.c.
UseExitHeading()
s32 UseExitHeading ()
Definition at line 298 of file code_F5750.c.
Referenced by N().
func_802D23F8()
s32 func_802D23F8 ()
Definition at line 300 of file code_F5750.c.
Referenced by func_802D249C().
func_802D244C()
s32 func_802D244C ()
Definition at line 302 of file code_F5750.c.
func_802D2484()
s32 func_802D2484 ()
Definition at line 304 of file code_F5750.c.
func_802D249C()
ApiStatus func_802D249C (ScriptInstance * script, s32 isInitialCall)
Definition at line 306 of file code_F5750.c.
func_802D24F4()
ApiStatus func_802D24F4 (ScriptInstance * script, s32 isInitialCall)
Definition at line 317 of file code_F5750.c.
func_802D2508()
s32 func_802D2508 ()
Definition at line 321 of file code_F5750.c.
func_802D2520()
s32 func_802D2520 ()
Definition at line 323 of file code_F5750.c.
func_802D286C()
s32 func_802D286C ()
Definition at line 325 of file code_F5750.c.
func_802D2884()
s32 func_802D2884 ()
Definition at line 327 of file code_F5750.c.
DisablePulseStone()
ApiStatus DisablePulseStone (ScriptInstance * script, s32 isInitialCall)
Definition at line 329 of file code_F5750.c.
GetCurrentPartner()
ApiStatus GetCurrentPartner (ScriptInstance * script, s32 isInitialCall)
Definition at line 342 of file code_F5750.c.
func_802D2B50()
s32 func_802D2B50 ()
Definition at line 356 of file code_F5750.c.
func_802D2B6C()
s32 func_802D2B6C ()
Definition at line 358 of file code_F5750.c.
Disable8bitMario()
ApiStatus Disable8bitMario (ScriptInstance * script, s32 isInitialCall)
Definition at line 360 of file code_F5750.c.
func_802D2C14()
s32 func_802D2C14 ()
Definition at line 378 of file code_F5750.c.
func_802D2C40()
s32 func_802D2C40 ()
Definition at line 380 of file code_F5750.c.
PlaySoundAtPlayer()
ApiStatus PlaySoundAtPlayer (ScriptInstance * script, s32 isInitialCall)
Definition at line 382 of file code_F5750.c.
Referenced by N().
func_802D2D30()
s32 func_802D2D30 ()
Definition at line 391 of file code_F5750.c.
func_802D2ED4()
s32 func_802D2ED4 ()
Definition at line 393 of file code_F5750.c.
func_802D2F34()
s32 func_802D2F34 ()
Definition at line 395 of file code_F5750.c.
func_802D2FCC()
s32 func_802D2FCC ()
Definition at line 397 of file code_F5750.c.
func_802D3028()
s32 func_802D3028 ()
Definition at line 399 of file code_F5750.c.
func_802D31E0()
s32 func_802D31E0 ()
Definition at line 401 of file code_F5750.c.
func_802D3398()
s32 func_802D3398 ()
Definition at line 403 of file code_F5750.c.
func_802D33D4()
s32 func_802D33D4 ()
Definition at line 405 of file code_F5750.c.
func_802D3474()
s32 func_802D3474 ()
Definition at line 407 of file code_F5750.c.
func_802D354C()
s32 func_802D354C ()
Definition at line 409 of file code_F5750.c.
func_802D3624()
s32 func_802D3624 ()
Definition at line 411 of file code_F5750.c.
func_802D3674()
s32 func_802D3674 ()
Definition at line 413 of file code_F5750.c.
func_802D36E0()
s32 func_802D36E0 ()
Definition at line 415 of file code_F5750.c.
func_802D378C()
s32 func_802D378C ()
Definition at line 417 of file code_F5750.c.
func_802D3840()
s32 func_802D3840 ()
Definition at line 419 of file code_F5750.c.
func_802D38EC()
s32 func_802D38EC ()
Definition at line 421 of file code_F5750.c.
func_802D3998()
s32 func_802D3998 ()
Definition at line 423 of file code_F5750.c.
func_802D39FC()
s32 func_802D39FC ()
Definition at line 425 of file code_F5750.c.
func_802D3A60()
s32 func_802D3A60 ()
Definition at line 427 of file code_F5750.c.
func_802D3C58()
s32 func_802D3C58 ()
Definition at line 429 of file code_F5750.c.
func_802D3EB8()
s32 func_802D3EB8 ()
Definition at line 431 of file code_F5750.c.
func_802D3F74()
s32 func_802D3F74 ()
Definition at line 433 of file code_F5750.c.
func_802D3FC8()
s32 func_802D3FC8 ()
Definition at line 435 of file code_F5750.c.
func_802D4050()
s32 func_802D4050 ()
Definition at line 437 of file code_F5750.c.
func_802D4164()
s32 func_802D4164 ()
Definition at line 439 of file code_F5750.c.
func_802D417C()
s32 func_802D417C ()
Definition at line 441 of file code_F5750.c.
func_802D420C()
s32 func_802D420C ()
Definition at line 443 of file code_F5750.c.
func_802D42AC()
s32 func_802D42AC ()
Definition at line 445 of file code_F5750.c.
func_802D4364()
s32 func_802D4364 ()
Definition at line 447 of file code_F5750.c.
func_802D43AC()
s32 func_802D43AC ()
Definition at line 449 of file code_F5750.c.
func_802D43D0()
s32 func_802D43D0 ()
Definition at line 451 of file code_F5750.c.
func_802D43F4()
s32 func_802D43F4 ()
Definition at line 453 of file code_F5750.c.
func_802D4434()
s32 func_802D4434 ()
Definition at line 455 of file code_F5750.c.
func_802D4488()
s32 func_802D4488 ()
Definition at line 457 of file code_F5750.c.
Referenced by clear_script_list().
func_802D4560()
s32 func_802D4560 ()
Definition at line 459 of file code_F5750.c.
Referenced by init_script_list().