src/code_1060_len_310.c File Reference - Paper Mario Documentation
code_1060_len_310.c File Reference
Functions
u32 func_80025D74 (void *arg0, const unsigned char *str, s32 count)
void func_80025C60 (void)
void func_80025CC0 (const char *fmt,...)
void func_80025CFC (const char *fmt,...)
void func_80025D38 (const char *fmt,...)
void func_80025F44 (char *arg0, char *file, s32 line, char *arg3)
Variables
const char D_80097D30 []
Function Documentation
func_80025D74()
u32 func_80025D74 (void * arg0, const unsigned char * str, s32 count)
Definition at line 35 of file code_1060_len_310.c.
Referenced by func_80025CC0(), func_80025CFC(), and func_80025D38().
func_80025C60()
void func_80025C60 (void)
Definition at line 6 of file code_1060_len_310.c.
Referenced by boot_main().
func_80025CC0()
void func_80025CC0 (const char * fmt, ...)
Definition at line 14 of file code_1060_len_310.c.
func_80025CFC()
void func_80025CFC (const char * fmt, ...)
Definition at line 21 of file code_1060_len_310.c.
Referenced by func_80025F44().
func_80025D38()
void func_80025D38 (const char * fmt, ...)
Definition at line 28 of file code_1060_len_310.c.
func_80025F44()
void func_80025F44 (char * arg0, char * file, s32 line, char * arg3)
Definition at line 84 of file code_1060_len_310.c.
Variable Documentation
D_80097D30
const char D_80097D30[] extern
Referenced by func_80025F44().