src/code_d5a50_len_5fd0.c File Reference - Paper Mario Documentation
code_d5a50_len_5fd0.c File Reference
Functions
s32 func_8013F350 ()
s32 func_8013F704 ()
s32 func_80141100 ()
s32 init_menu_icon_list ()
s32 func_801413F8 ()
s32 create_icon ()
s32 update_menu_icons ()
s32 func_80141704 ()
s32 func_80142210 ()
s32 func_8014271C ()
s32 render_menu_icon ()
s32 render_menu_icons ()
s32 func_80143C48 ()
s32 func_80144218 ()
s32 func_80144238 ()
s32 func_80144258 ()
s32 func_80144278 ()
s32 draw_menu_icon ()
s32 draw_icon_0 ()
s32 draw_icon_1 ()
s32 draw_icon_2 ()
s32 set_menu_icon_script ()
s32 get_menu_icon_script ()
s32 get_menu_icon ()
s32 free_icon ()
s32 set_icon_render_pos ()
s32 get_icon_render_pos ()
s32 func_801449DC ()
s32 set_icon_flags ()
s32 clear_icon_flags ()
s32 func_80144A5C ()
s32 func_80144C20 ()
s32 func_80144DF4 ()
s32 func_80144E4C ()
s32 func_80144E74 ()
s32 icon_set_opacity ()
s32 icon_set_tint ()
s32 func_80144F28 ()
s32 func_80144FD8 ()
s32 func_80145070 ()
s32 func_80145108 ()
s32 func_80145184 ()
s32 func_801451D4 ()
s32 func_80145224 ()
s32 func_80145274 ()
s32 func_801452B4 ()
s32 func_801452E8 ()
Variables
s32 D_8014EFC0 [] = { 0x00000000, }
s32 D_8014EFC4 [] = { 0x00011000, }
s32 D_8014EFC8 [] = { 0x00000000, }
s32 D_8014EFCC []
s32 D_8014F0C8 []
s32 D_8014F110 [] = { 0x00000000, 0x00000000, 0x00000000, 0x00000000 }
Function Documentation
func_8013F350()
s32 func_8013F350 ()
Definition at line 22 of file code_d5a50_len_5fd0.c.
func_8013F704()
s32 func_8013F704 ()
Definition at line 24 of file code_d5a50_len_5fd0.c.
func_80141100()
s32 func_80141100 ()
Definition at line 26 of file code_d5a50_len_5fd0.c.
Referenced by load_engine_data(), and step_init_state().
init_menu_icon_list()
s32 init_menu_icon_list ()
Definition at line 28 of file code_d5a50_len_5fd0.c.
func_801413F8()
s32 func_801413F8 ()
Definition at line 30 of file code_d5a50_len_5fd0.c.
create_icon()
s32 create_icon ()
Definition at line 32 of file code_d5a50_len_5fd0.c.
Referenced by initialize_status_menu(), and show_coin_counter().
update_menu_icons()
s32 update_menu_icons ()
Definition at line 34 of file code_d5a50_len_5fd0.c.
func_80141704()
s32 func_80141704 ()
Definition at line 36 of file code_d5a50_len_5fd0.c.
func_80142210()
s32 func_80142210 ()
Definition at line 38 of file code_d5a50_len_5fd0.c.
func_8014271C()
s32 func_8014271C ()
Definition at line 40 of file code_d5a50_len_5fd0.c.
render_menu_icon()
s32 render_menu_icon ()
Definition at line 42 of file code_d5a50_len_5fd0.c.
render_menu_icons()
s32 render_menu_icons ()
Definition at line 44 of file code_d5a50_len_5fd0.c.
func_80143C48()
s32 func_80143C48 ()
Definition at line 46 of file code_d5a50_len_5fd0.c.
func_80144218()
s32 func_80144218 ()
Definition at line 48 of file code_d5a50_len_5fd0.c.
func_80144238()
s32 func_80144238 ()
Definition at line 50 of file code_d5a50_len_5fd0.c.
func_80144258()
s32 func_80144258 ()
Definition at line 52 of file code_d5a50_len_5fd0.c.
func_80144278()
s32 func_80144278 ()
Definition at line 54 of file code_d5a50_len_5fd0.c.
draw_menu_icon()
s32 draw_menu_icon ()
Definition at line 56 of file code_d5a50_len_5fd0.c.
draw_icon_0()
s32 draw_icon_0 ()
Definition at line 58 of file code_d5a50_len_5fd0.c.
Referenced by coin_counter_draw_content().
draw_icon_1()
s32 draw_icon_1 ()
Definition at line 60 of file code_d5a50_len_5fd0.c.
draw_icon_2()
s32 draw_icon_2 ()
Definition at line 62 of file code_d5a50_len_5fd0.c.
Referenced by pause_update_cursor().
set_menu_icon_script()
s32 set_menu_icon_script ()
Definition at line 64 of file code_d5a50_len_5fd0.c.
get_menu_icon_script()
s32 get_menu_icon_script ()
Definition at line 66 of file code_d5a50_len_5fd0.c.
get_menu_icon()
s32 get_menu_icon ()
Definition at line 68 of file code_d5a50_len_5fd0.c.
free_icon()
s32 free_icon ()
Definition at line 70 of file code_d5a50_len_5fd0.c.
Referenced by pause_stats_cleanup(), pause_tabs_cleanup(), show_coin_counter(), and update_coin_counter().
set_icon_render_pos()
s32 set_icon_render_pos ()
Definition at line 72 of file code_d5a50_len_5fd0.c.
Referenced by coin_counter_draw_content(), and pause_update_cursor().
get_icon_render_pos()
s32 get_icon_render_pos ()
Definition at line 74 of file code_d5a50_len_5fd0.c.
func_801449DC()
s32 func_801449DC ()
Definition at line 76 of file code_d5a50_len_5fd0.c.
set_icon_flags()
s32 set_icon_flags ()
Definition at line 78 of file code_d5a50_len_5fd0.c.
Referenced by initialize_status_menu(), and show_coin_counter().
clear_icon_flags()
s32 clear_icon_flags ()
Definition at line 80 of file code_d5a50_len_5fd0.c.
Referenced by initialize_status_menu().
func_80144A5C()
s32 func_80144A5C ()
Definition at line 82 of file code_d5a50_len_5fd0.c.
func_80144C20()
s32 func_80144C20 ()
Definition at line 84 of file code_d5a50_len_5fd0.c.
func_80144DF4()
s32 func_80144DF4 ()
Definition at line 86 of file code_d5a50_len_5fd0.c.
func_80144E4C()
s32 func_80144E4C ()
Definition at line 88 of file code_d5a50_len_5fd0.c.
func_80144E74()
s32 func_80144E74 ()
Definition at line 90 of file code_d5a50_len_5fd0.c.
icon_set_opacity()
s32 icon_set_opacity ()
Definition at line 92 of file code_d5a50_len_5fd0.c.
Referenced by pause_update_cursor().
icon_set_tint()
s32 icon_set_tint ()
Definition at line 94 of file code_d5a50_len_5fd0.c.
Referenced by show_coin_counter().
func_80144F28()
s32 func_80144F28 ()
Definition at line 96 of file code_d5a50_len_5fd0.c.
func_80144FD8()
s32 func_80144FD8 ()
Definition at line 98 of file code_d5a50_len_5fd0.c.
func_80145070()
s32 func_80145070 ()
Definition at line 100 of file code_d5a50_len_5fd0.c.
func_80145108()
s32 func_80145108 ()
Definition at line 102 of file code_d5a50_len_5fd0.c.
func_80145184()
s32 func_80145184 ()
Definition at line 104 of file code_d5a50_len_5fd0.c.
func_801451D4()
s32 func_801451D4 ()
Definition at line 106 of file code_d5a50_len_5fd0.c.
func_80145224()
s32 func_80145224 ()
Definition at line 108 of file code_d5a50_len_5fd0.c.
func_80145274()
s32 func_80145274 ()
Definition at line 110 of file code_d5a50_len_5fd0.c.
func_801452B4()
s32 func_801452B4 ()
Definition at line 112 of file code_d5a50_len_5fd0.c.
Referenced by reset_status_menu().
func_801452E8()
s32 func_801452E8 ()
Definition at line 114 of file code_d5a50_len_5fd0.c.
Referenced by step_init_state().
Variable Documentation
D_8014EFC0
s32 D_8014EFC0[] = { 0x00000000, }
Definition at line 3 of file code_d5a50_len_5fd0.c.
D_8014EFC4
s32 D_8014EFC4[] = { 0x00011000, }
Definition at line 4 of file code_d5a50_len_5fd0.c.
D_8014EFC8
s32 D_8014EFC8[] = { 0x00000000, }
Definition at line 5 of file code_d5a50_len_5fd0.c.
D_8014EFCC
s32 D_8014EFCC[]
Definition at line 6 of file code_d5a50_len_5fd0.c.
D_8014F0C8
s32 D_8014F0C8[]
Definition at line 15 of file code_d5a50_len_5fd0.c.
D_8014F110
s32 D_8014F110[] = { 0x00000000, 0x00000000, 0x00000000, 0x00000000 }
Definition at line 19 of file code_d5a50_len_5fd0.c.