src/code_C50A0.c File Reference - Paper Mario Documentation
code_C50A0.c File Reference
Functions
s32 func_8012E9A0 ()
s32 func_8012EC94 ()
s32 func_8012F500 ()
s32 func_8012FE10 ()
s32 func_8012FE78 ()
s32 func_801309F0 ()
s32 func_80130A04 ()
s32 func_80130ACC ()
s32 draw_coin_sparkles ()
ItemEntity * get_item_entity (s32 itemEntityIndex)
s32 func_80130F70 ()
s32 func_80130FAC ()
s32 clear_item_entity_data ()
s32 init_item_entity_list ()
s32 func_80131128 ()
s32 make_item_entity (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 facingAngleSign, s32 pickupVar)
s32 make_item_entity_nodelay (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupVar)
s32 make_item_entity_delayed (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 pickupVar)
s32 init_got_item ()
s32 func_80131DD4 ()
s32 update_item_entities ()
s32 appendGfx_item_entity ()
s32 draw_item_entities ()
s32 func_80132D94 ()
s32 render_item_entities ()
s32 remove_item_entity_by_reference ()
s32 remove_item_entity_by_index ()
s32 func_80133A94 ()
s32 test_item_player_collision ()
s32 func_80133FC8 ()
void set_item_entity_flags (s32 index, s32 flags)
void clear_item_entity_flags (s32 index, s32 flags)
void func_801341B0 (s32 index)
s32 func_801341E8 (void)
void set_item_entity_position (s32 itemEntityIndex, f32 x, f32 y, f32 z)
void func_80134230 (s32 arg0)
s32 func_80134240 (void)
s32 update_item_entity_collectable ()
s32 func_8013559C ()
s32 update_item_entity_static ()
void func_801356C4 (void)
void func_801356CC (void)
void func_801356D4 (void)
s32 update_item_entity_temp ()
s32 func_801363A0 ()
s32 func_8013673C ()
s32 func_801369D0 ()
s32 func_80136A08 ()
Variables
s32 D_80155D88
ItemEntity ** D_801565A0
s16 D_801565A4
s16 D_801565A8
Function Documentation
func_8012E9A0()
s32 func_8012E9A0 ()
Definition at line 8 of file code_C50A0.c.
func_8012EC94()
s32 func_8012EC94 ()
Definition at line 10 of file code_C50A0.c.
func_8012F500()
s32 func_8012F500 ()
Definition at line 12 of file code_C50A0.c.
func_8012FE10()
s32 func_8012FE10 ()
Definition at line 14 of file code_C50A0.c.
func_8012FE78()
s32 func_8012FE78 ()
Definition at line 16 of file code_C50A0.c.
func_801309F0()
s32 func_801309F0 ()
Definition at line 18 of file code_C50A0.c.
func_80130A04()
s32 func_80130A04 ()
Definition at line 20 of file code_C50A0.c.
func_80130ACC()
s32 func_80130ACC ()
Definition at line 22 of file code_C50A0.c.
draw_coin_sparkles()
s32 draw_coin_sparkles ()
Definition at line 24 of file code_C50A0.c.
get_item_entity()
ItemEntity* get_item_entity (s32 itemEntityIndex)
Definition at line 26 of file code_C50A0.c.
Referenced by func_802D721C(), func_802E3650(), SetItemFlags(), SetItemPos(), ShowGotItem(), and SomeItemEntityFunc().
func_80130F70()
s32 func_80130F70 ()
Definition at line 30 of file code_C50A0.c.
func_80130FAC()
s32 func_80130FAC ()
Definition at line 32 of file code_C50A0.c.
clear_item_entity_data()
s32 clear_item_entity_data ()
Definition at line 34 of file code_C50A0.c.
Referenced by load_engine_data(), and step_init_state().
init_item_entity_list()
s32 init_item_entity_list ()
Definition at line 36 of file code_C50A0.c.
func_80131128()
s32 func_80131128 ()
Definition at line 38 of file code_C50A0.c.
make_item_entity()
s32 make_item_entity (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 facingAngleSign, s32 pickupVar)
Definition at line 43 of file code_C50A0.c.
Referenced by func_802E88EC(), make_item_entity_delayed(), and make_item_entity_nodelay().
make_item_entity_nodelay()
s32 make_item_entity_nodelay (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupVar)
Definition at line 45 of file code_C50A0.c.
Referenced by DropItemEntity(), DropItemEntityB(), func_802E38D8(), and MakeItemEntity().
make_item_entity_delayed()
s32 make_item_entity_delayed (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 pickupVar)
Definition at line 49 of file code_C50A0.c.
Referenced by OnFleeBattleDrops().
init_got_item()
s32 init_got_item ()
Definition at line 53 of file code_C50A0.c.
Referenced by ShowGotItem().
func_80131DD4()
s32 func_80131DD4 ()
Definition at line 55 of file code_C50A0.c.
update_item_entities()
s32 update_item_entities ()
Definition at line 57 of file code_C50A0.c.
Referenced by step_world().
appendGfx_item_entity()
s32 appendGfx_item_entity ()
Definition at line 59 of file code_C50A0.c.
draw_item_entities()
s32 draw_item_entities ()
Definition at line 61 of file code_C50A0.c.
func_80132D94()
s32 func_80132D94 ()
Definition at line 63 of file code_C50A0.c.
render_item_entities()
s32 render_item_entities ()
Definition at line 65 of file code_C50A0.c.
remove_item_entity_by_reference()
s32 remove_item_entity_by_reference ()
Definition at line 67 of file code_C50A0.c.
remove_item_entity_by_index()
s32 remove_item_entity_by_index ()
Definition at line 69 of file code_C50A0.c.
Referenced by RemoveItemEntity().
func_80133A94()
s32 func_80133A94 ()
Definition at line 71 of file code_C50A0.c.
test_item_player_collision()
s32 test_item_player_collision ()
Definition at line 73 of file code_C50A0.c.
func_80133FC8()
s32 func_80133FC8 ()
Definition at line 75 of file code_C50A0.c.
set_item_entity_flags()
void set_item_entity_flags (s32 index, s32 flags)
Definition at line 77 of file code_C50A0.c.
Referenced by DropItemEntityB(), func_80240000_800880(), and func_80240044_8008C4().
clear_item_entity_flags()
void clear_item_entity_flags (s32 index, s32 flags)
Definition at line 86 of file code_C50A0.c.
func_801341B0()
void func_801341B0 (s32 index)
Definition at line 92 of file code_C50A0.c.
func_801341E8()
s32 func_801341E8 (void)
Definition at line 100 of file code_C50A0.c.
set_item_entity_position()
void set_item_entity_position (s32 itemEntityIndex, f32 x, f32 y, f32 z)
Definition at line 109 of file code_C50A0.c.
Referenced by Bandit_DropCoin().
func_80134230()
void func_80134230 (s32 arg0)
Definition at line 117 of file code_C50A0.c.
Referenced by func_80282774(), and func_802827A8().
func_80134240()
s32 func_80134240 (void)
Definition at line 121 of file code_C50A0.c.
Referenced by func_80282774().
update_item_entity_collectable()
s32 update_item_entity_collectable ()
Definition at line 125 of file code_C50A0.c.
func_8013559C()
s32 func_8013559C ()
Definition at line 127 of file code_C50A0.c.
update_item_entity_static()
s32 update_item_entity_static ()
Definition at line 129 of file code_C50A0.c.
func_801356C4()
void func_801356C4 (void)
Definition at line 131 of file code_C50A0.c.
func_801356CC()
void func_801356CC (void)
Definition at line 134 of file code_C50A0.c.
func_801356D4()
void func_801356D4 (void)
Definition at line 137 of file code_C50A0.c.
update_item_entity_temp()
s32 update_item_entity_temp ()
Definition at line 140 of file code_C50A0.c.
func_801363A0()
s32 func_801363A0 ()
Definition at line 142 of file code_C50A0.c.
func_8013673C()
s32 func_8013673C ()
Definition at line 144 of file code_C50A0.c.
func_801369D0()
s32 func_801369D0 ()
Definition at line 146 of file code_C50A0.c.
func_80136A08()
s32 func_80136A08 ()
Definition at line 148 of file code_C50A0.c.
Variable Documentation
D_80155D88
s32 D_80155D88 extern
Referenced by func_80134230(), and func_80134240().
D_801565A0
ItemEntity** D_801565A0
Definition at line 4 of file code_C50A0.c.
Referenced by clear_item_entity_flags(), func_801341B0(), get_item_entity(), set_item_entity_flags(), and set_item_entity_position().
D_801565A4
s16 D_801565A4 extern
Referenced by func_801341E8().
D_801565A8
s16 D_801565A8 extern
Referenced by func_801341E8(), and set_item_entity_flags().