src/code_80850_len_3060.c File Reference - Paper Mario Documentation
code_80850_len_3060.c File Reference
Functions
void clear_player_data (void)
PlayerData * get_player_data (void)
s32 add_item (s32 itemID)
s32 get_item_count (void)
s32 get_item_empty_count (void)
s32 find_item (s32 itemID)
void sort_items (void)
s32 add_badge (s32 itemID)
s32 store_item (s32 itemID)
s32 get_stored_count (void)
s32 get_stored_empty_count (void)
void enforce_hpfp_limits (void)
void initialize_status_menu (void)
s32 status_menu_draw_number ()
s32 status_menu_draw_stat ()
s32 update_status_menu ()
void coin_counter_draw_content (s32 arg0, s32 posX, s32 posY)
void update_coin_counter (void)
void show_coin_counter (void)
void hide_coin_counter (void)
void func_800E96C8 (void)
ApiStatus ShowCoinCounter (ScriptInstance *script, s32 isInitialCall)
void draw_status_ui (void)
void open_status_menu_long (void)
void open_status_menu_short (void)
void func_800E97B8 (void)
void func_800E97E4 (void)
void func_800E9810 (void)
void func_800E983C (void)
void func_800E984C (void)
s32 func_800E9860 (void)
void func_800E9894 (void)
void func_800E98A8 (void)
void func_800E98C4 (void)
s32 func_800E98D4 (void)
void func_800E98EC (void)
void func_800E9900 (void)
s32 is_status_menu_visible (void)
void status_menu_start_blinking_hp (void)
void status_menu_stop_blinking_hp (void)
void status_menu_start_blinking_fp (void)
void status_menu_stop_blinking_fp (void)
void status_menu_start_blinking_coins (void)
void status_menu_stop_blinking_coins (void)
void status_menu_start_blinking_sp (void)
void status_menu_stop_blinking_sp (void)
void status_menu_start_blinking_sp_bars (s8 numBarsToBlink)
void status_menu_start_blinking_starpoints (void)
void status_menu_stop_blinking_starpoints (void)
void decrement_status_menu_disabled (void)
void increment_status_menu_disabled (void)
void sync_status_menu (void)
void reset_status_menu (void)
s32 is_partner_ability_active (void)
s16 add_coins (s32 amt)
s8 add_star_points (s32 amt)
u8 add_star_pieces (s32 amt)
void increment_max_SP ()
void set_max_SP (s8 newMaxSP)
void add_SP (s32 amt)
s32 recover_fp (s32 amt)
s32 recover_hp (s32 amt)
void subtract_hp (s32 amt)
s8 has_full_hp (void)
s8 has_full_fp (void)
s8 add_fortress_keys (s32 amt)
s8 subtract_fortress_keys (s8 amt)
s8 get_fortress_key_count (void)
Function Documentation
clear_player_data()
void clear_player_data (void)
Definition at line 3 of file code_80850_len_3060.c.
Referenced by load_engine_data(), and step_init_state().
get_player_data()
PlayerData* get_player_data (void)
Definition at line 98 of file code_80850_len_3060.c.
Referenced by func_8024002C_8CA92C().
add_item()
s32 add_item (s32 itemID)
Definition at line 102 of file code_80850_len_3060.c.
Referenced by add_badge(), and AddItem().
get_item_count()
s32 get_item_count (void)
Definition at line 122 of file code_80850_len_3060.c.
Referenced by get_item_empty_count(), and GetItemCount().
get_item_empty_count()
s32 get_item_empty_count (void)
Definition at line 136 of file code_80850_len_3060.c.
find_item()
s32 find_item (s32 itemID)
Definition at line 140 of file code_80850_len_3060.c.
sort_items()
void sort_items (void)
Definition at line 172 of file code_80850_len_3060.c.
Referenced by add_item(), remove_consumable(), RemoveItem(), and RemoveItemAt().
add_badge()
s32 add_badge (s32 itemID)
Definition at line 190 of file code_80850_len_3060.c.
Referenced by AddBadge().
store_item()
s32 store_item (s32 itemID)
Definition at line 213 of file code_80850_len_3060.c.
get_stored_count()
s32 get_stored_count (void)
Definition at line 232 of file code_80850_len_3060.c.
Referenced by get_stored_empty_count().
get_stored_empty_count()
s32 get_stored_empty_count (void)
Definition at line 246 of file code_80850_len_3060.c.
enforce_hpfp_limits()
void enforce_hpfp_limits (void)
Definition at line 250 of file code_80850_len_3060.c.
initialize_status_menu()
void initialize_status_menu (void)
Definition at line 271 of file code_80850_len_3060.c.
status_menu_draw_number()
s32 status_menu_draw_number ()
Definition at line 387 of file code_80850_len_3060.c.
status_menu_draw_stat()
s32 status_menu_draw_stat ()
Definition at line 389 of file code_80850_len_3060.c.
update_status_menu()
s32 update_status_menu ()
Definition at line 391 of file code_80850_len_3060.c.
Referenced by draw_status_ui().
coin_counter_draw_content()
void coin_counter_draw_content (s32 arg0, s32 posX, s32 posY)
Definition at line 393 of file code_80850_len_3060.c.
Referenced by show_coin_counter().
update_coin_counter()
void update_coin_counter (void)
Definition at line 412 of file code_80850_len_3060.c.
Referenced by draw_status_ui().
show_coin_counter()
void show_coin_counter (void)
Definition at line 452 of file code_80850_len_3060.c.
Referenced by ShowCoinCounter().
hide_coin_counter()
void hide_coin_counter (void)
Definition at line 492 of file code_80850_len_3060.c.
Referenced by ShowCoinCounter().
func_800E96C8()
void func_800E96C8 (void)
Definition at line 500 of file code_80850_len_3060.c.
ShowCoinCounter()
ApiStatus ShowCoinCounter (ScriptInstance * script, s32 isInitialCall)
Definition at line 508 of file code_80850_len_3060.c.
draw_status_ui()
void draw_status_ui (void)
Definition at line 518 of file code_80850_len_3060.c.
Referenced by func_80035DA0(), func_800360FC(), and func_800363FC().
open_status_menu_long()
void open_status_menu_long (void)
Definition at line 523 of file code_80850_len_3060.c.
open_status_menu_short()
void open_status_menu_short (void)
Definition at line 533 of file code_80850_len_3060.c.
func_800E97B8()
void func_800E97B8 (void)
Definition at line 543 of file code_80850_len_3060.c.
Referenced by DisablePlayerInput(), func_80280B44(), initialize_status_menu(), and ShowStatusMenu().
func_800E97E4()
void func_800E97E4 (void)
Definition at line 553 of file code_80850_len_3060.c.
func_800E9810()
void func_800E9810 (void)
Definition at line 564 of file code_80850_len_3060.c.
func_800E983C()
void func_800E983C (void)
Definition at line 575 of file code_80850_len_3060.c.
Referenced by DisablePlayerInput().
func_800E984C()
void func_800E984C (void)
Definition at line 579 of file code_80850_len_3060.c.
Referenced by DisablePlayerInput().
func_800E9860()
s32 func_800E9860 (void)
Definition at line 583 of file code_80850_len_3060.c.
func_800E9894()
void func_800E9894 (void)
Definition at line 597 of file code_80850_len_3060.c.
Referenced by Call800E9894(), and ShowStatusMenu().
func_800E98A8()
void func_800E98A8 (void)
Definition at line 601 of file code_80850_len_3060.c.
func_800E98C4()
void func_800E98C4 (void)
Definition at line 608 of file code_80850_len_3060.c.
Referenced by Call800E98C4SyncStatusMenu(), func_80280B44(), and ShowStatusMenu().
func_800E98D4()
s32 func_800E98D4 (void)
Definition at line 612 of file code_80850_len_3060.c.
func_800E98EC()
void func_800E98EC (void)
Definition at line 618 of file code_80850_len_3060.c.
func_800E9900()
void func_800E9900 (void)
Definition at line 622 of file code_80850_len_3060.c.
Referenced by func_80280B44().
is_status_menu_visible()
s32 is_status_menu_visible (void)
Definition at line 626 of file code_80850_len_3060.c.
status_menu_start_blinking_hp()
void status_menu_start_blinking_hp (void)
Definition at line 630 of file code_80850_len_3060.c.
Referenced by func_80218108_4CF2B8().
status_menu_stop_blinking_hp()
void status_menu_stop_blinking_hp (void)
Definition at line 645 of file code_80850_len_3060.c.
Referenced by func_80218130_4CF2E0().
status_menu_start_blinking_fp()
void status_menu_start_blinking_fp (void)
Definition at line 655 of file code_80850_len_3060.c.
Referenced by func_80218108_4CF2B8().
status_menu_stop_blinking_fp()
void status_menu_stop_blinking_fp (void)
Definition at line 670 of file code_80850_len_3060.c.
Referenced by func_80218130_4CF2E0().
status_menu_start_blinking_coins()
void status_menu_start_blinking_coins (void)
Definition at line 679 of file code_80850_len_3060.c.
status_menu_stop_blinking_coins()
void status_menu_stop_blinking_coins (void)
Definition at line 694 of file code_80850_len_3060.c.
status_menu_start_blinking_sp()
void status_menu_start_blinking_sp (void)
Definition at line 704 of file code_80850_len_3060.c.
Referenced by func_802180C8_4CF278().
status_menu_stop_blinking_sp()
void status_menu_stop_blinking_sp (void)
Definition at line 715 of file code_80850_len_3060.c.
Referenced by func_802180E8_4CF298().
status_menu_start_blinking_sp_bars()
void status_menu_start_blinking_sp_bars (s8 numBarsToBlink)
Definition at line 724 of file code_80850_len_3060.c.
status_menu_start_blinking_starpoints()
void status_menu_start_blinking_starpoints (void)
Definition at line 734 of file code_80850_len_3060.c.
status_menu_stop_blinking_starpoints()
void status_menu_stop_blinking_starpoints (void)
Definition at line 743 of file code_80850_len_3060.c.
decrement_status_menu_disabled()
void decrement_status_menu_disabled (void)
Definition at line 752 of file code_80850_len_3060.c.
Referenced by ActorSpeak(), EnableStatusMenu(), and func_802535B4().
increment_status_menu_disabled()
void increment_status_menu_disabled (void)
Definition at line 760 of file code_80850_len_3060.c.
Referenced by ActorSpeak(), EnableStatusMenu(), func_802535B4(), and UnkFunc1().
sync_status_menu()
void sync_status_menu (void)
Definition at line 766 of file code_80850_len_3060.c.
Referenced by Call800E98C4SyncStatusMenu(), func_80242224_7ECF34(), PostChapter1StatUpdate(), PostChapter2StatUpdate(), PostChapter3StatUpdate(), PostChapter4StatUpdate(), PostChapter5StatUpdate(), PostChapter6StatUpdate(), PostChapter7StatUpdate(), and SyncStatusMenu().
reset_status_menu()
void reset_status_menu (void)
Definition at line 777 of file code_80850_len_3060.c.
is_partner_ability_active()
s32 is_partner_ability_active (void)
Definition at line 1087 of file code_80850_len_3060.c.
Referenced by heroes_is_ability_active().
add_coins()
s16 add_coins (s32 amt)
Definition at line 1091 of file code_80850_len_3060.c.
Referenced by Add1Coin(), and AddCoin().
add_star_points()
s8 add_star_points (s32 amt)
Definition at line 1112 of file code_80850_len_3060.c.
Referenced by AddStarPoints().
add_star_pieces()
u8 add_star_pieces (s32 amt)
Definition at line 1131 of file code_80850_len_3060.c.
Referenced by AddStarPieces().
increment_max_SP()
void increment_max_SP ()
Definition at line 1152 of file code_80850_len_3060.c.
set_max_SP()
void set_max_SP (s8 newMaxSP)
Definition at line 1159 of file code_80850_len_3060.c.
Referenced by PostChapter1StatUpdate(), PostChapter2StatUpdate(), PostChapter3StatUpdate(), PostChapter4StatUpdate(), PostChapter5StatUpdate(), PostChapter6StatUpdate(), and PostChapter7StatUpdate().
add_SP()
void add_SP (s32 amt)
Definition at line 1166 of file code_80850_len_3060.c.
recover_fp()
s32 recover_fp (s32 amt)
Definition at line 1194 of file code_80850_len_3060.c.
recover_hp()
s32 recover_hp (s32 amt)
Definition at line 1216 of file code_80850_len_3060.c.
subtract_hp()
void subtract_hp (s32 amt)
Definition at line 1238 of file code_80850_len_3060.c.
has_full_hp()
s8 has_full_hp (void)
Definition at line 1251 of file code_80850_len_3060.c.
has_full_fp()
s8 has_full_fp (void)
Definition at line 1257 of file code_80850_len_3060.c.
add_fortress_keys()
s8 add_fortress_keys (s32 amt)
Definition at line 1263 of file code_80850_len_3060.c.
subtract_fortress_keys()
s8 subtract_fortress_keys (s8 amt)
Definition at line 1270 of file code_80850_len_3060.c.
Referenced by RemoveFortressKeys().
get_fortress_key_count()
s8 get_fortress_key_count (void)
Definition at line 1282 of file code_80850_len_3060.c.
Referenced by CountFortressKeys().