src/code_6e40_len_500.c File Reference - Paper Mario Documentation
code_6e40_len_500.c File Reference
Functions
void initialize_curtains (void)
void update_curtains (void)
s32 render_curtains ()
void set_curtain_scale_goal (f32 scale)
void set_curtain_scale (f32 scale)
void set_curtain_draw_callback (void(*callback)(void))
void set_curtain_fade_goal (f32 fade)
void set_curtain_fade (f32 fade)
Function Documentation
initialize_curtains()
void initialize_curtains (void)
Definition at line 3 of file code_6e40_len_500.c.
Referenced by step_init_state().
update_curtains()
void update_curtains (void)
Definition at line 11 of file code_6e40_len_500.c.
render_curtains()
s32 render_curtains ()
Definition at line 14 of file code_6e40_len_500.c.
set_curtain_scale_goal()
void set_curtain_scale_goal (f32 scale)
Definition at line 16 of file code_6e40_len_500.c.
Referenced by begin_state_intro(), and func_802405EC_E1EA4C().
set_curtain_scale()
void set_curtain_scale (f32 scale)
Definition at line 20 of file code_6e40_len_500.c.
set_curtain_draw_callback()
void set_curtain_draw_callback (void(*)(void) callback)
Definition at line 25 of file code_6e40_len_500.c.
set_curtain_fade_goal()
void set_curtain_fade_goal (f32 fade)
Definition at line 29 of file code_6e40_len_500.c.
Referenced by begin_state_intro().
set_curtain_fade()
void set_curtain_fade (f32 fade)
Definition at line 33 of file code_6e40_len_500.c.
Referenced by func_802405EC_E1EA4C().