src/code_DF950.c File Reference - Paper Mario Documentation
code_DF950.c File Reference
Functions
s32 func_80149250 ()
void func_80149600 (void)
s32 func_80149618 ()
s32 func_80149670 ()
s32 func_80149734 ()
s32 func_801497FC ()
s32 func_80149828 ()
s32 func_80149838 ()
s32 func_801498C4 ()
s32 func_80149908 ()
s32 func_80149974 ()
s32 func_801499EC (s32 soundID, s32 arg1, f32 arg2, f32 arg3, f32 arg4)
s32 func_80149A6C ()
s32 _play_sound ()
s32 func_80149BE4 ()
s32 stop_sound ()
void play_sound (s32 soundID)
void play_sound_at_player (s32 soundID, s32 arg1)
void play_sound_at_npc (s32 soundID, s32 arg1, s32 npcID)
s32 play_sound_at_position (s32 soundID, s32 value2, f32 posX, f32 posY, f32 posZ)
s32 func_80149E04 ()
s32 func_80149F58 ()
s32 func_8014A1B4 ()
Function Documentation
func_80149250()
s32 func_80149250 ()
Definition at line 3 of file code_DF950.c.
func_80149600()
void func_80149600 (void)
Definition at line 5 of file code_DF950.c.
func_80149618()
s32 func_80149618 ()
Definition at line 10 of file code_DF950.c.
Referenced by load_engine_data(), and step_init_state().
func_80149670()
s32 func_80149670 ()
Definition at line 12 of file code_DF950.c.
func_80149734()
s32 func_80149734 ()
Definition at line 14 of file code_DF950.c.
func_801497FC()
s32 func_801497FC ()
Definition at line 16 of file code_DF950.c.
func_80149828()
s32 func_80149828 ()
Definition at line 18 of file code_DF950.c.
func_80149838()
s32 func_80149838 ()
Definition at line 20 of file code_DF950.c.
func_801498C4()
s32 func_801498C4 ()
Definition at line 22 of file code_DF950.c.
func_80149908()
s32 func_80149908 ()
Definition at line 24 of file code_DF950.c.
func_80149974()
s32 func_80149974 ()
Definition at line 26 of file code_DF950.c.
func_801499EC()
s32 func_801499EC (s32 soundID, s32 arg1, f32 arg2, f32 arg3, f32 arg4)
Definition at line 28 of file code_DF950.c.
Referenced by func_80240060_BFA100().
func_80149A6C()
s32 func_80149A6C ()
Definition at line 30 of file code_DF950.c.
Referenced by func_802D62E4().
_play_sound()
s32 _play_sound ()
Definition at line 32 of file code_DF950.c.
Referenced by func_802D617C(), and play_sound().
func_80149BE4()
s32 func_80149BE4 ()
Definition at line 34 of file code_DF950.c.
stop_sound()
s32 stop_sound ()
Definition at line 36 of file code_DF950.c.
Referenced by set_action_state(), StopLoopingSoundAtActor(), and StopSound().
play_sound()
void play_sound (s32 soundID)
Definition at line 38 of file code_DF950.c.
Referenced by coin_counter_draw_content(), func_8003F018(), func_802E12F8(), func_802E8858(), inflict_partner_ko(), OnDefeatEnemy(), player_enter_blue_pipe(), PlaySound(), and remove_player_buffs().
play_sound_at_player()
void play_sound_at_player (s32 soundID, s32 arg1)
Definition at line 42 of file code_DF950.c.
Referenced by PlaySoundAtPlayer().
play_sound_at_npc()
void play_sound_at_npc (s32 soundID, s32 arg1, s32 npcID)
Definition at line 48 of file code_DF950.c.
play_sound_at_position()
s32 play_sound_at_position (s32 soundID, s32 value2, f32 posX, f32 posY, f32 posZ)
Definition at line 57 of file code_DF950.c.
Referenced by calc_item_check_hit(), func_80240BD8_8ACB68(), func_802D7520(), func_802D75D8(), func_802E2EB0(), func_802E3BA4(), play_sound_at_npc(), play_sound_at_player(), PlayLoopingSoundAtActor(), PlaySoundAt(), PlaySoundAtActor(), PlaySoundAtCollider(), PlaySoundAtF(), PlaySoundAtModel(), PlaySoundAtNpc(), and PlaySoundAtPart().
func_80149E04()
s32 func_80149E04 ()
Definition at line 59 of file code_DF950.c.
func_80149F58()
s32 func_80149F58 ()
Definition at line 61 of file code_DF950.c.
func_8014A1B4()
s32 func_8014A1B4 ()
Definition at line 63 of file code_DF950.c.