src/code_1A5830.c File Reference - Paper Mario Documentation
code_1A5830.c File Reference
Functions
void dispatch_event_actor (Actor *actor, Event event)
s32 func_80276F50 (Actor *actor)
void dispatch_event_general (Actor *actor, Event event)
s32 play_hit_sound ()
s32 calc_enemy_test_target ()
s32 calc_enemy_damage_target ()
s32 dispatch_damage_event_actor ()
s32 dispatch_damage_event_actor_0 ()
s32 dispatch_damage_event_actor_1 ()
ApiStatus BindTakeTurn (ScriptInstance *script, s32 isInitialCall)
ApiStatus PauseTakeTurn (ScriptInstance *script, s32 isInitialCall)
ApiStatus ResumeTakeTurn (ScriptInstance *script, s32 isInitialCall)
ApiStatus BindIdle (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableIdleScript (ScriptInstance *script, s32 isInitialCall)
ApiStatus BindHandleEvent (ScriptInstance *script, s32 isInitialCall)
ApiStatus BindNextTurn (ScriptInstance *script, s32 isInitialCall)
s32 JumpToGoal ()
s32 IdleJumpToGoal ()
s32 JumpToGoalSimple2 ()
s32 JumpWithBounce ()
s32 LandJump ()
s32 FallToGoal ()
s32 RunToGoal ()
s32 IdleRunToGoal ()
s32 JumpPartTo ()
s32 FallPartTo ()
s32 LandJumpPart ()
s32 RunPartTo ()
s32 update_lerp_battle ()
s32 FlyToGoal ()
s32 IdleFlyToGoal ()
s32 FlyPartTo ()
ApiStatus GetLastEvent (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetTargetActor (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetEnemyHP (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetActorHP (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetEnemyMaxHP (ScriptInstance *script, s32 isInitialCall)
s32 RemoveActor ()
s32 DropStarPoints ()
ApiStatus SetDefenseTable (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetStatusTable (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetIdleAnimations (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8027CC10 (ScriptInstance *script, s32 isInitialCall)
s32 EnemyDamageTarget ()
s32 EnemyFollowupAfflictTarget ()
s32 EnemyTestTarget ()
ApiStatus DispatchDamageEvent (ScriptInstance *script, s32 isInitialCall)
ApiStatus DispatchEvent (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8027D2D8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8027D32C (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetTargetOffset (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8027D434 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8027D4C8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableActorBlur (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8027D628 (ScriptInstance *script, s32 isInitialCall)
ApiStatus AfflictActor (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_8027D75C (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetEncounterState (ScriptInstance *script, s32 isInitialCall)
ApiStatus YieldTurn (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetActorSize (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetActorSize (ScriptInstance *script, s32 isInitialCall)
s32 SetPartSize ()
ApiStatus GetOriginalActorType (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCurrentActorType (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetLastDamage (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableActorGlow (ScriptInstance *script, s32 isInitialCall)
ApiStatus WasStatusInflicted (ScriptInstance *script, s32 isInitialCall)
ApiStatus CopyStatusEffects (ScriptInstance *script, s32 isInitialCall)
ApiStatus ClearStatusEffects (ScriptInstance *script, s32 isInitialCall)
Function Documentation
dispatch_event_actor()
void dispatch_event_actor (Actor * actor, Event event)
Definition at line 38 of file code_1A5830.c.
Referenced by dispatch_event_general(), and DispatchEvent().
func_80276F50()
s32 func_80276F50 (Actor * actor)
Definition at line 6 of file code_1A5830.c.
dispatch_event_general()
void dispatch_event_general (Actor * actor, Event event)
Definition at line 22 of file code_1A5830.c.
play_hit_sound()
s32 play_hit_sound ()
Definition at line 36 of file code_1A5830.c.
calc_enemy_test_target()
s32 calc_enemy_test_target ()
Definition at line 63 of file code_1A5830.c.
calc_enemy_damage_target()
s32 calc_enemy_damage_target ()
Definition at line 65 of file code_1A5830.c.
dispatch_damage_event_actor()
s32 dispatch_damage_event_actor ()
Definition at line 67 of file code_1A5830.c.
dispatch_damage_event_actor_0()
s32 dispatch_damage_event_actor_0 ()
Definition at line 69 of file code_1A5830.c.
Referenced by DispatchDamageEvent().
dispatch_damage_event_actor_1()
s32 dispatch_damage_event_actor_1 ()
Definition at line 71 of file code_1A5830.c.
BindTakeTurn()
ApiStatus BindTakeTurn (ScriptInstance * script, s32 isInitialCall)
Definition at line 73 of file code_1A5830.c.
PauseTakeTurn()
ApiStatus PauseTakeTurn (ScriptInstance * script, s32 isInitialCall)
Definition at line 87 of file code_1A5830.c.
ResumeTakeTurn()
ApiStatus ResumeTakeTurn (ScriptInstance * script, s32 isInitialCall)
Definition at line 100 of file code_1A5830.c.
BindIdle()
ApiStatus BindIdle (ScriptInstance * script, s32 isInitialCall)
Definition at line 113 of file code_1A5830.c.
EnableIdleScript()
ApiStatus EnableIdleScript (ScriptInstance * script, s32 isInitialCall)
Definition at line 140 of file code_1A5830.c.
BindHandleEvent()
ApiStatus BindHandleEvent (ScriptInstance * script, s32 isInitialCall)
Definition at line 171 of file code_1A5830.c.
BindNextTurn()
ApiStatus BindNextTurn (ScriptInstance * script, s32 isInitialCall)
Definition at line 185 of file code_1A5830.c.
JumpToGoal()
s32 JumpToGoal ()
Definition at line 199 of file code_1A5830.c.
IdleJumpToGoal()
s32 IdleJumpToGoal ()
Definition at line 201 of file code_1A5830.c.
JumpToGoalSimple2()
s32 JumpToGoalSimple2 ()
Definition at line 203 of file code_1A5830.c.
JumpWithBounce()
s32 JumpWithBounce ()
Definition at line 205 of file code_1A5830.c.
LandJump()
s32 LandJump ()
Definition at line 207 of file code_1A5830.c.
FallToGoal()
s32 FallToGoal ()
Definition at line 209 of file code_1A5830.c.
RunToGoal()
s32 RunToGoal ()
Definition at line 211 of file code_1A5830.c.
IdleRunToGoal()
s32 IdleRunToGoal ()
Definition at line 213 of file code_1A5830.c.
JumpPartTo()
s32 JumpPartTo ()
Definition at line 215 of file code_1A5830.c.
FallPartTo()
s32 FallPartTo ()
Definition at line 217 of file code_1A5830.c.
LandJumpPart()
s32 LandJumpPart ()
Definition at line 219 of file code_1A5830.c.
RunPartTo()
s32 RunPartTo ()
Definition at line 221 of file code_1A5830.c.
update_lerp_battle()
s32 update_lerp_battle ()
Definition at line 223 of file code_1A5830.c.
FlyToGoal()
s32 FlyToGoal ()
Definition at line 225 of file code_1A5830.c.
IdleFlyToGoal()
s32 IdleFlyToGoal ()
Definition at line 227 of file code_1A5830.c.
FlyPartTo()
s32 FlyPartTo ()
Definition at line 229 of file code_1A5830.c.
GetLastEvent()
ApiStatus GetLastEvent (ScriptInstance * script, s32 isInitialCall)
Definition at line 231 of file code_1A5830.c.
SetTargetActor()
ApiStatus SetTargetActor (ScriptInstance * script, s32 isInitialCall)
Definition at line 245 of file code_1A5830.c.
SetEnemyHP()
ApiStatus SetEnemyHP (ScriptInstance * script, s32 isInitialCall)
Definition at line 262 of file code_1A5830.c.
GetActorHP()
ApiStatus GetActorHP (ScriptInstance * script, s32 isInitialCall)
Definition at line 286 of file code_1A5830.c.
GetEnemyMaxHP()
ApiStatus GetEnemyMaxHP (ScriptInstance * script, s32 isInitialCall)
Definition at line 318 of file code_1A5830.c.
RemoveActor()
s32 RemoveActor ()
Definition at line 332 of file code_1A5830.c.
DropStarPoints()
s32 DropStarPoints ()
Definition at line 334 of file code_1A5830.c.
SetDefenseTable()
ApiStatus SetDefenseTable (ScriptInstance * script, s32 isInitialCall)
Definition at line 336 of file code_1A5830.c.
SetStatusTable()
ApiStatus SetStatusTable (ScriptInstance * script, s32 isInitialCall)
Definition at line 352 of file code_1A5830.c.
SetIdleAnimations()
ApiStatus SetIdleAnimations (ScriptInstance * script, s32 isInitialCall)
Definition at line 366 of file code_1A5830.c.
func_8027CC10()
ApiStatus func_8027CC10 (ScriptInstance * script, s32 isInitialCall)
Definition at line 382 of file code_1A5830.c.
EnemyDamageTarget()
s32 EnemyDamageTarget ()
Definition at line 401 of file code_1A5830.c.
EnemyFollowupAfflictTarget()
s32 EnemyFollowupAfflictTarget ()
Definition at line 403 of file code_1A5830.c.
EnemyTestTarget()
s32 EnemyTestTarget ()
Definition at line 405 of file code_1A5830.c.
DispatchDamageEvent()
ApiStatus DispatchDamageEvent (ScriptInstance * script, s32 isInitialCall)
Definition at line 407 of file code_1A5830.c.
DispatchEvent()
ApiStatus DispatchEvent (ScriptInstance * script, s32 isInitialCall)
Definition at line 429 of file code_1A5830.c.
func_8027D2D8()
ApiStatus func_8027D2D8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 441 of file code_1A5830.c.
func_8027D32C()
ApiStatus func_8027D32C (ScriptInstance * script, s32 isInitialCall)
Definition at line 452 of file code_1A5830.c.
SetTargetOffset()
ApiStatus SetTargetOffset (ScriptInstance * script, s32 isInitialCall)
Definition at line 463 of file code_1A5830.c.
func_8027D434()
ApiStatus func_8027D434 (ScriptInstance * script, s32 isInitialCall)
Definition at line 487 of file code_1A5830.c.
func_8027D4C8()
ApiStatus func_8027D4C8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 503 of file code_1A5830.c.
EnableActorBlur()
ApiStatus EnableActorBlur (ScriptInstance * script, s32 isInitialCall)
Definition at line 527 of file code_1A5830.c.
func_8027D628()
ApiStatus func_8027D628 (ScriptInstance * script, s32 isInitialCall)
Definition at line 549 of file code_1A5830.c.
AfflictActor()
ApiStatus AfflictActor (ScriptInstance * script, s32 isInitialCall)
Definition at line 560 of file code_1A5830.c.
func_8027D75C()
ApiStatus func_8027D75C (ScriptInstance * script, s32 isInitialCall)
Definition at line 599 of file code_1A5830.c.
GetEncounterState()
ApiStatus GetEncounterState (ScriptInstance * script, s32 isInitialCall)
Definition at line 612 of file code_1A5830.c.
YieldTurn()
ApiStatus YieldTurn (ScriptInstance * script, s32 isInitialCall)
Definition at line 617 of file code_1A5830.c.
SetActorSize()
ApiStatus SetActorSize (ScriptInstance * script, s32 isInitialCall)
Definition at line 622 of file code_1A5830.c.
GetActorSize()
ApiStatus GetActorSize (ScriptInstance * script, s32 isInitialCall)
Definition at line 646 of file code_1A5830.c.
SetPartSize()
s32 SetPartSize ()
Definition at line 663 of file code_1A5830.c.
GetOriginalActorType()
ApiStatus GetOriginalActorType (ScriptInstance * script, s32 isInitialCall)
Definition at line 665 of file code_1A5830.c.
GetCurrentActorType()
ApiStatus GetCurrentActorType (ScriptInstance * script, s32 isInitialCall)
Definition at line 678 of file code_1A5830.c.
GetLastDamage()
ApiStatus GetLastDamage (ScriptInstance * script, s32 isInitialCall)
Definition at line 691 of file code_1A5830.c.
EnableActorGlow()
ApiStatus EnableActorGlow (ScriptInstance * script, s32 isInitialCall)
Definition at line 705 of file code_1A5830.c.
WasStatusInflicted()
ApiStatus WasStatusInflicted (ScriptInstance * script, s32 isInitialCall)
Definition at line 734 of file code_1A5830.c.
CopyStatusEffects()
ApiStatus CopyStatusEffects (ScriptInstance * script, s32 isInitialCall)
Definition at line 751 of file code_1A5830.c.
ClearStatusEffects()
ApiStatus ClearStatusEffects (ScriptInstance * script, s32 isInitialCall)
Definition at line 782 of file code_1A5830.c.