src/code_7bb60_len_41b0.c File Reference - Paper Mario Documentation
code_7bb60_len_41b0.c File Reference
Functions
void func_800E26B0 (void)
s32 func_800E26C4 ()
void set_action_state (s32 actionState)
void move_player (s32 duration, f32 heading, f32 speed)
s32 collision_main_above ()
s32 func_800E29C8 ()
s32 func_800E2BB0 ()
s32 update_fall_state ()
s32 func_800E2F60 ()
s32 gravity_use_fall_parms ()
s32 func_800E3100 ()
s32 func_800E315C ()
s32 phys_player_land ()
f32 integrate_gravity (void)
f32 func_800E34D8 (void)
s32 func_800E3514 ()
s32 collision_main_lateral ()
s32 collision_check_player_intersecting_world ()
s32 func_800E4404 ()
s32 func_800E4508 ()
s32 func_800E45E0 ()
s32 func_800E46C8 ()
s32 func_800E4744 ()
s32 func_800E4AD8 ()
s32 func_800E4B40 ()
s32 func_800E4BB8 ()
s32 func_800E4F10 ()
s32 check_input_midair_jump ()
PartnerID get_current_partner_id (void)
s32 func_800E5098 ()
void func_800E5150 (void)
s32 func_800E5174 ()
s32 func_800E52F8 ()
s32 func_800E5348 ()
s32 func_800E546C ()
void save_ground_pos (void)
void func_800E5520 (void)
s32 func_800E5530 ()
s32 func_800E58F0 ()
s32 func_800E5938 ()
s32 func_800E59A0 ()
s32 func_800E5A2C ()
s32 func_800E5C78 ()
void update_locomotion_state (void)
void start_falling (void)
void start_bounce_a (void)
void start_bounce_b (void)
s32 check_input_hammer (void)
s32 check_input_jump ()
s32 check_input_spin ()
void func_800E636C (s32 arg0)
s32 func_800E63A4 ()
s32 func_800E6428 ()
s32 func_800E6500 ()
s32 make_disguise_npc ()
s32 func_800E66C4 ()
Variables
s32 D_8010C96C
s16 D_8010C9B0
Function Documentation
func_800E26B0()
void func_800E26B0 (void)
Definition at line 7 of file code_7bb60_len_41b0.c.
func_800E26C4()
s32 func_800E26C4 ()
Definition at line 13 of file code_7bb60_len_41b0.c.
set_action_state()
void set_action_state (s32 actionState)
Definition at line 140 of file code_7bb60_len_41b0.c.
Referenced by check_input_hammer(), func_8004309C(), func_800E0208(), func_802E44F8(), func_802E8858(), move_player(), SetPlayerActionState(), start_bounce_a(), start_bounce_b(), start_falling(), and update_locomotion_state().
move_player()
void move_player (s32 duration, f32 heading, f32 speed)
Definition at line 17 of file code_7bb60_len_41b0.c.
Referenced by func_80283BD0(), func_802E8BC0(), and PlayerMoveTo().
collision_main_above()
s32 collision_main_above ()
Definition at line 30 of file code_7bb60_len_41b0.c.
func_800E29C8()
s32 func_800E29C8 ()
Definition at line 32 of file code_7bb60_len_41b0.c.
func_800E2BB0()
s32 func_800E2BB0 ()
Definition at line 34 of file code_7bb60_len_41b0.c.
update_fall_state()
s32 update_fall_state ()
Definition at line 36 of file code_7bb60_len_41b0.c.
func_800E2F60()
s32 func_800E2F60 ()
Definition at line 38 of file code_7bb60_len_41b0.c.
gravity_use_fall_parms()
s32 gravity_use_fall_parms ()
Definition at line 40 of file code_7bb60_len_41b0.c.
Referenced by func_802E44F8().
func_800E3100()
s32 func_800E3100 ()
Definition at line 42 of file code_7bb60_len_41b0.c.
func_800E315C()
s32 func_800E315C ()
Definition at line 44 of file code_7bb60_len_41b0.c.
phys_player_land()
s32 phys_player_land ()
Definition at line 46 of file code_7bb60_len_41b0.c.
integrate_gravity()
f32 integrate_gravity (void)
Definition at line 48 of file code_7bb60_len_41b0.c.
Referenced by func_800E34D8().
func_800E34D8()
f32 func_800E34D8 (void)
Definition at line 63 of file code_7bb60_len_41b0.c.
func_800E3514()
s32 func_800E3514 ()
Definition at line 72 of file code_7bb60_len_41b0.c.
collision_main_lateral()
s32 collision_main_lateral ()
Definition at line 74 of file code_7bb60_len_41b0.c.
Referenced by func_800DFBE8().
collision_check_player_intersecting_world()
s32 collision_check_player_intersecting_world ()
Definition at line 76 of file code_7bb60_len_41b0.c.
func_800E4404()
s32 func_800E4404 ()
Definition at line 78 of file code_7bb60_len_41b0.c.
func_800E4508()
s32 func_800E4508 ()
Definition at line 80 of file code_7bb60_len_41b0.c.
func_800E45E0()
s32 func_800E45E0 ()
Definition at line 82 of file code_7bb60_len_41b0.c.
func_800E46C8()
s32 func_800E46C8 ()
Definition at line 84 of file code_7bb60_len_41b0.c.
func_800E4744()
s32 func_800E4744 ()
Definition at line 86 of file code_7bb60_len_41b0.c.
func_800E4AD8()
s32 func_800E4AD8 ()
Definition at line 88 of file code_7bb60_len_41b0.c.
func_800E4B40()
s32 func_800E4B40 ()
Definition at line 90 of file code_7bb60_len_41b0.c.
func_800E4BB8()
s32 func_800E4BB8 ()
Definition at line 92 of file code_7bb60_len_41b0.c.
Referenced by func_800DFBE8().
func_800E4F10()
s32 func_800E4F10 ()
Definition at line 94 of file code_7bb60_len_41b0.c.
check_input_midair_jump()
s32 check_input_midair_jump ()
Definition at line 96 of file code_7bb60_len_41b0.c.
get_current_partner_id()
PartnerID get_current_partner_id (void)
Definition at line 98 of file code_7bb60_len_41b0.c.
func_800E5098()
s32 func_800E5098 ()
Definition at line 102 of file code_7bb60_len_41b0.c.
func_800E5150()
void func_800E5150 (void)
Definition at line 104 of file code_7bb60_len_41b0.c.
func_800E5174()
s32 func_800E5174 ()
Definition at line 108 of file code_7bb60_len_41b0.c.
Referenced by func_800E5150().
func_800E52F8()
s32 func_800E52F8 ()
Definition at line 110 of file code_7bb60_len_41b0.c.
Referenced by func_80145CE8().
func_800E5348()
s32 func_800E5348 ()
Definition at line 112 of file code_7bb60_len_41b0.c.
func_800E546C()
s32 func_800E546C (void)
Definition at line 114 of file code_7bb60_len_41b0.c.
Referenced by func_802E88EC().
save_ground_pos()
void save_ground_pos (void)
Definition at line 116 of file code_7bb60_len_41b0.c.
func_800E5520()
void func_800E5520 (void)
Definition at line 124 of file code_7bb60_len_41b0.c.
Referenced by func_800DFC74().
func_800E5530()
s32 func_800E5530 ()
Definition at line 128 of file code_7bb60_len_41b0.c.
func_800E58F0()
s32 func_800E58F0 ()
Definition at line 130 of file code_7bb60_len_41b0.c.
func_800E5938()
s32 func_800E5938 ()
Definition at line 132 of file code_7bb60_len_41b0.c.
func_800E59A0()
s32 func_800E59A0 ()
Definition at line 134 of file code_7bb60_len_41b0.c.
func_800E5A2C()
s32 func_800E5A2C ()
Definition at line 136 of file code_7bb60_len_41b0.c.
Referenced by func_800DFBE8().
func_800E5C78()
s32 func_800E5C78 ()
Definition at line 138 of file code_7bb60_len_41b0.c.
update_locomotion_state()
void update_locomotion_state (void)
Definition at line 213 of file code_7bb60_len_41b0.c.
start_falling()
void start_falling (void)
Definition at line 221 of file code_7bb60_len_41b0.c.
start_bounce_a()
void start_bounce_a (void)
Definition at line 231 of file code_7bb60_len_41b0.c.
start_bounce_b()
void start_bounce_b (void)
Definition at line 241 of file code_7bb60_len_41b0.c.
check_input_hammer()
s32 check_input_hammer (void)
Definition at line 252 of file code_7bb60_len_41b0.c.
check_input_jump()
s32 check_input_jump ()
Definition at line 270 of file code_7bb60_len_41b0.c.
check_input_spin()
s32 check_input_spin ()
Definition at line 272 of file code_7bb60_len_41b0.c.
func_800E636C()
void func_800E636C (s32 arg0)
Definition at line 274 of file code_7bb60_len_41b0.c.
func_800E63A4()
s32 func_800E63A4 ()
Definition at line 282 of file code_7bb60_len_41b0.c.
func_800E6428()
s32 func_800E6428 ()
Definition at line 284 of file code_7bb60_len_41b0.c.
func_800E6500()
s32 func_800E6500 ()
Definition at line 286 of file code_7bb60_len_41b0.c.
make_disguise_npc()
s32 make_disguise_npc ()
Definition at line 288 of file code_7bb60_len_41b0.c.
func_800E66C4()
s32 func_800E66C4 ()
Definition at line 290 of file code_7bb60_len_41b0.c.
Variable Documentation
D_8010C96C
s32 D_8010C96C extern
Referenced by func_800E636C().
D_8010C9B0
s16 D_8010C9B0 extern
Referenced by func_800E5520().