src/code_e0b30_len_b80.c File Reference - Paper Mario Documentation
code_e0b30_len_b80.c File Reference
Functions
void transition_music_volume_to (s16 volume)
s32 get_song_variation_override_for_cur_map (SongID songID)
void func_8014A498 (void)
void func_8014A52C (void)
s32 func_8014A548 ()
s32 _set_music_track (s32 playerIndex, SongID songID, s32 variation, s32 fadeOutTime, s16 volume)
s32 set_music_track (s32 playerIndex, SongID songID, s32 variation, s32 fadeOutTime, s16 volume)
s32 func_8014A964 (s32 playerIndex, SongID songID, s32 variation, s32 fadeInTime, s16 arg4, s16 arg5)
s32 func_8014AA54 (s32 playerIndex, s32 arg1, s16 arg2)
s32 func_8014AB0C (s32 playerIndex, s16 arg1)
s32 func_8014AB60 (s32 playerIndex, s16 arg1)
s32 func_8014ABB4 (s32 playerIndex, s16 arg1)
s32 func_8014AC08 (void)
void func_8014AC5C (void)
void func_8014AC70 (void)
s32 func_8014AC94 ()
s32 func_8014AD40 ()
void func_8014ADA4 (void)
void func_8014ADF8 (SongID songID, s32 variation)
void func_8014AE6C (void)
void func_8014AEF8 (void)
void func_8014AF8C (s32 arg0, s32 arg1)
void func_8014AFA0 (void)
Function Documentation
transition_music_volume_to()
void transition_music_volume_to (s16 volume)
Definition at line 210 of file code_e0b30_len_b80.c.
Referenced by _set_music_track().
get_song_variation_override_for_cur_map()
s32 get_song_variation_override_for_cur_map (SongID songID)
If the given song ID is present in gSongsUsingVariationFlag, returns the current map's songVariation & 1 value. Otherwise, returns -1.
See also
gSongsUsingVariationFlag
Returns
-1: no override; 0: override to variation 0; 1 override to variation 1
Definition at line 11 of file code_e0b30_len_b80.c.
Referenced by _set_music_track(), and func_8014A964().
func_8014A498()
void func_8014A498 (void)
Definition at line 27 of file code_e0b30_len_b80.c.
Referenced by load_engine_data().
func_8014A52C()
void func_8014A52C (void)
Definition at line 42 of file code_e0b30_len_b80.c.
Referenced by step_init_state().
func_8014A548()
s32 func_8014A548 ()
Definition at line 47 of file code_e0b30_len_b80.c.
_set_music_track()
s32 _set_music_track (s32 playerIndex, SongID songID, s32 variation, s32 fadeOutTime, s16 volume)
Definition at line 49 of file code_e0b30_len_b80.c.
Referenced by func_8014ADA4(), func_8014AE6C(), and set_music_track().
set_music_track()
s32 set_music_track (s32 playerIndex, SongID songID, s32 variation, s32 fadeOutTime, s16 volume)
Definition at line 93 of file code_e0b30_len_b80.c.
Referenced by FadeOutMusic(), func_8014AC08(), func_8014ADF8(), func_8014AEF8(), and SetMusicTrack().
func_8014A964()
s32 func_8014A964 (s32 playerIndex, SongID songID, s32 variation, s32 fadeInTime, s16 arg4, s16 arg5)
Definition at line 101 of file code_e0b30_len_b80.c.
Referenced by FadeInMusic().
func_8014AA54()
s32 func_8014AA54 (s32 playerIndex, s32 arg1, s16 arg2)
Definition at line 135 of file code_e0b30_len_b80.c.
Referenced by func_802D5F28(), and UnkMusicFunc().
func_8014AB0C()
s32 func_8014AB0C (s32 playerIndex, s16 arg1)
Definition at line 162 of file code_e0b30_len_b80.c.
Referenced by func_802D5FA4().
func_8014AB60()
s32 func_8014AB60 (s32 playerIndex, s16 arg1)
Definition at line 173 of file code_e0b30_len_b80.c.
func_8014ABB4()
s32 func_8014ABB4 (s32 playerIndex, s16 arg1)
Definition at line 184 of file code_e0b30_len_b80.c.
func_8014AC08()
s32 func_8014AC08 (void)
Definition at line 195 of file code_e0b30_len_b80.c.
Referenced by step_init_state().
func_8014AC5C()
void func_8014AC5C (void)
Definition at line 202 of file code_e0b30_len_b80.c.
func_8014AC70()
void func_8014AC70 (void)
Definition at line 206 of file code_e0b30_len_b80.c.
func_8014AC94()
s32 func_8014AC94 ()
Definition at line 214 of file code_e0b30_len_b80.c.
func_8014AD40()
s32 func_8014AD40 ()
Definition at line 216 of file code_e0b30_len_b80.c.
func_8014ADA4()
void func_8014ADA4 (void)
Definition at line 218 of file code_e0b30_len_b80.c.
Referenced by func_802D5FD8().
func_8014ADF8()
void func_8014ADF8 (SongID songID, s32 variation)
Definition at line 227 of file code_e0b30_len_b80.c.
Referenced by func_802D5FF8().
func_8014AE6C()
void func_8014AE6C (void)
Definition at line 239 of file code_e0b30_len_b80.c.
Referenced by func_802D6050().
func_8014AEF8()
void func_8014AEF8 (void)
Definition at line 253 of file code_e0b30_len_b80.c.
Referenced by func_802D6070().
func_8014AF8C()
void func_8014AF8C (s32 arg0, s32 arg1)
Definition at line 266 of file code_e0b30_len_b80.c.
Referenced by func_802D6090().
func_8014AFA0()
void func_8014AFA0 (void)
Definition at line 273 of file code_e0b30_len_b80.c.