src/code_6240_len_c00.c File Reference - Paper Mario Documentation
code_6240_len_c00.c File Reference
Functions
void fio_serialize_state (void)
s32 get_spirits_rescued (void)
s32 fio_calc_header_checksum ()
s32 fio_validate_header_checksums ()
s32 fio_has_valid_backup ()
s32 fio_flush_backups ()
s32 fio_calc_file_checksum (s32 *saveData)
s32 fio_validate_file_checksum ()
s32 fio_fetch_saved_file_info ()
s32 fio_load_game ()
s32 fio_save_game ()
s32 fio_erase_game ()
s32 fio_deserialize_state ()
void func_8002B608 (void)
void fio_init_flash (void)
s32 fio_read_flash ()
s32 fio_write_flash ()
void fio_erase_flash (s32 pageNum)
Function Documentation
fio_serialize_state()
void fio_serialize_state (void)
Definition at line 67 of file code_6240_len_c00.c.
Referenced by func_8002B608().
get_spirits_rescued()
s32 get_spirits_rescued (void)
Definition at line 5 of file code_6240_len_c00.c.
fio_calc_header_checksum()
s32 fio_calc_header_checksum ()
Definition at line 28 of file code_6240_len_c00.c.
fio_validate_header_checksums()
s32 fio_validate_header_checksums ()
Definition at line 30 of file code_6240_len_c00.c.
fio_has_valid_backup()
s32 fio_has_valid_backup ()
Definition at line 32 of file code_6240_len_c00.c.
Referenced by step_init_state().
fio_flush_backups()
s32 fio_flush_backups ()
Definition at line 34 of file code_6240_len_c00.c.
fio_calc_file_checksum()
s32 fio_calc_file_checksum (s32 * saveData)
Definition at line 37 of file code_6240_len_c00.c.
fio_validate_file_checksum()
s32 fio_validate_file_checksum ()
Definition at line 50 of file code_6240_len_c00.c.
fio_fetch_saved_file_info()
s32 fio_fetch_saved_file_info ()
Definition at line 52 of file code_6240_len_c00.c.
fio_load_game()
s32 fio_load_game ()
Definition at line 54 of file code_6240_len_c00.c.
fio_save_game()
s32 fio_save_game ()
Definition at line 56 of file code_6240_len_c00.c.
Referenced by save_game_at_player_position().
fio_erase_game()
s32 fio_erase_game ()
Definition at line 58 of file code_6240_len_c00.c.
fio_deserialize_state()
s32 fio_deserialize_state ()
Definition at line 60 of file code_6240_len_c00.c.
func_8002B608()
void func_8002B608 (void)
Definition at line 62 of file code_6240_len_c00.c.
fio_init_flash()
void fio_init_flash (void)
Definition at line 69 of file code_6240_len_c00.c.
Referenced by load_engine_data().
fio_read_flash()
s32 fio_read_flash ()
Definition at line 73 of file code_6240_len_c00.c.
fio_write_flash()
s32 fio_write_flash ()
Definition at line 75 of file code_6240_len_c00.c.
fio_erase_flash()
void fio_erase_flash (s32 pageNum)
Definition at line 77 of file code_6240_len_c00.c.