src/code_8560.c File Reference - Paper Mario Documentation
code_8560.c File Reference
Functions
s32 func_8002D160 ()
s32 update_cameras ()
s32 render_frame ()
s32 create_cameras_a ()
s32 create_cameras_b ()
s32 initialize_next_camera ()
void set_cam_viewport (s16 id, s16 x, s16 y, s16 width, s16 height)
void get_cam_viewport (s32 camID, u16 *x, u16 *y, u16 *width, u16 *height)
void get_screen_coords (Cam camID, f32 x, f32 y, f32 z, f32 *outX, f32 *outY, f32 *outZ)
s32 func_8002E754 (s32 camID, s32 x, s32 y)
void func_8002E7CC (s32 camID, s32 *x, s32 *y, s32 *width, s32 *height)
s32 func_8002E82C ()
Function Documentation
func_8002D160()
s32 func_8002D160 ()
Definition at line 3 of file code_8560.c.
Referenced by boot_main().
update_cameras()
s32 update_cameras ()
Definition at line 5 of file code_8560.c.
Referenced by step_world().
render_frame()
s32 render_frame ()
Definition at line 7 of file code_8560.c.
create_cameras_a()
s32 create_cameras_a ()
Definition at line 9 of file code_8560.c.
Referenced by load_engine_data(), and step_init_state().
create_cameras_b()
s32 create_cameras_b ()
Definition at line 11 of file code_8560.c.
initialize_next_camera()
s32 initialize_next_camera ()
Definition at line 13 of file code_8560.c.
set_cam_viewport()
void set_cam_viewport (s16 id, s16 x, s16 y, s16 width, s16 height)
Definition at line 15 of file code_8560.c.
Referenced by SetCamViewport().
get_cam_viewport()
void get_cam_viewport (s32 camID, u16 * x, u16 * y, u16 * width, u16 * height)
Definition at line 17 of file code_8560.c.
get_screen_coords()
void get_screen_coords (Cam camID, f32 x, f32 y, f32 z, f32 * outX, f32 * outY, f32 * outZ)
Definition at line 25 of file code_8560.c.
Referenced by ActorSpeak().
func_8002E754()
s32 func_8002E754 (s32 camID, s32 x, s32 y)
Definition at line 27 of file code_8560.c.
func_8002E7CC()
void func_8002E7CC (s32 camID, s32 * x, s32 * y, s32 * width, s32 * height)
Definition at line 47 of file code_8560.c.
func_8002E82C()
s32 func_8002E82C ()
Definition at line 54 of file code_8560.c.