src/code_28910_len_5090.c File Reference - Paper Mario Documentation
code_28910_len_5090.c File Reference
Functions
void func_8004D510 (UnkAlA9C *arg0)
UnkAlA9C * func_8004D794 (s32 arg0)
s32 func_8004D7E0 ()
s32 func_8004DA0C (s32 arg0)
s32 func_8004DA74 ()
void func_8004DAA8 (UnkAlA9C *arg0)
s32 func_8004DAE0 ()
s32 func_8004DB28 ()
s32 func_8004DB4C ()
s32 func_8004DC80 ()
s32 func_8004DCB8 ()
s32 func_8004DE2C ()
void func_8004DFD4 (UnkAl19E0 *arg0)
s32 func_8004E0F4 ()
void func_8004E158 (UnkAlA9C *arg0, s32 arg1, s32 arg2, UnkAl19E0 *arg3)
s32 func_8004E344 ()
void func_8004E3A4 (UnkAlA9C *arg0)
void func_8004E444 (UnkAlA9C *arg0)
s16 func_8004E4B8 (UnkAlA9C *arg0)
s32 func_8004E5D8 ()
s32 func_8004E844 ()
s32 func_8004E880 ()
s32 func_8004E904 ()
s32 func_8004EA34 ()
s32 func_8004EAD4 ()
s32 func_8004EC04 ()
s32 func_8004EC68 ()
void func_8004FBBC (UnkAlA9C *arg0, UnkAl60 *arg1)
s32 func_8004FC08 (UnkAlA9C *arg0, u32 arg1)
void func_8004FCB4 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FCE4 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FD04 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FD38 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FD94 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FE10 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FE6C (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FEB0 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FED0 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FF3C (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FF58 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FF70 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FF88 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FFA8 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FFB4 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FFC8 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FFE4 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FFF0 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8004FFFC (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_80050004 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_80050020 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_80050128 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_8005015C (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_80050184 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_800501A8 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_800502F0 (UnkAlA9C *arg0, UnkAl60 *arg1)
void func_80050560 (UnkAlA9C *arg0, UnkAl60 *arg1)
s32 func_80050568 ()
s32 func_800505E4 ()
s32 func_80050654 ()
s32 func_8005068C ()
s32 func_800506C8 (s32 arg0, s32 arg1)
s32 func_80050770 ()
s32 func_80050818 ()
void func_8005083C (UnkAlA9C *arg0, s32 arg1, s16 arg2, s8 arg3)
s32 func_8005087C ()
s32 func_80050888 ()
s32 func_80050900 ()
s32 func_80050970 ()
s32 func_80050B90 ()
s32 func_80050C30 (u32 arg0)
void func_80050C54 (s32 arg0, s8 arg1)
s32 func_80050C64 ()
s32 func_80050CA0 ()
void func_80050D50 (UnkAl1E4 *arg0)
s32 func_80050E18 ()
s32 func_80050E84 ()
s32 func_80050EF0 ()
s32 func_80050F64 ()
s32 func_80050FD0 ()
s32 func_80051050 ()
s32 func_800510A4 ()
void func_800511BC (UnkAl834 *arg0)
void func_80051334 (UnkAl834 *arg0, UnkAl1E4 *arg1)
void func_80051434 (UnkAl834 *arg0, UnkAl1E4 *arg1)
s32 func_800521D0 ()
void func_800521E8 (UnkAl834 *arg0, UnkAl1E4 *arg1)
void func_800522A8 (UnkAl834 *arg0, UnkAl1E4 *arg1)
void func_8005232C (UnkAl834 *arg0, UnkAl1E4 *arg1)
Function Documentation
func_8004D510()
void func_8004D510 (UnkAlA9C * arg0)
Definition at line 3 of file code_28910_len_5090.c.
Referenced by func_800535C0().
func_8004D794()
UnkAlA9C* func_8004D794 (s32 arg0)
Definition at line 8 of file code_28910_len_5090.c.
Referenced by func_8004DA0C().
func_8004D7E0()
s32 func_8004D7E0 ()
Definition at line 23 of file code_28910_len_5090.c.
func_8004DA0C()
s32 func_8004DA0C (s32 arg0)
Definition at line 25 of file code_28910_len_5090.c.
Referenced by func_800559C4().
func_8004DA74()
s32 func_8004DA74 ()
Definition at line 50 of file code_28910_len_5090.c.
Referenced by func_800559E0().
func_8004DAA8()
void func_8004DAA8 (UnkAlA9C * arg0)
Definition at line 52 of file code_28910_len_5090.c.
Referenced by func_8004DA0C(), and func_8004E3A4().
func_8004DAE0()
s32 func_8004DAE0 ()
Definition at line 61 of file code_28910_len_5090.c.
Referenced by func_800559FC().
func_8004DB28()
s32 func_8004DB28 ()
Definition at line 63 of file code_28910_len_5090.c.
func_8004DB4C()
s32 func_8004DB4C ()
Definition at line 65 of file code_28910_len_5090.c.
func_8004DC80()
s32 func_8004DC80 ()
Definition at line 67 of file code_28910_len_5090.c.
Referenced by func_8004E3A4().
func_8004DCB8()
s32 func_8004DCB8 ()
Definition at line 69 of file code_28910_len_5090.c.
func_8004DE2C()
s32 func_8004DE2C ()
Definition at line 71 of file code_28910_len_5090.c.
func_8004DFD4()
void func_8004DFD4 (UnkAl19E0 * arg0)
Definition at line 73 of file code_28910_len_5090.c.
Referenced by func_800533D0().
func_8004E0F4()
s32 func_8004E0F4 ()
Definition at line 75 of file code_28910_len_5090.c.
func_8004E158()
void func_8004E158 (UnkAlA9C * arg0, s32 arg1, s32 arg2, UnkAl19E0 * arg3)
Definition at line 77 of file code_28910_len_5090.c.
Referenced by func_80052E5C().
func_8004E344()
s32 func_8004E344 ()
Definition at line 156 of file code_28910_len_5090.c.
Referenced by func_80052E5C().
func_8004E3A4()
void func_8004E3A4 (UnkAlA9C * arg0)
Definition at line 158 of file code_28910_len_5090.c.
Referenced by func_800533D0().
func_8004E444()
void func_8004E444 (UnkAlA9C * arg0)
Definition at line 179 of file code_28910_len_5090.c.
Referenced by func_8004E3A4(), and func_800533D0().
func_8004E4B8()
s16 func_8004E4B8 (UnkAlA9C * arg0)
Definition at line 181 of file code_28910_len_5090.c.
Referenced by func_800533D0().
func_8004E5D8()
s32 func_8004E5D8 ()
Definition at line 183 of file code_28910_len_5090.c.
func_8004E844()
s32 func_8004E844 ()
Definition at line 185 of file code_28910_len_5090.c.
func_8004E880()
s32 func_8004E880 ()
Definition at line 187 of file code_28910_len_5090.c.
Referenced by func_8004E158().
func_8004E904()
s32 func_8004E904 ()
Definition at line 189 of file code_28910_len_5090.c.
func_8004EA34()
s32 func_8004EA34 ()
Definition at line 191 of file code_28910_len_5090.c.
func_8004EAD4()
s32 func_8004EAD4 ()
Definition at line 193 of file code_28910_len_5090.c.
func_8004EC04()
s32 func_8004EC04 ()
Definition at line 195 of file code_28910_len_5090.c.
func_8004EC68()
s32 func_8004EC68 ()
Definition at line 197 of file code_28910_len_5090.c.
func_8004FBBC()
void func_8004FBBC (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 199 of file code_28910_len_5090.c.
func_8004FC08()
s32 func_8004FC08 (UnkAlA9C * arg0, u32 arg1)
Definition at line 212 of file code_28910_len_5090.c.
Referenced by func_8004FBBC(), and func_8004FD94().
func_8004FCB4()
void func_8004FCB4 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 227 of file code_28910_len_5090.c.
func_8004FCE4()
void func_8004FCE4 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 242 of file code_28910_len_5090.c.
func_8004FD04()
void func_8004FD04 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 246 of file code_28910_len_5090.c.
func_8004FD38()
void func_8004FD38 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 251 of file code_28910_len_5090.c.
func_8004FD94()
void func_8004FD94 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 264 of file code_28910_len_5090.c.
func_8004FE10()
void func_8004FE10 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 279 of file code_28910_len_5090.c.
func_8004FE6C()
void func_8004FE6C (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 301 of file code_28910_len_5090.c.
func_8004FEB0()
void func_8004FEB0 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 311 of file code_28910_len_5090.c.
func_8004FED0()
void func_8004FED0 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 324 of file code_28910_len_5090.c.
Referenced by func_8005083C().
func_8004FF3C()
void func_8004FF3C (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 350 of file code_28910_len_5090.c.
func_8004FF58()
void func_8004FF58 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 356 of file code_28910_len_5090.c.
func_8004FF70()
void func_8004FF70 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 361 of file code_28910_len_5090.c.
func_8004FF88()
void func_8004FF88 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 366 of file code_28910_len_5090.c.
func_8004FFA8()
void func_8004FFA8 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 370 of file code_28910_len_5090.c.
func_8004FFB4()
void func_8004FFB4 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 374 of file code_28910_len_5090.c.
func_8004FFC8()
void func_8004FFC8 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 379 of file code_28910_len_5090.c.
func_8004FFE4()
void func_8004FFE4 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 385 of file code_28910_len_5090.c.
func_8004FFF0()
void func_8004FFF0 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 389 of file code_28910_len_5090.c.
func_8004FFFC()
void func_8004FFFC (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 393 of file code_28910_len_5090.c.
func_80050004()
void func_80050004 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 397 of file code_28910_len_5090.c.
func_80050020()
void func_80050020 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 402 of file code_28910_len_5090.c.
func_80050128()
void func_80050128 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 404 of file code_28910_len_5090.c.
func_8005015C()
void func_8005015C (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 417 of file code_28910_len_5090.c.
func_80050184()
void func_80050184 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 424 of file code_28910_len_5090.c.
func_800501A8()
void func_800501A8 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 432 of file code_28910_len_5090.c.
func_800502F0()
void func_800502F0 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 434 of file code_28910_len_5090.c.
func_80050560()
void func_80050560 (UnkAlA9C * arg0, UnkAl60 * arg1)
Definition at line 436 of file code_28910_len_5090.c.
func_80050568()
s32 func_80050568 ()
Definition at line 439 of file code_28910_len_5090.c.
func_800505E4()
s32 func_800505E4 ()
Definition at line 441 of file code_28910_len_5090.c.
func_80050654()
s32 func_80050654 ()
Definition at line 443 of file code_28910_len_5090.c.
func_8005068C()
s32 func_8005068C ()
Definition at line 445 of file code_28910_len_5090.c.
func_800506C8()
s32 func_800506C8 (s32 arg0, s32 arg1)
Definition at line 447 of file code_28910_len_5090.c.
Referenced by func_80056028(), func_80056044(), and func_80056068().
func_80050770()
s32 func_80050770 ()
Definition at line 449 of file code_28910_len_5090.c.
func_80050818()
s32 func_80050818 ()
Definition at line 451 of file code_28910_len_5090.c.
func_8005083C()
void func_8005083C (UnkAlA9C * arg0, s32 arg1, s16 arg2, s8 arg3)
Definition at line 453 of file code_28910_len_5090.c.
Referenced by func_80055F58().
func_8005087C()
s32 func_8005087C ()
Definition at line 463 of file code_28910_len_5090.c.
func_80050888()
s32 func_80050888 ()
Definition at line 465 of file code_28910_len_5090.c.
func_80050900()
s32 func_80050900 ()
Definition at line 467 of file code_28910_len_5090.c.
func_80050970()
s32 func_80050970 ()
Definition at line 469 of file code_28910_len_5090.c.
func_80050B90()
s32 func_80050B90 ()
Definition at line 471 of file code_28910_len_5090.c.
Referenced by func_80052E5C().
func_80050C30()
s32 func_80050C30 (u32 arg0)
Definition at line 473 of file code_28910_len_5090.c.
Referenced by func_80055464(), func_800554A4(), func_800554E8(), func_8005553C(), func_80055590(), func_800555E4(), func_80055618(), func_8005566C(), func_800556D0(), and func_80055718().
func_80050C54()
void func_80050C54 (s32 arg0, s8 arg1)
Definition at line 481 of file code_28910_len_5090.c.
Referenced by func_80055618().
func_80050C64()
s32 func_80050C64 ()
Definition at line 485 of file code_28910_len_5090.c.
Referenced by func_800556D0(), and func_80055718().
func_80050CA0()
s32 func_80050CA0 ()
Definition at line 487 of file code_28910_len_5090.c.
Referenced by func_80055464().
func_80050D50()
void func_80050D50 (UnkAl1E4 * arg0)
Definition at line 489 of file code_28910_len_5090.c.
Referenced by func_800511BC().
func_80050E18()
s32 func_80050E18 ()
Definition at line 491 of file code_28910_len_5090.c.
Referenced by func_8005553C().
func_80050E84()
s32 func_80050E84 ()
Definition at line 493 of file code_28910_len_5090.c.
Referenced by func_80055590().
func_80050EF0()
s32 func_80050EF0 ()
Definition at line 495 of file code_28910_len_5090.c.
Referenced by func_800554A4().
func_80050F64()
s32 func_80050F64 ()
Definition at line 497 of file code_28910_len_5090.c.
Referenced by func_800554E8().
func_80050FD0()
s32 func_80050FD0 ()
Definition at line 499 of file code_28910_len_5090.c.
Referenced by func_8005566C().
func_80051050()
s32 func_80051050 ()
Definition at line 501 of file code_28910_len_5090.c.
Referenced by func_800555E4().
func_800510A4()
s32 func_800510A4 ()
Definition at line 503 of file code_28910_len_5090.c.
func_800511BC()
void func_800511BC (UnkAl834 * arg0)
Definition at line 507 of file code_28910_len_5090.c.
Referenced by func_800533D0().
func_80051334()
void func_80051334 (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 560 of file code_28910_len_5090.c.
Referenced by func_800511BC().
func_80051434()
void func_80051434 (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 562 of file code_28910_len_5090.c.
Referenced by func_800511BC().
func_800521D0()
s32 func_800521D0 ()
Definition at line 564 of file code_28910_len_5090.c.
func_800521E8()
void func_800521E8 (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 566 of file code_28910_len_5090.c.
Referenced by func_800511BC().
func_800522A8()
void func_800522A8 (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 568 of file code_28910_len_5090.c.
Referenced by func_800511BC().
func_8005232C()
void func_8005232C (UnkAl834 * arg0, UnkAl1E4 * arg1)
Definition at line 570 of file code_28910_len_5090.c.
Referenced by func_800511BC().