src/code_1370_len_7d0.c File Reference - Paper Mario Documentation
code_1370_len_7d0.c File Reference
Functions
void gfxRetrace_Callback (void)
void gfxPreNMI_Callback (void)
void boot_main (void)
s32 func_80026164 ()
Function Documentation
gfxRetrace_Callback()
void gfxRetrace_Callback (void)
Definition at line 44 of file code_1370_len_7d0.c.
Referenced by boot_main().
gfxPreNMI_Callback()
void gfxPreNMI_Callback (void)
Definition at line 48 of file code_1370_len_7d0.c.
Referenced by boot_main().
boot_main()
void boot_main (void)
Definition at line 9 of file code_1370_len_7d0.c.
Referenced by boot_idle().
func_80026164()
s32 func_80026164 ()
Definition at line 46 of file code_1370_len_7d0.c.