src/os/code_3fa50_len_f60.c File Reference - Paper Mario Documentation
code_3fa50_len_f60.c File Reference
Functions
void bcopy (const void *src, void *dst, int size)
void bzero (void *buf, int size)
s32 strchr ()
s32 strlen ()
s32 memcpy ()
s32 _Printf ()
s32 _Putfld ()
int sprintf (char *s, const char *fmt,...)
s32 proutSprintf ()
void osCreateMesgQueue (OSMesgQueue *queue, OSMesg *mesg, s32 unk)
Function Documentation
bcopy()
void bcopy (const void * src, void * dst, int size)
Definition at line 3 of file code_3fa50_len_f60.c.
Referenced by copy_matrix(), and nuContDataGet().
bzero()
void bzero (void * buf, int size)
Definition at line 5 of file code_3fa50_len_f60.c.
strchr()
s32 strchr ()
Definition at line 7 of file code_3fa50_len_f60.c.
strlen()
s32 strlen ()
Definition at line 9 of file code_3fa50_len_f60.c.
memcpy()
s32 memcpy ()
Definition at line 11 of file code_3fa50_len_f60.c.
_Printf()
s32 _Printf ()
Definition at line 13 of file code_3fa50_len_f60.c.
Referenced by func_80025CC0(), func_80025CFC(), and func_80025D38().
_Putfld()
s32 _Putfld ()
Definition at line 15 of file code_3fa50_len_f60.c.
sprintf()
int sprintf (char * s, const char * fmt, ...)
Definition at line 17 of file code_3fa50_len_f60.c.
proutSprintf()
s32 proutSprintf ()
Definition at line 19 of file code_3fa50_len_f60.c.
osCreateMesgQueue()
void osCreateMesgQueue (OSMesgQueue * queue, OSMesg * mesg, s32 unk)
Definition at line 21 of file code_3fa50_len_f60.c.
Referenced by nuPiReadRom(), and nuScCreateScheduler().