src/code_B9D60.c File Reference - Paper Mario Documentation
code_B9D60.c File Reference
Functions
void clear_character_set (void)
s32 clear_printers ()
s32 load_font_data ()
s32 load_font ()
s32 update_messages ()
s32 _update_message ()
s32 render_messages ()
s32 func_80124434 ()
s32 func_80124570 ()
s32 initialize_printer ()
s32 dma_load_string ()
s32 load_message_to_buffer ()
PrintContext * load_string (s32 stringID, s32 *a1)
s32 _load_string ()
s32 load_message_to_printer ()
s32 clamp_printer_coords ()
s32 cancel_message (PrintContext *printContext)
void set_message_images (s32 *images)
s32 set_message_string ()
s32 set_message_value ()
void close_message (PrintContext *printContext)
s32 func_80125C84 ()
s32 get_char_width ()
s32 get_string_properties ()
s32 get_string_width ()
s32 func_801264B0 ()
s32 draw_string ()
s32 func_80126790 ()
s32 func_80126EAC ()
s32 func_80126F78 ()
s32 draw_digit ()
s32 draw_number ()
void func_80127B70 (s32 arg0)
s32 func_80127BA4 ()
s32 func_80127D90 ()
void func_8012C2E0 (void)
s32 func_8012C324 ()
s32 func_8012C9A8 ()
s32 func_8012CA08 ()
s32 _draw_message_box ()
s32 func_8012D3DC ()
s32 func_8012DB58 ()
s32 func_8012E8E0 ()
Variables
Gfx D_8014C500 []
s32 D_801512F4
s16 D_80155C98
Function Documentation
clear_character_set()
void clear_character_set (void)
Definition at line 7 of file code_B9D60.c.
Referenced by load_engine_data().
clear_printers()
s32 clear_printers ()
Definition at line 11 of file code_B9D60.c.
Referenced by load_engine_data(), and step_init_state().
load_font_data()
s32 load_font_data ()
Definition at line 13 of file code_B9D60.c.
load_font()
s32 load_font ()
Definition at line 15 of file code_B9D60.c.
update_messages()
s32 update_messages ()
Definition at line 17 of file code_B9D60.c.
_update_message()
s32 _update_message ()
Definition at line 19 of file code_B9D60.c.
render_messages()
s32 render_messages ()
Definition at line 21 of file code_B9D60.c.
func_80124434()
s32 func_80124434 ()
Definition at line 23 of file code_B9D60.c.
func_80124570()
s32 func_80124570 ()
Definition at line 25 of file code_B9D60.c.
initialize_printer()
s32 initialize_printer ()
Definition at line 27 of file code_B9D60.c.
dma_load_string()
s32 dma_load_string ()
Definition at line 29 of file code_B9D60.c.
load_message_to_buffer()
s32 load_message_to_buffer ()
Definition at line 31 of file code_B9D60.c.
load_string()
PrintContext* load_string (s32 stringID, s32 * a1)
Definition at line 33 of file code_B9D60.c.
Referenced by ActorSpeak(), func_802E1204(), func_802E1298(), func_802E54CC(), and ShowBattleChoice().
_load_string()
s32 _load_string ()
Definition at line 37 of file code_B9D60.c.
Referenced by load_string().
load_message_to_printer()
s32 load_message_to_printer ()
Definition at line 39 of file code_B9D60.c.
Referenced by func_802E12F8(), and SwitchMessage().
clamp_printer_coords()
s32 clamp_printer_coords ()
Definition at line 41 of file code_B9D60.c.
cancel_message()
s32 cancel_message (PrintContext * printContext)
Definition at line 43 of file code_B9D60.c.
Referenced by CancelMessage(), and CancelMessageAndBlock().
set_message_images()
void set_message_images (s32 * images)
Definition at line 52 of file code_B9D60.c.
Referenced by SetMessageImages().
set_message_string()
s32 set_message_string ()
Definition at line 56 of file code_B9D60.c.
Referenced by SetMessageString().
set_message_value()
s32 set_message_value ()
Definition at line 58 of file code_B9D60.c.
Referenced by SetMessageValue().
close_message()
void close_message (PrintContext * printContext)
Definition at line 60 of file code_B9D60.c.
Referenced by CloseChoice(), CloseMessage(), and func_802E1350().
func_80125C84()
s32 func_80125C84 ()
Definition at line 64 of file code_B9D60.c.
get_char_width()
s32 get_char_width ()
Definition at line 66 of file code_B9D60.c.
get_string_properties()
s32 get_string_properties ()
Definition at line 68 of file code_B9D60.c.
get_string_width()
s32 get_string_width ()
Definition at line 70 of file code_B9D60.c.
func_801264B0()
s32 func_801264B0 ()
Definition at line 72 of file code_B9D60.c.
draw_string()
s32 draw_string ()
Definition at line 74 of file code_B9D60.c.
func_80126790()
s32 func_80126790 ()
Definition at line 76 of file code_B9D60.c.
func_80126EAC()
s32 func_80126EAC ()
Definition at line 78 of file code_B9D60.c.
func_80126F78()
s32 func_80126F78 ()
Definition at line 80 of file code_B9D60.c.
draw_digit()
s32 draw_digit ()
Definition at line 82 of file code_B9D60.c.
draw_number()
s32 draw_number ()
Definition at line 84 of file code_B9D60.c.
Referenced by coin_counter_draw_content().
func_80127B70()
void func_80127B70 (s32 arg0)
Definition at line 86 of file code_B9D60.c.
func_80127BA4()
s32 func_80127BA4 ()
Definition at line 90 of file code_B9D60.c.
func_80127D90()
s32 func_80127D90 ()
Definition at line 92 of file code_B9D60.c.
Referenced by func_80127B70().
func_8012C2E0()
void func_8012C2E0 (void)
Definition at line 95 of file code_B9D60.c.
func_8012C324()
s32 func_8012C324 ()
Definition at line 100 of file code_B9D60.c.
func_8012C9A8()
s32 func_8012C9A8 ()
Definition at line 102 of file code_B9D60.c.
func_8012CA08()
s32 func_8012CA08 ()
Definition at line 104 of file code_B9D60.c.
_draw_message_box()
s32 _draw_message_box ()
Definition at line 106 of file code_B9D60.c.
func_8012D3DC()
s32 func_8012D3DC ()
Definition at line 108 of file code_B9D60.c.
func_8012DB58()
s32 func_8012DB58 ()
Definition at line 110 of file code_B9D60.c.
func_8012E8E0()
s32 func_8012E8E0 ()
Definition at line 112 of file code_B9D60.c.
Variable Documentation
D_8014C500
Gfx D_8014C500[] extern
Referenced by func_8012C2E0().
D_801512F4
s32 D_801512F4 extern
Referenced by set_message_images().
D_80155C98
s16 D_80155C98 extern
Referenced by clear_character_set().