src/code_e79b0_len_1920.c File Reference - Paper Mario Documentation
code_e79b0_len_1920.c File Reference
Functions
void sort_scripts (void)
void find_script_labels (ScriptInstance *script)
void clear_script_list (void)
void init_script_list (void)
void func_802C3390 (ScriptInstance *script)
ScriptInstance * start_script (Bytecode *initialLine, s32 priority, s32 initialState)
ScriptInstance * start_script_in_group (Bytecode *initialLine, u8 priority, u8 initialState, u8 groupFlags)
s32 start_child_script ()
ScriptInstance * func_802C39F8 (ScriptInstance *parentScript, Bytecode *nextLine, s32 newState)
ScriptInstance * func_802C3C10 (ScriptInstance *script, Bytecode *line, s32 arg2)
ScriptInstance * restart_script (ScriptInstance *script)
s32 update_scripts ()
s32 func_802C3EE4 ()
void kill_script (ScriptInstance *instanceToKill)
void kill_script_by_ID (s32 id)
void kill_all_scripts (void)
s32 does_script_exist (s32 id)
s32 does_script_exist_by_ref (ScriptInstance *script)
void set_script_priority (ScriptInstance *script, s8 priority)
void set_script_timescale (ScriptInstance *script, f32 timescale)
void set_global_timespace (f32 timeScale)
f32 get_global_timespace (void)
void set_script_group (ScriptInstance *script, s8 groupFlags)
Trigger * bind_trigger (Bytecode *script, s32 flags, s32 triggerFlagIndex, s32 triggerVar0, s32 triggerVar1, s32 priority, s32 arg6)
Trigger * bind_trigger_1 (Bytecode *script, s32 flags, s32 triggerFlagIndex, s32 triggerVar0, s32 triggerVar1, s32 priority)
void suspend_group_script (ScriptInstance *script, s32 groupFlags)
void resume_group_script (ScriptInstance *script, s32 groupFlags)
s32 suspend_all_script (s32 id)
s32 resume_all_script (s32 id)
void suspend_group_script_index (s32 id, s32 groupFlags)
void resume_group_script_index (s32 id, s32 groupFlags)
void suspend_all_group (s32 groupFlags)
s32 resume_all_group (s32 groupFlags)
void suspend_group_others (ScriptInstance *script, s32 groupFlags)
void resume_group_others (ScriptInstance *script, s32 groupFlags)
ScriptInstance * get_script_by_index (s32 index)
ScriptInstance * get_script_by_id (s32 id)
void set_script_flags (ScriptInstance *script, s32 flags)
void clear_script_flags (ScriptInstance *script, s32 flags)
Variables
s32 gStaticScriptCounter = 1
s32 D_802D9CA4 = 0
f32 gGlobalTimeSpace = 1.0f
Function Documentation
sort_scripts()
void sort_scripts (void)
Definition at line 9 of file code_e79b0_len_1920.c.
find_script_labels()
void find_script_labels (ScriptInstance * script)
Definition at line 55 of file code_e79b0_len_1920.c.
Referenced by func_802C39F8(), func_802C3C10(), restart_script(), start_script(), and start_script_in_group().
clear_script_list()
void clear_script_list (void)
Definition at line 89 of file code_e79b0_len_1920.c.
Referenced by init_demo_data(), load_engine_data(), and step_init_state().
init_script_list()
void init_script_list (void)
Definition at line 122 of file code_e79b0_len_1920.c.
func_802C3390()
void func_802C3390 (ScriptInstance * script)
Definition at line 141 of file code_e79b0_len_1920.c.
Referenced by func_802C39F8(), func_802C3C10(), restart_script(), start_script(), and start_script_in_group().
start_script()
ScriptInstance* start_script (Bytecode * initialLine, s32 priority, s32 initialState)
Definition at line 161 of file code_e79b0_len_1920.c.
Referenced by _bound_script_trigger_handler(), BindIdle(), dispatch_event_actor(), DoNpcDefeat(), RestartNpcAI(), RestartNpcAux(), si_standard_trigger_executor(), and Spawn802D9D50().
start_script_in_group()
ScriptInstance* start_script_in_group (Bytecode * initialLine, u8 priority, u8 initialState, u8 groupFlags)
Definition at line 230 of file code_e79b0_len_1920.c.
Referenced by exec_ShakeCam1(), exec_ShakeCamX(), si_handle_spawn_script(), and si_handle_spawn_script_get_id().
start_child_script()
s32 start_child_script ()
Definition at line 302 of file code_e79b0_len_1920.c.
Referenced by si_handle_await_script().
func_802C39F8()
ScriptInstance* func_802C39F8 (ScriptInstance * parentScript, Bytecode * nextLine, s32 newState)
Definition at line 306 of file code_e79b0_len_1920.c.
func_802C3C10()
ScriptInstance* func_802C3C10 (ScriptInstance * script, Bytecode * line, s32 arg2)
Definition at line 375 of file code_e79b0_len_1920.c.
restart_script()
ScriptInstance* restart_script (ScriptInstance * script)
Definition at line 416 of file code_e79b0_len_1920.c.
Referenced by EnableIdleScript(), and si_handle_jump().
update_scripts()
s32 update_scripts ()
Definition at line 439 of file code_e79b0_len_1920.c.
func_802C3EE4()
s32 func_802C3EE4 ()
Definition at line 442 of file code_e79b0_len_1920.c.
kill_script()
void kill_script (ScriptInstance * instanceToKill)
Definition at line 444 of file code_e79b0_len_1920.c.
Referenced by DoNpcDefeat(), func_802C3C10(), kill_all_scripts(), kill_script_by_ID(), si_handle_end_parallel_thread(), si_handle_end_spawn_thread(), and si_handle_return().
kill_script_by_ID()
void kill_script_by_ID (s32 id)
Definition at line 496 of file code_e79b0_len_1920.c.
Referenced by BindIdle(), BindNpcHit(), BindNpcInteract(), delete_player_actor(), dispatch_event_actor(), RestartNpcAI(), RestartNpcAux(), and si_handle_kill_script().
kill_all_scripts()
void kill_all_scripts (void)
Definition at line 508 of file code_e79b0_len_1920.c.
does_script_exist()
s32 does_script_exist (s32 id)
Definition at line 520 of file code_e79b0_len_1920.c.
Referenced by _bound_script_trigger_handler(), AwaitScriptComplete(), func_8004309C(), si_handle_does_script_exist(), and si_standard_trigger_executor().
does_script_exist_by_ref()
s32 does_script_exist_by_ref (ScriptInstance * script)
Definition at line 533 of file code_e79b0_len_1920.c.
Referenced by DispatchDamageEvent(), func_80252B3C(), ItemAfflictEnemy(), and ItemDamageEnemy().
set_script_priority()
void set_script_priority (ScriptInstance * script, s8 priority)
Definition at line 544 of file code_e79b0_len_1920.c.
Referenced by si_handle_set_priority().
set_script_timescale()
void set_script_timescale (ScriptInstance * script, f32 timescale)
Definition at line 548 of file code_e79b0_len_1920.c.
Referenced by si_handle_set_timescale().
set_global_timespace()
void set_global_timespace (f32 timeScale)
Definition at line 552 of file code_e79b0_len_1920.c.
get_global_timespace()
f32 get_global_timespace (void)
Definition at line 556 of file code_e79b0_len_1920.c.
set_script_group()
void set_script_group (ScriptInstance * script, s8 groupFlags)
Definition at line 560 of file code_e79b0_len_1920.c.
Referenced by si_handle_set_group().
bind_trigger()
Trigger* bind_trigger (Bytecode * script, s32 flags, s32 triggerFlagIndex, s32 triggerVar0, s32 triggerVar1, s32 priority, s32 arg6)
Definition at line 564 of file code_e79b0_len_1920.c.
Referenced by bind_trigger_1().
bind_trigger_1()
Trigger* bind_trigger_1 (Bytecode * script, s32 flags, s32 triggerFlagIndex, s32 triggerVar0, s32 triggerVar1, s32 priority)
Definition at line 584 of file code_e79b0_len_1920.c.
suspend_group_script()
void suspend_group_script (ScriptInstance * script, s32 groupFlags)
Definition at line 589 of file code_e79b0_len_1920.c.
Referenced by resume_group_script(), suspend_all_group(), suspend_all_script(), suspend_group_others(), and suspend_group_script_index().
resume_group_script()
void resume_group_script (ScriptInstance * script, s32 groupFlags)
Definition at line 610 of file code_e79b0_len_1920.c.
Referenced by resume_all_group(), resume_all_script(), resume_group_others(), and resume_group_script_index().
suspend_all_script()
s32 suspend_all_script (s32 id)
Definition at line 631 of file code_e79b0_len_1920.c.
Referenced by EnableIdleScript(), EnableNpcAI(), EnableNpcAux(), PauseTakeTurn(), and si_handle_suspend_script().
resume_all_script()
s32 resume_all_script (s32 id)
Definition at line 643 of file code_e79b0_len_1920.c.
Referenced by EnableIdleScript(), EnableNpcAI(), EnableNpcAux(), func_8004309C(), ResumeTakeTurn(), and si_handle_resume_script().
suspend_group_script_index()
void suspend_group_script_index (s32 id, s32 groupFlags)
Definition at line 655 of file code_e79b0_len_1920.c.
resume_group_script_index()
void resume_group_script_index (s32 id, s32 groupFlags)
Definition at line 667 of file code_e79b0_len_1920.c.
suspend_all_group()
void suspend_all_group (s32 groupFlags)
Definition at line 679 of file code_e79b0_len_1920.c.
Referenced by func_802C3390(), and si_handle_suspend_all().
resume_all_group()
s32 resume_all_group (s32 groupFlags)
Definition at line 691 of file code_e79b0_len_1920.c.
Referenced by func_8004309C(), and si_handle_resume_all().
suspend_group_others()
void suspend_group_others (ScriptInstance * script, s32 groupFlags)
Definition at line 703 of file code_e79b0_len_1920.c.
Referenced by si_handle_suspend_others().
resume_group_others()
void resume_group_others (ScriptInstance * script, s32 groupFlags)
Definition at line 715 of file code_e79b0_len_1920.c.
Referenced by si_handle_resume_others().
get_script_by_index()
ScriptInstance* get_script_by_index (s32 index)
Definition at line 727 of file code_e79b0_len_1920.c.
Referenced by dispatch_event_actor(), and func_802C73B8().
get_script_by_id()
ScriptInstance* get_script_by_id (s32 id)
Definition at line 731 of file code_e79b0_len_1920.c.
set_script_flags()
void set_script_flags (ScriptInstance * script, s32 flags)
Definition at line 746 of file code_e79b0_len_1920.c.
clear_script_flags()
void clear_script_flags (ScriptInstance * script, s32 flags)
Definition at line 764 of file code_e79b0_len_1920.c.
Variable Documentation
gStaticScriptCounter
s32 gStaticScriptCounter = 1
Definition at line 3 of file code_e79b0_len_1920.c.
Referenced by func_802C39F8(), start_script(), and start_script_in_group().
D_802D9CA4
s32 D_802D9CA4 = 0
Definition at line 4 of file code_e79b0_len_1920.c.
Referenced by clear_script_list(), func_802C39F8(), init_script_list(), start_script(), and start_script_in_group().
gGlobalTimeSpace
f32 gGlobalTimeSpace = 1.0f
Definition at line 5 of file code_e79b0_len_1920.c.
Referenced by func_802C39F8(), func_802C3C10(), get_global_timespace(), restart_script(), set_global_timespace(), set_script_timescale(), start_script(), and start_script_in_group().