src/os/code_3b7f0_len_120.c File Reference - Paper Mario Documentation
code_3b7f0_len_120.c File Reference
Functions
s32 nuSiCallBackAdd ()
s32 nuSiCallBackRemove ()
Function Documentation
nuSiCallBackAdd()
s32 nuSiCallBackAdd ()
Definition at line 3 of file code_3b7f0_len_120.c.
Referenced by nuContPakMgrInit(), and nuContRmbMgrInit().
nuSiCallBackRemove()
s32 nuSiCallBackRemove ()
Definition at line 5 of file code_3b7f0_len_120.c.
Referenced by nuContPakMgrRemove(), and nuContRmbMgrRemove().