src/code_19FAF0.c File Reference - Paper Mario Documentation
code_19FAF0.c File Reference
Functions
ApiStatus func_80271210 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_80271258 (ScriptInstance *script, s32 isInitialCall)
s32 func_802712A0 ()
s32 func_80271328 ()
s32 func_802713B0 ()
ApiStatus func_8027143C (ScriptInstance *script, s32 isInitialCall)
s32 func_80271484 ()
s32 func_80271588 ()
s32 dispatch_event_player ()
s32 dispatch_event_player_continue_turn ()
s32 calc_player_test_enemy ()
s32 calc_player_damage_enemy ()
s32 dispatch_damage_event_player ()
void dispatch_damage_event_player_0 (s32 damageAmount, Event event)
void dispatch_damage_event_player_1 (s32 damageAmount, Event event)
s32 GetMenuSelection ()
s32 func_80273444 ()
s32 PlayerFallToGoal ()
s32 PlayerLandJump ()
s32 PlayerRunToGoal ()
s32 CancelablePlayerRunToGoal ()
ApiStatus GetPlayerHP (ScriptInstance *script, s32 isInitialCall)
s32 PlayerDamageEnemy ()
s32 PlayerPowerBounceEnemy ()
s32 PlayerTestEnemy ()
s32 DispatchDamagePlayerEvent ()
s32 EnablePlayerBlur ()
ApiStatus func_802749D8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802749F8 (ScriptInstance *script, s32 isInitialCall)
s32 func_80274A18 ()
s32 func_802752AC ()
s32 func_80275F00 ()
s32 DidActionSucceed ()
ApiStatus func_80276EFC (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_80276F1C (ScriptInstance *script, s32 isInitialCall)
Function Documentation
func_80271210()
ApiStatus func_80271210 (ScriptInstance * script, s32 isInitialCall)
Definition at line 4 of file code_19FAF0.c.
func_80271258()
ApiStatus func_80271258 (ScriptInstance * script, s32 isInitialCall)
Definition at line 9 of file code_19FAF0.c.
func_802712A0()
s32 func_802712A0 ()
Definition at line 14 of file code_19FAF0.c.
func_80271328()
s32 func_80271328 ()
Definition at line 16 of file code_19FAF0.c.
func_802713B0()
s32 func_802713B0 ()
Definition at line 18 of file code_19FAF0.c.
func_8027143C()
ApiStatus func_8027143C (ScriptInstance * script, s32 isInitialCall)
Definition at line 20 of file code_19FAF0.c.
func_80271484()
s32 func_80271484 ()
Definition at line 25 of file code_19FAF0.c.
func_80271588()
s32 func_80271588 ()
Definition at line 27 of file code_19FAF0.c.
dispatch_event_player()
s32 dispatch_event_player ()
Definition at line 29 of file code_19FAF0.c.
Referenced by dispatch_event_general(), and func_80276F1C().
dispatch_event_player_continue_turn()
s32 dispatch_event_player_continue_turn ()
Definition at line 31 of file code_19FAF0.c.
calc_player_test_enemy()
s32 calc_player_test_enemy ()
Definition at line 33 of file code_19FAF0.c.
calc_player_damage_enemy()
s32 calc_player_damage_enemy ()
Definition at line 35 of file code_19FAF0.c.
dispatch_damage_event_player()
s32 dispatch_damage_event_player ()
Definition at line 37 of file code_19FAF0.c.
Referenced by dispatch_damage_event_player_0(), and dispatch_damage_event_player_1().
dispatch_damage_event_player_0()
void dispatch_damage_event_player_0 (s32 damageAmount, Event event)
Definition at line 39 of file code_19FAF0.c.
dispatch_damage_event_player_1()
void dispatch_damage_event_player_1 (s32 damageAmount, Event event)
Definition at line 47 of file code_19FAF0.c.
GetMenuSelection()
s32 GetMenuSelection ()
Definition at line 51 of file code_19FAF0.c.
func_80273444()
s32 func_80273444 ()
Definition at line 53 of file code_19FAF0.c.
PlayerFallToGoal()
s32 PlayerFallToGoal ()
Definition at line 55 of file code_19FAF0.c.
PlayerLandJump()
s32 PlayerLandJump ()
Definition at line 57 of file code_19FAF0.c.
PlayerRunToGoal()
s32 PlayerRunToGoal ()
Definition at line 59 of file code_19FAF0.c.
CancelablePlayerRunToGoal()
s32 CancelablePlayerRunToGoal ()
Definition at line 61 of file code_19FAF0.c.
GetPlayerHP()
ApiStatus GetPlayerHP (ScriptInstance * script, s32 isInitialCall)
Definition at line 63 of file code_19FAF0.c.
PlayerDamageEnemy()
s32 PlayerDamageEnemy ()
Definition at line 68 of file code_19FAF0.c.
PlayerPowerBounceEnemy()
s32 PlayerPowerBounceEnemy ()
Definition at line 70 of file code_19FAF0.c.
PlayerTestEnemy()
s32 PlayerTestEnemy ()
Definition at line 72 of file code_19FAF0.c.
DispatchDamagePlayerEvent()
s32 DispatchDamagePlayerEvent ()
Definition at line 74 of file code_19FAF0.c.
EnablePlayerBlur()
s32 EnablePlayerBlur ()
Definition at line 76 of file code_19FAF0.c.
func_802749D8()
ApiStatus func_802749D8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 78 of file code_19FAF0.c.
func_802749F8()
ApiStatus func_802749F8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 83 of file code_19FAF0.c.
func_80274A18()
s32 func_80274A18 ()
Definition at line 88 of file code_19FAF0.c.
func_802752AC()
s32 func_802752AC ()
Definition at line 90 of file code_19FAF0.c.
func_80275F00()
s32 func_80275F00 ()
Definition at line 92 of file code_19FAF0.c.
DidActionSucceed()
s32 DidActionSucceed ()
Definition at line 94 of file code_19FAF0.c.
func_80276EFC()
ApiStatus func_80276EFC (ScriptInstance * script, s32 isInitialCall)
Definition at line 96 of file code_19FAF0.c.
func_80276F1C()
ApiStatus func_80276F1C (ScriptInstance * script, s32 isInitialCall)
Definition at line 101 of file code_19FAF0.c.