src/code_109660_len_1270.c File Reference - Paper Mario Documentation
code_109660_len_1270.c File Reference
Data Structures
struct struct802E7DE0
struct struct802E7F40
struct struct802E89B0
Functions
MapConfig * get_current_map_header (void)
void disable_player_input (void)
void disable_player_static_collisions (void)
void move_player (s32, f32, f32)
s32 func_802E854C ()
s32 func_802E7DE0 ()
void func_802E7F40 (Entity *entity)
void func_802E7F6C (Entity *entity)
s32 func_802E7FA0 ()
s32 func_802E8858 (Entity *entity)
f32 func_800E546C (void)
void func_802E88EC (Entity *entity, f32 arg1)
void func_802E89B0 (Entity *entity)
void func_802E89F8 (Entity *entity)
void func_802E8A58 (Entity *entity)
void func_802E8ADC (Entity *entity)
void func_802E8BC0 (Entity *entity)
void func_802E8C94 (Entity *entity)
void player_enter_blue_pipe (Entity *bluePipe)
void func_802E8D74 (Entity *entity)
void func_802E8E10 (Entity *entity)
s32 push_entity_matrix ()
f32 func_802E8F94 (Entity *entity)
Variables
f64 D_802EB370
f64 D_802EB380
Function Documentation
get_current_map_header()
MapConfig* get_current_map_header (void)
Definition at line 29 of file world.c.
Referenced by func_802E8BC0(), and GetEntryPos().
disable_player_input()
void disable_player_input (void)
Definition at line 149 of file code_77480.c.
Referenced by DisablePlayerInput(), func_802E114C(), func_802E44F8(), func_802E54CC(), and func_802E8BC0().
disable_player_static_collisions()
void disable_player_static_collisions (void)
Definition at line 131 of file code_77480.c.
Referenced by DisablePlayerPhysics(), and func_802E8BC0().
move_player()
void move_player (s32 duration, f32 heading, f32 speed)
Definition at line 17 of file code_7bb60_len_41b0.c.
Referenced by func_80283BD0(), func_802E8BC0(), and PlayerMoveTo().
func_802E854C()
s32 func_802E854C ()
Definition at line 57 of file code_109660_len_1270.c.
func_802E7DE0()
s32 func_802E7DE0 ()
Definition at line 27 of file code_109660_len_1270.c.
Referenced by func_802E7F6C().
func_802E7F40()
void func_802E7F40 (Entity * entity)
Definition at line 38 of file code_109660_len_1270.c.
func_802E7F6C()
void func_802E7F6C (Entity * entity)
Definition at line 46 of file code_109660_len_1270.c.
Referenced by func_802E8858().
func_802E7FA0()
s32 func_802E7FA0 ()
Definition at line 53 of file code_109660_len_1270.c.
func_802E8858()
s32 func_802E8858 (Entity * entity)
Definition at line 59 of file code_109660_len_1270.c.
func_800E546C()
f32 func_800E546C (void)
Definition at line 114 of file code_7bb60_len_41b0.c.
Referenced by func_802E88EC().
func_802E88EC()
void func_802E88EC (Entity * entity, f32 arg1)
Definition at line 81 of file code_109660_len_1270.c.
func_802E89B0()
void func_802E89B0 (Entity * entity)
Definition at line 111 of file code_109660_len_1270.c.
func_802E89F8()
void func_802E89F8 (Entity * entity)
Definition at line 123 of file code_109660_len_1270.c.
func_802E8A58()
void func_802E8A58 (Entity * entity)
Definition at line 137 of file code_109660_len_1270.c.
func_802E8ADC()
void func_802E8ADC (Entity * entity)
Definition at line 163 of file code_109660_len_1270.c.
func_802E8BC0()
void func_802E8BC0 (Entity * entity)
Definition at line 191 of file code_109660_len_1270.c.
func_802E8C94()
void func_802E8C94 (Entity * entity)
Definition at line 215 of file code_109660_len_1270.c.
player_enter_blue_pipe()
void player_enter_blue_pipe (Entity * bluePipe)
Definition at line 223 of file code_109660_len_1270.c.
func_802E8D74()
void func_802E8D74 (Entity * entity)
Definition at line 236 of file code_109660_len_1270.c.
func_802E8E10()
void func_802E8E10 (Entity * entity)
Definition at line 251 of file code_109660_len_1270.c.
push_entity_matrix()
s32 push_entity_matrix ()
Definition at line 259 of file code_109660_len_1270.c.
Referenced by func_802E8F94().
func_802E8F94()
f32 func_802E8F94 (Entity * entity)
Definition at line 261 of file code_109660_len_1270.c.
Variable Documentation
D_802EB370
f64 D_802EB370 extern
Referenced by func_802E88EC().
D_802EB380
f64 D_802EB380 extern
Referenced by func_802E89F8().