src/code_dba20_len_350.c File Reference - Paper Mario Documentation
code_dba20_len_350.c File Reference
Functions
void clear_saved_variables (void)
void clear_area_flags (void)
s32 clear_global_flag (s32 index)
s32 set_global_flag (s32 index)
s32 get_global_flag (s32 index)
s8 set_global_byte (s32 index, s8 value)
s32 get_global_byte (s32 index)
s32 clear_area_flag (s32 index)
s32 set_area_flag (s32 index)
s32 get_area_flag (s32 index)
s8 set_area_byte (s32 index, s8 value)
s32 get_area_byte (s32 index)
Function Documentation
clear_saved_variables()
void clear_saved_variables (void)
Definition at line 3 of file code_dba20_len_350.c.
Referenced by init_demo_data(), load_engine_data(), and step_init_state().
clear_area_flags()
void clear_area_flags (void)
Definition at line 24 of file code_dba20_len_350.c.
clear_global_flag()
s32 clear_global_flag (s32 index)
Definition at line 39 of file code_dba20_len_350.c.
set_global_flag()
s32 set_global_flag (s32 index)
Definition at line 63 of file code_dba20_len_350.c.
Referenced by func_802E1204(), and func_802E54CC().
get_global_flag()
s32 get_global_flag (s32 index)
Definition at line 87 of file code_dba20_len_350.c.
Referenced by func_802E1204(), func_802E3B08(), func_802E4154(), func_802E54CC(), func_802E56EC(), func_802E88EC(), func_802E89B0(), func_802E8F94(), and get_variable().
set_global_byte()
s8 set_global_byte (s32 index, s8 value)
Definition at line 107 of file code_dba20_len_350.c.
get_global_byte()
s32 get_global_byte (s32 index)
Definition at line 115 of file code_dba20_len_350.c.
Referenced by get_float_variable(), get_variable(), is_actor_hp_bar_visible(), and is_actortype_hpbar_visible().
clear_area_flag()
s32 clear_area_flag (s32 index)
Definition at line 119 of file code_dba20_len_350.c.
set_area_flag()
s32 set_area_flag (s32 index)
Definition at line 133 of file code_dba20_len_350.c.
Referenced by func_802E1EA8().
get_area_flag()
s32 get_area_flag (s32 index)
Definition at line 147 of file code_dba20_len_350.c.
Referenced by get_variable().
set_area_byte()
s8 set_area_byte (s32 index, s8 value)
Definition at line 159 of file code_dba20_len_350.c.
get_area_byte()
s32 get_area_byte (s32 index)
Definition at line 167 of file code_dba20_len_350.c.
Referenced by get_float_variable(), and get_variable().