src/code_FBE10.c File Reference - Paper Mario Documentation
code_FBE10.c File Reference
Functions
void func_802D7460 (f32 x, f32 y, f32 z, s32 arg3)
void func_802D74C0 (f32 x, f32 y, f32 z, s32 arg3)
ApiStatus func_802D7520 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D75D8 (ScriptInstance *script, s32 isInitialCall)
s32 func_802D7690 ()
s32 ShowEmote (ScriptInstance *script, s32 isInitialCall)
ApiStatus RemoveEffect (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D7B10 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D7B44 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D7B74 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D7BA4 (ScriptInstance *script, s32 isInitialCall)
ApiStatus Spawn802D9D50 (ScriptInstance *script, s32 isInitialCall)
s32 func_802D7E08 ()
s32 ShowSleepBubble ()
s32 func_802D8248 ()
s32 PlayEffect ()
Function Documentation
func_802D7460()
void func_802D7460 (f32 x, f32 y, f32 z, s32 arg3)
Definition at line 3 of file code_FBE10.c.
Referenced by func_802D7520(), and UnkBattleFunc2().
func_802D74C0()
void func_802D74C0 (f32 x, f32 y, f32 z, s32 arg3)
Definition at line 5 of file code_FBE10.c.
Referenced by func_802D75D8(), and UnkBattleFunc2_2().
func_802D7520()
ApiStatus func_802D7520 (ScriptInstance * script, s32 isInitialCall)
Definition at line 7 of file code_FBE10.c.
func_802D75D8()
ApiStatus func_802D75D8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 18 of file code_FBE10.c.
func_802D7690()
s32 func_802D7690 ()
Definition at line 29 of file code_FBE10.c.
ShowEmote()
s32 ShowEmote (ScriptInstance * script, s32 isInitialCall)
Definition at line 31 of file code_FBE10.c.
Referenced by N().
RemoveEffect()
ApiStatus RemoveEffect (ScriptInstance * script, s32 isInitialCall)
Definition at line 33 of file code_FBE10.c.
func_802D7B10()
ApiStatus func_802D7B10 (ScriptInstance * script, s32 isInitialCall)
Definition at line 40 of file code_FBE10.c.
func_802D7B44()
ApiStatus func_802D7B44 (ScriptInstance * script, s32 isInitialCall)
Definition at line 48 of file code_FBE10.c.
func_802D7B74()
ApiStatus func_802D7B74 (ScriptInstance * script, s32 isInitialCall)
Definition at line 57 of file code_FBE10.c.
func_802D7BA4()
ApiStatus func_802D7BA4 (ScriptInstance * script, s32 isInitialCall)
Definition at line 66 of file code_FBE10.c.
Spawn802D9D50()
ApiStatus Spawn802D9D50 (ScriptInstance * script, s32 isInitialCall)
Definition at line 97 of file code_FBE10.c.
func_802D7E08()
s32 func_802D7E08 ()
Definition at line 119 of file code_FBE10.c.
ShowSleepBubble()
s32 ShowSleepBubble ()
Definition at line 121 of file code_FBE10.c.
func_802D8248()
s32 func_802D8248 ()
Definition at line 123 of file code_FBE10.c.
PlayEffect()
s32 PlayEffect ()
Definition at line 125 of file code_FBE10.c.
Referenced by N().