src/code_31650.c File Reference - Paper Mario Documentation
code_31650.c File Reference
Functions
s32 func_80056250 ()
void func_800565A4 (void)
Acmd * alAudioFrame (Acmd *cmdList, s32 *cmdLen, s16 *outBuf, s32 outLen)
void func_80056D34 (void)
void func_80056D44 (s16 arg0)
s16 func_80056D50 (void)
void func_80056D5C (s8 arg0)
void func_80056D78 (u8 arg0, u16 arg1)
u16 func_80056DA4 (u8 arg0, u16 arg1)
void func_80056DCC (u8 arg0, u8 arg1)
s32 func_80056E34 ()
void func_80056EC0 (u8 arg0, s8 arg1)
void func_80056EE8 (u8 arg0)
void func_80056F78 (u8 arg0)
void func_80056FA4 (u8 arg0, u8 arg1, s32 arg2, f32 arg3, s16 arg4, u8 arg5, u8 arg6, s32 arg7)
void func_80057224 (u8 arg0, UnkAl30 *arg1)
void func_80057344 (u8 arg0, f32 arg1)
void func_8005736C (u8 arg0, s16 arg1, s32 arg2, u8 arg3, u8 arg4)
void func_80057548 (u8 arg0, u8 arg1, u8 arg2)
void func_800576EC (u8 arg0, s32 arg1, s32 arg2)
s32 func_80057874 ()
s32 func_800579D8 ()
s32 func_80057B64 (u8 arg0)
s32 func_80057B8C (u8 arg0)
f32 func_80057BB4 (u8 arg0)
u8 func_80057BDC (u8 arg0)
s16 func_80057C04 (u8 arg0)
s16 func_80057C2C (u8 arg0)
s32 func_80057C54 ()
s32 func_80057D0C ()
void func_80057DC8 (s32 arg0)
void func_80057E08 (u8 arg0)
void func_80057E5C (u8 arg0)
void func_80057EB0 (void)
void func_80057ED0 (s16 arg0)
s32 func_80057F20 ()
void * alHeapAlloc (ALHeap *heap, s32 arg1, s32 size)
void func_80057FD8 (u8 *src, u8 *dst, s32 size)
s32 func_80058004 ()
s32 func_80058050 ()
s32 func_80058B20 ()
s32 func_80058C6C ()
Variables
UnkAl0 * D_80078E50 = NULL
UnkAl0 * D_80078E54 = NULL
s8 D_80078E58 = 0
s16 D_80078E5A = 0x7FFF
s8 D_80078E5C = 0
s32 D_80078E60 []
Function Documentation
func_80056250()
s32 func_80056250 ()
Definition at line 16 of file code_31650.c.
func_800565A4()
void func_800565A4 (void)
Definition at line 18 of file code_31650.c.
alAudioFrame()
Acmd* alAudioFrame (Acmd * cmdList, s32 * cmdLen, s16 * outBuf, s32 outLen)
Definition at line 26 of file code_31650.c.
func_80056D34()
void func_80056D34 (void)
Definition at line 28 of file code_31650.c.
Referenced by func_8004B328().
func_80056D44()
void func_80056D44 (s16 arg0)
Definition at line 32 of file code_31650.c.
Referenced by func_8004B328().
func_80056D50()
s16 func_80056D50 (void)
Definition at line 36 of file code_31650.c.
Referenced by func_8004B328().
func_80056D5C()
void func_80056D5C (s8 arg0)
Definition at line 41 of file code_31650.c.
Referenced by func_8005615C(), and func_80056180().
func_80056D78()
void func_80056D78 (u8 arg0, u16 arg1)
Definition at line 49 of file code_31650.c.
Referenced by func_80053A98().
func_80056DA4()
u16 func_80056DA4 (u8 arg0, u16 arg1)
Definition at line 55 of file code_31650.c.
func_80056DCC()
void func_80056DCC (u8 arg0, u8 arg1)
Definition at line 61 of file code_31650.c.
Referenced by func_80053654().
func_80056E34()
s32 func_80056E34 ()
Definition at line 69 of file code_31650.c.
func_80056EC0()
void func_80056EC0 (u8 arg0, s8 arg1)
Definition at line 71 of file code_31650.c.
Referenced by func_80052E5C().
func_80056EE8()
void func_80056EE8 (u8 arg0)
Definition at line 77 of file code_31650.c.
Referenced by func_800525A0(), and func_80053654().
func_80056F78()
void func_80056F78 (u8 arg0)
Definition at line 79 of file code_31650.c.
func_80056FA4()
void func_80056FA4 (u8 arg0, u8 arg1, s32 arg2, f32 arg3, s16 arg4, u8 arg5, u8 arg6, s32 arg7)
Definition at line 86 of file code_31650.c.
Referenced by func_80053654().
func_80057224()
void func_80057224 (u8 arg0, UnkAl30 * arg1)
Definition at line 88 of file code_31650.c.
Referenced by func_80052E5C().
func_80057344()
void func_80057344 (u8 arg0, f32 arg1)
Definition at line 90 of file code_31650.c.
Referenced by func_80053654().
func_8005736C()
void func_8005736C (u8 arg0, s16 arg1, s32 arg2, u8 arg3, u8 arg4)
Definition at line 96 of file code_31650.c.
Referenced by func_80053654().
func_80057548()
void func_80057548 (u8 arg0, u8 arg1, u8 arg2)
Definition at line 98 of file code_31650.c.
Referenced by func_80053654().
func_800576EC()
void func_800576EC (u8 arg0, s32 arg1, s32 arg2)
Definition at line 100 of file code_31650.c.
Referenced by func_80053888(), and func_800538C4().
func_80057874()
s32 func_80057874 ()
Definition at line 102 of file code_31650.c.
func_800579D8()
s32 func_800579D8 ()
Definition at line 104 of file code_31650.c.
func_80057B64()
s32 func_80057B64 (u8 arg0)
Definition at line 106 of file code_31650.c.
func_80057B8C()
s32 func_80057B8C (u8 arg0)
Definition at line 112 of file code_31650.c.
func_80057BB4()
f32 func_80057BB4 (u8 arg0)
Definition at line 118 of file code_31650.c.
func_80057BDC()
u8 func_80057BDC (u8 arg0)
Definition at line 124 of file code_31650.c.
func_80057C04()
s16 func_80057C04 (u8 arg0)
Definition at line 130 of file code_31650.c.
func_80057C2C()
s16 func_80057C2C (u8 arg0)
Definition at line 136 of file code_31650.c.
func_80057C54()
s32 func_80057C54 ()
Definition at line 142 of file code_31650.c.
func_80057D0C()
s32 func_80057D0C ()
Definition at line 144 of file code_31650.c.
func_80057DC8()
void func_80057DC8 (s32 arg0)
Definition at line 146 of file code_31650.c.
Referenced by func_80053654().
func_80057E08()
void func_80057E08 (u8 arg0)
Definition at line 160 of file code_31650.c.
Referenced by func_80053654().
func_80057E5C()
void func_80057E5C (u8 arg0)
Definition at line 175 of file code_31650.c.
Referenced by func_80053654().
func_80057EB0()
void func_80057EB0 (void)
Definition at line 190 of file code_31650.c.
Referenced by func_80053654().
func_80057ED0()
void func_80057ED0 (s16 arg0)
Definition at line 196 of file code_31650.c.
Referenced by func_80052E5C().
func_80057F20()
s32 func_80057F20 ()
Definition at line 211 of file code_31650.c.
alHeapAlloc()
void* alHeapAlloc (ALHeap * heap, s32 arg1, s32 size)
Definition at line 213 of file code_31650.c.
Referenced by func_80052E5C().
func_80057FD8()
void func_80057FD8 (u8 * src, u8 * dst, s32 size)
Definition at line 225 of file code_31650.c.
func_80058004()
s32 func_80058004 ()
Definition at line 235 of file code_31650.c.
func_80058050()
s32 func_80058050 ()
Definition at line 237 of file code_31650.c.
func_80058B20()
s32 func_80058B20 ()
Definition at line 239 of file code_31650.c.
func_80058C6C()
s32 func_80058C6C ()
Definition at line 241 of file code_31650.c.
Variable Documentation
D_80078E50
UnkAl0* D_80078E50 = NULL
Definition at line 4 of file code_31650.c.
Referenced by func_800565A4().
D_80078E54
UnkAl0* D_80078E54 = NULL
Definition at line 5 of file code_31650.c.
Referenced by func_80052E5C(), func_80056D78(), func_80056DA4(), func_80056DCC(), func_80056EC0(), func_80056F78(), func_80057344(), func_80057B64(), func_80057B8C(), func_80057BB4(), func_80057BDC(), func_80057C04(), and func_80057C2C().
D_80078E58
s8 D_80078E58 = 0
Definition at line 6 of file code_31650.c.
Referenced by func_80056D34().
D_80078E5A
s16 D_80078E5A = 0x7FFF
Definition at line 7 of file code_31650.c.
Referenced by func_80056D44(), and func_80056D50().
D_80078E5C
s8 D_80078E5C = 0
Definition at line 8 of file code_31650.c.
Referenced by func_80056D5C().
D_80078E60
s32 D_80078E60[]
Definition at line 9 of file code_31650.c.