src/os/code_3b4a0_len_270.c File Reference - Paper Mario Documentation
code_3b4a0_len_270.c File Reference
Functions
s32 nuContRmbForceStop ()
s32 nuContRmbForceStopEnd ()
s32 nuPiReadRomOverlay ()
s32 nuGfxThreadStart ()
s32 nuGfxThread ()
Function Documentation
nuContRmbForceStop()
s32 nuContRmbForceStop ()
Definition at line 3 of file code_3b4a0_len_270.c.
Referenced by func_80033B88().
nuContRmbForceStopEnd()
s32 nuContRmbForceStopEnd ()
Definition at line 5 of file code_3b4a0_len_270.c.
Referenced by func_80035E54().
nuPiReadRomOverlay()
s32 nuPiReadRomOverlay ()
Definition at line 7 of file code_3b4a0_len_270.c.
nuGfxThreadStart()
s32 nuGfxThreadStart ()
Definition at line 9 of file code_3b4a0_len_270.c.
Referenced by nuGfxInitEX2().
nuGfxThread()
s32 nuGfxThread ()
Definition at line 11 of file code_3b4a0_len_270.c.