src/code_138CC0.c File Reference - Paper Mario Documentation
code_138CC0.c File Reference
Functions
s32 pause_stats_draw_contents ()
s32 pause_stats_init ()
s32 pause_stats_handle_input ()
void pause_stats_cleanup (void)
s32 pause_badges_comparator (s16 *a, s16 *b)
s32 pause_badges_count_all (void)
s32 pause_badges_count_equipped (void)
s32 pause_badges_get_pos_x (s32 page, s32 itemIndex)
s32 pause_badges_get_pos_y (s32 page, s32 itemIndex)
s32 pause_badges_get_column (s32 page, s32 itemIdx)
s32 pause_badges_get_row (s32 page, s32 itemIdx)
s32 pause_badges_is_visible (s32 y)
s32 pause_badges_scroll_offset_y (s32 offset)
s32 pause_badges_scroll_offset_x (s32 x)
s32 pause_badges_try_remove ()
s32 pause_badges_try_equip ()
s32 pause_badges_draw_bp_orbs ()
s32 pause_badges_draw_contents ()
s32 pause_badges_load_badges ()
s32 pause_badges_init ()
s32 pause_badges_handle_input ()
void pause_badges_update (void)
s32 pause_badges_cleanup ()
Function Documentation
pause_stats_draw_contents()
s32 pause_stats_draw_contents ()
Definition at line 3 of file code_138CC0.c.
pause_stats_init()
s32 pause_stats_init ()
Definition at line 5 of file code_138CC0.c.
pause_stats_handle_input()
s32 pause_stats_handle_input ()
Definition at line 7 of file code_138CC0.c.
pause_stats_cleanup()
void pause_stats_cleanup (void)
Definition at line 9 of file code_138CC0.c.
pause_badges_comparator()
s32 pause_badges_comparator (s16 * a, s16 * b)
Definition at line 18 of file code_138CC0.c.
Referenced by pause_badges_count_all(), and pause_badges_count_equipped().
pause_badges_count_all()
s32 pause_badges_count_all (void)
Definition at line 43 of file code_138CC0.c.
pause_badges_count_equipped()
s32 pause_badges_count_equipped (void)
Definition at line 58 of file code_138CC0.c.
pause_badges_get_pos_x()
s32 pause_badges_get_pos_x (s32 page, s32 itemIndex)
Definition at line 73 of file code_138CC0.c.
pause_badges_get_pos_y()
s32 pause_badges_get_pos_y (s32 page, s32 itemIndex)
Definition at line 77 of file code_138CC0.c.
Referenced by pause_badges_update().
pause_badges_get_column()
s32 pause_badges_get_column (s32 page, s32 itemIdx)
Definition at line 82 of file code_138CC0.c.
pause_badges_get_row()
s32 pause_badges_get_row (s32 page, s32 itemIdx)
Definition at line 86 of file code_138CC0.c.
pause_badges_is_visible()
s32 pause_badges_is_visible (s32 y)
Definition at line 90 of file code_138CC0.c.
pause_badges_scroll_offset_y()
s32 pause_badges_scroll_offset_y (s32 offset)
Definition at line 98 of file code_138CC0.c.
pause_badges_scroll_offset_x()
s32 pause_badges_scroll_offset_x (s32 x)
Definition at line 102 of file code_138CC0.c.
pause_badges_try_remove()
s32 pause_badges_try_remove ()
Definition at line 106 of file code_138CC0.c.
pause_badges_try_equip()
s32 pause_badges_try_equip ()
Definition at line 108 of file code_138CC0.c.
pause_badges_draw_bp_orbs()
s32 pause_badges_draw_bp_orbs ()
Definition at line 110 of file code_138CC0.c.
pause_badges_draw_contents()
s32 pause_badges_draw_contents ()
Definition at line 112 of file code_138CC0.c.
pause_badges_load_badges()
s32 pause_badges_load_badges ()
Definition at line 114 of file code_138CC0.c.
pause_badges_init()
s32 pause_badges_init ()
Definition at line 116 of file code_138CC0.c.
pause_badges_handle_input()
s32 pause_badges_handle_input ()
Definition at line 118 of file code_138CC0.c.
pause_badges_update()
void pause_badges_update (void)
Definition at line 120 of file code_138CC0.c.
pause_badges_cleanup()
s32 pause_badges_cleanup ()
Definition at line 145 of file code_138CC0.c.