src/code_fa4c0_len_3bf0.c File Reference - Paper Mario Documentation
code_fa4c0_len_3bf0.c File Reference
Functions
s32 func_802D5B10 ()
s32 func_802D5C70 ()
ApiStatus FadeOutMusic (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetMusicTrack (ScriptInstance *script, s32 isInitialCall)
ApiStatus FadeInMusic (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D5EE0 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D5F28 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D5FA4 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D5FD8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D5FF8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D6050 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D6070 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D6090 (ScriptInstance *script, s32 isInitialCall)
ApiStatus ClearAmbientSounds (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlayAmbientSounds (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlaySound (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D617C (ScriptInstance *script, s32 initialCall)
ApiStatus PlaySoundAt (ScriptInstance *script, s32 isInitialCall)
ApiStatus StopSound (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D62E4 (ScriptInstance *script, s32 initialCall)
ApiStatus UseDoorSounds (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D6340 (ScriptInstance *script, s32 initialCall)
ApiStatus PlaySoundAtF (ScriptInstance *script, s32 isInitialCall)
s32 func_802D6420 ()
s32 func_802D663C ()
ApiStatus RemoveKeyItemAt (ScriptInstance *script, s32 isInitialCall)
ApiStatus RemoveItemAt (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddKeyItem (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D6954 (ScriptInstance *script, s32 isInitialCall)
ApiStatus HasKeyItem (ScriptInstance *script, s32 isInitialCall)
ApiStatus FindKeyItem (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddItem (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D6AF0 (ScriptInstance *script, s32 initialCall)
ApiStatus FindItem (ScriptInstance *script, s32 isInitialCall)
ApiStatus RemoveItem (ScriptInstance *script, s32 isInitialCall)
ApiStatus CountFortressKeys (ScriptInstance *script, s32 isInitialCall)
ApiStatus RemoveFortressKeys (ScriptInstance *script, s32 isInitialCall)
ApiStatus MakeItemEntity (ScriptInstance *script, s32 isInitialCall)
ApiStatus DropItemEntity (ScriptInstance *script, s32 isInitialCall)
ApiStatus DropItemEntityB (ScriptInstance *script, s32 isInitialCall)
ApiStatus RemoveItemEntity (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddBadge (ScriptInstance *script, s32 isInitialCall)
ApiStatus RemoveBadge (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetItemPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetItemFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D721C (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddCoin (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddStarPoints (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddStarPieces (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetItemPower (ScriptInstance *script, s32 isInitialCall)
ApiStatus ShowGotItem (ScriptInstance *script, s32 isInitialCall)
Function Documentation
func_802D5B10()
s32 func_802D5B10 ()
Definition at line 3 of file code_fa4c0_len_3bf0.c.
func_802D5C70()
s32 func_802D5C70 ()
Definition at line 5 of file code_fa4c0_len_3bf0.c.
FadeOutMusic()
ApiStatus FadeOutMusic (ScriptInstance * script, s32 isInitialCall)
Definition at line 7 of file code_fa4c0_len_3bf0.c.
SetMusicTrack()
ApiStatus SetMusicTrack (ScriptInstance * script, s32 isInitialCall)
Definition at line 15 of file code_fa4c0_len_3bf0.c.
Referenced by N().
FadeInMusic()
ApiStatus FadeInMusic (ScriptInstance * script, s32 isInitialCall)
Definition at line 25 of file code_fa4c0_len_3bf0.c.
func_802D5EE0()
ApiStatus func_802D5EE0 (ScriptInstance * script, s32 isInitialCall)
Definition at line 37 of file code_fa4c0_len_3bf0.c.
func_802D5F28()
ApiStatus func_802D5F28 (ScriptInstance * script, s32 isInitialCall)
Definition at line 45 of file code_fa4c0_len_3bf0.c.
func_802D5FA4()
ApiStatus func_802D5FA4 (ScriptInstance * script, s32 isInitialCall)
Definition at line 52 of file code_fa4c0_len_3bf0.c.
func_802D5FD8()
ApiStatus func_802D5FD8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 57 of file code_fa4c0_len_3bf0.c.
func_802D5FF8()
ApiStatus func_802D5FF8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 62 of file code_fa4c0_len_3bf0.c.
func_802D6050()
ApiStatus func_802D6050 (ScriptInstance * script, s32 isInitialCall)
Definition at line 69 of file code_fa4c0_len_3bf0.c.
func_802D6070()
ApiStatus func_802D6070 (ScriptInstance * script, s32 isInitialCall)
Definition at line 74 of file code_fa4c0_len_3bf0.c.
func_802D6090()
ApiStatus func_802D6090 (ScriptInstance * script, s32 isInitialCall)
Definition at line 79 of file code_fa4c0_len_3bf0.c.
ClearAmbientSounds()
ApiStatus ClearAmbientSounds (ScriptInstance * script, s32 isInitialCall)
Definition at line 86 of file code_fa4c0_len_3bf0.c.
PlayAmbientSounds()
ApiStatus PlayAmbientSounds (ScriptInstance * script, s32 isInitialCall)
Definition at line 93 of file code_fa4c0_len_3bf0.c.
PlaySound()
ApiStatus PlaySound (ScriptInstance * script, s32 isInitialCall)
Definition at line 100 of file code_fa4c0_len_3bf0.c.
Referenced by N().
func_802D617C()
ApiStatus func_802D617C (ScriptInstance * script, s32 initialCall)
Definition at line 108 of file code_fa4c0_len_3bf0.c.
PlaySoundAt()
ApiStatus PlaySoundAt (ScriptInstance * script, s32 isInitialCall)
Definition at line 117 of file code_fa4c0_len_3bf0.c.
StopSound()
ApiStatus StopSound (ScriptInstance * script, s32 isInitialCall)
Definition at line 129 of file code_fa4c0_len_3bf0.c.
func_802D62E4()
ApiStatus func_802D62E4 (ScriptInstance * script, s32 initialCall)
Definition at line 136 of file code_fa4c0_len_3bf0.c.
UseDoorSounds()
ApiStatus UseDoorSounds (ScriptInstance * script, s32 isInitialCall)
Definition at line 143 of file code_fa4c0_len_3bf0.c.
func_802D6340()
ApiStatus func_802D6340 (ScriptInstance * script, s32 initialCall)
Definition at line 150 of file code_fa4c0_len_3bf0.c.
PlaySoundAtF()
ApiStatus PlaySoundAtF (ScriptInstance * script, s32 isInitialCall)
Definition at line 157 of file code_fa4c0_len_3bf0.c.
func_802D6420()
s32 func_802D6420 ()
Definition at line 169 of file code_fa4c0_len_3bf0.c.
func_802D663C()
s32 func_802D663C ()
Definition at line 171 of file code_fa4c0_len_3bf0.c.
RemoveKeyItemAt()
ApiStatus RemoveKeyItemAt (ScriptInstance * script, s32 isInitialCall)
Definition at line 173 of file code_fa4c0_len_3bf0.c.
RemoveItemAt()
ApiStatus RemoveItemAt (ScriptInstance * script, s32 isInitialCall)
Definition at line 182 of file code_fa4c0_len_3bf0.c.
AddKeyItem()
ApiStatus AddKeyItem (ScriptInstance * script, s32 isInitialCall)
Definition at line 192 of file code_fa4c0_len_3bf0.c.
func_802D6954()
ApiStatus func_802D6954 (ScriptInstance * script, s32 isInitialCall)
Definition at line 216 of file code_fa4c0_len_3bf0.c.
HasKeyItem()
ApiStatus HasKeyItem (ScriptInstance * script, s32 isInitialCall)
Definition at line 224 of file code_fa4c0_len_3bf0.c.
FindKeyItem()
ApiStatus FindKeyItem (ScriptInstance * script, s32 isInitialCall)
Definition at line 240 of file code_fa4c0_len_3bf0.c.
AddItem()
ApiStatus AddItem (ScriptInstance * script, s32 isInitialCall)
Definition at line 263 of file code_fa4c0_len_3bf0.c.
func_802D6AF0()
ApiStatus func_802D6AF0 (ScriptInstance * script, s32 initialCall)
Definition at line 272 of file code_fa4c0_len_3bf0.c.
FindItem()
ApiStatus FindItem (ScriptInstance * script, s32 isInitialCall)
Definition at line 277 of file code_fa4c0_len_3bf0.c.
RemoveItem()
ApiStatus RemoveItem (ScriptInstance * script, s32 isInitialCall)
Definition at line 300 of file code_fa4c0_len_3bf0.c.
CountFortressKeys()
ApiStatus CountFortressKeys (ScriptInstance * script, s32 isInitialCall)
Definition at line 330 of file code_fa4c0_len_3bf0.c.
RemoveFortressKeys()
ApiStatus RemoveFortressKeys (ScriptInstance * script, s32 isInitialCall)
Definition at line 337 of file code_fa4c0_len_3bf0.c.
MakeItemEntity()
ApiStatus MakeItemEntity (ScriptInstance * script, s32 isInitialCall)
Definition at line 344 of file code_fa4c0_len_3bf0.c.
Referenced by N().
DropItemEntity()
ApiStatus DropItemEntity (ScriptInstance * script, s32 isInitialCall)
Definition at line 357 of file code_fa4c0_len_3bf0.c.
Referenced by N().
DropItemEntityB()
ApiStatus DropItemEntityB (ScriptInstance * script, s32 isInitialCall)
Definition at line 370 of file code_fa4c0_len_3bf0.c.
RemoveItemEntity()
ApiStatus RemoveItemEntity (ScriptInstance * script, s32 isInitialCall)
Definition at line 384 of file code_fa4c0_len_3bf0.c.
AddBadge()
ApiStatus AddBadge (ScriptInstance * script, s32 isInitialCall)
Definition at line 392 of file code_fa4c0_len_3bf0.c.
RemoveBadge()
ApiStatus RemoveBadge (ScriptInstance * script, s32 isInitialCall)
Definition at line 401 of file code_fa4c0_len_3bf0.c.
SetItemPos()
ApiStatus SetItemPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 421 of file code_fa4c0_len_3bf0.c.
SetItemFlags()
ApiStatus SetItemFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 439 of file code_fa4c0_len_3bf0.c.
func_802D721C()
ApiStatus func_802D721C (ScriptInstance * script, s32 isInitialCall)
Definition at line 454 of file code_fa4c0_len_3bf0.c.
AddCoin()
ApiStatus AddCoin (ScriptInstance * script, s32 isInitialCall)
Definition at line 464 of file code_fa4c0_len_3bf0.c.
AddStarPoints()
ApiStatus AddStarPoints (ScriptInstance * script, s32 isInitialCall)
Definition at line 469 of file code_fa4c0_len_3bf0.c.
AddStarPieces()
ApiStatus AddStarPieces (ScriptInstance * script, s32 isInitialCall)
Definition at line 474 of file code_fa4c0_len_3bf0.c.
GetItemPower()
ApiStatus GetItemPower (ScriptInstance * script, s32 isInitialCall)
Definition at line 479 of file code_fa4c0_len_3bf0.c.
ShowGotItem()
ApiStatus ShowGotItem (ScriptInstance * script, s32 isInitialCall)
Definition at line 490 of file code_fa4c0_len_3bf0.c.