src/code_dbd70_len_700.c File Reference - Paper Mario Documentation
code_dbd70_len_700.c File Reference
Functions
void default_trigger_function_handler (s32 *arg0)
s32 clear_trigger_data ()
void init_trigger_list (void)
Trigger * create_trigger (TriggerDefinition *def)
s32 update_triggers ()
void delete_trigger (Trigger *toDelete)
s32 is_trigger_bound (Trigger *trigger, Bytecode *script)
Trigger * get_trigger_by_id (s32 triggerID)
s32 func_80145CE8 (s32 arg0)
Function Documentation
default_trigger_function_handler()
void default_trigger_function_handler (s32 * arg0)
Definition at line 3 of file code_dbd70_len_700.c.
clear_trigger_data()
s32 clear_trigger_data ()
Definition at line 7 of file code_dbd70_len_700.c.
Referenced by load_engine_data(), and step_init_state().
init_trigger_list()
void init_trigger_list (void)
Definition at line 9 of file code_dbd70_len_700.c.
create_trigger()
Trigger* create_trigger (TriggerDefinition * def)
Definition at line 19 of file code_dbd70_len_700.c.
Referenced by bind_trigger(), si_handle_bind_lock(), and si_handle_bind_trigger().
update_triggers()
s32 update_triggers ()
Definition at line 21 of file code_dbd70_len_700.c.
delete_trigger()
void delete_trigger (Trigger * toDelete)
Definition at line 23 of file code_dbd70_len_700.c.
Referenced by DeleteTrigger(), and si_handle_unbind().
is_trigger_bound()
s32 is_trigger_bound (Trigger * trigger, Bytecode * script)
Definition at line 39 of file code_dbd70_len_700.c.
Referenced by _bound_script_trigger_handler().
get_trigger_by_id()
Trigger* get_trigger_by_id (s32 triggerID)
Definition at line 41 of file code_dbd70_len_700.c.
Referenced by func_802BD100().
func_80145CE8()
s32 func_80145CE8 (s32 arg0)
Definition at line 45 of file code_dbd70_len_700.c.