src/code_104940_len_dc0.c File Reference - Paper Mario Documentation
code_104940_len_dc0.c File Reference
Functions
s32 func_802E30C0 ()
void func_802E31B0 (Entity *entity)
f32 func_802E31EC (Entity *entity)
void func_802E328C (Entity *entity)
s32 func_802E3370 ()
s32 func_802E3650 (Entity *entity)
void entity_init_Hammer23Block_normal (Entity *entity)
void func_802E3714 (Entity *entity)
void func_802E3728 (Entity *entity)
void func_802E37E4 (Entity *entity)
void func_802E3898 (Entity *entity)
void func_802E38D8 (Entity *entity)
void func_802E3A00 (Entity *entity)
void func_802E3A48 (Entity *entity)
void func_802E3B08 (Entity *entity)
s32 func_802E3BA4 (Entity *entity)
void entity_init_Hammer1Block_normal (Entity *entity)
s32 entity_init_HammerBlock_small (Entity *entity)
Variables
f64 D_802EB1D0
f64 D_802EB1D8
f64 D_802EB1E0
f64 D_802EB1E8
f64 D_802EB1F0
f64 D_802EB1F8
f64 D_802EB200
f64 D_802EB208
s32 D_802E9E54
StaticEntityData D_802EA07C
s32 D_802E9E80
Function Documentation
func_802E30C0()
s32 func_802E30C0 ()
Definition at line 14 of file code_104940_len_dc0.c.
Referenced by entity_init_Hammer1Block_normal().
func_802E31B0()
void func_802E31B0 (Entity * entity)
Definition at line 16 of file code_104940_len_dc0.c.
func_802E31EC()
f32 func_802E31EC (Entity * entity)
Definition at line 20 of file code_104940_len_dc0.c.
func_802E328C()
void func_802E328C (Entity * entity)
Definition at line 35 of file code_104940_len_dc0.c.
func_802E3370()
s32 func_802E3370 ()
Definition at line 51 of file code_104940_len_dc0.c.
Referenced by func_802E3650().
func_802E3650()
s32 func_802E3650 (Entity * entity)
Definition at line 53 of file code_104940_len_dc0.c.
Referenced by func_802E10F4(), func_802E2450(), func_802E328C(), func_802E3A48(), func_802E3E80(), func_802E5308(), and func_802E56D0().
entity_init_Hammer23Block_normal()
void entity_init_Hammer23Block_normal (Entity * entity)
Definition at line 71 of file code_104940_len_dc0.c.
Referenced by entity_init_Hammer1Block_normal(), func_802E13B8(), func_802E3898(), func_802E464C(), func_802E46BC(), func_802E55A8(), and func_802E578C().
func_802E3714()
void func_802E3714 (Entity * entity)
Definition at line 81 of file code_104940_len_dc0.c.
func_802E3728()
void func_802E3728 (Entity * entity)
Definition at line 87 of file code_104940_len_dc0.c.
func_802E37E4()
void func_802E37E4 (Entity * entity)
Definition at line 101 of file code_104940_len_dc0.c.
func_802E3898()
void func_802E3898 (Entity * entity)
Definition at line 116 of file code_104940_len_dc0.c.
func_802E38D8()
void func_802E38D8 (Entity * entity)
Definition at line 129 of file code_104940_len_dc0.c.
func_802E3A00()
void func_802E3A00 (Entity * entity)
Definition at line 154 of file code_104940_len_dc0.c.
Referenced by func_802E3728(), func_802E37E4(), and func_802E3A48().
func_802E3A48()
void func_802E3A48 (Entity * entity)
Definition at line 170 of file code_104940_len_dc0.c.
func_802E3B08()
void func_802E3B08 (Entity * entity)
Definition at line 186 of file code_104940_len_dc0.c.
func_802E3BA4()
s32 func_802E3BA4 (Entity * entity)
Definition at line 203 of file code_104940_len_dc0.c.
entity_init_Hammer1Block_normal()
void entity_init_Hammer1Block_normal (Entity * entity)
Definition at line 321 of file code_104940_len_dc0.c.
entity_init_HammerBlock_small()
s32 entity_init_HammerBlock_small (Entity * entity)
Definition at line 326 of file code_104940_len_dc0.c.
Variable Documentation
D_802EB1D0
f64 D_802EB1D0 extern
Referenced by func_802E328C().
D_802EB1D8
f64 D_802EB1D8 extern
Referenced by func_802E328C().
D_802EB1E0
f64 D_802EB1E0 extern
Referenced by func_802E328C().
D_802EB1E8
f64 D_802EB1E8 extern
Referenced by func_802E328C().
D_802EB1F0
f64 D_802EB1F0 extern
D_802EB1F8
f64 D_802EB1F8 extern
D_802EB200
f64 D_802EB200 extern
D_802EB208
f64 D_802EB208 extern
D_802E9E54
s32 D_802E9E54 extern
Referenced by func_802E38D8().
D_802EA07C
StaticEntityData D_802EA07C extern
Referenced by func_802E38D8(), func_802E3A48(), func_802E3B08(), func_802E4154(), and func_802E421C().
D_802E9E80
s32 D_802E9E80 extern
Referenced by func_802E3BA4().