src/code_135EE0.c File Reference - Paper Mario Documentation
code_135EE0.c File Reference
Functions
void pause_set_cursor_opacity (s32 val)
s32 func_80242BAC ()
s32 func_80242D04 ()
void pause_interp_cursor (void)
s32 func_80242F90 ()
s32 func_80242FBC ()
s32 func_80242FF4 ()
s32 func_80243090 ()
s32 func_802430E4 ()
s32 func_8024313C ()
s32 func_80243188 ()
s32 func_80243238 ()
s32 func_802432E8 ()
s32 func_80243388 ()
s32 pause_interp_text_scroll ()
s32 pause_interp_vertical_scroll (s32 deltaBefore)
void pause_update_cursor (s32 arg0, s32 offsetX, s32 offsetY)
void func_80243568 (void)
s32 pause_textbox_draw_contents ()
s32 pause_tutorial_draw_contents ()
s32 pause_init ()
s32 pause_tutorial_input ()
s32 pause_handle_input ()
s32 pause_cleanup ()
s32 pause_get_total_equipped_bp_cost ()
void pause_draw_rect (s32 ulx, s32 uly, s32 lrx, s32 lry, s32 tileDescriptor, s32 uls, s32 ult, s32 dsdx, s32 dtdy)
s32 pause_sort_item_list ()
Function Documentation
pause_set_cursor_opacity()
void pause_set_cursor_opacity (s32 val)
Definition at line 5 of file code_135EE0.c.
func_80242BAC()
s32 func_80242BAC ()
Definition at line 12 of file code_135EE0.c.
func_80242D04()
s32 func_80242D04 ()
Definition at line 14 of file code_135EE0.c.
pause_interp_cursor()
void pause_interp_cursor (void)
Definition at line 18 of file code_135EE0.c.
Referenced by pause_update_cursor().
func_80242F90()
s32 func_80242F90 ()
Definition at line 69 of file code_135EE0.c.
func_80242FBC()
s32 func_80242FBC ()
Definition at line 71 of file code_135EE0.c.
func_80242FF4()
s32 func_80242FF4 ()
Definition at line 73 of file code_135EE0.c.
func_80243090()
s32 func_80243090 ()
Definition at line 75 of file code_135EE0.c.
func_802430E4()
s32 func_802430E4 ()
Definition at line 77 of file code_135EE0.c.
func_8024313C()
s32 func_8024313C ()
Definition at line 79 of file code_135EE0.c.
func_80243188()
s32 func_80243188 ()
Definition at line 81 of file code_135EE0.c.
func_80243238()
s32 func_80243238 ()
Definition at line 83 of file code_135EE0.c.
func_802432E8()
s32 func_802432E8 ()
Definition at line 85 of file code_135EE0.c.
func_80243388()
s32 func_80243388 ()
Definition at line 87 of file code_135EE0.c.
pause_interp_text_scroll()
s32 pause_interp_text_scroll ()
Definition at line 89 of file code_135EE0.c.
pause_interp_vertical_scroll()
s32 pause_interp_vertical_scroll (s32 deltaBefore)
Definition at line 93 of file code_135EE0.c.
Referenced by pause_badges_update().
pause_update_cursor()
void pause_update_cursor (s32 arg0, s32 offsetX, s32 offsetY)
Definition at line 120 of file code_135EE0.c.
func_80243568()
void func_80243568 (void)
Definition at line 135 of file code_135EE0.c.
pause_textbox_draw_contents()
s32 pause_textbox_draw_contents ()
Definition at line 138 of file code_135EE0.c.
pause_tutorial_draw_contents()
s32 pause_tutorial_draw_contents ()
Definition at line 140 of file code_135EE0.c.
pause_init()
s32 pause_init ()
Definition at line 142 of file code_135EE0.c.
pause_tutorial_input()
s32 pause_tutorial_input ()
Definition at line 144 of file code_135EE0.c.
pause_handle_input()
s32 pause_handle_input ()
Definition at line 146 of file code_135EE0.c.
pause_cleanup()
s32 pause_cleanup ()
Definition at line 148 of file code_135EE0.c.
pause_get_total_equipped_bp_cost()
s32 pause_get_total_equipped_bp_cost ()
Definition at line 150 of file code_135EE0.c.
pause_draw_rect()
void pause_draw_rect (s32 ulx, s32 uly, s32 lrx, s32 lry, s32 tileDescriptor, s32 uls, s32 ult, s32 dsdx, s32 dtdy)
Definition at line 153 of file code_135EE0.c.
pause_sort_item_list()
s32 pause_sort_item_list ()
Definition at line 155 of file code_135EE0.c.
Referenced by pause_badges_count_all(), and pause_badges_count_equipped().