src/code_26840_len_20d0.c File Reference - Paper Mario Documentation
code_26840_len_20d0.c File Reference
Functions
void func_8004B440 (UnkAl6CC *arg0, u8 arg1, u8 arg2, UnkAl19E0 *arg3, u8 arg4)
void func_8004B62C (UnkAl6CC *arg0)
void func_8004B698 (UnkAl6CC *arg0)
void func_8004B6D8 (UnkAl6CC *arg0, s32 arg1, s16 arg2, s16 arg3, u8 arg4)
void func_8004B748 (UnkAl6CC *arg0)
s32 func_8004B9E4 (UnkAl6CC *arg0, s32 arg1)
void func_8004BA54 (UnkAl6CC *arg0, s32 arg1)
s32 func_8004BA74 ()
s32 func_8004C0E4 ()
s32 func_8004C268 ()
s32 func_8004C2A4 ()
s32 func_8004C300 ()
s32 func_8004C358 ()
s32 func_8004C3D4 ()
s16 func_8004C444 (UnkAl6CC *arg0)
s32 func_8004C578 ()
s32 func_8004C844 ()
s32 func_8004C884 ()
s32 func_8004CD94 ()
s32 func_8004CDF8 ()
s32 func_8004CE70 ()
s32 func_8004CEA4 ()
s32 func_8004CEC4 ()
s32 func_8004CF0C ()
s32 func_8004CF3C ()
s32 func_8004D00C ()
s32 func_8004D038 ()
s32 func_8004D050 ()
s32 func_8004D07C ()
s32 func_8004D114 ()
s32 func_8004D130 ()
s32 func_8004D15C ()
s32 func_8004D180 ()
s32 func_8004D1B4 ()
s32 func_8004D23C ()
s32 func_8004D2B0 ()
s32 func_8004D2E4 ()
s32 func_8004D310 ()
void func_8004D31C (void)
s32 func_8004D324 ()
s32 func_8004D33C ()
s32 func_8004D354 ()
s32 func_8004D36C ()
s32 func_8004D3A0 ()
s32 func_8004D3F8 ()
s32 func_8004D428 ()
s32 func_8004D484 ()
s32 func_8004D4BC ()
Function Documentation
func_8004B440()
void func_8004B440 (UnkAl6CC * arg0, u8 arg1, u8 arg2, UnkAl19E0 * arg3, u8 arg4)
Definition at line 4 of file code_26840_len_20d0.c.
Referenced by func_80052E5C().
func_8004B62C()
void func_8004B62C (UnkAl6CC * arg0)
Definition at line 86 of file code_26840_len_20d0.c.
Referenced by func_80052E5C().
func_8004B698()
void func_8004B698 (UnkAl6CC * arg0)
Definition at line 88 of file code_26840_len_20d0.c.
Referenced by func_8004B440().
func_8004B6D8()
void func_8004B6D8 (UnkAl6CC * arg0, s32 arg1, s16 arg2, s16 arg3, u8 arg4)
Definition at line 105 of file code_26840_len_20d0.c.
Referenced by func_800551E0(), func_80055240(), func_800552D0(), func_80055330(), func_800553C0(), and func_80055408().
func_8004B748()
void func_8004B748 (UnkAl6CC * arg0)
Definition at line 132 of file code_26840_len_20d0.c.
Referenced by func_800535C0().
func_8004B9E4()
s32 func_8004B9E4 (UnkAl6CC * arg0, s32 arg1)
Definition at line 134 of file code_26840_len_20d0.c.
Referenced by func_8004B440(), and func_80054D74().
func_8004BA54()
void func_8004BA54 (UnkAl6CC * arg0, s32 arg1)
Definition at line 154 of file code_26840_len_20d0.c.
Referenced by func_8004B440(), func_80056204(), and func_80056228().
func_8004BA74()
s32 func_8004BA74 ()
Definition at line 162 of file code_26840_len_20d0.c.
func_8004C0E4()
s32 func_8004C0E4 ()
Definition at line 164 of file code_26840_len_20d0.c.
func_8004C268()
s32 func_8004C268 ()
Definition at line 166 of file code_26840_len_20d0.c.
func_8004C2A4()
s32 func_8004C2A4 ()
Definition at line 168 of file code_26840_len_20d0.c.
func_8004C300()
s32 func_8004C300 ()
Definition at line 170 of file code_26840_len_20d0.c.
func_8004C358()
s32 func_8004C358 ()
Definition at line 172 of file code_26840_len_20d0.c.
func_8004C3D4()
s32 func_8004C3D4 ()
Definition at line 174 of file code_26840_len_20d0.c.
func_8004C444()
s16 func_8004C444 (UnkAl6CC * arg0)
Definition at line 176 of file code_26840_len_20d0.c.
Referenced by func_800533D0().
func_8004C578()
s32 func_8004C578 ()
Definition at line 178 of file code_26840_len_20d0.c.
func_8004C844()
s32 func_8004C844 ()
Definition at line 180 of file code_26840_len_20d0.c.
func_8004C884()
s32 func_8004C884 ()
Definition at line 182 of file code_26840_len_20d0.c.
func_8004CD94()
s32 func_8004CD94 ()
Definition at line 184 of file code_26840_len_20d0.c.
func_8004CDF8()
s32 func_8004CDF8 ()
Definition at line 186 of file code_26840_len_20d0.c.
func_8004CE70()
s32 func_8004CE70 ()
Definition at line 188 of file code_26840_len_20d0.c.
func_8004CEA4()
s32 func_8004CEA4 ()
Definition at line 190 of file code_26840_len_20d0.c.
func_8004CEC4()
s32 func_8004CEC4 ()
Definition at line 192 of file code_26840_len_20d0.c.
func_8004CF0C()
s32 func_8004CF0C ()
Definition at line 194 of file code_26840_len_20d0.c.
func_8004CF3C()
s32 func_8004CF3C ()
Definition at line 196 of file code_26840_len_20d0.c.
func_8004D00C()
s32 func_8004D00C ()
Definition at line 198 of file code_26840_len_20d0.c.
func_8004D038()
s32 func_8004D038 ()
Definition at line 200 of file code_26840_len_20d0.c.
func_8004D050()
s32 func_8004D050 ()
Definition at line 202 of file code_26840_len_20d0.c.
func_8004D07C()
s32 func_8004D07C ()
Definition at line 204 of file code_26840_len_20d0.c.
func_8004D114()
s32 func_8004D114 ()
Definition at line 206 of file code_26840_len_20d0.c.
func_8004D130()
s32 func_8004D130 ()
Definition at line 208 of file code_26840_len_20d0.c.
func_8004D15C()
s32 func_8004D15C ()
Definition at line 210 of file code_26840_len_20d0.c.
func_8004D180()
s32 func_8004D180 ()
Definition at line 212 of file code_26840_len_20d0.c.
func_8004D1B4()
s32 func_8004D1B4 ()
Definition at line 214 of file code_26840_len_20d0.c.
func_8004D23C()
s32 func_8004D23C ()
Definition at line 216 of file code_26840_len_20d0.c.
func_8004D2B0()
s32 func_8004D2B0 ()
Definition at line 218 of file code_26840_len_20d0.c.
func_8004D2E4()
s32 func_8004D2E4 ()
Definition at line 220 of file code_26840_len_20d0.c.
func_8004D310()
s32 func_8004D310 ()
Definition at line 222 of file code_26840_len_20d0.c.
func_8004D31C()
void func_8004D31C (void)
Definition at line 224 of file code_26840_len_20d0.c.
func_8004D324()
s32 func_8004D324 ()
Definition at line 227 of file code_26840_len_20d0.c.
func_8004D33C()
s32 func_8004D33C ()
Definition at line 229 of file code_26840_len_20d0.c.
func_8004D354()
s32 func_8004D354 ()
Definition at line 231 of file code_26840_len_20d0.c.
func_8004D36C()
s32 func_8004D36C ()
Definition at line 233 of file code_26840_len_20d0.c.
func_8004D3A0()
s32 func_8004D3A0 ()
Definition at line 235 of file code_26840_len_20d0.c.
func_8004D3F8()
s32 func_8004D3F8 ()
Definition at line 237 of file code_26840_len_20d0.c.
func_8004D428()
s32 func_8004D428 ()
Definition at line 239 of file code_26840_len_20d0.c.
func_8004D484()
s32 func_8004D484 ()
Definition at line 241 of file code_26840_len_20d0.c.
func_8004D4BC()
s32 func_8004D4BC ()
Definition at line 243 of file code_26840_len_20d0.c.