src/code_17FEB0.c File Reference - Paper Mario Documentation
code_17FEB0.c File Reference
Functions
HitResult calc_item_check_hit (void)
s32 calc_item_damage_enemy ()
ApiStatus ItemDamageEnemy (ScriptInstance *script, s32 isInitialCall)
ApiStatus ItemAfflictEnemy (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_80252B3C (ScriptInstance *script, s32 isInitialCall)
ApiStatus ItemCheckHit (ScriptInstance *script, s32 isInitialCall)
Function Documentation
calc_item_check_hit()
HitResult calc_item_check_hit (void)
Definition at line 3 of file code_17FEB0.c.
Referenced by ItemCheckHit().
calc_item_damage_enemy()
s32 calc_item_damage_enemy ()
Definition at line 40 of file code_17FEB0.c.
Referenced by func_80252B3C(), ItemAfflictEnemy(), and ItemDamageEnemy().
ItemDamageEnemy()
ApiStatus ItemDamageEnemy (ScriptInstance * script, s32 isInitialCall)
Definition at line 42 of file code_17FEB0.c.
ItemAfflictEnemy()
ApiStatus ItemAfflictEnemy (ScriptInstance * script, s32 isInitialCall)
Definition at line 109 of file code_17FEB0.c.
func_80252B3C()
ApiStatus func_80252B3C (ScriptInstance * script, s32 isInitialCall)
Definition at line 177 of file code_17FEB0.c.
ItemCheckHit()
ApiStatus ItemCheckHit (ScriptInstance * script, s32 isInitialCall)
Definition at line 244 of file code_17FEB0.c.