src/code_6000.c File Reference - Paper Mario Documentation
code_6000.c File Reference
Functions
HeapNode * general_heap_create (void)
s32 general_heap_malloc (s32 size)
s32 general_heap_malloc_tail (s32 size)
s32 general_heap_free (s32 size)
s32 battle_heap_create (void)
s32 func_8002ACDC (void)
s32 heap_malloc (s32 size)
s32 heap_free (s32 size)
s32 collision_heap_create (void)
s32 collision_heap_malloc (s32 size)
s32 collision_heap_free (void *data)
Variables
s32 D_80268000
s32 D_802FB800
s32 D_803DA800
Function Documentation
general_heap_create()
HeapNode* general_heap_create (void)
Definition at line 7 of file code_6000.c.
Referenced by load_engine_data(), and step_init_state().
general_heap_malloc()
s32 general_heap_malloc (s32 size)
Definition at line 11 of file code_6000.c.
Referenced by func_8005A2BC(), heap_malloc(), and play_effect().
general_heap_malloc_tail()
s32 general_heap_malloc_tail (s32 size)
Definition at line 15 of file code_6000.c.
general_heap_free()
s32 general_heap_free (s32 size)
Definition at line 19 of file code_6000.c.
Referenced by heap_free(), load_map_bg(), remove_all_effects(), and remove_effect().
battle_heap_create()
s32 battle_heap_create (void)
Definition at line 23 of file code_6000.c.
func_8002ACDC()
s32 func_8002ACDC (void)
Definition at line 31 of file code_6000.c.
heap_malloc()
s32 heap_malloc (s32 size)
Definition at line 35 of file code_6000.c.
Referenced by LoadPath(), setup_path_data(), si_handle_allocate_array(), and start_script_in_group().
heap_free()
s32 heap_free (s32 size)
Definition at line 43 of file code_6000.c.
Referenced by delete_player_actor(), delete_trigger(), disable_npc_blur(), func_80241CC8_8D31D8(), func_802C3C10(), kill_script(), and setup_path_data().
collision_heap_create()
s32 collision_heap_create (void)
Definition at line 51 of file code_6000.c.
collision_heap_malloc()
s32 collision_heap_malloc (s32 size)
Definition at line 58 of file code_6000.c.
collision_heap_free()
s32 collision_heap_free (void * data)
Definition at line 66 of file code_6000.c.
Variable Documentation
D_80268000
s32 D_80268000 extern
Referenced by collision_heap_create(), collision_heap_free(), and collision_heap_malloc().
D_802FB800
s32 D_802FB800 extern
Referenced by general_heap_create(), general_heap_free(), general_heap_malloc(), and general_heap_malloc_tail().
D_803DA800
s32 D_803DA800 extern
Referenced by battle_heap_create(), collision_heap_free(), collision_heap_malloc(), heap_free(), and heap_malloc().