src/code_42e0_len_1f60.c File Reference - Paper Mario Documentation
code_42e0_len_1f60.c File Reference
Macros
#define ROM_CHUNK_SIZE 0x2000
Functions
void sin_cos_rad (f32 rad, f32 *outSinTheta, f32 *outCosTheta)
void func_80029860 (s32 romStart, s32 vramDest, s32 length)
void poll_rumble (void)
void start_rumble (s32 freq, s32 frame)
void func_80028F8C (void)
void func_80028FE0 (void)
f32 length2D (f32 x, f32 y)
HeapNode * _heap_create (s32 *addr, u32 size)
s32 _heap_malloc ()
s32 _heap_malloc_tail ()
s32 _heap_free ()
s32 _heap_realloc ()
s32 cosine ()
s32 sign (s32 val)
s32 int_to_string ()
void mem_clear (s8 *data, s32 numBytes)
s32 transform_point ()
void copy_matrix (Matrix4f *src, Matrix4f *dest)
s32 dma_copy (s32 romStart, s32 romEnd, void *vramDest)
s32 func_800297D4 (s32 romStart, s32 romEnd, void *vramDest)
s32 _advance_rng (void)
f32 func_80029934 (void)
s32 func_80029994 (s32 arg0)
s32 rand_int (s32 arg0)
f32 signF (f32 val)
s32 round (f32 arg0)
f32 clamp_angle (f32 theta)
f32 get_clamped_angle_diff (f32 a, f32 b)
f32 atan2 (f32 startX, f32 startZ, f32 endX, f32 endZ)
f32 get_player_normal_yaw (void)
f32 get_player_normal_pitch (void)
f32 dist2D (f32 ax, f32 ay, f32 bx, f32 by)
f32 dist3D (f32 ax, f32 ay, f32 az, f32 bx, f32 by, f32 bz)
void add_vec2D_polar (f32 *x, f32 *y, f32 r, f32 theta)
u16 _wrap_trig_lookup_value (f32 theta)
f32 sin_rad (f32 angle)
f32 cos_rad (f32 angle)
void sin_cos_deg (f32 rad, f32 *outSinTheta, f32 *outCosTheta)
f32 sin_deg (f32 angle)
f32 cos_deg (f32 angle)
f32 update_lerp (Easing easing, f32 start, f32 end, s32 elapsed, s32 duration)
s32 func_8002A904 ()
s32 func_8002AAC4 ()
s32 func_8002AB5C ()
Variables
u16 D_80074260 = 0
s32 D_80074264 = 0
s32 D_80074268 [2] = {0, 0}
s32 D_80074270 = 0
f32 D_80074274 []
s8 D_800743E0 []
s32 gRandSeed = 1
f32 D_80074414 []
Gfx D_80074580 []
Macro Definition Documentation
ROM_CHUNK_SIZE
#define ROM_CHUNK_SIZE 0x2000
Definition at line 62 of file code_42e0_len_1f60.c.
Function Documentation
sin_cos_rad()
void sin_cos_rad (f32 rad, f32 * outSinTheta, f32 * outCosTheta)
Definition at line 319 of file code_42e0_len_1f60.c.
Referenced by add_vec2D_polar().
func_80029860()
void func_80029860 (s32 romStart, s32 vramDest, s32 length)
Definition at line 194 of file code_42e0_len_1f60.c.
Referenced by func_800297D4().
poll_rumble()
void poll_rumble (void)
Definition at line 64 of file code_42e0_len_1f60.c.
Referenced by load_engine_data().
start_rumble()
void start_rumble (s32 freq, s32 frame)
Definition at line 69 of file code_42e0_len_1f60.c.
Referenced by StartRumbleWithParams().
func_80028F8C()
void func_80028F8C (void)
Definition at line 88 of file code_42e0_len_1f60.c.
func_80028FE0()
void func_80028FE0 (void)
Definition at line 103 of file code_42e0_len_1f60.c.
Referenced by func_80028F8C().
length2D()
f32 length2D (f32 x, f32 y)
Definition at line 107 of file code_42e0_len_1f60.c.
_heap_create()
HeapNode* _heap_create (s32 * addr, u32 size)
Definition at line 111 of file code_42e0_len_1f60.c.
Referenced by battle_heap_create(), collision_heap_create(), and general_heap_create().
_heap_malloc()
s32 _heap_malloc ()
Definition at line 126 of file code_42e0_len_1f60.c.
Referenced by collision_heap_malloc(), general_heap_malloc(), and heap_malloc().
_heap_malloc_tail()
s32 _heap_malloc_tail ()
Definition at line 128 of file code_42e0_len_1f60.c.
Referenced by general_heap_malloc_tail().
_heap_free()
s32 _heap_free ()
Definition at line 130 of file code_42e0_len_1f60.c.
Referenced by collision_heap_free(), general_heap_free(), and heap_free().
_heap_realloc()
s32 _heap_realloc ()
Definition at line 132 of file code_42e0_len_1f60.c.
cosine()
s32 cosine ()
Definition at line 134 of file code_42e0_len_1f60.c.
sign()
s32 sign (s32 val)
Definition at line 136 of file code_42e0_len_1f60.c.
Referenced by pause_interp_vertical_scroll(), and signF().
int_to_string()
s32 int_to_string ()
Definition at line 145 of file code_42e0_len_1f60.c.
mem_clear()
void mem_clear (s8 * data, s32 numBytes)
Definition at line 148 of file code_42e0_len_1f60.c.
Referenced by clear_player_status(), and func_800DFC74().
transform_point()
s32 transform_point ()
Definition at line 156 of file code_42e0_len_1f60.c.
copy_matrix()
void copy_matrix (Matrix4f * src, Matrix4f * dest)
Definition at line 158 of file code_42e0_len_1f60.c.
dma_copy()
s32 dma_copy (s32 romStart, s32 romEnd, void * vramDest)
Definition at line 162 of file code_42e0_len_1f60.c.
Referenced by func_80240000_BFD880(), func_802B2000(), func_802B203C(), func_802B2078(), func_802B20B4(), load_engine_data(), load_world_script_api(), LoadMoveScript(), and play_effect().
func_800297D4()
s32 func_800297D4 (s32 romStart, s32 romEnd, void * vramDest)
Definition at line 179 of file code_42e0_len_1f60.c.
_advance_rng()
s32 _advance_rng (void)
Definition at line 196 of file code_42e0_len_1f60.c.
Referenced by func_80029934(), and func_80029994().
func_80029934()
f32 func_80029934 (void)
Definition at line 204 of file code_42e0_len_1f60.c.
func_80029994()
s32 func_80029994 (s32 arg0)
Definition at line 215 of file code_42e0_len_1f60.c.
rand_int()
s32 rand_int (s32 arg0)
Definition at line 232 of file code_42e0_len_1f60.c.
Referenced by func_80260DD8(), get_coin_drop_amount(), OnFleeBattleDrops(), RandInt(), and UnkNpcAIFunc1().
signF()
f32 signF (f32 val)
Definition at line 234 of file code_42e0_len_1f60.c.
round()
s32 round (f32 arg0)
Definition at line 249 of file code_42e0_len_1f60.c.
Referenced by func_802CA988().
clamp_angle()
f32 clamp_angle (f32 theta)
Definition at line 257 of file code_42e0_len_1f60.c.
Referenced by ClampAngleFloat(), ClampAngleInt(), func_80218000_4CF1B0(), func_80283908(), func_802E10F4(), func_802E3728(), func_802E5E50(), func_802E9050(), GetCurrentCameraYawClamped180(), GetNpcYaw(), InterpPlayerYaw(), SomeItemEntityFunc(), SomeXYZFuncTodoRename(), UnkNpcAIFunc1(), and UnkYawFunc().
get_clamped_angle_diff()
f32 get_clamped_angle_diff (f32 a, f32 b)
Definition at line 259 of file code_42e0_len_1f60.c.
Referenced by set_npc_yaw().
atan2()
f32 atan2 (f32 startX, f32 startZ, f32 endX, f32 endZ)
Definition at line 270 of file code_42e0_len_1f60.c.
Referenced by func_80240034_7EAD44(), func_802E8ADC(), func_802E8BC0(), func_802E9050(), get_dpad_input_radial(), get_player_normal_pitch(), get_player_normal_yaw(), GetAngleBetweenNPCs(), GetAngleToNPC(), GetAngleToPlayer(), PlayerMoveTo(), set_script_owner_npc_anim(), UnkNpcAIFunc2(), and UnkNpcAIFunc9().
get_player_normal_yaw()
f32 get_player_normal_yaw (void)
Definition at line 272 of file code_42e0_len_1f60.c.
get_player_normal_pitch()
f32 get_player_normal_pitch (void)
Definition at line 276 of file code_42e0_len_1f60.c.
dist2D()
f32 dist2D (f32 ax, f32 ay, f32 bx, f32 by)
Definition at line 284 of file code_42e0_len_1f60.c.
Referenced by AwaitPlayerApproach(), AwaitPlayerLeave(), AwaitPlayerNearNpc(), func_800E0088(), get_dpad_input_radial(), GetDist2D(), is_point_within_region(), IsPlayerWithin(), PlayerMoveTo(), and UnkMusicFunc().
dist3D()
f32 dist3D (f32 ax, f32 ay, f32 az, f32 bx, f32 by, f32 bz)
Definition at line 291 of file code_42e0_len_1f60.c.
add_vec2D_polar()
void add_vec2D_polar (f32 * x, f32 * y, f32 r, f32 theta)
Definition at line 299 of file code_42e0_len_1f60.c.
Referenced by AddVectorPolar(), func_80283908(), SomeXYZFunc2(), and UnkYawFunc().
_wrap_trig_lookup_value()
u16 _wrap_trig_lookup_value (f32 theta)
Definition at line 308 of file code_42e0_len_1f60.c.
Referenced by cos_deg(), cos_rad(), sin_cos_deg(), sin_cos_rad(), sin_deg(), and sin_rad().
sin_rad()
f32 sin_rad (f32 angle)
Definition at line 326 of file code_42e0_len_1f60.c.
Referenced by func_80218000_4CF1B0(), func_802E3728(), func_802E37E4(), and npc_move_heading().
cos_rad()
f32 cos_rad (f32 angle)
Definition at line 330 of file code_42e0_len_1f60.c.
Referenced by npc_move_heading(), SomeItemEntityFunc(), and UnkFloatFunc().
sin_cos_deg()
void sin_cos_deg (f32 rad, f32 * outSinTheta, f32 * outCosTheta)
Definition at line 334 of file code_42e0_len_1f60.c.
sin_deg()
f32 sin_deg (f32 angle)
Definition at line 341 of file code_42e0_len_1f60.c.
Referenced by DemoJoystickRadial(), func_80240358_8C82E8(), SomeXYZFuncTodoRename(), and UnkCameraFunc().
cos_deg()
f32 cos_deg (f32 angle)
Definition at line 345 of file code_42e0_len_1f60.c.
Referenced by DemoJoystickRadial(), func_80240358_8C82E8(), SomeItemEntityFunc(), SomeXYZFuncTodoRename(), and UnkCameraFunc().
update_lerp()
f32 update_lerp (Easing easing, f32 start, f32 end, s32 elapsed, s32 duration)
Definition at line 349 of file code_42e0_len_1f60.c.
Referenced by UpdateLerp().
func_8002A904()
s32 func_8002A904 ()
Definition at line 351 of file code_42e0_len_1f60.c.
func_8002AAC4()
s32 func_8002AAC4 ()
Definition at line 353 of file code_42e0_len_1f60.c.
func_8002AB5C()
s32 func_8002AB5C ()
Definition at line 355 of file code_42e0_len_1f60.c.
Referenced by func_80033788().
Variable Documentation
D_80074260
u16 D_80074260 = 0
Definition at line 6 of file code_42e0_len_1f60.c.
Referenced by func_80028F8C(), func_80028FE0(), and start_rumble().
D_80074264
s32 D_80074264 = 0
Definition at line 7 of file code_42e0_len_1f60.c.
Referenced by func_80028F8C().
D_80074268
s32 D_80074268[2] = {0, 0}
Definition at line 10 of file code_42e0_len_1f60.c.
D_80074270
s32 D_80074270 = 0
Definition at line 12 of file code_42e0_len_1f60.c.
D_80074274
f32 D_80074274[]
Definition at line 14 of file code_42e0_len_1f60.c.
D_800743E0
s8 D_800743E0[]
Definition at line 26 of file code_42e0_len_1f60.c.
gRandSeed
s32 gRandSeed = 1
Definition at line 32 of file code_42e0_len_1f60.c.
Referenced by _advance_rng(), and boot_main().
D_80074414
f32 D_80074414[]
Definition at line 34 of file code_42e0_len_1f60.c.
D_80074580
Gfx D_80074580[]
Definition at line 46 of file code_42e0_len_1f60.c.