src/code_105F90.c File Reference - Paper Mario Documentation
code_105F90.c File Reference
Functions
s32 func_802E4710 ()
s32 func_802E4730 ()
void func_802E4AEC (s32 entityIndex)
void func_802E4B10 (Entity *entity)
void func_802E4B60 (Entity *entity)
s32 func_802E4C10 ()
void func_802E4DE0 (Entity *entity)
s32 func_802E4E04 ()
void func_802E5308 (Entity *entity)
s32 func_802E5324 ()
void func_802E540C (Entity *entity)
void func_802E5428 (Entity *entity)
void func_802E545C (Entity *entity)
void func_802E548C (Entity *entity)
void func_802E54A8 (Entity *entity)
void func_802E54CC (Entity *entity)
void func_802E555C (Entity *entity)
s8 func_802E55A8 (Entity *entity, StaticEntityData *data)
void func_802E5648 (Entity *entity)
Variables
s32 D_802EA728
s32 D_802EA760
s32 D_802EB3C0
StaticEntityData D_802EA7BC
Function Documentation
func_802E4710()
s32 func_802E4710 ()
Definition at line 3 of file code_105F90.c.
func_802E4730()
s32 func_802E4730 ()
Definition at line 5 of file code_105F90.c.
Referenced by func_802E4AEC().
func_802E4AEC()
void func_802E4AEC (s32 entityIndex)
Definition at line 7 of file code_105F90.c.
Referenced by func_802E4B60().
func_802E4B10()
void func_802E4B10 (Entity * entity)
Definition at line 11 of file code_105F90.c.
Referenced by func_802E4B60(), and func_802E540C().
func_802E4B60()
void func_802E4B60 (Entity * entity)
Definition at line 20 of file code_105F90.c.
Referenced by func_802E5428().
func_802E4C10()
s32 func_802E4C10 ()
Definition at line 49 of file code_105F90.c.
Referenced by func_802E545C().
func_802E4DE0()
void func_802E4DE0 (Entity * entity)
Definition at line 51 of file code_105F90.c.
func_802E4E04()
s32 func_802E4E04 ()
Definition at line 61 of file code_105F90.c.
Referenced by func_802E548C().
func_802E5308()
void func_802E5308 (Entity * entity)
Definition at line 63 of file code_105F90.c.
func_802E5324()
s32 func_802E5324 ()
Definition at line 67 of file code_105F90.c.
Referenced by func_802E545C().
func_802E540C()
void func_802E540C (Entity * entity)
Definition at line 69 of file code_105F90.c.
func_802E5428()
void func_802E5428 (Entity * entity)
Definition at line 75 of file code_105F90.c.
func_802E545C()
void func_802E545C (Entity * entity)
Definition at line 80 of file code_105F90.c.
func_802E548C()
void func_802E548C (Entity * entity)
Definition at line 85 of file code_105F90.c.
func_802E54A8()
void func_802E54A8 (Entity * entity)
Definition at line 91 of file code_105F90.c.
func_802E54CC()
void func_802E54CC (Entity * entity)
Definition at line 97 of file code_105F90.c.
func_802E555C()
void func_802E555C (Entity * entity)
Definition at line 111 of file code_105F90.c.
func_802E55A8()
s8 func_802E55A8 (Entity * entity, StaticEntityData * data)
Definition at line 120 of file code_105F90.c.
Referenced by func_802E5648().
func_802E5648()
void func_802E5648 (Entity * entity)
Definition at line 141 of file code_105F90.c.
Variable Documentation
D_802EA728
s32 D_802EA728 extern
Referenced by func_802E5428().
D_802EA760
s32 D_802EA760 extern
Referenced by func_802E54A8().
D_802EB3C0
s32 D_802EB3C0 extern
Referenced by func_802E54CC(), and func_802E555C().
D_802EA7BC
StaticEntityData D_802EA7BC extern
Referenced by func_802E5648().