src/code_ef070_len_3400.c File Reference - Paper Mario Documentation
code_ef070_len_3400.c File Reference
Functions
ApiStatus SetCamEnabled (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamFlag80 (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamPerspective (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CA90C (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CA988 (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamViewport (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CABE8 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CACC0 (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamBGColor (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CAE50 (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamTarget (ScriptInstance *script, s32 isInitialCall)
s32 func_802CB008 (ScriptInstance *script, s32 isInitialCall)
s32 ShakeCam (ScriptInstance *script, s32 isInitialCall)
void exec_ShakeCam1 (s32 arg0, s32 arg1, s32 arg2)
void exec_ShakeCamX (s32 arg0, s32 arg1, s32 arg2, f32 arg3)
ApiStatus SetCamLeadPlayer (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CB710 (ScriptInstance *script, s32 isInitialCall)
ApiStatus PanToTarget (ScriptInstance *script, s32 isInitialCall)
s32 UseSettingsFrom (ScriptInstance *script, s32 isInitialCall)
s32 LoadSettings (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamType (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamPitch (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamDistance (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamPosA (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamPosB (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamPosC (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPanTarget (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamSpeed (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCamType (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCamPitch (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCamDistance (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCamPosA (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCamPosB (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCamPosC (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCamPosition (ScriptInstance *script, s32 isInitialCall)
ApiStatus WaitForCam (ScriptInstance *script, s32 isInitialCall)
s32 SetCamProperties (ScriptInstance *script, s32 isInitialCall)
s32 AdjustCam (ScriptInstance *script, s32 isInitialCall)
s32 ResetCam (ScriptInstance *script, s32 isInitialCall)
void func_802CCAC0 (void)
s32 draw_anim_models ()
ApiStatus func_802CCCB0 (ScriptInstance *script, s32 isInitialCall)
ApiStatus LoadModelAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CCDAC (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlayModelAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CCEDC (ScriptInstance *script, s32 isInitialCall)
ApiStatus ChangeModelAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetAnimModelPosition (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetAnimModelPosition (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddAnimModelPosition (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetAnimModelRotation (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetAnimModelScale (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CD348 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CD3C0 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CD418 (ScriptInstance *script, s32 isInitialCall)
s32 func_802CD4B4 ()
void func_802CD57C (void)
s32 func_802CD5C0 ()
s32 func_802CD6E0 ()
s32 func_802CD7D8 ()
s32 func_802CD8F8 ()
s32 func_802CD9F0 ()
Function Documentation
SetCamEnabled()
ApiStatus SetCamEnabled (ScriptInstance * script, s32 isInitialCall)
Definition at line 3 of file code_ef070_len_3400.c.
Referenced by N().
SetCamFlag80()
ApiStatus SetCamFlag80 (ScriptInstance * script, s32 isInitialCall)
Definition at line 16 of file code_ef070_len_3400.c.
SetCamPerspective()
ApiStatus SetCamPerspective (ScriptInstance * script, s32 isInitialCall)
Definition at line 29 of file code_ef070_len_3400.c.
Referenced by N().
func_802CA90C()
ApiStatus func_802CA90C (ScriptInstance * script, s32 isInitialCall)
Definition at line 48 of file code_ef070_len_3400.c.
func_802CA988()
ApiStatus func_802CA988 (ScriptInstance * script, s32 isInitialCall)
Definition at line 60 of file code_ef070_len_3400.c.
SetCamViewport()
ApiStatus SetCamViewport (ScriptInstance * script, s32 isInitialCall)
Definition at line 91 of file code_ef070_len_3400.c.
func_802CABE8()
ApiStatus func_802CABE8 (ScriptInstance * script, s32 isInitialCall)
Definition at line 103 of file code_ef070_len_3400.c.
func_802CACC0()
ApiStatus func_802CACC0 (ScriptInstance * script, s32 isInitialCall)
Definition at line 120 of file code_ef070_len_3400.c.
SetCamBGColor()
ApiStatus SetCamBGColor (ScriptInstance * script, s32 isInitialCall)
Definition at line 137 of file code_ef070_len_3400.c.
Referenced by N().
func_802CAE50()
ApiStatus func_802CAE50 (ScriptInstance * script, s32 isInitialCall)
Definition at line 152 of file code_ef070_len_3400.c.
SetCamTarget()
ApiStatus SetCamTarget (ScriptInstance * script, s32 isInitialCall)
Definition at line 167 of file code_ef070_len_3400.c.
Referenced by N().
func_802CB008()
s32 func_802CB008 (ScriptInstance * script, s32 isInitialCall)
Definition at line 182 of file code_ef070_len_3400.c.
ShakeCam()
s32 ShakeCam (ScriptInstance * script, s32 isInitialCall)
Definition at line 184 of file code_ef070_len_3400.c.
exec_ShakeCam1()
void exec_ShakeCam1 (s32 arg0, s32 arg1, s32 arg2)
Definition at line 186 of file code_ef070_len_3400.c.
Referenced by SetPlayerAnimation().
exec_ShakeCamX()
void exec_ShakeCamX (s32 arg0, s32 arg1, s32 arg2, f32 arg3)
Definition at line 195 of file code_ef070_len_3400.c.
SetCamLeadPlayer()
ApiStatus SetCamLeadPlayer (ScriptInstance * script, s32 isInitialCall)
Definition at line 205 of file code_ef070_len_3400.c.
Referenced by N().
func_802CB710()
ApiStatus func_802CB710 (ScriptInstance * script, s32 isInitialCall)
Definition at line 220 of file code_ef070_len_3400.c.
PanToTarget()
ApiStatus PanToTarget (ScriptInstance * script, s32 isInitialCall)
Definition at line 231 of file code_ef070_len_3400.c.
Referenced by N().
UseSettingsFrom()
s32 UseSettingsFrom (ScriptInstance * script, s32 isInitialCall)
Definition at line 251 of file code_ef070_len_3400.c.
Referenced by N().
LoadSettings()
s32 LoadSettings (ScriptInstance * script, s32 isInitialCall)
Definition at line 253 of file code_ef070_len_3400.c.
SetCamType()
ApiStatus SetCamType (ScriptInstance * script, s32 isInitialCall)
Definition at line 255 of file code_ef070_len_3400.c.
SetCamPitch()
ApiStatus SetCamPitch (ScriptInstance * script, s32 isInitialCall)
Definition at line 268 of file code_ef070_len_3400.c.
Referenced by N().
SetCamDistance()
ApiStatus SetCamDistance (ScriptInstance * script, s32 isInitialCall)
Definition at line 281 of file code_ef070_len_3400.c.
Referenced by N().
SetCamPosA()
ApiStatus SetCamPosA (ScriptInstance * script, s32 isInitialCall)
Definition at line 292 of file code_ef070_len_3400.c.
SetCamPosB()
ApiStatus SetCamPosB (ScriptInstance * script, s32 isInitialCall)
Definition at line 305 of file code_ef070_len_3400.c.
SetCamPosC()
ApiStatus SetCamPosC (ScriptInstance * script, s32 isInitialCall)
Definition at line 318 of file code_ef070_len_3400.c.
SetPanTarget()
ApiStatus SetPanTarget (ScriptInstance * script, s32 isInitialCall)
Definition at line 331 of file code_ef070_len_3400.c.
Referenced by N().
SetCamSpeed()
ApiStatus SetCamSpeed (ScriptInstance * script, s32 isInitialCall)
Definition at line 347 of file code_ef070_len_3400.c.
Referenced by N().
GetCamType()
ApiStatus GetCamType (ScriptInstance * script, s32 isInitialCall)
Definition at line 358 of file code_ef070_len_3400.c.
GetCamPitch()
ApiStatus GetCamPitch (ScriptInstance * script, s32 isInitialCall)
Definition at line 371 of file code_ef070_len_3400.c.
GetCamDistance()
ApiStatus GetCamDistance (ScriptInstance * script, s32 isInitialCall)
Definition at line 384 of file code_ef070_len_3400.c.
GetCamPosA()
ApiStatus GetCamPosA (ScriptInstance * script, s32 isInitialCall)
Definition at line 395 of file code_ef070_len_3400.c.
GetCamPosB()
ApiStatus GetCamPosB (ScriptInstance * script, s32 isInitialCall)
Definition at line 408 of file code_ef070_len_3400.c.
GetCamPosC()
ApiStatus GetCamPosC (ScriptInstance * script, s32 isInitialCall)
Definition at line 421 of file code_ef070_len_3400.c.
GetCamPosition()
ApiStatus GetCamPosition (ScriptInstance * script, s32 isInitialCall)
Definition at line 434 of file code_ef070_len_3400.c.
WaitForCam()
ApiStatus WaitForCam (ScriptInstance * script, s32 isInitialCall)
Definition at line 449 of file code_ef070_len_3400.c.
Referenced by N().
SetCamProperties()
s32 SetCamProperties (ScriptInstance * script, s32 isInitialCall)
Definition at line 462 of file code_ef070_len_3400.c.
AdjustCam()
s32 AdjustCam (ScriptInstance * script, s32 isInitialCall)
Definition at line 464 of file code_ef070_len_3400.c.
ResetCam()
s32 ResetCam (ScriptInstance * script, s32 isInitialCall)
Definition at line 466 of file code_ef070_len_3400.c.
func_802CCAC0()
void func_802CCAC0 (void)
Definition at line 468 of file code_ef070_len_3400.c.
draw_anim_models()
s32 draw_anim_models ()
Definition at line 480 of file code_ef070_len_3400.c.
func_802CCCB0()
ApiStatus func_802CCCB0 (ScriptInstance * script, s32 isInitialCall)
Definition at line 482 of file code_ef070_len_3400.c.
LoadModelAnimation()
ApiStatus LoadModelAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 492 of file code_ef070_len_3400.c.
func_802CCDAC()
ApiStatus func_802CCDAC (ScriptInstance * script, s32 isInitialCall)
Definition at line 516 of file code_ef070_len_3400.c.
PlayModelAnimation()
ApiStatus PlayModelAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 540 of file code_ef070_len_3400.c.
func_802CCEDC()
ApiStatus func_802CCEDC (ScriptInstance * script, s32 isInitialCall)
Definition at line 552 of file code_ef070_len_3400.c.
ChangeModelAnimation()
ApiStatus ChangeModelAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 565 of file code_ef070_len_3400.c.
SetAnimModelPosition()
ApiStatus SetAnimModelPosition (ScriptInstance * script, s32 isInitialCall)
Definition at line 580 of file code_ef070_len_3400.c.
GetAnimModelPosition()
ApiStatus GetAnimModelPosition (ScriptInstance * script, s32 isInitialCall)
Definition at line 595 of file code_ef070_len_3400.c.
AddAnimModelPosition()
ApiStatus AddAnimModelPosition (ScriptInstance * script, s32 isInitialCall)
Definition at line 610 of file code_ef070_len_3400.c.
SetAnimModelRotation()
ApiStatus SetAnimModelRotation (ScriptInstance * script, s32 isInitialCall)
Definition at line 625 of file code_ef070_len_3400.c.
SetAnimModelScale()
ApiStatus SetAnimModelScale (ScriptInstance * script, s32 isInitialCall)
Definition at line 640 of file code_ef070_len_3400.c.
func_802CD348()
ApiStatus func_802CD348 (ScriptInstance * script, s32 isInitialCall)
Definition at line 655 of file code_ef070_len_3400.c.
func_802CD3C0()
ApiStatus func_802CD3C0 (ScriptInstance * script, s32 isInitialCall)
Definition at line 664 of file code_ef070_len_3400.c.
func_802CD418()
ApiStatus func_802CD418 (ScriptInstance * script, s32 isInitialCall)
Definition at line 672 of file code_ef070_len_3400.c.
func_802CD4B4()
s32 func_802CD4B4 ()
Definition at line 688 of file code_ef070_len_3400.c.
Referenced by clear_script_list().
func_802CD57C()
void func_802CD57C (void)
Definition at line 690 of file code_ef070_len_3400.c.
Referenced by init_script_list().
func_802CD5C0()
s32 func_802CD5C0 ()
Definition at line 698 of file code_ef070_len_3400.c.
func_802CD6E0()
s32 func_802CD6E0 ()
Definition at line 700 of file code_ef070_len_3400.c.
func_802CD7D8()
s32 func_802CD7D8 ()
Definition at line 702 of file code_ef070_len_3400.c.
func_802CD8F8()
s32 func_802CD8F8 ()
Definition at line 704 of file code_ef070_len_3400.c.
func_802CD9F0()
s32 func_802CD9F0 ()
Definition at line 706 of file code_ef070_len_3400.c.