src/code_B4580.c File Reference - Paper Mario Documentation
code_B4580.c File Reference
Functions
s32 func_8011DE80 ()
s32 func_8011DFD0 ()
s32 func_8011E014 ()
s32 func_8011E058 ()
s32 func_8011E09C ()
s32 func_8011E0DC ()
s32 func_8011E150 ()
s32 func_8011E1C4 ()
s32 func_8011E224 ()
s32 func_8011E310 ()
s32 func_8011E398 ()
s32 func_8011E400 ()
s32 func_8011E438 ()
s32 func_8011E4B8 ()
s32 func_8011E5E0 ()
s32 func_8011E718 ()
s32 func_8011E8BC ()
s32 func_8011EA54 ()
s32 func_8011EBF0 ()
s32 func_8011F058 ()
s32 func_8011F118 ()
s32 func_8011F304 ()
s32 func_8011F3E8 ()
s32 func_8011F4D4 ()
s32 func_8011FA54 ()
s32 func_8011FF74 ()
s32 func_8011FF98 ()
s32 func_8011FFB4 ()
AnimatedMesh * get_anim_mesh (s32 animModelID)
AnimatedMesh * func_80120000 (s32 animModelID, s32 arg1, s32 arg2)
s32 func_80120028 ()
s32 func_8012003C ()
s32 func_8012004C ()
s32 func_80120064 ()
s32 func_8012008C ()
s32 func_8012009C ()
s32 func_801200B8 ()
s32 func_801200EC ()
s32 func_80120118 ()
s32 play_model_animation ()
s32 func_80120198 ()
s32 func_80120234 ()
s32 func_801203AC ()
s32 func_80120420 ()
s32 func_80120474 ()
s32 func_80120530 ()
s32 func_80120678 ()
s32 func_801206F8 ()
Function Documentation
func_8011DE80()
s32 func_8011DE80 ()
Definition at line 3 of file code_B4580.c.
func_8011DFD0()
s32 func_8011DFD0 ()
Definition at line 5 of file code_B4580.c.
func_8011E014()
s32 func_8011E014 ()
Definition at line 7 of file code_B4580.c.
func_8011E058()
s32 func_8011E058 ()
Definition at line 9 of file code_B4580.c.
func_8011E09C()
s32 func_8011E09C ()
Definition at line 11 of file code_B4580.c.
func_8011E0DC()
s32 func_8011E0DC ()
Definition at line 13 of file code_B4580.c.
func_8011E150()
s32 func_8011E150 ()
Definition at line 15 of file code_B4580.c.
func_8011E1C4()
s32 func_8011E1C4 ()
Definition at line 17 of file code_B4580.c.
func_8011E224()
s32 func_8011E224 ()
Definition at line 19 of file code_B4580.c.
Referenced by load_engine_data(), and step_init_state().
func_8011E310()
s32 func_8011E310 ()
Definition at line 21 of file code_B4580.c.
func_8011E398()
s32 func_8011E398 ()
Definition at line 23 of file code_B4580.c.
func_8011E400()
s32 func_8011E400 ()
Definition at line 25 of file code_B4580.c.
func_8011E438()
s32 func_8011E438 ()
Definition at line 27 of file code_B4580.c.
Referenced by func_802CD3C0().
func_8011E4B8()
s32 func_8011E4B8 ()
Definition at line 29 of file code_B4580.c.
Referenced by func_802CCDAC(), and LoadModelAnimation().
func_8011E5E0()
s32 func_8011E5E0 ()
Definition at line 31 of file code_B4580.c.
func_8011E718()
s32 func_8011E718 ()
Definition at line 33 of file code_B4580.c.
func_8011E8BC()
s32 func_8011E8BC ()
Definition at line 35 of file code_B4580.c.
func_8011EA54()
s32 func_8011EA54 ()
Definition at line 37 of file code_B4580.c.
Referenced by func_802CCAC0().
func_8011EBF0()
s32 func_8011EBF0 ()
Definition at line 39 of file code_B4580.c.
func_8011F058()
s32 func_8011F058 ()
Definition at line 41 of file code_B4580.c.
func_8011F118()
s32 func_8011F118 ()
Definition at line 43 of file code_B4580.c.
func_8011F304()
s32 func_8011F304 ()
Definition at line 45 of file code_B4580.c.
func_8011F3E8()
s32 func_8011F3E8 ()
Definition at line 47 of file code_B4580.c.
func_8011F4D4()
s32 func_8011F4D4 ()
Definition at line 49 of file code_B4580.c.
func_8011FA54()
s32 func_8011FA54 ()
Definition at line 51 of file code_B4580.c.
func_8011FF74()
s32 func_8011FF74 ()
Definition at line 53 of file code_B4580.c.
func_8011FF98()
s32 func_8011FF98 ()
Definition at line 55 of file code_B4580.c.
func_8011FFB4()
s32 func_8011FFB4 ()
Definition at line 57 of file code_B4580.c.
get_anim_mesh()
AnimatedMesh* get_anim_mesh (s32 animModelID)
Definition at line 59 of file code_B4580.c.
Referenced by func_802CD348(), func_802CD3C0(), func_802CD418(), and func_802E46BC().
func_80120000()
AnimatedMesh* func_80120000 (s32 animModelID, s32 arg1, s32 arg2)
Definition at line 63 of file code_B4580.c.
func_80120028()
s32 func_80120028 ()
Definition at line 71 of file code_B4580.c.
func_8012003C()
s32 func_8012003C ()
Definition at line 73 of file code_B4580.c.
func_8012004C()
s32 func_8012004C ()
Definition at line 75 of file code_B4580.c.
func_80120064()
s32 func_80120064 ()
Definition at line 77 of file code_B4580.c.
func_8012008C()
s32 func_8012008C ()
Definition at line 79 of file code_B4580.c.
func_8012009C()
s32 func_8012009C ()
Definition at line 81 of file code_B4580.c.
func_801200B8()
s32 func_801200B8 ()
Definition at line 83 of file code_B4580.c.
func_801200EC()
s32 func_801200EC ()
Definition at line 85 of file code_B4580.c.
func_80120118()
s32 func_80120118 ()
Definition at line 87 of file code_B4580.c.
play_model_animation()
s32 play_model_animation ()
Definition at line 89 of file code_B4580.c.
Referenced by ChangeModelAnimation(), func_802402BC_8D878C(), func_80240A6C_8D482C(), func_802E40A0(), and PlayModelAnimation().
func_80120198()
s32 func_80120198 ()
Definition at line 91 of file code_B4580.c.
Referenced by func_802CCEDC().
func_80120234()
s32 func_80120234 ()
Definition at line 93 of file code_B4580.c.
func_801203AC()
s32 func_801203AC ()
Definition at line 95 of file code_B4580.c.
Referenced by LoadModelAnimation().
func_80120420()
s32 func_80120420 ()
Definition at line 97 of file code_B4580.c.
func_80120474()
s32 func_80120474 ()
Definition at line 99 of file code_B4580.c.
Referenced by func_802CCDAC().
func_80120530()
s32 func_80120530 ()
Definition at line 101 of file code_B4580.c.
func_80120678()
s32 func_80120678 ()
Definition at line 103 of file code_B4580.c.
func_801206F8()
s32 func_801206F8 ()
Definition at line 105 of file code_B4580.c.