src/code_dd930_len_1c0.c File Reference - Paper Mario Documentation
code_dd930_len_1c0.c File Reference
Data Structures
struct struct_80147230
Functions
void func_80147230 (void)
void func_80147264 (void)
s32 play_ambient_sounds (s32 fadeInTime, s32 fadeOutTime)
Variables
struct_80147230 D_8014F140
struct_80147230 D_8015C7C0
Function Documentation
func_80147230()
void func_80147230 (void)
Definition at line 15 of file code_dd930_len_1c0.c.
Referenced by load_engine_data().
func_80147264()
void func_80147264 (void)
Definition at line 19 of file code_dd930_len_1c0.c.
play_ambient_sounds()
s32 play_ambient_sounds (s32 fadeInTime, s32 fadeOutTime)
Definition at line 59 of file code_dd930_len_1c0.c.
Referenced by ClearAmbientSounds(), and PlayAmbientSounds().
Variable Documentation
D_8014F140
struct_80147230 D_8014F140 extern
Referenced by func_80147230().
D_8015C7C0
struct_80147230 D_8015C7C0 extern
Referenced by func_80147230(), func_80147264(), and play_ambient_sounds().