src/code_102C80.c File Reference - Paper Mario Documentation
code_102C80.c File Reference
Functions
void func_802E246C (Entity *entity, void *arg1, void *arg2)
void func_802E1400 (Entity *entity)
void func_802E1460 (Entity *entity)
void func_802E14D8 (Entity *entity)
void func_801125E8 (f32 *, f32 *, f32 *, f32 *, f32 *, f32 *)
void func_802E153C (Entity *entity)
void func_802E1614 (Entity *entity)
void func_802E1660 (Entity *entity)
void func_802E1740 (Entity *entity)
void func_802E176C (Entity *entity)
s32 func_802E17A8 (Entity *entity)
void func_802E1EA8 (Entity *entity)
void func_802E1EDC (Entity *entity)
void func_802E234C (Entity *entity)
void entity_init_BlueSwitch (Entity *entity)
void entity_init_HugeBlueSwitch (Entity *entity)
void func_802E2450 (Entity *entity)
void func_802E263C (Entity *entity)
void func_802E2BA4 (s32 entityIndex)
Function Documentation
func_802E246C()
void func_802E246C (Entity * entity, void * arg1, void * arg2)
Definition at line 519 of file code_102C80.c.
Referenced by func_802E2EB0().
func_802E1400()
void func_802E1400 (Entity * entity)
Definition at line 5 of file code_102C80.c.
func_802E1460()
void func_802E1460 (Entity * entity)
Definition at line 17 of file code_102C80.c.
func_802E14D8()
void func_802E14D8 (Entity * entity)
Definition at line 30 of file code_102C80.c.
func_801125E8()
void func_801125E8 (f32 * , f32 * , f32 * , f32 * , f32 * , f32 *)
Referenced by func_802E153C().
func_802E153C()
void func_802E153C (Entity * entity)
Definition at line 46 of file code_102C80.c.
Referenced by func_802E1660(), func_802E17A8(), and func_802E1EDC().
func_802E1614()
void func_802E1614 (Entity * entity)
Definition at line 69 of file code_102C80.c.
func_802E1660()
void func_802E1660 (Entity * entity)
Definition at line 80 of file code_102C80.c.
func_802E1740()
void func_802E1740 (Entity * entity)
Definition at line 126 of file code_102C80.c.
func_802E176C()
void func_802E176C (Entity * entity)
Definition at line 132 of file code_102C80.c.
func_802E17A8()
s32 func_802E17A8 (Entity * entity)
Definition at line 144 of file code_102C80.c.
func_802E1EA8()
void func_802E1EA8 (Entity * entity)
Definition at line 319 of file code_102C80.c.
func_802E1EDC()
void func_802E1EDC (Entity * entity)
Definition at line 327 of file code_102C80.c.
func_802E234C()
void func_802E234C (Entity * entity)
Definition at line 470 of file code_102C80.c.
Referenced by entity_init_BlueSwitch(), and entity_init_HugeBlueSwitch().
entity_init_BlueSwitch()
void entity_init_BlueSwitch (Entity * entity)
Definition at line 480 of file code_102C80.c.
entity_init_HugeBlueSwitch()
void entity_init_HugeBlueSwitch (Entity * entity)
Definition at line 501 of file code_102C80.c.
func_802E2450()
void func_802E2450 (Entity * entity)
Definition at line 514 of file code_102C80.c.
func_802E263C()
void func_802E263C (Entity * entity)
Definition at line 521 of file code_102C80.c.
func_802E2BA4()
void func_802E2BA4 (s32 entityIndex)
Definition at line 525 of file code_102C80.c.