src/code_190B20.c File Reference - Paper Mario Documentation
code_190B20.c File Reference
Functions
s32 create_target_list ()
void player_create_target_list (Actor *actor)
void enemy_create_target_list (Actor *actor)
s32 func_80263064 ()
s32 func_80263230 ()
s32 func_8026324C ()
s32 func_80263268 ()
s32 func_80263300 ()
s32 func_802633E8 ()
s32 func_80263434 ()
s32 func_80263464 ()
s32 func_802634B8 ()
s32 func_802636E4 ()
s32 func_80263914 ()
s32 count_power_plus ()
s32 deduct_current_move_fp ()
s32 func_80263C60 ()
s32 func_80263CC4 ()
s32 set_animation ()
s32 func_80263E08 ()
void set_animation_rate (ActorID actorID, s32 partIndex, f32 rate)
void set_actor_yaw (ActorID actorID, s32 yaw)
void set_part_yaw (ActorID actorID, s32 partIndex, s32 value)
s32 func_80263FE8 ()
s32 func_80264084 ()
s32 add_xz_vec3f ()
s32 add_xz_vec3f_copy1 ()
s32 add_xz_vec3f_copy2 ()
s32 play_movement_dust_effects ()
ActorPart * get_actor_part (Actor *actor, s32 partIndex)
s32 load_player_actor ()
s32 load_partner_actor ()
s32 create_actor ()
s32 func_80265CE8 ()
s32 func_80265D44 ()
s32 lookup_defense (DefenseTableEntry *defenseTable, Element elementKey)
s32 lookup_status_chance ()
s32 lookup_status_duration_mod ()
s32 inflict_status ()
s32 inflict_partner_ko (Actor *target, s32 statusTypeKey, s32 duration)
s32 get_defense (Actor *actor, s32 *defenseTable, s32 elementFlags)
s32 func_802664DC ()
s32 show_damage_popup ()
s32 func_80266684 ()
s32 func_802666E4 ()
s32 func_802667F0 ()
s32 func_80266970 ()
s32 func_80266978 ()
s32 func_80266ADC ()
s32 func_80266AF8 ()
s32 func_80266B14 ()
s32 try_inflict_status ()
s32 inflict_status_set_duration ()
s32 func_80266D6C ()
s32 func_80266DAC ()
s32 func_80266E14 ()
s32 func_80266E40 ()
s32 func_80266EA8 ()
s32 func_80266EE8 ()
s32 func_80266F60 ()
s32 func_80266F8C ()
s32 func_80266FD8 ()
s32 func_80267018 ()
s32 func_8026709C ()
s32 func_802670C8 ()
void add_part_decoration (ActorPart *part, s32 decorationIndex, DecorationId decorationType)
void add_actor_decoration (Actor *actor, s32 decorationIndex, DecorationId decorationType)
void remove_part_decoration (ActorPart *part, s32 decorationIndex)
void remove_actor_decoration (Actor *actor, s32 decorationIndex)
s32 heroes_is_ability_active (Actor *actor, Ability ability)
void create_part_shadow (ActorID actorID, s32 partIndex)
void remove_part_shadow (ActorID actorID, s32 partIndex)
void create_part_shadow_by_ref (s32 arg0, ActorPart *part)
void func_80071A50 (s32, f32 x, f32 y, f32 z, f32 scale, s32)
void func_80071C30 (s32, f32 x, f32 y, f32 z, f32 scale, s32)
void remove_player_buffs (PlayerBuff buffs)
s32 func_8026777C ()
s32 func_8026787C ()
s32 func_80267A3C ()
s32 reset_all_actor_sounds ()
void hide_foreground_models_unsafe (void)
void show_foreground_models_unsafe (void)
void hide_foreground_models (void)
void show_foreground_models (void)
s32 start_rumble_type ()
Function Documentation
create_target_list()
s32 create_target_list ()
Definition at line 3 of file code_190B20.c.
Referenced by enemy_create_target_list(), and player_create_target_list().
player_create_target_list()
void player_create_target_list (Actor * actor)
Definition at line 5 of file code_190B20.c.
Referenced by count_targets(), func_80218644_6DE404(), func_802186E0_6DE4A0(), func_80218770_6DE530(), func_802187F0_6DE5B0(), and PlayerCreateTargetList().
enemy_create_target_list()
void enemy_create_target_list (Actor * actor)
Definition at line 9 of file code_190B20.c.
Referenced by EnemyCreateTargetList().
func_80263064()
s32 func_80263064 ()
Definition at line 13 of file code_190B20.c.
func_80263230()
s32 func_80263230 ()
Definition at line 15 of file code_190B20.c.
func_8026324C()
s32 func_8026324C ()
Definition at line 17 of file code_190B20.c.
func_80263268()
s32 func_80263268 ()
Definition at line 19 of file code_190B20.c.
func_80263300()
s32 func_80263300 ()
Definition at line 21 of file code_190B20.c.
func_802633E8()
s32 func_802633E8 ()
Definition at line 23 of file code_190B20.c.
func_80263434()
s32 func_80263434 ()
Definition at line 25 of file code_190B20.c.
func_80263464()
s32 func_80263464 ()
Definition at line 27 of file code_190B20.c.
func_802634B8()
s32 func_802634B8 ()
Definition at line 29 of file code_190B20.c.
func_802636E4()
s32 func_802636E4 ()
Definition at line 31 of file code_190B20.c.
func_80263914()
s32 func_80263914 ()
Definition at line 33 of file code_190B20.c.
count_power_plus()
s32 count_power_plus ()
Definition at line 35 of file code_190B20.c.
deduct_current_move_fp()
s32 deduct_current_move_fp ()
Definition at line 37 of file code_190B20.c.
Referenced by LoadMoveScript().
func_80263C60()
s32 func_80263C60 ()
Definition at line 39 of file code_190B20.c.
func_80263CC4()
s32 func_80263CC4 ()
Definition at line 41 of file code_190B20.c.
set_animation()
s32 set_animation ()
Definition at line 43 of file code_190B20.c.
Referenced by SetAnimation().
func_80263E08()
s32 func_80263E08 ()
Definition at line 45 of file code_190B20.c.
Referenced by ActorSpeak().
set_animation_rate()
void set_animation_rate (ActorID actorID, s32 partIndex, f32 rate)
Definition at line 47 of file code_190B20.c.
Referenced by SetAnimationRate().
set_actor_yaw()
void set_actor_yaw (ActorID actorID, s32 yaw)
Definition at line 49 of file code_190B20.c.
Referenced by SetActorYaw().
set_part_yaw()
void set_part_yaw (ActorID actorID, s32 partIndex, s32 value)
Definition at line 53 of file code_190B20.c.
Referenced by SetPartYaw().
func_80263FE8()
s32 func_80263FE8 ()
Definition at line 57 of file code_190B20.c.
func_80264084()
s32 func_80264084 ()
Definition at line 59 of file code_190B20.c.
add_xz_vec3f()
s32 add_xz_vec3f ()
Definition at line 61 of file code_190B20.c.
add_xz_vec3f_copy1()
s32 add_xz_vec3f_copy1 ()
Definition at line 63 of file code_190B20.c.
add_xz_vec3f_copy2()
s32 add_xz_vec3f_copy2 ()
Definition at line 65 of file code_190B20.c.
play_movement_dust_effects()
s32 play_movement_dust_effects ()
Definition at line 67 of file code_190B20.c.
get_actor_part()
ActorPart * get_actor_part (Actor * actor, s32 partIndex)
Definition at line 69 of file code_190B20.c.
Referenced by ActorSpeak(), AddPartDispOffset(), AddPartMovementVar(), calc_item_check_hit(), create_part_shadow(), func_8026D51C(), func_8026D5A4(), func_8026DEF0(), func_8026DF88(), func_8027CC10(), func_8027D434(), func_8027D4C8(), GetAnimation(), GetPartDispOffset(), GetPartEventFlags(), GetPartFlags(), GetPartMovementVar(), GetPartOffset(), GetPartPos(), GetPartRotation(), GetPartScale(), GetPartTarget(), GetPartTargetFlags(), GetPartYaw(), PlaySoundAtPart(), remove_part_shadow(), set_part_absolute_position(), set_part_yaw(), SetDefenseTable(), SetEnemyTargetOffset(), SetIdleAnimations(), SetPartDispOffset(), SetPartEventBits(), SetPartEventFlags(), SetPartFlagBits(), SetPartFlags(), SetPartGoalToTarget(), SetPartJumpGravity(), SetPartMovementVar(), SetPartMoveSpeed(), SetPartPos(), SetPartRotation(), SetPartRotationOffset(), SetPartScale(), SetPartTargetFlagBits(), SetPartTargetFlags(), and SetTargetOffset().
load_player_actor()
s32 load_player_actor ()
Definition at line 86 of file code_190B20.c.
load_partner_actor()
s32 load_partner_actor ()
Definition at line 88 of file code_190B20.c.
create_actor()
s32 create_actor ()
Definition at line 90 of file code_190B20.c.
func_80265CE8()
s32 func_80265CE8 ()
Definition at line 92 of file code_190B20.c.
func_80265D44()
s32 func_80265D44 ()
Definition at line 94 of file code_190B20.c.
lookup_defense()
s32 lookup_defense (DefenseTableEntry * defenseTable, Element elementKey)
Definition at line 96 of file code_190B20.c.
Referenced by get_defense().
lookup_status_chance()
s32 lookup_status_chance ()
Definition at line 115 of file code_190B20.c.
lookup_status_duration_mod()
s32 lookup_status_duration_mod ()
Definition at line 117 of file code_190B20.c.
inflict_status()
s32 inflict_status ()
Definition at line 119 of file code_190B20.c.
Referenced by CopyStatusEffects(), and inflict_partner_ko().
inflict_partner_ko()
s32 inflict_partner_ko (Actor * target, s32 statusTypeKey, s32 duration)
Definition at line 121 of file code_190B20.c.
get_defense()
s32 get_defense (Actor * actor, s32 * defenseTable, s32 elementFlags)
Definition at line 137 of file code_190B20.c.
func_802664DC()
s32 func_802664DC ()
Definition at line 231 of file code_190B20.c.
show_damage_popup()
s32 show_damage_popup ()
Definition at line 233 of file code_190B20.c.
func_80266684()
s32 func_80266684 ()
Definition at line 235 of file code_190B20.c.
func_802666E4()
s32 func_802666E4 ()
Definition at line 237 of file code_190B20.c.
func_802667F0()
s32 func_802667F0 ()
Definition at line 239 of file code_190B20.c.
func_80266970()
s32 func_80266970 ()
Definition at line 241 of file code_190B20.c.
func_80266978()
s32 func_80266978 ()
Definition at line 243 of file code_190B20.c.
func_80266ADC()
s32 func_80266ADC ()
Definition at line 245 of file code_190B20.c.
Referenced by func_8027D2D8().
func_80266AF8()
s32 func_80266AF8 ()
Definition at line 247 of file code_190B20.c.
Referenced by func_8026D8EC(), and func_8027D32C().
func_80266B14()
s32 func_80266B14 ()
Definition at line 249 of file code_190B20.c.
try_inflict_status()
s32 try_inflict_status ()
Definition at line 251 of file code_190B20.c.
inflict_status_set_duration()
s32 inflict_status_set_duration ()
Definition at line 253 of file code_190B20.c.
Referenced by AfflictActor(), and func_80261D98().
func_80266D6C()
s32 func_80266D6C ()
Definition at line 255 of file code_190B20.c.
func_80266DAC()
s32 func_80266DAC ()
Definition at line 257 of file code_190B20.c.
func_80266E14()
s32 func_80266E14 ()
Definition at line 259 of file code_190B20.c.
func_80266E40()
s32 func_80266E40 ()
Definition at line 261 of file code_190B20.c.
func_80266EA8()
s32 func_80266EA8 ()
Definition at line 263 of file code_190B20.c.
func_80266EE8()
s32 func_80266EE8 ()
Definition at line 265 of file code_190B20.c.
Referenced by EnableActorGlow().
func_80266F60()
s32 func_80266F60 ()
Definition at line 267 of file code_190B20.c.
func_80266F8C()
s32 func_80266F8C ()
Definition at line 269 of file code_190B20.c.
func_80266FD8()
s32 func_80266FD8 ()
Definition at line 271 of file code_190B20.c.
func_80267018()
s32 func_80267018 ()
Definition at line 273 of file code_190B20.c.
func_8026709C()
s32 func_8026709C ()
Definition at line 275 of file code_190B20.c.
func_802670C8()
s32 func_802670C8 ()
Definition at line 277 of file code_190B20.c.
add_part_decoration()
void add_part_decoration (ActorPart * part, s32 decorationIndex, DecorationId decorationType)
Definition at line 279 of file code_190B20.c.
Referenced by add_actor_decoration().
add_actor_decoration()
void add_actor_decoration (Actor * actor, s32 decorationIndex, DecorationId decorationType)
Definition at line 291 of file code_190B20.c.
remove_part_decoration()
void remove_part_decoration (ActorPart * part, s32 decorationIndex)
Definition at line 300 of file code_190B20.c.
Referenced by remove_actor_decoration().
remove_actor_decoration()
void remove_actor_decoration (Actor * actor, s32 decorationIndex)
Definition at line 304 of file code_190B20.c.
Referenced by delete_player_actor().
heroes_is_ability_active()
s32 heroes_is_ability_active (Actor * actor, Ability ability)
Definition at line 313 of file code_190B20.c.
create_part_shadow()
void create_part_shadow (ActorID actorID, s32 partIndex)
Definition at line 331 of file code_190B20.c.
remove_part_shadow()
void remove_part_shadow (ActorID actorID, s32 partIndex)
Definition at line 339 of file code_190B20.c.
create_part_shadow_by_ref()
void create_part_shadow_by_ref (s32 arg0, ActorPart * part)
Definition at line 346 of file code_190B20.c.
func_80071A50()
void func_80071A50 (s32 , f32 x, f32 y, f32 z, f32 scale, s32)
Referenced by remove_player_buffs().
func_80071C30()
void func_80071C30 (s32 , f32 x, f32 y, f32 z, f32 scale, s32)
Referenced by remove_player_buffs().
remove_player_buffs()
void remove_player_buffs (PlayerBuff buffs)
Definition at line 355 of file code_190B20.c.
Referenced by RemovePlayerBuffs().
func_8026777C()
s32 func_8026777C ()
Definition at line 420 of file code_190B20.c.
Referenced by func_80261D98().
func_8026787C()
s32 func_8026787C ()
Definition at line 422 of file code_190B20.c.
func_80267A3C()
s32 func_80267A3C ()
Definition at line 424 of file code_190B20.c.
reset_all_actor_sounds()
s32 reset_all_actor_sounds ()
Definition at line 426 of file code_190B20.c.
Referenced by ResetAllActorSounds().
hide_foreground_models_unsafe()
void hide_foreground_models_unsafe (void)
Definition at line 428 of file code_190B20.c.
Referenced by SetForegroundModelsVisibleUnsafe().
show_foreground_models_unsafe()
void show_foreground_models_unsafe (void)
Definition at line 443 of file code_190B20.c.
Referenced by func_8023FF84(), and SetForegroundModelsVisibleUnsafe().
hide_foreground_models()
void hide_foreground_models (void)
Definition at line 458 of file code_190B20.c.
Referenced by SetForegroundModelsVisible().
show_foreground_models()
void show_foreground_models (void)
Definition at line 476 of file code_190B20.c.
Referenced by SetForegroundModelsVisible().
start_rumble_type()
s32 start_rumble_type ()
Definition at line 496 of file code_190B20.c.
Referenced by StartRumble().