src/code_ebd0_len_6a0.c File Reference - Paper Mario Documentation
code_ebd0_len_6a0.c File Reference
Functions
void intro_logos_set_fade_alpha (s16 alpha)
void intro_logos_set_fade_color (s16 color)
s16 intro_logos_fade_in (s16 subtractAlpha)
s16 intro_logos_fade_out (s16 addAlpha)
void intro_logos_update_fade (void)
void begin_state_battle (void)
s32 step_battle ()
void func_80033B54 (void)
void func_80033B88 (void)
s32 func_80033BC0 ()
void func_80033E64 (void)
Function Documentation
intro_logos_set_fade_alpha()
void intro_logos_set_fade_alpha (s16 alpha)
Definition at line 3 of file code_ebd0_len_6a0.c.
Referenced by begin_state_intro().
intro_logos_set_fade_color()
void intro_logos_set_fade_color (s16 color)
Definition at line 9 of file code_ebd0_len_6a0.c.
Referenced by begin_state_intro().
intro_logos_fade_in()
s16 intro_logos_fade_in (s16 subtractAlpha)
Definition at line 17 of file code_ebd0_len_6a0.c.
intro_logos_fade_out()
s16 intro_logos_fade_out (s16 addAlpha)
Definition at line 31 of file code_ebd0_len_6a0.c.
intro_logos_update_fade()
void intro_logos_update_fade (void)
Definition at line 45 of file code_ebd0_len_6a0.c.
Referenced by begin_state_intro().
begin_state_battle()
void begin_state_battle (void)
Definition at line 50 of file code_ebd0_len_6a0.c.
step_battle()
s32 step_battle ()
Definition at line 54 of file code_ebd0_len_6a0.c.
func_80033B54()
void func_80033B54 (void)
Definition at line 56 of file code_ebd0_len_6a0.c.
func_80033B88()
void func_80033B88 (void)
Definition at line 63 of file code_ebd0_len_6a0.c.
func_80033BC0()
s32 func_80033BC0 ()
Definition at line 69 of file code_ebd0_len_6a0.c.
func_80033E64()
void func_80033E64 (void)
Definition at line 71 of file code_ebd0_len_6a0.c.