src/code_d610_len_1330.c File Reference - Paper Mario Documentation
code_d610_len_1330.c File Reference
Functions
s32 func_80032210 ()
s32 func_800322DC ()
s32 func_800325E4 ()
s32 func_800328A4 ()
s32 func_80032970 ()
s32 func_80032C64 ()
s32 func_80033394 ()
void func_800334E8 (void)
s32 set_game_mode ()
s32 get_game_mode ()
Function Documentation
func_80032210()
s32 func_80032210 ()
Definition at line 3 of file code_d610_len_1330.c.
func_800322DC()
s32 func_800322DC ()
Definition at line 5 of file code_d610_len_1330.c.
func_800325E4()
s32 func_800325E4 ()
Definition at line 7 of file code_d610_len_1330.c.
func_800328A4()
s32 func_800328A4 ()
Definition at line 9 of file code_d610_len_1330.c.
func_80032970()
s32 func_80032970 ()
Definition at line 11 of file code_d610_len_1330.c.
func_80032C64()
s32 func_80032C64 ()
Definition at line 13 of file code_d610_len_1330.c.
func_80033394()
s32 func_80033394 ()
Definition at line 15 of file code_d610_len_1330.c.
func_800334E8()
void func_800334E8 (void)
Definition at line 17 of file code_d610_len_1330.c.
set_game_mode()
s32 set_game_mode ()
Definition at line 20 of file code_d610_len_1330.c.
Referenced by load_engine_data(), SetGameMode(), and step_init_state().
get_game_mode()
s32 get_game_mode ()
Definition at line 22 of file code_d610_len_1330.c.