src/os/code_4ac90_len_3910.c File Reference - Paper Mario Documentation
code_4ac90_len_3910.c File Reference
Functions
s32 func_8006F890 ()
void func_8006F8F0 (f32 arg0, f32 arg1, f32 arg2)
s32 func_8006F950 ()
s32 func_8006F9B0 ()
s32 func_8006FA10 ()
s32 func_8006FA70 ()
s32 fx_walk_large ()
void fx_walk_normal (s32 arg0, f32 arg1, f32 arg2, f32 arg3, s32 arg4, s32 arg5)
s32 func_8006FB90 ()
s32 func_8006FBF0 ()
s32 func_8006FC50 ()
s32 func_8006FCB0 ()
s32 func_8006FD10 ()
s32 func_8006FD70 ()
s32 func_8006FDD0 ()
s32 func_8006FE30 ()
void fx_emote (s32 arg0, Npc *arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, s32 arg7, s32 *arg8)
void func_8006FEF0 (s32 a0, f32 a1, f32 a2, f32 a3, f32 a4)
s32 func_8006FF50 ()
s32 func_8006FFB0 ()
s32 func_80070010 ()
s32 func_80070070 ()
s32 func_800700D0 ()
s32 func_80070130 ()
void func_80070190 (s32 arg0, f32 arg1, f32 arg2, f32 arg3, s32 arg4, f32 arg5, s32 arg6, s32 arg7)
s32 func_800701F0 ()
s32 func_80070250 ()
s32 func_800702B0 ()
s32 func_80070310 ()
s32 func_80070370 ()
s32 func_800703D0 ()
s32 func_80070430 ()
s32 func_80070490 ()
s32 func_800704F0 ()
void func_80070550 (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, s32 arg6, s32 arg7)
s32 func_800705B0 ()
s32 func_80070610 ()
s32 func_80070670 ()
s32 func_800706D0 ()
s32 func_80070730 ()
s32 fx_sweat ()
s32 fx_sleep_bubble ()
s32 func_80070850 ()
s32 func_800708B0 ()
s32 func_80070910 ()
s32 func_80070970 ()
s32 func_800709D0 ()
s32 func_80070A30 ()
void func_80070A90 (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
void func_80070AF0 (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
s32 func_80070B50 ()
s32 func_80070BB0 ()
s32 func_80070C10 ()
s32 func_80070C70 ()
s32 func_80070CD0 ()
s32 func_80070D30 ()
s32 func_80070D90 ()
s32 func_80070DF0 ()
s32 func_80070E50 ()
s32 func_80070EB0 ()
s32 func_80070F10 ()
s32 func_80070F70 ()
s32 func_80070FD0 ()
s32 func_80071030 ()
void func_80071090 (s32 a0, f32 a1, f32 a2, f32 a3, s32 a4)
s32 func_800710F0 ()
s32 func_80071150 ()
s32 func_800711B0 ()
s32 func_80071210 ()
s32 func_80071270 ()
s32 func_800712D0 ()
s32 func_80071330 ()
s32 func_80071390 ()
s32 func_800713F0 ()
s32 func_80071450 ()
s32 func_800714B0 ()
s32 func_80071510 ()
s32 func_80071570 ()
s32 func_800715D0 ()
s32 func_80071630 ()
s32 func_80071690 ()
s32 func_800716F0 ()
void func_80071750 (s32 a0, f32 a1, f32 a2, f32 a3, f32 a4, s32 a5)
s32 func_800717B0 ()
s32 func_80071810 ()
s32 func_80071870 ()
s32 func_800718D0 ()
s32 func_80071930 ()
s32 func_80071990 ()
s32 func_800719F0 ()
s32 func_80071A50 ()
s32 func_80071AB0 ()
s32 func_80071B10 ()
s32 func_80071B70 ()
s32 func_80071BD0 ()
s32 func_80071C30 ()
s32 func_80071C90 ()
s32 func_80071CF0 ()
s32 func_80071D50 ()
s32 func_80071DB0 ()
s32 func_80071E10 ()
s32 func_80071E70 ()
s32 func_80071ED0 ()
s32 func_80071F30 ()
s32 func_80071F90 ()
s32 func_80071FF0 ()
s32 func_80072050 ()
void func_800720B0 (s32 a0, f32 a1, f32 a2, f32 a3, f32 a4, s32 a5)
s32 func_80072110 ()
s32 func_80072170 ()
s32 func_800721D0 ()
s32 func_80072230 (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
s32 func_80072290 ()
s32 func_800722F0 ()
s32 func_80072350 ()
s32 func_800723B0 ()
s32 func_80072410 ()
s32 func_80072470 ()
s32 func_800724D0 ()
s32 func_80072530 ()
s32 func_80072590 ()
s32 func_800725F0 ()
s32 func_80072650 ()
s32 func_800726B0 ()
s32 func_80072710 ()
s32 func_80072770 ()
s32 func_800727D0 ()
s32 func_80072830 ()
s32 func_80072890 ()
s32 func_800728F0 ()
void func_80072950 (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 time)
s32 func_800729B0 ()
s32 func_80072A10 ()
s32 func_80072A70 ()
s32 func_80072AD0 ()
s32 func_80072B30 ()
s32 func_80072BB0 ()
s32 func_80072BCC ()
s32 func_80072BDC ()
s32 load_battle ()
s32 func_80072CCC ()
s32 func_80072CDC ()
void func_80072CEC ()
s32 func_80072CF4 ()
s32 setup_demo_player ()
s32 load_demo_battle ()
Variables
EffectTableEntry D_8007F210 [135]
Function Documentation
func_8006F890()
s32 func_8006F890 ()
Definition at line 5 of file code_4ac90_len_3910.c.
func_8006F8F0()
void func_8006F8F0 (f32 arg0, f32 arg1, f32 arg2)
Definition at line 7 of file code_4ac90_len_3910.c.
Referenced by OnDefeatEnemy().
func_8006F950()
s32 func_8006F950 ()
Definition at line 9 of file code_4ac90_len_3910.c.
func_8006F9B0()
s32 func_8006F9B0 ()
Definition at line 11 of file code_4ac90_len_3910.c.
func_8006FA10()
s32 func_8006FA10 ()
Definition at line 13 of file code_4ac90_len_3910.c.
func_8006FA70()
s32 func_8006FA70 ()
Definition at line 15 of file code_4ac90_len_3910.c.
fx_walk_large()
s32 fx_walk_large ()
Definition at line 17 of file code_4ac90_len_3910.c.
fx_walk_normal()
void fx_walk_normal (s32 arg0, f32 arg1, f32 arg2, f32 arg3, s32 arg4, s32 arg5)
Definition at line 19 of file code_4ac90_len_3910.c.
Referenced by func_80240720_9AEE20().
func_8006FB90()
s32 func_8006FB90 ()
Definition at line 21 of file code_4ac90_len_3910.c.
func_8006FBF0()
s32 func_8006FBF0 ()
Definition at line 23 of file code_4ac90_len_3910.c.
func_8006FC50()
s32 func_8006FC50 ()
Definition at line 25 of file code_4ac90_len_3910.c.
func_8006FCB0()
s32 func_8006FCB0 ()
Definition at line 27 of file code_4ac90_len_3910.c.
func_8006FD10()
s32 func_8006FD10 ()
Definition at line 29 of file code_4ac90_len_3910.c.
func_8006FD70()
s32 func_8006FD70 ()
Definition at line 31 of file code_4ac90_len_3910.c.
func_8006FDD0()
s32 func_8006FDD0 ()
Definition at line 33 of file code_4ac90_len_3910.c.
func_8006FE30()
s32 func_8006FE30 ()
Definition at line 35 of file code_4ac90_len_3910.c.
fx_emote()
void fx_emote (s32 arg0, Npc * arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, s32 arg7, s32 * arg8)
Definition at line 38 of file code_4ac90_len_3910.c.
Referenced by func_80045900(), UnkNpcAIFunc11(), and UnkNpcAIFunc8().
func_8006FEF0()
void func_8006FEF0 (s32 a0, f32 a1, f32 a2, f32 a3, f32 a4)
Definition at line 40 of file code_4ac90_len_3910.c.
Referenced by func_802403B8_8AC348(), func_80240530_8AC4C0(), func_80240BD8_8ACB68(), and func_802BD100_3251D0().
func_8006FF50()
s32 func_8006FF50 ()
Definition at line 42 of file code_4ac90_len_3910.c.
func_8006FFB0()
s32 func_8006FFB0 ()
Definition at line 44 of file code_4ac90_len_3910.c.
func_80070010()
s32 func_80070010 ()
Definition at line 46 of file code_4ac90_len_3910.c.
func_80070070()
s32 func_80070070 ()
Definition at line 48 of file code_4ac90_len_3910.c.
func_800700D0()
s32 func_800700D0 ()
Definition at line 50 of file code_4ac90_len_3910.c.
func_80070130()
s32 func_80070130 ()
Definition at line 52 of file code_4ac90_len_3910.c.
func_80070190()
void func_80070190 (s32 arg0, f32 arg1, f32 arg2, f32 arg3, s32 arg4, f32 arg5, s32 arg6, s32 arg7)
Definition at line 55 of file code_4ac90_len_3910.c.
Referenced by OnDefeatEnemy().
func_800701F0()
s32 func_800701F0 ()
Definition at line 57 of file code_4ac90_len_3910.c.
func_80070250()
s32 func_80070250 ()
Definition at line 59 of file code_4ac90_len_3910.c.
func_800702B0()
s32 func_800702B0 ()
Definition at line 61 of file code_4ac90_len_3910.c.
func_80070310()
s32 func_80070310 ()
Definition at line 63 of file code_4ac90_len_3910.c.
func_80070370()
s32 func_80070370 ()
Definition at line 65 of file code_4ac90_len_3910.c.
func_800703D0()
s32 func_800703D0 ()
Definition at line 67 of file code_4ac90_len_3910.c.
func_80070430()
s32 func_80070430 ()
Definition at line 69 of file code_4ac90_len_3910.c.
func_80070490()
s32 func_80070490 ()
Definition at line 71 of file code_4ac90_len_3910.c.
func_800704F0()
s32 func_800704F0 ()
Definition at line 73 of file code_4ac90_len_3910.c.
func_80070550()
void func_80070550 (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, s32 arg6, s32 arg7)
Definition at line 76 of file code_4ac90_len_3910.c.
Referenced by func_802E5E50().
func_800705B0()
s32 func_800705B0 ()
Definition at line 78 of file code_4ac90_len_3910.c.
func_80070610()
s32 func_80070610 ()
Definition at line 80 of file code_4ac90_len_3910.c.
func_80070670()
s32 func_80070670 ()
Definition at line 82 of file code_4ac90_len_3910.c.
func_800706D0()
s32 func_800706D0 ()
Definition at line 84 of file code_4ac90_len_3910.c.
func_80070730()
s32 func_80070730 ()
Definition at line 86 of file code_4ac90_len_3910.c.
fx_sweat()
s32 fx_sweat ()
Definition at line 88 of file code_4ac90_len_3910.c.
fx_sleep_bubble()
s32 fx_sleep_bubble ()
Definition at line 90 of file code_4ac90_len_3910.c.
func_80070850()
s32 func_80070850 ()
Definition at line 92 of file code_4ac90_len_3910.c.
func_800708B0()
s32 func_800708B0 ()
Definition at line 94 of file code_4ac90_len_3910.c.
func_80070910()
s32 func_80070910 ()
Definition at line 96 of file code_4ac90_len_3910.c.
func_80070970()
s32 func_80070970 ()
Definition at line 98 of file code_4ac90_len_3910.c.
func_800709D0()
s32 func_800709D0 ()
Definition at line 100 of file code_4ac90_len_3910.c.
func_80070A30()
s32 func_80070A30 ()
Definition at line 102 of file code_4ac90_len_3910.c.
func_80070A90()
void func_80070A90 (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
Definition at line 104 of file code_4ac90_len_3910.c.
Referenced by func_8027143C().
func_80070AF0()
void func_80070AF0 (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
Definition at line 106 of file code_4ac90_len_3910.c.
Referenced by func_80271210(), and func_80271258().
func_80070B50()
s32 func_80070B50 ()
Definition at line 108 of file code_4ac90_len_3910.c.
func_80070BB0()
s32 func_80070BB0 ()
Definition at line 110 of file code_4ac90_len_3910.c.
func_80070C10()
s32 func_80070C10 ()
Definition at line 112 of file code_4ac90_len_3910.c.
func_80070C70()
s32 func_80070C70 ()
Definition at line 114 of file code_4ac90_len_3910.c.
func_80070CD0()
s32 func_80070CD0 ()
Definition at line 116 of file code_4ac90_len_3910.c.
func_80070D30()
s32 func_80070D30 ()
Definition at line 118 of file code_4ac90_len_3910.c.
func_80070D90()
s32 func_80070D90 ()
Definition at line 120 of file code_4ac90_len_3910.c.
func_80070DF0()
s32 func_80070DF0 ()
Definition at line 122 of file code_4ac90_len_3910.c.
func_80070E50()
s32 func_80070E50 ()
Definition at line 124 of file code_4ac90_len_3910.c.
func_80070EB0()
s32 func_80070EB0 ()
Definition at line 126 of file code_4ac90_len_3910.c.
func_80070F10()
s32 func_80070F10 ()
Definition at line 128 of file code_4ac90_len_3910.c.
func_80070F70()
s32 func_80070F70 ()
Definition at line 130 of file code_4ac90_len_3910.c.
func_80070FD0()
s32 func_80070FD0 ()
Definition at line 132 of file code_4ac90_len_3910.c.
func_80071030()
s32 func_80071030 ()
Definition at line 134 of file code_4ac90_len_3910.c.
func_80071090()
void func_80071090 (s32 a0, f32 a1, f32 a2, f32 a3, s32 a4)
Definition at line 136 of file code_4ac90_len_3910.c.
Referenced by func_802BD1AC_3251D0(), and func_802BD26C().
func_800710F0()
s32 func_800710F0 ()
Definition at line 138 of file code_4ac90_len_3910.c.
func_80071150()
s32 func_80071150 ()
Definition at line 140 of file code_4ac90_len_3910.c.
func_800711B0()
s32 func_800711B0 ()
Definition at line 142 of file code_4ac90_len_3910.c.
func_80071210()
s32 func_80071210 ()
Definition at line 144 of file code_4ac90_len_3910.c.
func_80071270()
s32 func_80071270 ()
Definition at line 146 of file code_4ac90_len_3910.c.
func_800712D0()
s32 func_800712D0 ()
Definition at line 148 of file code_4ac90_len_3910.c.
func_80071330()
s32 func_80071330 ()
Definition at line 150 of file code_4ac90_len_3910.c.
func_80071390()
s32 func_80071390 ()
Definition at line 152 of file code_4ac90_len_3910.c.
func_800713F0()
s32 func_800713F0 ()
Definition at line 154 of file code_4ac90_len_3910.c.
func_80071450()
s32 func_80071450 ()
Definition at line 156 of file code_4ac90_len_3910.c.
func_800714B0()
s32 func_800714B0 ()
Definition at line 158 of file code_4ac90_len_3910.c.
func_80071510()
s32 func_80071510 ()
Definition at line 160 of file code_4ac90_len_3910.c.
func_80071570()
s32 func_80071570 ()
Definition at line 162 of file code_4ac90_len_3910.c.
func_800715D0()
s32 func_800715D0 ()
Definition at line 164 of file code_4ac90_len_3910.c.
func_80071630()
s32 func_80071630 ()
Definition at line 166 of file code_4ac90_len_3910.c.
func_80071690()
s32 func_80071690 ()
Definition at line 168 of file code_4ac90_len_3910.c.
func_800716F0()
s32 func_800716F0 ()
Definition at line 170 of file code_4ac90_len_3910.c.
func_80071750()
void func_80071750 (s32 a0, f32 a1, f32 a2, f32 a3, f32 a4, s32 a5)
Definition at line 172 of file code_4ac90_len_3910.c.
Referenced by func_8003F4CC(), and func_802404A0_8AC430().
func_800717B0()
s32 func_800717B0 ()
Definition at line 174 of file code_4ac90_len_3910.c.
func_80071810()
s32 func_80071810 ()
Definition at line 176 of file code_4ac90_len_3910.c.
func_80071870()
s32 func_80071870 ()
Definition at line 178 of file code_4ac90_len_3910.c.
func_800718D0()
s32 func_800718D0 ()
Definition at line 180 of file code_4ac90_len_3910.c.
func_80071930()
s32 func_80071930 ()
Definition at line 182 of file code_4ac90_len_3910.c.
func_80071990()
s32 func_80071990 ()
Definition at line 184 of file code_4ac90_len_3910.c.
func_800719F0()
s32 func_800719F0 ()
Definition at line 186 of file code_4ac90_len_3910.c.
func_80071A50()
s32 func_80071A50 ()
Definition at line 188 of file code_4ac90_len_3910.c.
func_80071AB0()
s32 func_80071AB0 ()
Definition at line 190 of file code_4ac90_len_3910.c.
func_80071B10()
s32 func_80071B10 ()
Definition at line 192 of file code_4ac90_len_3910.c.
func_80071B70()
s32 func_80071B70 ()
Definition at line 194 of file code_4ac90_len_3910.c.
func_80071BD0()
s32 func_80071BD0 ()
Definition at line 196 of file code_4ac90_len_3910.c.
func_80071C30()
s32 func_80071C30 ()
Definition at line 198 of file code_4ac90_len_3910.c.
func_80071C90()
s32 func_80071C90 ()
Definition at line 200 of file code_4ac90_len_3910.c.
func_80071CF0()
s32 func_80071CF0 ()
Definition at line 202 of file code_4ac90_len_3910.c.
func_80071D50()
s32 func_80071D50 ()
Definition at line 204 of file code_4ac90_len_3910.c.
func_80071DB0()
s32 func_80071DB0 ()
Definition at line 206 of file code_4ac90_len_3910.c.
func_80071E10()
s32 func_80071E10 ()
Definition at line 208 of file code_4ac90_len_3910.c.
func_80071E70()
s32 func_80071E70 ()
Definition at line 210 of file code_4ac90_len_3910.c.
func_80071ED0()
s32 func_80071ED0 ()
Definition at line 212 of file code_4ac90_len_3910.c.
func_80071F30()
s32 func_80071F30 ()
Definition at line 214 of file code_4ac90_len_3910.c.
func_80071F90()
s32 func_80071F90 ()
Definition at line 216 of file code_4ac90_len_3910.c.
func_80071FF0()
s32 func_80071FF0 ()
Definition at line 218 of file code_4ac90_len_3910.c.
func_80072050()
s32 func_80072050 ()
Definition at line 220 of file code_4ac90_len_3910.c.
func_800720B0()
void func_800720B0 (s32 a0, f32 a1, f32 a2, f32 a3, f32 a4, s32 a5)
Definition at line 222 of file code_4ac90_len_3910.c.
Referenced by func_8003F414().
func_80072110()
s32 func_80072110 ()
Definition at line 224 of file code_4ac90_len_3910.c.
func_80072170()
s32 func_80072170 ()
Definition at line 226 of file code_4ac90_len_3910.c.
func_800721D0()
s32 func_800721D0 ()
Definition at line 228 of file code_4ac90_len_3910.c.
func_80072230()
s32 func_80072230 (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Definition at line 231 of file code_4ac90_len_3910.c.
Referenced by func_802E1EDC(), func_802E31B0(), and func_802E405C().
func_80072290()
s32 func_80072290 ()
Definition at line 233 of file code_4ac90_len_3910.c.
func_800722F0()
s32 func_800722F0 ()
Definition at line 235 of file code_4ac90_len_3910.c.
func_80072350()
s32 func_80072350 ()
Definition at line 237 of file code_4ac90_len_3910.c.
func_800723B0()
s32 func_800723B0 ()
Definition at line 239 of file code_4ac90_len_3910.c.
func_80072410()
s32 func_80072410 ()
Definition at line 241 of file code_4ac90_len_3910.c.
func_80072470()
s32 func_80072470 ()
Definition at line 243 of file code_4ac90_len_3910.c.
func_800724D0()
s32 func_800724D0 ()
Definition at line 245 of file code_4ac90_len_3910.c.
func_80072530()
s32 func_80072530 ()
Definition at line 247 of file code_4ac90_len_3910.c.
func_80072590()
s32 func_80072590 ()
Definition at line 249 of file code_4ac90_len_3910.c.
func_800725F0()
s32 func_800725F0 ()
Definition at line 251 of file code_4ac90_len_3910.c.
func_80072650()
s32 func_80072650 ()
Definition at line 253 of file code_4ac90_len_3910.c.
func_800726B0()
s32 func_800726B0 ()
Definition at line 255 of file code_4ac90_len_3910.c.
func_80072710()
s32 func_80072710 ()
Definition at line 257 of file code_4ac90_len_3910.c.
func_80072770()
s32 func_80072770 ()
Definition at line 259 of file code_4ac90_len_3910.c.
func_800727D0()
s32 func_800727D0 ()
Definition at line 261 of file code_4ac90_len_3910.c.
func_80072830()
s32 func_80072830 ()
Definition at line 263 of file code_4ac90_len_3910.c.
func_80072890()
s32 func_80072890 ()
Definition at line 265 of file code_4ac90_len_3910.c.
func_800728F0()
s32 func_800728F0 ()
Definition at line 267 of file code_4ac90_len_3910.c.
func_80072950()
void func_80072950 (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 time)
Definition at line 269 of file code_4ac90_len_3910.c.
Referenced by SpawnSunEffect().
func_800729B0()
s32 func_800729B0 ()
Definition at line 271 of file code_4ac90_len_3910.c.
func_80072A10()
s32 func_80072A10 ()
Definition at line 273 of file code_4ac90_len_3910.c.
func_80072A70()
s32 func_80072A70 ()
Definition at line 275 of file code_4ac90_len_3910.c.
func_80072AD0()
s32 func_80072AD0 ()
Definition at line 277 of file code_4ac90_len_3910.c.
func_80072B30()
s32 func_80072B30 ()
Definition at line 280 of file code_4ac90_len_3910.c.
Referenced by step_init_state().
func_80072BB0()
s32 func_80072BB0 ()
Definition at line 282 of file code_4ac90_len_3910.c.
func_80072BCC()
s32 func_80072BCC ()
Definition at line 284 of file code_4ac90_len_3910.c.
Referenced by func_80044238().
func_80072BDC()
s32 func_80072BDC ()
Definition at line 286 of file code_4ac90_len_3910.c.
load_battle()
s32 load_battle ()
Definition at line 288 of file code_4ac90_len_3910.c.
func_80072CCC()
s32 func_80072CCC ()
Definition at line 290 of file code_4ac90_len_3910.c.
func_80072CDC()
s32 func_80072CDC ()
Definition at line 292 of file code_4ac90_len_3910.c.
func_80072CEC()
void func_80072CEC ()
Definition at line 294 of file code_4ac90_len_3910.c.
func_80072CF4()
s32 func_80072CF4 ()
Definition at line 297 of file code_4ac90_len_3910.c.
setup_demo_player()
s32 setup_demo_player ()
Definition at line 299 of file code_4ac90_len_3910.c.
load_demo_battle()
s32 load_demo_battle ()
Definition at line 301 of file code_4ac90_len_3910.c.
Referenced by LoadDemoBattle().
Variable Documentation
D_8007F210
EffectTableEntry D_8007F210[135] extern