src/code_f8f60_len_1560.c File Reference - Paper Mario Documentation
code_f8f60_len_1560.c File Reference
Functions
ApiStatus MakeLerp (ScriptInstance *script, s32 isInitialCall)
ApiStatus UpdateLerp (ScriptInstance *script, s32 isInitialCall)
ApiStatus RandInt (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetAngleBetweenNPCs (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetAngleToNPC (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetAngleToPlayer (ScriptInstance *script, s32 isInitialCall)
ApiStatus AwaitPlayerApproach (ScriptInstance *script, s32 isInitialCall)
ApiStatus IsPlayerWithin (ScriptInstance *script, s32 isInitialCall)
ApiStatus AwaitPlayerLeave (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddVectorPolar (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D4BDC (ScriptInstance *script, s32 initialCall)
ApiStatus func_802D4C4C (ScriptInstance *script, s32 initialCall)
ApiStatus func_802D4CC4 (ScriptInstance *script, s32 initialCall)
ApiStatus func_802D4D14 (ScriptInstance *script, s32 initialCall)
ApiStatus func_802D4D88 (ScriptInstance *script, s32 initialCall)
void setup_path_data (s32 numVecs, f32 *arg1, struct Vec3f *arg2, struct Vec3f *arg3)
s32 func_802D5270 ()
s32 LoadPath (ScriptInstance *script, s32 isInitialCall)
s32 GetNextPathPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetDist2D (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D5830 (ScriptInstance *script, s32 initialCall)
ApiStatus func_802D585C (ScriptInstance *script, s32 initialCall)
ApiStatus SetValueByRef (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetValueByRef (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableStatusMenu (ScriptInstance *script, s32 isInitialCall)
ApiStatus ShowStatusMenu (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetGameMode (ScriptInstance *script, s32 isInitialCall)
ApiStatus ClampAngleInt (ScriptInstance *script, s32 isInitialCall)
ApiStatus ClampAngleFloat (ScriptInstance *script, s32 isInitialCall)
Function Documentation
MakeLerp()
ApiStatus MakeLerp (ScriptInstance * script, s32 isInitialCall)
Definition at line 3 of file code_f8f60_len_1560.c.
UpdateLerp()
ApiStatus UpdateLerp (ScriptInstance * script, s32 isInitialCall)
Definition at line 15 of file code_f8f60_len_1560.c.
RandInt()
ApiStatus RandInt (ScriptInstance * script, s32 isInitialCall)
Definition at line 34 of file code_f8f60_len_1560.c.
GetAngleBetweenNPCs()
ApiStatus GetAngleBetweenNPCs (ScriptInstance * script, s32 isInitialCall)
Definition at line 45 of file code_f8f60_len_1560.c.
GetAngleToNPC()
ApiStatus GetAngleToNPC (ScriptInstance * script, s32 isInitialCall)
Definition at line 59 of file code_f8f60_len_1560.c.
GetAngleToPlayer()
ApiStatus GetAngleToPlayer (ScriptInstance * script, s32 isInitialCall)
Definition at line 72 of file code_f8f60_len_1560.c.
Referenced by N().
AwaitPlayerApproach()
ApiStatus AwaitPlayerApproach (ScriptInstance * script, s32 isInitialCall)
Definition at line 85 of file code_f8f60_len_1560.c.
IsPlayerWithin()
ApiStatus IsPlayerWithin (ScriptInstance * script, s32 isInitialCall)
Definition at line 113 of file code_f8f60_len_1560.c.
AwaitPlayerLeave()
ApiStatus AwaitPlayerLeave (ScriptInstance * script, s32 isInitialCall)
Definition at line 144 of file code_f8f60_len_1560.c.
Referenced by N().
AddVectorPolar()
ApiStatus AddVectorPolar (ScriptInstance * script, s32 isInitialCall)
Definition at line 172 of file code_f8f60_len_1560.c.
Referenced by N().
func_802D4BDC()
ApiStatus func_802D4BDC (ScriptInstance * script, s32 initialCall)
Definition at line 191 of file code_f8f60_len_1560.c.
func_802D4C4C()
ApiStatus func_802D4C4C (ScriptInstance * script, s32 initialCall)
Definition at line 219 of file code_f8f60_len_1560.c.
func_802D4CC4()
ApiStatus func_802D4CC4 (ScriptInstance * script, s32 initialCall)
Definition at line 246 of file code_f8f60_len_1560.c.
func_802D4D14()
ApiStatus func_802D4D14 (ScriptInstance * script, s32 initialCall)
Definition at line 257 of file code_f8f60_len_1560.c.
func_802D4D88()
ApiStatus func_802D4D88 (ScriptInstance * script, s32 initialCall)
Definition at line 267 of file code_f8f60_len_1560.c.
setup_path_data()
void setup_path_data (s32 numVecs, f32 * arg1, struct Vec3f * arg2, struct Vec3f * arg3)
Definition at line 274 of file code_f8f60_len_1560.c.
Referenced by LoadPath().
func_802D5270()
s32 func_802D5270 ()
Definition at line 352 of file code_f8f60_len_1560.c.
LoadPath()
s32 LoadPath (ScriptInstance * script, s32 isInitialCall)
Definition at line 354 of file code_f8f60_len_1560.c.
GetNextPathPos()
s32 GetNextPathPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 376 of file code_f8f60_len_1560.c.
GetDist2D()
ApiStatus GetDist2D (ScriptInstance * script, s32 isInitialCall)
Definition at line 378 of file code_f8f60_len_1560.c.
func_802D5830()
ApiStatus func_802D5830 (ScriptInstance * script, s32 initialCall)
Definition at line 392 of file code_f8f60_len_1560.c.
Referenced by N().
func_802D585C()
ApiStatus func_802D585C (ScriptInstance * script, s32 initialCall)
Definition at line 397 of file code_f8f60_len_1560.c.
SetValueByRef()
ApiStatus SetValueByRef (ScriptInstance * script, s32 isInitialCall)
Definition at line 413 of file code_f8f60_len_1560.c.
Referenced by N().
GetValueByRef()
ApiStatus GetValueByRef (ScriptInstance * script, s32 isInitialCall)
Definition at line 423 of file code_f8f60_len_1560.c.
Referenced by N().
EnableStatusMenu()
ApiStatus EnableStatusMenu (ScriptInstance * script, s32 isInitialCall)
Definition at line 434 of file code_f8f60_len_1560.c.
ShowStatusMenu()
ApiStatus ShowStatusMenu (ScriptInstance * script, s32 isInitialCall)
Definition at line 444 of file code_f8f60_len_1560.c.
SetGameMode()
ApiStatus SetGameMode (ScriptInstance * script, s32 isInitialCall)
Definition at line 455 of file code_f8f60_len_1560.c.
ClampAngleInt()
ApiStatus ClampAngleInt (ScriptInstance * script, s32 isInitialCall)
Definition at line 463 of file code_f8f60_len_1560.c.
ClampAngleFloat()
ApiStatus ClampAngleFloat (ScriptInstance * script, s32 isInitialCall)
Definition at line 471 of file code_f8f60_len_1560.c.