src/os/code_42a00_len_100.c File Reference - Paper Mario Documentation
code_42a00_len_100.c File Reference
Functions
void guMtxCatF (float m[4][4], float n[4][4], float r[4][4])
Function Documentation
guMtxCatF()
void guMtxCatF (float m[4][4], float n[4][4], float r[4][4])
Definition at line 3 of file code_42a00_len_100.c.
Referenced by func_802E2BA4(), RotateModel(), ScaleModel(), SomeMatrixOperation2(), and TranslateModel().