src/os/code_44380_len_4e0.c File Reference - Paper Mario Documentation
code_44380_len_4e0.c File Reference
Functions
s32 osPfsFreeBlocks (OSPfs *pfs, s32 *unk1)
s32 osPfsNumFiles (OSPfs *pfs, s32 *unk1, s32 *unk2)
s32 osPfsInitPak (OSMesgQueue *queue, OSPfs *pfs, int unk1)
s32 osPfsCheckRamArea ()
Function Documentation
osPfsFreeBlocks()
s32 osPfsFreeBlocks (OSPfs * pfs, s32 * unk1)
Definition at line 3 of file code_44380_len_4e0.c.
Referenced by contPakFree().
osPfsNumFiles()
s32 osPfsNumFiles (OSPfs * pfs, s32 * unk1, s32 * unk2)
Definition at line 5 of file code_44380_len_4e0.c.
Referenced by contPakFileNum().
osPfsInitPak()
s32 osPfsInitPak (OSMesgQueue * queue, OSPfs * pfs, int unk1)
Definition at line 7 of file code_44380_len_4e0.c.
Referenced by contPakOpen().
osPfsCheckRamArea()
s32 osPfsCheckRamArea ()
Definition at line 9 of file code_44380_len_4e0.c.