src/code_77480.c File Reference - Paper Mario Documentation
code_77480.c File Reference
Functions
s32 test_below_player ()
s32 func_800DE46C ()
s32 trace_below_player ()
s32 collision_check_above ()
s32 trace_above_player ()
s32 do_lateral_collision ()
s32 func_800DEE5C ()
s32 func_800DF15C ()
void func_800DF3FC (f32 *arg0, f32 *arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5)
s32 test_player_lateral ()
s32 update_player ()
s32 check_input_use_partner ()
s32 func_800DFAAC ()
void func_800DFBE8 (void)
void clear_player_status (void)
void func_800DFC74 (void)
s32 func_800DFCF4 (void)
s32 func_800DFD48 ()
void func_800DFEFC (void)
void func_800DFF50 (s32 arg0)
void func_800DFF78 (void)
s32 func_800DFFCC ()
f32 func_800E0088 (f32 x, f32 z)
void enable_player_shadow (void)
void disable_player_shadow (void)
s32 disable_player_static_collisions (void)
s32 enable_player_static_collisions (void)
s32 disable_player_input (void)
s32 enable_player_input (void)
void func_800E01DC (void)
s32 func_800E0208 (void)
void func_800E0260 (void)
s32 func_800E0294 ()
void func_800E0330 (void)
void func_800E0374 (void)
s32 func_800E0398 ()
void func_800E04D0 (void)
void func_800E0514 (void)
s32 func_800E0538 (void)
s32 func_800E0580 ()
void func_800E0658 (void)
void func_800E069C (void)
void func_800E06C0 (s32 arg0)
s32 func_800E06D8 ()
s32 func_800E0818 ()
void func_800E0AD0 (void)
void func_800E0B14 (void)
void func_800E0B38 (void)
s32 func_800E0B90 ()
s32 func_800E0FEC ()
void render_player (void)
void render_player_model ()
s32 appendGfx_player ()
s32 appendGfx_player_spin ()
s32 update_player_shadow ()
Variables
s32 D_8010C920
s32 D_8010C93C
s32 D_8010C940
s32 D_8010C950
s32 D_8010C958
Function Documentation
test_below_player()
s32 test_below_player ()
Definition at line 9 of file code_77480.c.
func_800DE46C()
s32 func_800DE46C ()
Definition at line 11 of file code_77480.c.
trace_below_player()
s32 trace_below_player ()
Definition at line 13 of file code_77480.c.
collision_check_above()
s32 collision_check_above ()
Definition at line 15 of file code_77480.c.
trace_above_player()
s32 trace_above_player ()
Definition at line 17 of file code_77480.c.
do_lateral_collision()
s32 do_lateral_collision ()
Definition at line 19 of file code_77480.c.
func_800DEE5C()
s32 func_800DEE5C ()
Definition at line 21 of file code_77480.c.
func_800DF15C()
s32 func_800DF15C ()
Definition at line 23 of file code_77480.c.
func_800DF3FC()
void func_800DF3FC (f32 * arg0, f32 * arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5)
Definition at line 25 of file code_77480.c.
test_player_lateral()
s32 test_player_lateral ()
Definition at line 32 of file code_77480.c.
update_player()
s32 update_player ()
Definition at line 34 of file code_77480.c.
Referenced by step_world().
check_input_use_partner()
s32 check_input_use_partner ()
Definition at line 36 of file code_77480.c.
func_800DFAAC()
s32 func_800DFAAC ()
Definition at line 38 of file code_77480.c.
func_800DFBE8()
void func_800DFBE8 (void)
Definition at line 40 of file code_77480.c.
clear_player_status()
void clear_player_status (void)
Definition at line 54 of file code_77480.c.
Referenced by load_engine_data(), and step_init_state().
func_800DFC74()
void func_800DFC74 (void)
Definition at line 58 of file code_77480.c.
func_800DFCF4()
s32 func_800DFCF4 (void)
Definition at line 74 of file code_77480.c.
func_800DFD48()
s32 func_800DFD48 ()
Definition at line 82 of file code_77480.c.
Referenced by func_800DFEFC(), and func_800DFF78().
func_800DFEFC()
void func_800DFEFC (void)
Definition at line 84 of file code_77480.c.
func_800DFF50()
void func_800DFF50 (s32 arg0)
Definition at line 95 of file code_77480.c.
func_800DFF78()
void func_800DFF78 (void)
Definition at line 103 of file code_77480.c.
func_800DFFCC()
s32 func_800DFFCC ()
Definition at line 114 of file code_77480.c.
func_800E0088()
f32 func_800E0088 (f32 x, f32 z)
Definition at line 117 of file code_77480.c.
Referenced by func_802401B0_8C8140(), and func_802E8BC0().
enable_player_shadow()
void enable_player_shadow (void)
Definition at line 123 of file code_77480.c.
Referenced by HidePlayerShadow().
disable_player_shadow()
void disable_player_shadow (void)
Definition at line 127 of file code_77480.c.
Referenced by HidePlayerShadow(), and player_enter_blue_pipe().
disable_player_static_collisions()
s32 disable_player_static_collisions (void)
Definition at line 131 of file code_77480.c.
Referenced by DisablePlayerPhysics(), and func_802E8BC0().
enable_player_static_collisions()
s32 enable_player_static_collisions (void)
Definition at line 139 of file code_77480.c.
Referenced by DisablePlayerPhysics(), and func_802D6954().
disable_player_input()
s32 disable_player_input (void)
Definition at line 149 of file code_77480.c.
Referenced by DisablePlayerInput(), func_802E114C(), func_802E44F8(), func_802E54CC(), and func_802E8BC0().
enable_player_input()
s32 enable_player_input (void)
Definition at line 157 of file code_77480.c.
Referenced by DisablePlayerInput(), func_8004309C(), func_802D6954(), func_802E117C(), func_802E4540(), func_802E555C(), set_action_state(), and world_goombario_pre_battle().
func_800E01DC()
void func_800E01DC (void)
Definition at line 167 of file code_77480.c.
Referenced by DisablePlayerInput().
func_800E0208()
s32 func_800E0208 (void)
Definition at line 175 of file code_77480.c.
Referenced by func_800E34D8().
func_800E0260()
void func_800E0260 (void)
Definition at line 188 of file code_77480.c.
func_800E0294()
s32 func_800E0294 ()
Definition at line 195 of file code_77480.c.
func_800E0330()
void func_800E0330 (void)
Definition at line 197 of file code_77480.c.
Referenced by func_800E0260().
func_800E0374()
void func_800E0374 (void)
Definition at line 203 of file code_77480.c.
Referenced by func_800DFC74().
func_800E0398()
s32 func_800E0398 ()
Definition at line 208 of file code_77480.c.
func_800E04D0()
void func_800E04D0 (void)
Definition at line 210 of file code_77480.c.
Referenced by func_800E0260().
func_800E0514()
void func_800E0514 (void)
Definition at line 216 of file code_77480.c.
Referenced by func_800DFC74().
func_800E0538()
s32 func_800E0538 (void)
Definition at line 221 of file code_77480.c.
func_800E0580()
s32 func_800E0580 ()
Definition at line 234 of file code_77480.c.
func_800E0658()
void func_800E0658 (void)
Definition at line 236 of file code_77480.c.
Referenced by func_800E0260().
func_800E069C()
void func_800E069C (void)
Definition at line 242 of file code_77480.c.
Referenced by func_800DFC74().
func_800E06C0()
void func_800E06C0 (s32 arg0)
Definition at line 247 of file code_77480.c.
func_800E06D8()
s32 func_800E06D8 ()
Definition at line 251 of file code_77480.c.
func_800E0818()
s32 func_800E0818 ()
Definition at line 253 of file code_77480.c.
func_800E0AD0()
void func_800E0AD0 (void)
Definition at line 255 of file code_77480.c.
Referenced by func_800E0260().
func_800E0B14()
void func_800E0B14 (void)
Definition at line 261 of file code_77480.c.
Referenced by func_800DFC74().
func_800E0B38()
void func_800E0B38 (void)
Definition at line 266 of file code_77480.c.
func_800E0B90()
s32 func_800E0B90 ()
Definition at line 280 of file code_77480.c.
func_800E0FEC()
s32 func_800E0FEC ()
Definition at line 282 of file code_77480.c.
render_player()
void render_player (void)
Definition at line 284 of file code_77480.c.
render_player_model()
void render_player_model ()
Definition at line 290 of file code_77480.c.
Referenced by render_player().
appendGfx_player()
s32 appendGfx_player ()
Definition at line 292 of file code_77480.c.
appendGfx_player_spin()
s32 appendGfx_player_spin ()
Definition at line 294 of file code_77480.c.
update_player_shadow()
s32 update_player_shadow ()
Definition at line 296 of file code_77480.c.
Variable Documentation
D_8010C920
s32 D_8010C920 extern
Referenced by func_800E04D0(), and func_800E0514().
D_8010C93C
s32 D_8010C93C extern
Referenced by func_800E0330(), and func_800E0374().
D_8010C940
s32 D_8010C940 extern
Referenced by func_800E0658(), and func_800E069C().
D_8010C950
s32 D_8010C950 extern
Referenced by func_800E06C0().
D_8010C958
s32 D_8010C958 extern
Referenced by func_800E0AD0(), and func_800E0B14().