src/os/code_42780_len_120.c File Reference - Paper Mario Documentation
code_42780_len_120.c File Reference
Functions
void osViBlack (u8 unk)
void osViRepeatLine (u8 unk)
void guMtxIdent (Mtx *m)
Function Documentation
osViBlack()
void osViBlack (u8 unk)
Definition at line 3 of file code_42780_len_120.c.
Referenced by nuGfxDisplayOff(), and nuScCreateScheduler().
osViRepeatLine()
void osViRepeatLine (u8 unk)
Definition at line 5 of file code_42780_len_120.c.
guMtxIdent()
void guMtxIdent (Mtx * m)
Definition at line 7 of file code_42780_len_120.c.
Referenced by func_802CCDAC(), and LoadModelAnimation().