src/code_105700_len_2130.c File Reference - Paper Mario Documentation
code_105700_len_2130.c File Reference
Data Structures
struct struct802E3F0C
Functions
void func_802E3E80 (Entity *entity)
void func_802E3E9C (Entity *entity)
s32 func_802E3EE0 ()
void func_802E3F0C (Entity *entity)
void func_802E4040 (Entity *entity)
void func_802E405C (Entity *entity)
void func_802E40A0 (Entity *entity)
void func_802E4108 (Entity *entity)
void func_802E4154 (Entity *entity)
void func_802E421C (Entity *entity)
void func_802E4484 (Entity *entity)
s32 func_802E44CC (Entity *entity)
void func_802E44F8 (void)
void func_802E4540 (void)
void func_802E455C (s32 entityIndex)
void func_802E464C (Entity *entity)
void func_802E4694 (Entity *entity)
void func_802E46BC (Entity *entity)
Function Documentation
func_802E3E80()
void func_802E3E80 (Entity * entity)
Definition at line 11 of file code_105700_len_2130.c.
func_802E3E9C()
void func_802E3E9C (Entity * entity)
Definition at line 15 of file code_105700_len_2130.c.
func_802E3EE0()
s32 func_802E3EE0 ()
Definition at line 36 of file code_105700_len_2130.c.
func_802E3F0C()
void func_802E3F0C (Entity * entity)
Definition at line 38 of file code_105700_len_2130.c.
func_802E4040()
void func_802E4040 (Entity * entity)
Definition at line 40 of file code_105700_len_2130.c.
func_802E405C()
void func_802E405C (Entity * entity)
Definition at line 44 of file code_105700_len_2130.c.
func_802E40A0()
void func_802E40A0 (Entity * entity)
Definition at line 48 of file code_105700_len_2130.c.
func_802E4108()
void func_802E4108 (Entity * entity)
Definition at line 61 of file code_105700_len_2130.c.
func_802E4154()
void func_802E4154 (Entity * entity)
Definition at line 72 of file code_105700_len_2130.c.
func_802E421C()
void func_802E421C (Entity * entity)
Definition at line 90 of file code_105700_len_2130.c.
func_802E4484()
void func_802E4484 (Entity * entity)
Definition at line 156 of file code_105700_len_2130.c.
func_802E44CC()
s32 func_802E44CC (Entity * entity)
Definition at line 164 of file code_105700_len_2130.c.
func_802E44F8()
void func_802E44F8 (void)
Definition at line 173 of file code_105700_len_2130.c.
func_802E4540()
void func_802E4540 (void)
Definition at line 183 of file code_105700_len_2130.c.
func_802E455C()
void func_802E455C (s32 entityIndex)
Definition at line 187 of file code_105700_len_2130.c.
Referenced by func_802E464C(), and func_802E46BC().
func_802E464C()
void func_802E464C (Entity * entity)
Definition at line 205 of file code_105700_len_2130.c.
Referenced by func_802E4694().
func_802E4694()
void func_802E4694 (Entity * entity)
Definition at line 215 of file code_105700_len_2130.c.
func_802E46BC()
void func_802E46BC (Entity * entity)
Definition at line 220 of file code_105700_len_2130.c.