src/code_f4c60_len_4300.c File Reference - Paper Mario Documentation
code_f4c60_len_4300.c File Reference
Functions
ApiStatus _show_message (ScriptInstance *script, s32 isInitialCall, s32 arg2)
ApiStatus SpeakToPlayer (ScriptInstance *script, s32 isInitialCall)
ApiStatus EndSpeech (ScriptInstance *script, s32 isInitialCall)
ApiStatus ContinueSpeech (ScriptInstance *script, s32 isInitialCall)
ApiStatus SpeakToNpc (ScriptInstance *script, s32 isInitialCall)
s32 ShowMessageAtScreenPos (ScriptInstance *script, s32 isInitialCall)
s32 ShowMessageAtWorldPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus CloseMessage (ScriptInstance *script, s32 isInitialCall)
ApiStatus SwitchMessage (ScriptInstance *script, s32 isInitialCall)
s32 ShowChoice (ScriptInstance *script, s32 isInitialCall)
ApiStatus CloseChoice (ScriptInstance *script, s32 isInitialCall)
ApiStatus CancelMessage (ScriptInstance *script, s32 isInitialCall)
ApiStatus CancelMessageAndBlock (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetMessageImages (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D0C94 (ScriptInstance *script, s32 initialCall)
ApiStatus SetMessageString (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetMessageValue (ScriptInstance *script, s32 initialCall)
Function Documentation
_show_message()
ApiStatus _show_message (ScriptInstance * script, s32 isInitialCall, s32 arg2)
Definition at line 21 of file code_f4c60_len_4300.c.
Referenced by ContinueSpeech(), EndSpeech(), SpeakToNpc(), and SpeakToPlayer().
SpeakToPlayer()
ApiStatus SpeakToPlayer (ScriptInstance * script, s32 isInitialCall)
Definition at line 5 of file code_f4c60_len_4300.c.
Referenced by N().
EndSpeech()
ApiStatus EndSpeech (ScriptInstance * script, s32 isInitialCall)
Definition at line 9 of file code_f4c60_len_4300.c.
ContinueSpeech()
ApiStatus ContinueSpeech (ScriptInstance * script, s32 isInitialCall)
Definition at line 13 of file code_f4c60_len_4300.c.
SpeakToNpc()
ApiStatus SpeakToNpc (ScriptInstance * script, s32 isInitialCall)
Definition at line 17 of file code_f4c60_len_4300.c.
ShowMessageAtScreenPos()
s32 ShowMessageAtScreenPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 23 of file code_f4c60_len_4300.c.
Referenced by N().
ShowMessageAtWorldPos()
s32 ShowMessageAtWorldPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 25 of file code_f4c60_len_4300.c.
CloseMessage()
ApiStatus CloseMessage (ScriptInstance * script, s32 isInitialCall)
Definition at line 27 of file code_f4c60_len_4300.c.
SwitchMessage()
ApiStatus SwitchMessage (ScriptInstance * script, s32 isInitialCall)
Definition at line 42 of file code_f4c60_len_4300.c.
ShowChoice()
s32 ShowChoice (ScriptInstance * script, s32 isInitialCall)
Definition at line 59 of file code_f4c60_len_4300.c.
CloseChoice()
ApiStatus CloseChoice (ScriptInstance * script, s32 isInitialCall)
Definition at line 61 of file code_f4c60_len_4300.c.
CancelMessage()
ApiStatus CancelMessage (ScriptInstance * script, s32 isInitialCall)
Definition at line 66 of file code_f4c60_len_4300.c.
CancelMessageAndBlock()
ApiStatus CancelMessageAndBlock (ScriptInstance * script, s32 isInitialCall)
Definition at line 71 of file code_f4c60_len_4300.c.
Referenced by world_goombario_pre_battle().
SetMessageImages()
ApiStatus SetMessageImages (ScriptInstance * script, s32 isInitialCall)
Definition at line 76 of file code_f4c60_len_4300.c.
func_802D0C94()
ApiStatus func_802D0C94 (ScriptInstance * script, s32 initialCall)
Definition at line 81 of file code_f4c60_len_4300.c.
SetMessageString()
ApiStatus SetMessageString (ScriptInstance * script, s32 isInitialCall)
Definition at line 90 of file code_f4c60_len_4300.c.
SetMessageValue()
ApiStatus SetMessageValue (ScriptInstance * script, s32 initialCall)
Definition at line 99 of file code_f4c60_len_4300.c.