src/code_2d9a0_len_890.c File Reference - Paper Mario Documentation
code_2d9a0_len_890.c File Reference
Functions
void func_800525A0 (UnkAl19E0 *arg0)
void func_80052614 (UnkAl19E0 *arg0)
void func_80052660 (UnkAl19E0 *arg0)
void func_80052B44 (UnkAl48 *arg0)
s32 func_80052BC0 (s32 arg0)
void func_80052BF8 (UnkAl48 *arg0, s32 *arg1)
s32 func_80052CFC (UnkAl48 *arg0)
s32 func_80052E18 ()
Function Documentation
func_800525A0()
void func_800525A0 (UnkAl19E0 * arg0)
Definition at line 4 of file code_2d9a0_len_890.c.
func_80052614()
void func_80052614 (UnkAl19E0 * arg0)
Definition at line 19 of file code_2d9a0_len_890.c.
Referenced by func_80052E5C().
func_80052660()
void func_80052660 (UnkAl19E0 * arg0)
Definition at line 37 of file code_2d9a0_len_890.c.
Referenced by func_800533D0().
func_80052B44()
void func_80052B44 (UnkAl48 * arg0)
Definition at line 39 of file code_2d9a0_len_890.c.
func_80052BC0()
s32 func_80052BC0 (s32 arg0)
Definition at line 48 of file code_2d9a0_len_890.c.
Referenced by func_80052B44().
func_80052BF8()
void func_80052BF8 (UnkAl48 * arg0, s32 * arg1)
Definition at line 52 of file code_2d9a0_len_890.c.
Referenced by func_80053654().
func_80052CFC()
s32 func_80052CFC (UnkAl48 * arg0)
Definition at line 54 of file code_2d9a0_len_890.c.
func_80052E18()
s32 func_80052E18 ()
Definition at line 56 of file code_2d9a0_len_890.c.