src/code_f2470_len_27f0.c File Reference - Paper Mario Documentation
code_f2470_len_27f0.c File Reference
Functions
Npc * resolve_npc (ScriptInstance *script, NpcId npcIdOrPtr)
void set_npc_animation (Npc *npc, u32 arg1)
ApiStatus CreateNpc (ScriptInstance *script, s32 isInitialCall)
ApiStatus DeleteNpc (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetNpcPointer (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcRotation (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CDE68 (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcScale (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcCollisionSize (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcSpeed (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcJumpscale (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetNpcAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcAnimationSpeed (ScriptInstance *script, s32 isInitialCall)
s32 NpcMoveTo (ScriptInstance *script, s32 isInitialCall)
s32 _npc_jump_to ()
ApiStatus NpcJump0 (ScriptInstance *script, s32 isInitialCall)
ApiStatus NpcJump1 (ScriptInstance *script, s32 isInitialCall)
s32 NpcFlyTo (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetNpcYaw (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcYaw (ScriptInstance *script, s32 isInitialCall)
s32 InterpNpcYaw (ScriptInstance *script, s32 isInitialCall)
s32 NpcFacePlayer (ScriptInstance *script, s32 isInitialCall)
s32 NpcFaceNpc (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcFlagBits (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetNpcPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CF1B4 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CF208 (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableNpcShadow (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableNpcBlur (ScriptInstance *script, s32 isInitialCall)
ApiStatus ClearPartnerMoveHistory (ScriptInstance *script, s32 isInitialCall)
ApiStatus NpcSetHomePosToCurrent (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPartnerPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus DisablePartnerAI (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnablePartnerAI (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CF54C (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CF56C (ScriptInstance *script, s32 isInitialCall)
ApiStatus BringPartnerOut (ScriptInstance *script, s32 isInitialCall)
ApiStatus PutPartnerAway (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCurrentPartnerID (ScriptInstance *script, s32 isInitialCall)
ApiStatus PartnerCanUseAbility (ScriptInstance *script, s32 isInitialCall)
ApiStatus PartnerIsFlying (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CFD30 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CFE2C (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CFE80 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CFEEC (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CFFC0 (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcEffect (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlaySoundAtNpc (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D0244 (ScriptInstance *script, s32 isInitialCall)
Function Documentation
resolve_npc()
Npc* resolve_npc (ScriptInstance * script, NpcId npcIdOrPtr)
Definition at line 4 of file code_f2470_len_27f0.c.
Referenced by ClearPartnerMoveHistory(), EnableNpcBlur(), EnableNpcShadow(), func_80045838(), func_802CDE68(), func_802CF1B4(), func_802CF208(), func_802CFD30(), func_802CFE2C(), func_802CFE80(), func_802CFEEC(), func_802CFFC0(), func_802D0244(), GetAngleBetweenNPCs(), GetAngleToNPC(), GetAngleToPlayer(), GetNpcAnimation(), GetNpcPos(), GetNpcYaw(), NpcSetHomePosToCurrent(), PlaySoundAtNpc(), SetNpcAnimation(), SetNpcAnimationSpeed(), SetNpcCollisionSize(), SetNpcEffect(), SetNpcFlagBits(), SetNpcJumpscale(), SetNpcPos(), SetNpcRotation(), SetNpcScale(), SetNpcSpeed(), and SetNpcYaw().
set_npc_animation()
void set_npc_animation (Npc * npc, u32 arg1)
Definition at line 14 of file code_f2470_len_27f0.c.
Referenced by SetNpcAnimation().
CreateNpc()
ApiStatus CreateNpc (ScriptInstance * script, s32 isInitialCall)
Definition at line 26 of file code_f2470_len_27f0.c.
DeleteNpc()
ApiStatus DeleteNpc (ScriptInstance * script, s32 isInitialCall)
Definition at line 28 of file code_f2470_len_27f0.c.
GetNpcPointer()
ApiStatus GetNpcPointer (ScriptInstance * script, s32 isInitialCall)
Definition at line 40 of file code_f2470_len_27f0.c.
SetNpcPos()
ApiStatus SetNpcPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 49 of file code_f2470_len_27f0.c.
Referenced by N().
SetNpcRotation()
ApiStatus SetNpcRotation (ScriptInstance * script, s32 isInitialCall)
Definition at line 72 of file code_f2470_len_27f0.c.
Referenced by N().
func_802CDE68()
ApiStatus func_802CDE68 (ScriptInstance * script, s32 isInitialCall)
Definition at line 90 of file code_f2470_len_27f0.c.
SetNpcScale()
ApiStatus SetNpcScale (ScriptInstance * script, s32 isInitialCall)
Definition at line 105 of file code_f2470_len_27f0.c.
SetNpcCollisionSize()
ApiStatus SetNpcCollisionSize (ScriptInstance * script, s32 isInitialCall)
Definition at line 123 of file code_f2470_len_27f0.c.
SetNpcSpeed()
ApiStatus SetNpcSpeed (ScriptInstance * script, s32 isInitialCall)
Definition at line 139 of file code_f2470_len_27f0.c.
Referenced by N().
SetNpcJumpscale()
ApiStatus SetNpcJumpscale (ScriptInstance * script, s32 isInitialCall)
Definition at line 153 of file code_f2470_len_27f0.c.
Referenced by N().
SetNpcAnimation()
ApiStatus SetNpcAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 167 of file code_f2470_len_27f0.c.
Referenced by N().
GetNpcAnimation()
ApiStatus GetNpcAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 181 of file code_f2470_len_27f0.c.
SetNpcAnimationSpeed()
ApiStatus SetNpcAnimationSpeed (ScriptInstance * script, s32 isInitialCall)
Definition at line 195 of file code_f2470_len_27f0.c.
NpcMoveTo()
s32 NpcMoveTo (ScriptInstance * script, s32 isInitialCall)
Definition at line 209 of file code_f2470_len_27f0.c.
Referenced by N().
_npc_jump_to()
s32 _npc_jump_to ()
Definition at line 211 of file code_f2470_len_27f0.c.
Referenced by NpcJump0(), and NpcJump1().
NpcJump0()
ApiStatus NpcJump0 (ScriptInstance * script, s32 isInitialCall)
Definition at line 213 of file code_f2470_len_27f0.c.
Referenced by N().
NpcJump1()
ApiStatus NpcJump1 (ScriptInstance * script, s32 isInitialCall)
Definition at line 217 of file code_f2470_len_27f0.c.
NpcFlyTo()
s32 NpcFlyTo (ScriptInstance * script, s32 isInitialCall)
Definition at line 221 of file code_f2470_len_27f0.c.
GetNpcYaw()
ApiStatus GetNpcYaw (ScriptInstance * script, s32 isInitialCall)
Definition at line 223 of file code_f2470_len_27f0.c.
SetNpcYaw()
ApiStatus SetNpcYaw (ScriptInstance * script, s32 isInitialCall)
Definition at line 237 of file code_f2470_len_27f0.c.
InterpNpcYaw()
s32 InterpNpcYaw (ScriptInstance * script, s32 isInitialCall)
Definition at line 250 of file code_f2470_len_27f0.c.
Referenced by N().
NpcFacePlayer()
s32 NpcFacePlayer (ScriptInstance * script, s32 isInitialCall)
Definition at line 252 of file code_f2470_len_27f0.c.
Referenced by N().
NpcFaceNpc()
s32 NpcFaceNpc (ScriptInstance * script, s32 isInitialCall)
Definition at line 254 of file code_f2470_len_27f0.c.
SetNpcFlagBits()
ApiStatus SetNpcFlagBits (ScriptInstance * script, s32 isInitialCall)
Definition at line 256 of file code_f2470_len_27f0.c.
Referenced by N().
GetNpcPos()
ApiStatus GetNpcPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 276 of file code_f2470_len_27f0.c.
Referenced by N().
func_802CF1B4()
ApiStatus func_802CF1B4 (ScriptInstance * script, s32 isInitialCall)
Definition at line 294 of file code_f2470_len_27f0.c.
func_802CF208()
ApiStatus func_802CF208 (ScriptInstance * script, s32 isInitialCall)
Definition at line 308 of file code_f2470_len_27f0.c.
EnableNpcShadow()
ApiStatus EnableNpcShadow (ScriptInstance * script, s32 isInitialCall)
Definition at line 322 of file code_f2470_len_27f0.c.
Referenced by N().
EnableNpcBlur()
ApiStatus EnableNpcBlur (ScriptInstance * script, s32 isInitialCall)
Definition at line 340 of file code_f2470_len_27f0.c.
ClearPartnerMoveHistory()
ApiStatus ClearPartnerMoveHistory (ScriptInstance * script, s32 isInitialCall)
Definition at line 358 of file code_f2470_len_27f0.c.
NpcSetHomePosToCurrent()
ApiStatus NpcSetHomePosToCurrent (ScriptInstance * script, s32 isInitialCall)
Definition at line 371 of file code_f2470_len_27f0.c.
GetPartnerPos()
ApiStatus GetPartnerPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 384 of file code_f2470_len_27f0.c.
DisablePartnerAI()
ApiStatus DisablePartnerAI (ScriptInstance * script, s32 isInitialCall)
Definition at line 401 of file code_f2470_len_27f0.c.
EnablePartnerAI()
ApiStatus EnablePartnerAI (ScriptInstance * script, s32 isInitialCall)
Definition at line 412 of file code_f2470_len_27f0.c.
Referenced by N().
func_802CF54C()
ApiStatus func_802CF54C (ScriptInstance * script, s32 isInitialCall)
Definition at line 417 of file code_f2470_len_27f0.c.
func_802CF56C()
ApiStatus func_802CF56C (ScriptInstance * script, s32 isInitialCall)
Definition at line 422 of file code_f2470_len_27f0.c.
BringPartnerOut()
ApiStatus BringPartnerOut (ScriptInstance * script, s32 isInitialCall)
Definition at line 434 of file code_f2470_len_27f0.c.
PutPartnerAway()
ApiStatus PutPartnerAway (ScriptInstance * script, s32 isInitialCall)
Definition at line 436 of file code_f2470_len_27f0.c.
GetCurrentPartnerID()
ApiStatus GetCurrentPartnerID (ScriptInstance * script, s32 isInitialCall)
Definition at line 438 of file code_f2470_len_27f0.c.
PartnerCanUseAbility()
ApiStatus PartnerCanUseAbility (ScriptInstance * script, s32 isInitialCall)
Definition at line 443 of file code_f2470_len_27f0.c.
PartnerIsFlying()
ApiStatus PartnerIsFlying (ScriptInstance * script, s32 isInitialCall)
Definition at line 450 of file code_f2470_len_27f0.c.
func_802CFD30()
ApiStatus func_802CFD30 (ScriptInstance * script, s32 isInitialCall)
Definition at line 457 of file code_f2470_len_27f0.c.
Referenced by N().
func_802CFE2C()
ApiStatus func_802CFE2C (ScriptInstance * script, s32 isInitialCall)
Definition at line 475 of file code_f2470_len_27f0.c.
Referenced by N().
func_802CFE80()
ApiStatus func_802CFE80 (ScriptInstance * script, s32 isInitialCall)
Definition at line 489 of file code_f2470_len_27f0.c.
func_802CFEEC()
ApiStatus func_802CFEEC (ScriptInstance * script, s32 isInitialCall)
Definition at line 503 of file code_f2470_len_27f0.c.
func_802CFFC0()
ApiStatus func_802CFFC0 (ScriptInstance * script, s32 isInitialCall)
Definition at line 520 of file code_f2470_len_27f0.c.
SetNpcEffect()
ApiStatus SetNpcEffect (ScriptInstance * script, s32 isInitialCall)
Definition at line 542 of file code_f2470_len_27f0.c.
PlaySoundAtNpc()
ApiStatus PlaySoundAtNpc (ScriptInstance * script, s32 isInitialCall)
Definition at line 557 of file code_f2470_len_27f0.c.
Referenced by N().
func_802D0244()
ApiStatus func_802D0244 (ScriptInstance * script, s32 isInitialCall)
Definition at line 572 of file code_f2470_len_27f0.c.