src/code_20ec0_len_5040.c File Reference - Paper Mario Documentation
code_20ec0_len_5040.c File Reference
Macros
#define NAMESPACE base
Functions
s32 func_80045AC0 ()
s32 func_80045B10 ()
s32 func_80045B68 ()
s32 func_80045BC8 ()
s32 func_80045C28 ()
s32 func_80045C88 ()
s32 func_80045CC4 ()
s32 func_80045D00 ()
s32 func_80045D7C ()
s32 func_80045E4C ()
s32 func_80045ED0 ()
s32 func_80045FA4 ()
s32 func_80045FB4 ()
s32 func_80046030 ()
s32 func_800465E0 ()
s32 func_80047608 ()
s32 func_800476F4 ()
s32 func_8004778C ()
s32 func_800477F4 ()
s32 func_80047820 ()
s32 func_80047898 ()
s32 func_800478F8 ()
s32 func_80047928 ()
s32 func_800479A0 ()
s32 func_80047A00 ()
s32 func_80047A30 ()
s32 func_80047AA8 ()
s32 func_80047B08 ()
s32 func_80047B38 ()
s32 func_80047B84 ()
s32 func_80047BE4 ()
s32 func_80047C14 ()
s32 func_80047CA4 ()
s32 func_80047D00 ()
s32 func_80047D30 ()
s32 func_80047DC0 ()
s32 func_80047E1C ()
s32 func_80047E4C ()
s32 func_80047EDC ()
s32 func_80047F28 ()
s32 func_80047F58 ()
s32 func_80047FE8 ()
s32 func_80048034 ()
s32 func_80048064 ()
s32 func_800480F4 ()
s32 func_80048140 ()
s32 func_80048170 ()
s32 func_80048200 ()
s32 func_8004824C ()
s32 spawn_drops ()
s32 get_coin_drop_amount (Enemy *enemy)
s32 func_80048E34 ()
s32 func_80048F0C ()
s32 is_point_within_region (s32 shape, f32 pointX, f32 pointY, f32 centerX, f32 centerY, f32 sizeX, f32 sizeZ)
s32 func_800490B4 (s32 arg0, Enemy *arg1, f32 arg2, s32 arg3, s32 arg4)
s32 func_800493EC ()
s32 func_800494C0 (Npc *npc, s32 arg1, s32 arg2)
s32 func_80049550 ()
s32 func_800495A0 ()
s32 func_800496B8 ()
s32 func_80049C04 ()
s32 func_80049E3C ()
s32 func_80049ECC ()
s32 func_80049F7C ()
s32 func_8004A124 ()
s32 func_8004A3E8 ()
s32 DoBasicAI (ScriptInstance *script, s32 isInitialCall)
s32 func_8004A6F0 ()
s32 func_8004A73C ()
s32 func_8004A784 ()
Macro Definition Documentation
NAMESPACE
#define NAMESPACE base
Definition at line 199 of file code_20ec0_len_5040.c.
Function Documentation
func_80045AC0()
s32 func_80045AC0 ()
Definition at line 4 of file code_20ec0_len_5040.c.
func_80045B10()
s32 func_80045B10 ()
Definition at line 6 of file code_20ec0_len_5040.c.
func_80045B68()
s32 func_80045B68 ()
Definition at line 8 of file code_20ec0_len_5040.c.
func_80045BC8()
s32 func_80045BC8 ()
Definition at line 10 of file code_20ec0_len_5040.c.
func_80045C28()
s32 func_80045C28 ()
Definition at line 12 of file code_20ec0_len_5040.c.
func_80045C88()
s32 func_80045C88 ()
Definition at line 14 of file code_20ec0_len_5040.c.
func_80045CC4()
s32 func_80045CC4 ()
Definition at line 16 of file code_20ec0_len_5040.c.
func_80045D00()
s32 func_80045D00 ()
Definition at line 18 of file code_20ec0_len_5040.c.
Referenced by func_8003EE98(), and func_8003EECC().
func_80045D7C()
s32 func_80045D7C ()
Definition at line 20 of file code_20ec0_len_5040.c.
func_80045E4C()
s32 func_80045E4C ()
Definition at line 22 of file code_20ec0_len_5040.c.
func_80045ED0()
s32 func_80045ED0 ()
Definition at line 24 of file code_20ec0_len_5040.c.
func_80045FA4()
s32 func_80045FA4 ()
Definition at line 26 of file code_20ec0_len_5040.c.
Referenced by func_8003EE98(), and func_8003EECC().
func_80045FB4()
s32 func_80045FB4 ()
Definition at line 28 of file code_20ec0_len_5040.c.
func_80046030()
s32 func_80046030 ()
Definition at line 30 of file code_20ec0_len_5040.c.
func_800465E0()
s32 func_800465E0 ()
Definition at line 32 of file code_20ec0_len_5040.c.
func_80047608()
s32 func_80047608 ()
Definition at line 34 of file code_20ec0_len_5040.c.
func_800476F4()
s32 func_800476F4 ()
Definition at line 36 of file code_20ec0_len_5040.c.
Referenced by delete_player_actor().
func_8004778C()
s32 func_8004778C ()
Definition at line 38 of file code_20ec0_len_5040.c.
func_800477F4()
s32 func_800477F4 ()
Definition at line 40 of file code_20ec0_len_5040.c.
func_80047820()
s32 func_80047820 ()
Definition at line 42 of file code_20ec0_len_5040.c.
func_80047898()
s32 func_80047898 ()
Definition at line 44 of file code_20ec0_len_5040.c.
Referenced by ClearStatusEffects().
func_800478F8()
s32 func_800478F8 ()
Definition at line 46 of file code_20ec0_len_5040.c.
func_80047928()
s32 func_80047928 ()
Definition at line 48 of file code_20ec0_len_5040.c.
func_800479A0()
s32 func_800479A0 ()
Definition at line 50 of file code_20ec0_len_5040.c.
Referenced by ClearStatusEffects(), and remove_player_buffs().
func_80047A00()
s32 func_80047A00 ()
Definition at line 52 of file code_20ec0_len_5040.c.
func_80047A30()
s32 func_80047A30 ()
Definition at line 54 of file code_20ec0_len_5040.c.
func_80047AA8()
s32 func_80047AA8 ()
Definition at line 56 of file code_20ec0_len_5040.c.
Referenced by ClearStatusEffects(), and remove_player_buffs().
func_80047B08()
s32 func_80047B08 ()
Definition at line 58 of file code_20ec0_len_5040.c.
func_80047B38()
s32 func_80047B38 ()
Definition at line 60 of file code_20ec0_len_5040.c.
func_80047B84()
s32 func_80047B84 ()
Definition at line 62 of file code_20ec0_len_5040.c.
func_80047BE4()
s32 func_80047BE4 ()
Definition at line 64 of file code_20ec0_len_5040.c.
func_80047C14()
s32 func_80047C14 ()
Definition at line 66 of file code_20ec0_len_5040.c.
func_80047CA4()
s32 func_80047CA4 ()
Definition at line 68 of file code_20ec0_len_5040.c.
func_80047D00()
s32 func_80047D00 ()
Definition at line 70 of file code_20ec0_len_5040.c.
func_80047D30()
s32 func_80047D30 ()
Definition at line 72 of file code_20ec0_len_5040.c.
func_80047DC0()
s32 func_80047DC0 ()
Definition at line 74 of file code_20ec0_len_5040.c.
func_80047E1C()
s32 func_80047E1C ()
Definition at line 76 of file code_20ec0_len_5040.c.
func_80047E4C()
s32 func_80047E4C ()
Definition at line 78 of file code_20ec0_len_5040.c.
func_80047EDC()
s32 func_80047EDC ()
Definition at line 80 of file code_20ec0_len_5040.c.
func_80047F28()
s32 func_80047F28 ()
Definition at line 82 of file code_20ec0_len_5040.c.
func_80047F58()
s32 func_80047F58 ()
Definition at line 84 of file code_20ec0_len_5040.c.
func_80047FE8()
s32 func_80047FE8 ()
Definition at line 86 of file code_20ec0_len_5040.c.
func_80048034()
s32 func_80048034 ()
Definition at line 88 of file code_20ec0_len_5040.c.
func_80048064()
s32 func_80048064 ()
Definition at line 90 of file code_20ec0_len_5040.c.
func_800480F4()
s32 func_800480F4 ()
Definition at line 92 of file code_20ec0_len_5040.c.
func_80048140()
s32 func_80048140 ()
Definition at line 94 of file code_20ec0_len_5040.c.
func_80048170()
s32 func_80048170 ()
Definition at line 96 of file code_20ec0_len_5040.c.
func_80048200()
s32 func_80048200 ()
Definition at line 98 of file code_20ec0_len_5040.c.
func_8004824C()
s32 func_8004824C ()
Definition at line 100 of file code_20ec0_len_5040.c.
spawn_drops()
s32 spawn_drops ()
Definition at line 102 of file code_20ec0_len_5040.c.
Referenced by OnDefeatEnemy().
get_coin_drop_amount()
s32 get_coin_drop_amount (Enemy * enemy)
Definition at line 106 of file code_20ec0_len_5040.c.
func_80048E34()
s32 func_80048E34 ()
Definition at line 166 of file code_20ec0_len_5040.c.
func_80048F0C()
s32 func_80048F0C ()
Definition at line 168 of file code_20ec0_len_5040.c.
is_point_within_region()
s32 is_point_within_region (s32 shape, f32 pointX, f32 pointY, f32 centerX, f32 centerY, f32 sizeX, f32 sizeZ)
Definition at line 170 of file code_20ec0_len_5040.c.
func_800490B4()
s32 func_800490B4 (s32 arg0, Enemy * arg1, f32 arg2, s32 arg3, s32 arg4)
Definition at line 187 of file code_20ec0_len_5040.c.
Referenced by UnkNpcAIFunc11().
func_800493EC()
s32 func_800493EC ()
Definition at line 189 of file code_20ec0_len_5040.c.
func_800494C0()
s32 func_800494C0 (Npc * npc, s32 arg1, s32 arg2)
Definition at line 191 of file code_20ec0_len_5040.c.
Referenced by func_80045838().
func_80049550()
s32 func_80049550 ()
Definition at line 193 of file code_20ec0_len_5040.c.
func_800495A0()
s32 func_800495A0 ()
Definition at line 195 of file code_20ec0_len_5040.c.
func_800496B8()
s32 func_800496B8 ()
Definition at line 197 of file code_20ec0_len_5040.c.
func_80049C04()
s32 func_80049C04 ()
Definition at line 202 of file code_20ec0_len_5040.c.
func_80049E3C()
s32 func_80049E3C ()
Definition at line 204 of file code_20ec0_len_5040.c.
func_80049ECC()
s32 func_80049ECC ()
Definition at line 206 of file code_20ec0_len_5040.c.
func_80049F7C()
s32 func_80049F7C ()
Definition at line 208 of file code_20ec0_len_5040.c.
func_8004A124()
s32 func_8004A124 ()
Definition at line 210 of file code_20ec0_len_5040.c.
func_8004A3E8()
s32 func_8004A3E8 ()
Definition at line 212 of file code_20ec0_len_5040.c.
DoBasicAI()
s32 DoBasicAI (ScriptInstance * script, s32 isInitialCall)
Definition at line 214 of file code_20ec0_len_5040.c.
Referenced by N().
func_8004A6F0()
s32 func_8004A6F0 ()
Definition at line 216 of file code_20ec0_len_5040.c.
func_8004A73C()
s32 func_8004A73C ()
Definition at line 218 of file code_20ec0_len_5040.c.
func_8004A784()
s32 func_8004A784 ()
Definition at line 220 of file code_20ec0_len_5040.c.