include/functions.h File Reference - Paper Mario Documentation
functions.h File Reference
Functions
void nuBoot (void)
void boot_idle (void)
void boot_main (void)
void osCleanupThread (void)
void func_80070A90 (s32, f32, f32, f32)
void func_80070AF0 (s32, f32, f32, f32)
s32 heap_malloc (s32 size)
HeapNode * _heap_create (s32 *addr, u32 size)
s32 dma_copy (s32 romStart, s32 romEnd, void *vramDest)
s32 get_global_byte (s32 index)
s32 get_global_flag (s32 index)
s32 get_area_byte (s32 index)
s32 get_area_flag (s32 index)
Shadow * get_shadow_by_index (s32 index)
void render_player_model ()
f32 integrate_gravity (void)
f32 get_clamped_angle_diff (f32, f32)
u32 get_entity_type (s32 arg0)
Entity * get_entity_by_index (s32 index)
s32 create_entity (StaticEntityData *, s32, s32, s32, s32, s32)
void func_80070550 (s32, f32, f32, f32, f32, f32, s32, s32)
void func_802E263C (Entity *entity)
void create_shadow_callback (Shadow *entity)
void func_802E10F4 (Entity *entity)
void func_802E114C (void)
void func_802E117C (void)
void save_game_at_player_position (void)
void func_802E1204 (Entity *entity)
void func_802E1270 (Entity *entity)
void func_802E1298 (void)
void func_802E12F8 (void)
void func_802E1328 (Entity *entity)
void func_802E1350 (Entity *entity)
void func_802E13B8 (Entity *entity)
void func_802E1400 (Entity *entity)
void func_802E1460 (Entity *entity)
void func_802E14D8 (Entity *entity)
void func_802E1614 (Entity *entity)
void func_802E1660 (Entity *entity)
void func_802E1740 (Entity *entity)
void func_802E176C (Entity *entity)
s32 func_802E17A8 (Entity *entity)
void func_802E1EA8 (Entity *entity)
void func_802E1EDC (Entity *entity)
void func_802E234C (Entity *entity)
f32 func_802E31EC (Entity *entity)
void func_802E328C (Entity *entity)
s32 func_802E3BA4 (Entity *entity)
void entity_init_BlueSwitch (Entity *entity)
void entity_init_HugeBlueSwitch (Entity *entity)
s32 func_80072230 (s32, f32, f32, f32, f32, s32)
PrintContext * load_string (s32 stringID, s32 *a1)
void get_screen_coords (Cam camID, f32 x, f32 y, f32 z, f32 *outX, f32 *outY, f32 *outZ)
void parent_collider_to_model (s32 colliderID, s16 modelIndex)
void clone_model (u16 srcModelID, u16 newModelID)
Model * get_model_from_list_index (s32 listIndex)
s32 get_model_list_index_from_tree_index (s32 treeIndex)
void get_model_center_and_size (s32 modelID, f32 *centerX, f32 *centerY, f32 *centerZ, f32 *sizeX, f32 *sizeY, f32 *sizeZ)
void func_80027088 (s32)
void func_8006F8F0 (f32, f32, f32)
void func_8006FEF0 (s32, f32, f32, f32, f32)
void func_80070190 (s32, f32, f32, f32, s32, f32, s32, s32)
void func_80071090 (s32, f32, f32, f32, s32)
void func_80071750 (s32, f32, f32, f32, f32, s32)
void func_800720B0 (s32, f32, f32, f32, f32, s32)
void func_80072950 (s32, f32, f32, f32, f32, s32 time)
void update_collider_transform (s16 colliderID)
void get_collider_center (s32 colliderID, f32 *x, f32 *y, f32 *z)
s32 is_trigger_bound (Trigger *, Bytecode *script)
Trigger * create_trigger (TriggerDefinition *def)
s32 _bound_script_trigger_handler (Trigger *trigger)
Trigger * get_trigger_by_id (s32 triggerID)
Actor * get_actor (ActorID actorID)
ActorPart * get_actor_part (Actor *actor, s32 partIndex)
s32 func_800494C0 (Npc *npc, s32 arg1, s32 arg2)
s32 get_variable (ScriptInstance *script, Bytecode var)
s32 set_variable (ScriptInstance *script, Bytecode var, s32 value)
f32 get_float_variable (ScriptInstance *script, Bytecode var)
f32 set_float_variable (ScriptInstance *script, Bytecode var, f32 value)
void set_script_timescale (ScriptInstance *script, f32 timescale)
f32 sin_deg (f32 x)
f32 cos_deg (f32 x)
f32 sin_rad (f32 x)
f32 cos_rad (f32 x)
s32 round (f32)
f32 atan2 (f32 startX, f32 startZ, f32 endX, f32 endZ)
f32 clamp_angle (f32 theta)
s32 sign (s32 value)
s32 func_80055448 (s32)
s32 func_80055464 (s32, s32)
void func_800561A4 (s32)
s32 osGetId ()
void set_curtain_scale_goal (f32 scale)
void set_curtain_fade (f32 scale)
void fx_walk_normal (s32 arg0, f32 arg1, f32 arg2, f32 arg3, s32 arg4, s32 arg5)
void fx_emote (s32, Npc *, f32, f32, f32, f32, f32, s32, s32 *)
f32 func_800E0088 (f32, f32)
void func_800E06C0 (s32)
void func_800E97B8 (void)
s32 func_800EB168 (s32)
Shadow * create_shadow_type (s32 type, f32 x, f32 y, f32 z)
PlayerData * get_player_data (void)
s32 pause_interp_vertical_scroll (s32 deltaBefore)
void pause_draw_rect (s32 ulx, s32 uly, s32 lrx, s32 lry, s32 tileDescriptor, s32 uls, s32 ult, s32 dsdx, s32 dtdy)
s32 func_800DCB7C (s32, f32 *, f32 *, f32 *, f32 *)
s32 func_800DDC44 (s32, f32 *, f32 *, f32 *, f32, f32, f32, f32)
Npc * get_npc_by_index (s32 listIndex)
void func_800EBA3C (Npc *partner)
void func_800EBB40 (Npc *partner)
void enable_partner_ai (void)
void enable_partner_walking (Npc *partner, s32 val)
void enable_partner_flying (Npc *partner, s32 val)
void update_player_move_history (Npc *partner)
s32 is_current_partner_flying (void)
void func_800ED5D0 (Npc *partner)
void clear_partner_move_history (Npc *partner)
s32 func_800EF394 (f32)
s32 does_script_exist (s32 id)
s32 does_script_exist_by_ref (ScriptInstance *script)
ScriptInstance * start_script (Bytecode *initialLine, s32 priority, s32 initialState)
ScriptInstance * start_script_in_group (Bytecode *initialLine, u8 priority, u8 initialState, u8 groupFlags)
void set_animation_rate (ActorID actorID, s32 partIndex, f32 rate)
void func_8011B7C0 (u16, s32, s32)
AnimatedMesh * get_anim_mesh (s32 arg0)
void func_80137D88 (s32, f32)
void func_80137DA4 (s32, f32)
void func_80137DC0 (s32, f32 *, f32 *)
s32 func_80137E10 (s32, u8, u8, u8)
void func_80137E4C (s32, s32, s32, s32)
s32 rand_int (s32)
void sort_items (void)
s32 is_ability_active (s32 arg0)
f32 update_lerp (Easing easing, f32 start, f32 end, s32 elapsed, s32 duration)
s32 make_item_entity (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 facingAngleSign, s32 pickupVar)
s32 make_item_entity_delayed (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 pickupVar)
void set_item_entity_position (s32 itemEntityIndex, f32 x, f32 y, f32 z)
ItemEntity * get_item_entity (s32 itemEntityIndex)
s32 make_item_entity_nodelay (s32 itemID, f32 x, f32 y, f32 z, ItemSpawnMode itemSpawnMode, s32 pickupVar)
void set_item_entity_flags (s32 itemEntityIndex, s32 flag)
void set_cam_viewport (s16 id, s16 x, s16 y, s16 width, s16 height)
void disable_player_shadow (void)
void move_player (s32 duration, f32 heading, f32 speed)
Npc * get_npc_safe (NpcId npcId)
Npc * get_npc_unsafe (NpcId npcId)
Npc * resolve_npc (ScriptInstance *script, NpcId npcIdOrPtr)
void set_npc_yaw (Npc *npcPtr, f32 angle)
void npc_move_heading (Npc *npc, f32 speed, f32 yaw)
void disable_npc_blur (Npc *npc)
f32 dist2D (f32 ax, f32 ay, f32 bx, f32 by)
f32 dist3D (f32 ax, f32 ay, f32 az, f32 bx, f32 by, f32 bz)
void add_vec2D_polar (f32 *x, f32 *y, f32 r, f32 theta)
s32 func_801499EC (s32 soundID, s32 arg1, f32 arg2, f32 arg3, f32 arg4)
s32 play_sound_at_position (s32 soundID, s32 value2, f32 posX, f32 posY, f32 posZ)
s32 set_music_track (s32 playerIndex, s32 songID, s32 variation, s32 fadeOutTime, s16 volume)
s32 func_8014AA54 (s32 playerIndex, s32 arg1, s16 arg2)
void player_create_target_list (Actor *actor)
void enemy_create_target_list (Actor *actor)
void set_actor_yaw (ActorID actorID, s32 yaw)
void set_part_yaw (ActorID actorID, s32 partIndex, s32 value)
void add_part_decoration (ActorPart *part, s32 decorationIndex, DecorationId decorationType)
void add_actor_decoration (Actor *actor, s32 decorationIndex, DecorationId decorationType)
void remove_part_decoration (ActorPart *part, s32 decorationIndex)
void remove_actor_decoration (Actor *actor, s32 decorationIndex)
s32 heroes_is_ability_active (Actor *actor, Ability ability)
void create_part_shadow (ActorID actorID, s32 partIndex)
void remove_part_shadow (ActorID actorID, s32 partIndex)
void create_part_shadow_by_ref (s32 arg0, ActorPart *part)
ScriptInstance * get_script_by_index (s32 index)
void suspend_all_group (s32 groupFlags)
void kill_script (ScriptInstance *instanceToKill)
void exec_entity_updatecmd (Entity *entity)
void func_802D7460 (f32 x, f32 y, f32 z, s32 arg3)
void func_802D74C0 (f32 x, f32 y, f32 z, s32 arg3)
Function Documentation
nuBoot()
void nuBoot (void)
Definition at line 11 of file code_39cb0_len_100.c.
boot_idle()
void boot_idle (void)
Definition at line 18 of file code_39cb0_len_100.c.
Referenced by nuBoot().
boot_main()
void boot_main (void)
Definition at line 9 of file code_1370_len_7d0.c.
Referenced by boot_idle().
osCleanupThread()
void osCleanupThread (void)
func_80070A90()
void func_80070A90 (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
Definition at line 104 of file code_4ac90_len_3910.c.
Referenced by func_8027143C().
func_80070AF0()
void func_80070AF0 (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
Definition at line 106 of file code_4ac90_len_3910.c.
Referenced by func_80271210(), and func_80271258().
heap_malloc()
s32 heap_malloc (s32 size)
Definition at line 35 of file code_6000.c.
Referenced by LoadPath(), setup_path_data(), si_handle_allocate_array(), and start_script_in_group().
_heap_create()
HeapNode* _heap_create (s32 * addr, u32 size)
Definition at line 111 of file code_42e0_len_1f60.c.
Referenced by battle_heap_create(), collision_heap_create(), and general_heap_create().
dma_copy()
s32 dma_copy (s32 romStart, s32 romEnd, void * vramDest)
Definition at line 162 of file code_42e0_len_1f60.c.
Referenced by func_80240000_BFD880(), func_802B2000(), func_802B203C(), func_802B2078(), func_802B20B4(), load_engine_data(), load_world_script_api(), LoadMoveScript(), and play_effect().
get_global_byte()
s32 get_global_byte (s32 index)
Definition at line 115 of file code_dba20_len_350.c.
Referenced by get_float_variable(), get_variable(), is_actor_hp_bar_visible(), and is_actortype_hpbar_visible().
get_global_flag()
s32 get_global_flag (s32 index)
Definition at line 87 of file code_dba20_len_350.c.
Referenced by func_802E1204(), func_802E3B08(), func_802E4154(), func_802E54CC(), func_802E56EC(), func_802E88EC(), func_802E89B0(), func_802E8F94(), and get_variable().
get_area_byte()
s32 get_area_byte (s32 index)
Definition at line 167 of file code_dba20_len_350.c.
Referenced by get_float_variable(), and get_variable().
get_area_flag()
s32 get_area_flag (s32 index)
Definition at line 147 of file code_dba20_len_350.c.
Referenced by get_variable().
get_shadow_by_index()
Shadow* get_shadow_by_index (s32 index)
Definition at line 44 of file code_a5dd0_len_114e0.c.
Referenced by disable_player_shadow(), enable_player_shadow(), func_802E4108(), func_802E421C(), and func_802E4484().
render_player_model()
void render_player_model ()
Definition at line 290 of file code_77480.c.
Referenced by render_player().
integrate_gravity()
f32 integrate_gravity (void)
Definition at line 48 of file code_7bb60_len_41b0.c.
Referenced by func_800E34D8().
get_clamped_angle_diff()
f32 get_clamped_angle_diff (f32 a, f32 b)
Definition at line 259 of file code_42e0_len_1f60.c.
Referenced by set_npc_yaw().
get_entity_type()
u32 get_entity_type (s32 arg0)
Definition at line 72 of file code_a5dd0_len_114e0.c.
Referenced by func_802E2EB0(), func_802E2FD0(), func_802E31EC(), func_802E328C(), func_802E3BA4(), func_802E40A0(), func_802E4154(), and func_802E421C().
get_entity_by_index()
Entity* get_entity_by_index (s32 index)
Definition at line 40 of file code_a5dd0_len_114e0.c.
Referenced by AssignFlag(), func_802402BC_8D878C(), func_80240304_8D87D4(), func_80240444_8CAD44(), func_80240A6C_8D482C(), func_80240EC0_8DAFC0(), func_802E2BA4(), func_802E38D8(), func_802E4108(), func_802E421C(), func_802E455C(), func_802E4B10(), func_802E4B60(), func_802E55A8(), func_802E5690(), func_802E56EC(), func_802E581C(), GetEntityPosition(), SetEntityFlags100000(), and SetEntityPosition().
create_entity()
s32 create_entity (StaticEntityData * data, s32 x, s32 y, s32 z, s32 arg4, s32 flags)
Definition at line 115 of file code_a5dd0_len_114e0.c.
Referenced by func_802E2FD0(), func_802E38D8(), func_802E3A48(), func_802E3B08(), func_802E4154(), func_802E421C(), func_802E55A8(), and func_802E56EC().
func_80070550()
void func_80070550 (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, s32 arg6, s32 arg7)
Definition at line 76 of file code_4ac90_len_3910.c.
Referenced by func_802E5E50().
func_802E263C()
void func_802E263C (Entity * entity)
Definition at line 521 of file code_102C80.c.
create_shadow_callback()
void create_shadow_callback (Shadow * entity)
Definition at line 3 of file code_102610_len_2330.c.
func_802E10F4()
void func_802E10F4 (Entity * entity)
Definition at line 24 of file code_102610_len_2330.c.
func_802E114C()
void func_802E114C (void)
Definition at line 32 of file code_102610_len_2330.c.
func_802E117C()
void func_802E117C (void)
Definition at line 38 of file code_102610_len_2330.c.
save_game_at_player_position()
void save_game_at_player_position (void)
Definition at line 43 of file code_102610_len_2330.c.
func_802E1204()
void func_802E1204 (Entity * entity)
Definition at line 52 of file code_102610_len_2330.c.
func_802E1270()
void func_802E1270 (Entity * entity)
Definition at line 66 of file code_102610_len_2330.c.
func_802E1298()
void func_802E1298 (void)
Definition at line 74 of file code_102610_len_2330.c.
func_802E12F8()
void func_802E12F8 (void)
Definition at line 83 of file code_102610_len_2330.c.
func_802E1328()
void func_802E1328 (Entity * entity)
Definition at line 88 of file code_102610_len_2330.c.
func_802E1350()
void func_802E1350 (Entity * entity)
Definition at line 96 of file code_102610_len_2330.c.
func_802E13B8()
void func_802E13B8 (Entity * entity)
Definition at line 108 of file code_102610_len_2330.c.
func_802E1400()
void func_802E1400 (Entity * entity)
Definition at line 5 of file code_102C80.c.
func_802E1460()
void func_802E1460 (Entity * entity)
Definition at line 17 of file code_102C80.c.
func_802E14D8()
void func_802E14D8 (Entity * entity)
Definition at line 30 of file code_102C80.c.
func_802E1614()
void func_802E1614 (Entity * entity)
Definition at line 69 of file code_102C80.c.
func_802E1660()
void func_802E1660 (Entity * entity)
Definition at line 80 of file code_102C80.c.
func_802E1740()
void func_802E1740 (Entity * entity)
Definition at line 126 of file code_102C80.c.
func_802E176C()
void func_802E176C (Entity * entity)
Definition at line 132 of file code_102C80.c.
func_802E17A8()
s32 func_802E17A8 (Entity * entity)
Definition at line 144 of file code_102C80.c.
func_802E1EA8()
void func_802E1EA8 (Entity * entity)
Definition at line 319 of file code_102C80.c.
func_802E1EDC()
void func_802E1EDC (Entity * entity)
Definition at line 327 of file code_102C80.c.
func_802E234C()
void func_802E234C (Entity * entity)
Definition at line 470 of file code_102C80.c.
Referenced by entity_init_BlueSwitch(), and entity_init_HugeBlueSwitch().
func_802E31EC()
f32 func_802E31EC (Entity * entity)
Definition at line 20 of file code_104940_len_dc0.c.
func_802E328C()
void func_802E328C (Entity * entity)
Definition at line 35 of file code_104940_len_dc0.c.
func_802E3BA4()
s32 func_802E3BA4 (Entity * entity)
Definition at line 203 of file code_104940_len_dc0.c.
entity_init_BlueSwitch()
void entity_init_BlueSwitch (Entity * entity)
Definition at line 480 of file code_102C80.c.
entity_init_HugeBlueSwitch()
void entity_init_HugeBlueSwitch (Entity * entity)
Definition at line 501 of file code_102C80.c.
func_80072230()
s32 func_80072230 (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Definition at line 231 of file code_4ac90_len_3910.c.
Referenced by func_802E1EDC(), func_802E31B0(), and func_802E405C().
load_string()
PrintContext* load_string (s32 stringID, s32 * a1)
Definition at line 33 of file code_B9D60.c.
Referenced by ActorSpeak(), func_802E1204(), func_802E1298(), func_802E54CC(), and ShowBattleChoice().
get_screen_coords()
void get_screen_coords (Cam camID, f32 x, f32 y, f32 z, f32 * outX, f32 * outY, f32 * outZ)
Definition at line 25 of file code_8560.c.
Referenced by ActorSpeak().
parent_collider_to_model()
void parent_collider_to_model (s32 colliderID, s16 modelIndex)
Definition at line 21 of file code_362a0_len_2f70.c.
Referenced by ParentColliderToModel().
clone_model()
void clone_model (u16 srcModelID, u16 newModelID)
Definition at line 258 of file code_a5dd0_len_114e0.c.
Referenced by CloneModel().
get_model_from_list_index()
Model* get_model_from_list_index (s32 listIndex)
Definition at line 233 of file code_a5dd0_len_114e0.c.
Referenced by EnableModel(), EnableTexPanning(), func_8011D72C(), func_802C8EE4(), func_802C90FC(), func_802C91A4(), hide_foreground_models(), hide_foreground_models_unsafe(), RotateModel(), ScaleModel(), SetModelFlag10(), SetModelFlags(), SetRenderMode(), SetTexPanner(), show_foreground_models(), show_foreground_models_unsafe(), SomeMatrixOperation2(), and TranslateModel().
get_model_list_index_from_tree_index()
s32 get_model_list_index_from_tree_index (s32 treeIndex)
Definition at line 241 of file code_a5dd0_len_114e0.c.
Referenced by EnableModel(), EnableTexPanning(), func_8011D72C(), func_802C8EE4(), func_802C90FC(), func_802C91A4(), GetModelIndex(), hide_foreground_models(), hide_foreground_models_unsafe(), ParentColliderToModel(), RotateModel(), ScaleModel(), SetModelFlag10(), SetModelFlags(), SetRenderMode(), SetTexPanner(), show_foreground_models(), show_foreground_models_unsafe(), SomeMatrixOperation2(), and TranslateModel().
get_model_center_and_size()
void get_model_center_and_size (s32 modelID, f32 * centerX, f32 * centerY, f32 * centerZ, f32 * sizeX, f32 * sizeY, f32 * sizeZ)
Definition at line 246 of file code_a5dd0_len_114e0.c.
Referenced by GetModelCenter(), and PlaySoundAtModel().
func_80027088()
void func_80027088 (s32 arg0)
Definition at line 113 of file code_1b40_len_20b0.c.
Referenced by func_802BD3E4(), func_802BD41C(), func_802D5830(), func_802E114C(), func_802E117C(), func_802E54CC(), func_802E555C(), and world_goombario_pre_battle().
func_8006F8F0()
void func_8006F8F0 (f32 arg0, f32 arg1, f32 arg2)
Definition at line 7 of file code_4ac90_len_3910.c.
Referenced by OnDefeatEnemy().
func_8006FEF0()
void func_8006FEF0 (s32 a0, f32 a1, f32 a2, f32 a3, f32 a4)
Definition at line 40 of file code_4ac90_len_3910.c.
Referenced by func_802403B8_8AC348(), func_80240530_8AC4C0(), func_80240BD8_8ACB68(), and func_802BD100_3251D0().
func_80070190()
void func_80070190 (s32 arg0, f32 arg1, f32 arg2, f32 arg3, s32 arg4, f32 arg5, s32 arg6, s32 arg7)
Definition at line 55 of file code_4ac90_len_3910.c.
Referenced by OnDefeatEnemy().
func_80071090()
void func_80071090 (s32 a0, f32 a1, f32 a2, f32 a3, s32 a4)
Definition at line 136 of file code_4ac90_len_3910.c.
Referenced by func_802BD1AC_3251D0(), and func_802BD26C().
func_80071750()
void func_80071750 (s32 a0, f32 a1, f32 a2, f32 a3, f32 a4, s32 a5)
Definition at line 172 of file code_4ac90_len_3910.c.
Referenced by func_8003F4CC(), and func_802404A0_8AC430().
func_800720B0()
void func_800720B0 (s32 a0, f32 a1, f32 a2, f32 a3, f32 a4, s32 a5)
Definition at line 222 of file code_4ac90_len_3910.c.
Referenced by func_8003F414().
func_80072950()
void func_80072950 (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 time)
Definition at line 269 of file code_4ac90_len_3910.c.
Referenced by SpawnSunEffect().
update_collider_transform()
void update_collider_transform (s16 colliderID)
Definition at line 27 of file code_362a0_len_2f70.c.
Referenced by ParentColliderToModel(), and UpdateColliderTransform().
get_collider_center()
void get_collider_center (s32 colliderID, f32 * x, f32 * y, f32 * z)
Definition at line 33 of file code_362a0_len_2f70.c.
Referenced by func_802405EC_7EB2FC(), GetColliderCenter(), and PlaySoundAtCollider().
is_trigger_bound()
s32 is_trigger_bound (Trigger * trigger, Bytecode * script)
Definition at line 39 of file code_dbd70_len_700.c.
Referenced by _bound_script_trigger_handler().
create_trigger()
Trigger* create_trigger (TriggerDefinition * def)
Definition at line 19 of file code_dbd70_len_700.c.
Referenced by bind_trigger(), si_handle_bind_lock(), and si_handle_bind_trigger().
_bound_script_trigger_handler()
s32 _bound_script_trigger_handler (Trigger * trigger)
Definition at line 963 of file si.c.
Referenced by bind_trigger(), and si_handle_bind_trigger().
get_trigger_by_id()
Trigger* get_trigger_by_id (s32 triggerID)
Definition at line 41 of file code_dbd70_len_700.c.
Referenced by func_802BD100().
get_actor()
Actor* get_actor (ActorID actorID)
Definition at line 82 of file code_197F40.c.
Referenced by ActorExists(), ActorSpeak(), AddActorPos(), AddActorVar(), AddGoalPos(), AddPartDispOffset(), AddPartMovementVar(), AfflictActor(), ApplyShrinkFromOwner(), BindHandleEvent(), BindIdle(), BindNextTurn(), BindTakeTurn(), calc_item_check_hit(), ClearStatusEffects(), CopyStatusEffects(), CountPlayerTargets(), create_part_shadow(), DispatchDamageEvent(), DispatchEvent(), EnableActorBlur(), EnableActorGlow(), EnableIdleScript(), EnemyCreateTargetList(), ForceHomePos(), func_80218000_4CF1B0(), func_80218618_4FF068(), func_80252B3C(), func_80261D98(), func_8026D51C(), func_8026D5A4(), func_8026D8EC(), func_8026D940(), func_8026DA94(), func_8026DEF0(), func_8026DF88(), func_8027CC10(), func_8027D2D8(), func_8027D32C(), func_8027D434(), func_8027D4C8(), func_8027D628(), func_8027D75C(), GetActorFlags(), GetActorHP(), GetActorLevel(), GetActorPos(), GetActorRotation(), GetActorScale(), GetActorSize(), GetActorVar(), GetActorYaw(), GetAnimation(), GetCurrentActorType(), GetEnemyMaxHP(), GetGoalPos(), GetHomePos(), GetIdleGoal(), GetIndexFromHome(), GetIndexFromPos(), GetLastDamage(), GetLastEvent(), GetOriginalActorType(), GetPartDispOffset(), GetPartEventFlags(), GetPartFlags(), GetPartMovementVar(), GetPartOffset(), GetPartPos(), GetPartRotation(), GetPartScale(), GetPartTarget(), GetPartTargetFlags(), GetPartYaw(), GetTargetListLength(), HPBarToCurrent(), HPBarToHome(), InitTargetIterator(), ItemAfflictEnemy(), ItemCheckHit(), ItemDamageEnemy(), MultiplyByActorScale(), MultiplyVec2ByActorScale(), MultiplyVec3yActorScale(), PauseTakeTurn(), PlayerCreateTargetList(), PlayLoopingSoundAtActor(), PlaySoundAtActor(), PlaySoundAtPart(), remove_part_shadow(), ResetAllActorSounds(), ResumeTakeTurn(), set_actor_current_position(), set_actor_home_position(), set_actor_yaw(), set_part_absolute_position(), set_part_yaw(), SetActorDispOffset(), SetActorFlagBits(), SetActorFlags(), SetActorIdleJumpGravity(), SetActorIdleSpeed(), SetActorJumpGravity(), SetActorPos(), SetActorRotation(), SetActorRotationOffset(), SetActorScale(), SetActorScaleModifier(), SetActorSize(), SetActorSpeed(), SetActorVar(), SetDefenseTable(), SetEnemyHP(), SetEnemyTargetOffset(), SetGoalPos(), SetGoalToFirstTarget(), SetGoalToHome(), SetGoalToTarget(), SetHomePos(), SetIdleAnimations(), SetIdleGoal(), SetIdleGoalToHome(), SetJumpAnimations(), SetPartDispOffset(), SetPartEventBits(), SetPartEventFlags(), SetPartFlagBits(), SetPartFlags(), SetPartGoalToTarget(), SetPartJumpGravity(), SetPartMovementVar(), SetPartMoveSpeed(), SetPartPos(), SetPartRotation(), SetPartRotationOffset(), SetPartScale(), SetPartTargetFlagBits(), SetPartTargetFlags(), SetStatusTable(), SetTargetActor(), SetTargetOffset(), ShowShockEffect(), StopLoopingSoundAtActor(), and UnkBattleFunc1().
get_actor_part()
ActorPart* get_actor_part (Actor * actor, s32 partIndex)
Definition at line 69 of file code_190B20.c.
Referenced by ActorSpeak(), AddPartDispOffset(), AddPartMovementVar(), calc_item_check_hit(), create_part_shadow(), func_8026D51C(), func_8026D5A4(), func_8026DEF0(), func_8026DF88(), func_8027CC10(), func_8027D434(), func_8027D4C8(), GetAnimation(), GetPartDispOffset(), GetPartEventFlags(), GetPartFlags(), GetPartMovementVar(), GetPartOffset(), GetPartPos(), GetPartRotation(), GetPartScale(), GetPartTarget(), GetPartTargetFlags(), GetPartYaw(), PlaySoundAtPart(), remove_part_shadow(), set_part_absolute_position(), set_part_yaw(), SetDefenseTable(), SetEnemyTargetOffset(), SetIdleAnimations(), SetPartDispOffset(), SetPartEventBits(), SetPartEventFlags(), SetPartFlagBits(), SetPartFlags(), SetPartGoalToTarget(), SetPartJumpGravity(), SetPartMovementVar(), SetPartMoveSpeed(), SetPartPos(), SetPartRotation(), SetPartRotationOffset(), SetPartScale(), SetPartTargetFlagBits(), SetPartTargetFlags(), and SetTargetOffset().
func_800494C0()
s32 func_800494C0 (Npc * npc, s32 arg1, s32 arg2)
Definition at line 191 of file code_20ec0_len_5040.c.
Referenced by func_80045838().
get_variable()
s32 get_variable (ScriptInstance * script, Bytecode var)
Definition at line 1182 of file si.c.
Referenced by ActorExists(), ActorSpeak(), AddActorPos(), AddActorVar(), AddAnimModelPosition(), AddBadge(), AddCoin(), AddGoalPos(), AddItem(), AddKeyItem(), AddPartDispOffset(), AddPartMovementVar(), AddStarPieces(), AddStarPoints(), AfflictActor(), ApplyShrinkFromOwner(), AwaitPlayerApproach(), AwaitPlayerLeave(), AwaitScriptComplete(), Bandit_DropCoin(), BindHandleEvent(), BindIdle(), BindNextTurn(), BindNpcAux(), BindNpcDefeat(), BindNpcHit(), BindNpcIdle(), BindNpcInteract(), BindTakeTurn(), Call800EB168(), ChangeModelAnimation(), CheckItemFlags40(), ClampAngleInt(), ClearAmbientSounds(), ClearPartnerMoveHistory(), ClearStatusEffects(), CloneModel(), CopyStatusEffects(), CountPlayerTargets(), DeleteNpc(), DeleteTrigger(), DemoPressButton(), DemoReleaseButton(), DemoSetButtons(), Disable8bitMario(), DisablePartner(), DisablePartnerAI(), DisablePlayerInput(), DisablePlayerPhysics(), DisablePulseStone(), DispatchDamageEvent(), DispatchEvent(), DropItemEntity(), DropItemEntityB(), EnableActorBlur(), EnableActorGlow(), EnableIdleScript(), EnableModel(), EnableNpcAI(), EnableNpcAux(), EnableNpcBlur(), EnableNpcShadow(), EnablePartner(), EnableSpriteShading(), EnableStatusMenu(), EnableTexPanning(), FadeInMusic(), FadeOutMusic(), FindItem(), FindKeyItem(), ForceHomePos(), func_8003F414(), func_8003F4CC(), func_80044238(), func_80045580(), func_80045798(), func_800457C4(), func_80045838(), func_80045900(), func_80218618_4FF068(), func_80240000_800880(), func_80240000_8C7F90(), func_80240044_8008C4(), func_802402BC_8D878C(), func_80240304_8D87D4(), func_802403B8_8AC348(), func_80240530_8AC4C0(), func_802405EC_7EB2FC(), func_80240A6C_8D482C(), func_80240BD8_8ACB68(), func_80241CC8_8D31D8(), func_80252B3C(), func_802535B4(), func_802536A8(), func_80253734(), func_80253B30(), func_8026919C(), func_802692EC(), func_80269550(), func_802695D4(), func_8026962C(), func_8026BF48(), func_8026D51C(), func_8026D5A4(), func_8026D8EC(), func_8026D940(), func_8026DA94(), func_8026DEF0(), func_8026DF88(), func_8026E16C(), func_8026F60C(), func_80276F1C(), func_8027CC10(), func_8027D2D8(), func_8027D32C(), func_8027D434(), func_8027D4C8(), func_8027D628(), func_8027D75C(), func_80281C20(), func_80282338(), func_80283BD0(), func_802BD100_3251D0(), func_802BD1AC_3251D0(), func_802BD26C(), func_802BD32C(), func_802BD388(), func_802BD458(), func_802C8EE4(), func_802C90FC(), func_802C91A4(), func_802C9428(), func_802C94A0(), func_802C971C(), func_802C9748(), func_802C9B40(), func_802C9C70(), func_802CA90C(), func_802CA988(), func_802CABE8(), func_802CACC0(), func_802CAE50(), func_802CB710(), func_802CCDAC(), func_802CCEDC(), func_802CD348(), func_802CD3C0(), func_802CD418(), func_802CDE68(), func_802CF1B4(), func_802CF208(), func_802CF56C(), func_802CFD30(), func_802CFE2C(), func_802CFE80(), func_802CFEEC(), func_802CFFC0(), func_802D0244(), func_802D0C94(), func_802D4CC4(), func_802D5830(), func_802D585C(), func_802D5EE0(), func_802D5F28(), func_802D5FA4(), func_802D5FF8(), func_802D6090(), func_802D617C(), func_802D62E4(), func_802D6340(), func_802D721C(), func_802D7520(), func_802D75D8(), func_802D7B10(), func_802D7B44(), func_802D7B74(), get_spirits_rescued(), GetActorFlags(), GetActorHP(), GetActorLevel(), GetActorPos(), GetActorRotation(), GetActorScale(), GetActorSize(), GetActorVar(), GetActorYaw(), GetAngleBetweenNPCs(), GetAngleToNPC(), GetAngleToPlayer(), GetAnimation(), GetAnimModelPosition(), GetCamDistance(), GetCamPitch(), GetCamPosA(), GetCamPosB(), GetCamPosC(), GetCamPosition(), GetCamType(), GetCamVfov(), GetColliderCenter(), GetCurrentActorType(), GetEnemyMaxHP(), GetEntityPosition(), GetEntryPos(), GetGoalPos(), GetHomePos(), GetIdleGoal(), GetIndexFromHome(), GetIndexFromPos(), GetItemName(), GetItemPower(), GetLastDamage(), GetLastEvent(), GetModelCenter(), GetModelIndex(), GetNpcAnimation(), GetNpcCollisionHeight(), GetNpcPointer(), GetNpcPos(), GetNpcVar(), GetNpcYaw(), GetOriginalActorType(), GetPartDispOffset(), GetPartEventFlags(), GetPartFlags(), GetPartMovementVar(), GetPartOffset(), GetPartPos(), GetPartRotation(), GetPartScale(), GetPartTarget(), GetPartTargetFlags(), GetPartYaw(), GetSelfAnimationFromTable(), GetSelfVar(), GetValueByRef(), HasKeyItem(), HidePlayerShadow(), HPBarToCurrent(), HPBarToHome(), InterpPlayerYaw(), IsPlayerWithin(), IsSaveVar123(), ItemAfflictEnemy(), ItemCheckHit(), ItemDamageEnemy(), load_map_bg(), LoadDemoBattle(), LoadModelAnimation(), LoadPath(), MakeItemEntity(), MakeLerp(), MakeNpcs(), MakeShopOwner(), MakeStatusField(), NpcSetHomePosToCurrent(), OverrideBattleDmaDest(), PanToTarget(), ParentColliderToModel(), PauseTakeTurn(), PlayAmbientSounds(), PlayerMoveTo(), PlayLoopingSoundAtActor(), PlayModelAnimation(), PlaySound(), PlaySoundAt(), PlaySoundAtActor(), PlaySoundAtCollider(), PlaySoundAtF(), PlaySoundAtModel(), PlaySoundAtNpc(), PlaySoundAtPart(), PlaySoundAtPlayer(), RandInt(), RemoveBadge(), RemoveEffect(), RemoveFortressKeys(), RemoveItem(), RemoveItemAt(), RemoveItemEntity(), RemoveKeyItemAt(), ResetAllActorSounds(), RestartNpcAI(), RestartNpcAux(), ResumeTakeTurn(), RotateModel(), ScaleModel(), SetActionSuccess(), SetActorDispOffset(), SetActorFlagBits(), SetActorFlags(), SetActorIdleJumpGravity(), SetActorIdleSpeed(), SetActorJumpGravity(), SetActorPos(), SetActorRotation(), SetActorRotationOffset(), SetActorScale(), SetActorScaleModifier(), SetActorSize(), SetActorSpeed(), SetActorVar(), SetActorYaw(), SetAnimation(), SetAnimationRate(), SetAnimModelPosition(), SetAnimModelRotation(), SetAnimModelScale(), SetBattleFlagBits(), SetBattleFlagBits2(), SetBattleMusic(), SetCamBGColor(), SetCamDistance(), SetCamEnabled(), SetCamFlag80(), SetCamLeadPlayer(), SetCamPerspective(), SetCamPitch(), SetCamPosA(), SetCamPosB(), SetCamPosC(), SetCamSpeed(), SetCamTarget(), SetCamType(), SetCamVfov(), SetCamViewport(), SetDefenseTable(), SetEncounterStatusFlags(), SetEnemyFlagBits(), SetEnemyHP(), SetEnemyTargetOffset(), SetEntityPosition(), SetForegroundModelsVisible(), SetForegroundModelsVisibleUnsafe(), SetGameMode(), SetGoalPos(), SetGoalToFirstTarget(), SetGoalToHome(), SetGoalToTarget(), SetGroupEnabled(), SetHomePos(), SetIdleAnimations(), SetIdleGoal(), SetIdleGoalToHome(), SetItemFlags(), SetItemPos(), SetJumpAnimations(), SetManyVars(), SetMessageString(), SetMessageValue(), SetModelFlag10(), SetModelFlags(), SetMusicTrack(), SetNpcAnimation(), SetNpcAnimationSpeed(), SetNpcCollisionSize(), SetNpcEffect(), SetNpcFlagBits(), SetNpcJumpscale(), SetNpcPos(), SetNpcRotation(), SetNpcScale(), SetNpcSpeed(), SetNpcVar(), SetNpcYaw(), SetOwnerID(), SetPanTarget(), SetPartDispOffset(), SetPartEventBits(), SetPartEventFlags(), SetPartFlagBits(), SetPartFlags(), SetPartGoalToTarget(), SetPartJumpGravity(), SetPartMovementVar(), SetPartMoveSpeed(), SetPartPos(), SetPartRotation(), SetPartRotationOffset(), SetPartScale(), SetPartTargetFlagBits(), SetPartTargetFlags(), SetPartYaw(), SetPlayerActionState(), SetPlayerAnimation(), SetPlayerCollisionSize(), SetPlayerFlagBits(), SetPlayerPos(), SetRenderMode(), SetSelfEnemyFlagBits(), SetSelfRotation(), SetSelfVar(), SetStatusTable(), SetTargetActor(), SetTargetOffset(), SetTattleString(), SetTexPanner(), SetTexPanOffset(), SetValueByRef(), ShowBattleChoice(), ShowCoinCounter(), ShowGotItem(), ShowShockEffect(), ShowStatusMenu(), si_handle_add(), si_handle_allocate_array(), si_handle_AND(), si_handle_AND_const(), si_handle_await_script(), si_handle_bind_lock(), si_handle_bind_trigger(), si_handle_call(), si_handle_case_equal(), si_handle_case_greater(), si_handle_case_greater_equal(), si_handle_case_less(), si_handle_case_less_equal(), si_handle_case_multi_and_equal(), si_handle_case_multi_or_equal(), si_handle_case_not_equal(), si_handle_case_range(), si_handle_divide(), si_handle_does_script_exist(), si_handle_end_loop(), si_handle_get_Nth_float(), si_handle_get_Nth_word(), si_handle_goto(), si_handle_if_equal(), si_handle_if_flag(), si_handle_if_greater(), si_handle_if_greater_equal(), si_handle_if_less(), si_handle_if_less_equal(), si_handle_if_not_equal(), si_handle_if_not_flag(), si_handle_jump(), si_handle_kill_script(), si_handle_match(), si_handle_mod(), si_handle_multiply(), si_handle_OR(), si_handle_OR_const(), si_handle_resume_all(), si_handle_resume_others(), si_handle_resume_script(), si_handle_set_array(), si_handle_set_flag_array(), si_handle_set_float_buffer_ptr(), si_handle_set_group(), si_handle_set_int_buffer_ptr(), si_handle_set_priority(), si_handle_set_var(), si_handle_sleep_frames(), si_handle_spawn_script(), si_handle_spawn_script_get_id(), si_handle_subtract(), si_handle_suspend_all(), si_handle_suspend_others(), si_handle_suspend_script(), SomeMatrixOperation2(), SomeXYZFuncTodoRename(), Spawn802D9D50(), StartBattleWith(), StartRumble(), StartRumbleWithParams(), StopLoopingSoundAtActor(), StopSound(), SwitchMessage(), TranslateModel(), UnkBattleFunc1(), UnkBattleFunc2(), UnkBattleFunc2_2(), UnkCameraFunc(), UnkFloatFunc(), UnkMusicFunc(), UnkPositionFunc(), UnkYawFunc(), UpdateColliderTransform(), UseDoorSounds(), WaitForCam(), and WasStatusInflicted().
set_variable()
s32 set_variable (ScriptInstance * script, Bytecode var, s32 value)
Definition at line 1325 of file si.c.
Referenced by ActorExists(), AddBadge(), AddItem(), ApplyShrinkFromOwner(), CheckActionState(), CheckButtonDown(), CheckButtonHeld(), CheckButtonPress(), ClampAngleInt(), CountFortressKeys(), CountPlayerTargets(), exec_ShakeCamX(), FindItem(), FindKeyItem(), func_80035E54(), func_800441F0(), func_800445A8(), func_800445D4(), func_8004580C(), func_800458CC(), func_80240000_9A4650(), func_80240044_8008C4(), func_80241CC8_8D31D8(), func_80252B3C(), func_802537C0(), func_80253B30(), func_80269318(), func_80269524(), func_802695A8(), func_80269600(), func_80269E80(), func_8026DEF0(), func_8026DF88(), func_8027D75C(), func_802C9B40(), func_802CA988(), func_802D249C(), func_802D6AF0(), GetActionSuccess(), GetActionSuccessCopy(), GetActorFlags(), GetActorHP(), GetActorLevel(), GetActorPos(), GetActorRotation(), GetActorSize(), GetActorVar(), GetActorYaw(), GetAngleBetweenNPCs(), GetAngleToNPC(), GetAngleToPlayer(), GetAnimation(), GetAttackerActorID(), GetBattleFlags(), GetBattleFlags2(), GetBattleOutcome(), GetBattlePhase(), GetBattleState(), GetBlockResult(), GetCamType(), GetCamVfov(), GetCurrentActorType(), GetCurrentPartner(), GetCurrentPartnerID(), GetDemoState(), GetEncounterEnemyIsOwner(), GetEncounterState(), GetEnemyMaxHP(), GetEntityPosition(), GetEntryID(), GetEntryPos(), GetFrameCounter(), GetGameStatus75(), GetGoalPos(), GetHomePos(), GetIdleGoal(), GetIndexFromHome(), GetIndexFromPos(), GetItemName(), GetItemPower(), GetLastDamage(), GetLastElement(), GetLastEvent(), GetLoadType(), GetMapID(), GetModelIndex(), GetNpcAnimation(), GetNpcCollisionHeight(), GetNpcPointer(), GetNpcPos(), GetNpcVar(), GetNpcYaw(), GetOriginalActorType(), GetOwnerEncounterTrigger(), GetOwnerID(), GetPartDispOffset(), GetPartEventFlags(), GetPartFlags(), GetPartMovementVar(), GetPartnerCall800EB168(), GetPartnerPos(), GetPartOffset(), GetPartPos(), GetPartTarget(), GetPartTargetFlags(), GetPartYaw(), GetPlayerActionState(), GetPlayerAnimation(), GetPlayerHP(), GetPlayerPos(), GetPlayerTargetYaw(), GetSelectedMoveID(), GetSelfAnimationFromTable(), GetSelfNpcID(), GetSelfVar(), GetTargetListLength(), GetValueByRef(), HasKeyItem(), IsMessageBoxDisplayed(), IsPlayerWithin(), ItemAfflictEnemy(), ItemCheckHit(), ItemDamageEnemy(), MakeStatusField(), PartnerCanUseAbility(), PartnerIsFlying(), RandInt(), RemoveItem(), SetValueByRef(), si_handle_add(), si_handle_allocate_array(), si_handle_AND(), si_handle_AND_const(), si_handle_bind_trigger(), si_handle_divide(), si_handle_does_script_exist(), si_handle_end_loop(), si_handle_get_1_word(), si_handle_get_2_word(), si_handle_get_3_word(), si_handle_get_4_word(), si_handle_get_Nth_word(), si_handle_mod(), si_handle_multiply(), si_handle_OR(), si_handle_OR_const(), si_handle_set_const(), si_handle_set_var(), si_handle_spawn_script_get_id(), si_handle_subtract(), SomeXYZFuncTodoRename(), UnkCameraFunc(), UnkFloatFunc(), UnkYawFunc(), and WasStatusInflicted().
get_float_variable()
f32 get_float_variable (ScriptInstance * script, Bytecode var)
Definition at line 1329 of file si.c.
Referenced by AddActorPos(), AddAnimModelPosition(), AddGoalPos(), AddPartDispOffset(), AddVectorPolar(), CheckActionState(), ClampAngleFloat(), DemoJoystickRadial(), DemoJoystickXY(), func_80282594(), func_802CD348(), func_802CDE68(), func_802D4D14(), func_802D7520(), func_802D75D8(), GetDist2D(), InterpPlayerYaw(), MultiplyByActorScale(), MultiplyVec2ByActorScale(), MultiplyVec3yActorScale(), PanToTarget(), PlaySoundAtF(), RotateModel(), ScaleModel(), SetActorDispOffset(), SetActorIdleJumpGravity(), SetActorIdleSpeed(), SetActorJumpGravity(), SetActorRotation(), SetActorRotationOffset(), SetActorScale(), SetActorScaleModifier(), SetActorSpeed(), SetAnimationRate(), SetAnimModelPosition(), SetAnimModelRotation(), SetAnimModelScale(), SetCamDistance(), SetCamPerspective(), SetCamPitch(), SetCamPosA(), SetCamPosB(), SetCamPosC(), SetCamSpeed(), SetCamVfov(), SetNpcAnimationSpeed(), SetNpcJumpscale(), SetNpcRotation(), SetNpcScale(), SetNpcSpeed(), SetPanTarget(), SetPartDispOffset(), SetPartJumpGravity(), SetPartMoveSpeed(), SetPartRotation(), SetPartRotationOffset(), SetPartScale(), SetPlayerAnimationSpeed(), SetPlayerJumpscale(), SetPlayerSpeed(), si_handle_addF(), si_handle_divideF(), si_handle_get_1_float(), si_handle_get_2_float(), si_handle_get_3_float(), si_handle_get_4_float(), si_handle_multiplyF(), si_handle_set_float(), si_handle_set_timescale(), si_handle_sleep_seconds(), si_handle_subtractF(), SomeMatrixOperation2(), SomeXYZFunc2(), TranslateModel(), UnkFloatFunc(), UnkMovePartner(), and WaitForCam().
set_float_variable()
f32 set_float_variable (ScriptInstance * script, Bytecode var, f32 value)
Definition at line 1377 of file si.c.
Referenced by AddVectorPolar(), ClampAngleFloat(), exec_ShakeCamX(), GetActorScale(), GetAnimModelPosition(), GetCamDistance(), GetCamPitch(), GetCamPosA(), GetCamPosB(), GetCamPosC(), GetCamPosition(), GetDist2D(), GetPartRotation(), GetPartScale(), MultiplyByActorScale(), MultiplyVec2ByActorScale(), MultiplyVec3yActorScale(), si_handle_addF(), si_handle_divideF(), si_handle_get_1_float(), si_handle_get_2_float(), si_handle_get_3_float(), si_handle_get_4_float(), si_handle_get_Nth_float(), si_handle_multiplyF(), si_handle_set_float(), si_handle_subtractF(), SomeXYZFunc2(), and UnkFloatFunc().
set_script_timescale()
void set_script_timescale (ScriptInstance * script, f32 timescale)
Definition at line 548 of file code_e79b0_len_1920.c.
Referenced by si_handle_set_timescale().
sin_deg()
f32 sin_deg (f32 x)
Definition at line 341 of file code_42e0_len_1f60.c.
Referenced by DemoJoystickRadial(), func_80240358_8C82E8(), SomeXYZFuncTodoRename(), and UnkCameraFunc().
cos_deg()
f32 cos_deg (f32 x)
Definition at line 345 of file code_42e0_len_1f60.c.
Referenced by DemoJoystickRadial(), func_80240358_8C82E8(), SomeItemEntityFunc(), SomeXYZFuncTodoRename(), and UnkCameraFunc().
sin_rad()
f32 sin_rad (f32 x)
Definition at line 326 of file code_42e0_len_1f60.c.
Referenced by func_80218000_4CF1B0(), func_802E3728(), func_802E37E4(), and npc_move_heading().
cos_rad()
f32 cos_rad (f32 x)
Definition at line 330 of file code_42e0_len_1f60.c.
Referenced by npc_move_heading(), SomeItemEntityFunc(), and UnkFloatFunc().
round()
s32 round (f32 arg0)
Definition at line 249 of file code_42e0_len_1f60.c.
Referenced by func_802CA988().
atan2()
f32 atan2 (f32 startX, f32 startZ, f32 endX, f32 endZ)
Definition at line 270 of file code_42e0_len_1f60.c.
Referenced by func_80240034_7EAD44(), func_802E8ADC(), func_802E8BC0(), func_802E9050(), get_dpad_input_radial(), get_player_normal_pitch(), get_player_normal_yaw(), GetAngleBetweenNPCs(), GetAngleToNPC(), GetAngleToPlayer(), PlayerMoveTo(), set_script_owner_npc_anim(), UnkNpcAIFunc2(), and UnkNpcAIFunc9().
clamp_angle()
f32 clamp_angle (f32 theta)
Definition at line 257 of file code_42e0_len_1f60.c.
Referenced by ClampAngleFloat(), ClampAngleInt(), func_80218000_4CF1B0(), func_80283908(), func_802E10F4(), func_802E3728(), func_802E5E50(), func_802E9050(), GetCurrentCameraYawClamped180(), GetNpcYaw(), InterpPlayerYaw(), SomeItemEntityFunc(), SomeXYZFuncTodoRename(), UnkNpcAIFunc1(), and UnkYawFunc().
sign()
s32 sign (s32 value)
Definition at line 136 of file code_42e0_len_1f60.c.
Referenced by pause_interp_vertical_scroll(), and signF().
func_80055448()
s32 func_80055448 (s32 arg0)
Definition at line 126 of file code_303c0_len_3e10.c.
Referenced by func_80147264().
func_80055464()
s32 func_80055464 (s32 arg0, s32 arg1)
Definition at line 130 of file code_303c0_len_3e10.c.
Referenced by func_80055760(), and func_80147264().
func_800561A4()
void func_800561A4 (s32 arg0)
Definition at line 443 of file code_303c0_len_3e10.c.
osGetId()
s32 osGetId ()
Definition at line 11 of file code_44b40_len_a90.c.
set_curtain_scale_goal()
void set_curtain_scale_goal (f32 scale)
Definition at line 16 of file code_6e40_len_500.c.
Referenced by begin_state_intro(), and func_802405EC_E1EA4C().
set_curtain_fade()
void set_curtain_fade (f32 scale)
Definition at line 33 of file code_6e40_len_500.c.
Referenced by func_802405EC_E1EA4C().
fx_walk_normal()
void fx_walk_normal (s32 arg0, f32 arg1, f32 arg2, f32 arg3, s32 arg4, s32 arg5)
Definition at line 19 of file code_4ac90_len_3910.c.
Referenced by func_80240720_9AEE20().
fx_emote()
void fx_emote (s32 arg0, Npc * arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, s32 arg7, s32 * arg8)
Definition at line 38 of file code_4ac90_len_3910.c.
Referenced by func_80045900(), UnkNpcAIFunc11(), and UnkNpcAIFunc8().
func_800E0088()
f32 func_800E0088 (f32 x, f32 z)
Definition at line 117 of file code_77480.c.
Referenced by func_802401B0_8C8140(), and func_802E8BC0().
func_800E06C0()
void func_800E06C0 (s32 arg0)
Definition at line 247 of file code_77480.c.
func_800E97B8()
void func_800E97B8 (void)
Definition at line 543 of file code_80850_len_3060.c.
Referenced by DisablePlayerInput(), func_80280B44(), initialize_status_menu(), and ShowStatusMenu().
func_800EB168()
s32 func_800EB168 (s32 arg0)
Definition at line 32 of file code_838b0_len_5900.c.
Referenced by Call800EB168(), func_80240000_8C7F90(), func_80245440_805CC0(), and GetPartnerCall800EB168().
create_shadow_type()
Shadow* create_shadow_type (s32 type, f32 x, f32 y, f32 z)
Definition at line 150 of file code_a5dd0_len_114e0.c.
Referenced by create_part_shadow(), create_part_shadow_by_ref(), and func_800DFC74().
get_player_data()
PlayerData* get_player_data (void)
Definition at line 98 of file code_80850_len_3060.c.
Referenced by func_8024002C_8CA92C().
pause_interp_vertical_scroll()
s32 pause_interp_vertical_scroll (s32 deltaBefore)
Definition at line 93 of file code_135EE0.c.
Referenced by pause_badges_update().
pause_draw_rect()
void pause_draw_rect (s32 ulx, s32 uly, s32 lrx, s32 lry, s32 tileDescriptor, s32 uls, s32 ult, s32 dsdx, s32 dtdy)
Definition at line 153 of file code_135EE0.c.
func_800DCB7C()
s32 func_800DCB7C (s32 arg0, f32 * arg1, f32 * arg2, f32 * arg3, f32 * arg4)
Definition at line 7 of file code_759b0_len_61b0.c.
Referenced by func_80045900().
func_800DDC44()
s32 func_800DDC44 (s32 arg0, f32 * arg1, f32 * arg2, f32 * arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7)
Definition at line 31 of file code_759b0_len_61b0.c.
Referenced by UnkNpcAIFunc12().
get_npc_by_index()
Npc* get_npc_by_index (s32 listIndex)
Definition at line 33 of file code_13870_len_6980.c.
Referenced by func_800E636C().
func_800EBA3C()
void func_800EBA3C (Npc * partner)
Definition at line 64 of file code_838b0_len_5900.c.
Referenced by GoombariaUpdate().
func_800EBB40()
void func_800EBB40 (Npc * partner)
Definition at line 66 of file code_838b0_len_5900.c.
Referenced by GoombariaUpdate().
enable_partner_ai()
void enable_partner_ai (void)
Definition at line 90 of file code_838b0_len_5900.c.
Referenced by EnablePartnerAI(), and func_80283908().
enable_partner_walking()
void enable_partner_walking (Npc * partner, s32 val)
Definition at line 62 of file code_838b0_len_5900.c.
Referenced by GoombariaUpdate().
enable_partner_flying()
void enable_partner_flying (Npc * partner, s32 val)
Definition at line 70 of file code_838b0_len_5900.c.
Referenced by TwinkUpdate().
update_player_move_history()
void update_player_move_history (Npc * partner)
Definition at line 72 of file code_838b0_len_5900.c.
Referenced by TwinkUpdate().
is_current_partner_flying()
s32 is_current_partner_flying (void)
Definition at line 22 of file code_838b0_len_5900.c.
Referenced by PartnerIsFlying(), and TeleportPartnerToPlayer().
func_800ED5D0()
void func_800ED5D0 (Npc * partner)
Definition at line 74 of file code_838b0_len_5900.c.
Referenced by TwinkUpdate().
clear_partner_move_history()
void clear_partner_move_history (Npc * partner)
Definition at line 106 of file code_838b0_len_5900.c.
Referenced by ClearPartnerMoveHistory(), func_80240000_8C7F90(), TeleportPartnerToPlayer(), and world_goombario_pre_battle().
func_800EF394()
s32 func_800EF394 (f32 arg0)
Definition at line 92 of file code_838b0_len_5900.c.
Referenced by func_80245504_805D84(), func_80281C20(), and func_80283B88().
does_script_exist()
s32 does_script_exist (s32 id)
Definition at line 520 of file code_e79b0_len_1920.c.
Referenced by _bound_script_trigger_handler(), AwaitScriptComplete(), func_8004309C(), si_handle_does_script_exist(), and si_standard_trigger_executor().
does_script_exist_by_ref()
s32 does_script_exist_by_ref (ScriptInstance * script)
Definition at line 533 of file code_e79b0_len_1920.c.
Referenced by DispatchDamageEvent(), func_80252B3C(), ItemAfflictEnemy(), and ItemDamageEnemy().
start_script()
ScriptInstance* start_script (Bytecode * initialLine, s32 priority, s32 initialState)
Definition at line 161 of file code_e79b0_len_1920.c.
Referenced by _bound_script_trigger_handler(), BindIdle(), dispatch_event_actor(), DoNpcDefeat(), RestartNpcAI(), RestartNpcAux(), si_standard_trigger_executor(), and Spawn802D9D50().
start_script_in_group()
ScriptInstance* start_script_in_group (Bytecode * initialLine, u8 priority, u8 initialState, u8 groupFlags)
Definition at line 230 of file code_e79b0_len_1920.c.
Referenced by exec_ShakeCam1(), exec_ShakeCamX(), si_handle_spawn_script(), and si_handle_spawn_script_get_id().
set_animation_rate()
void set_animation_rate (ActorID actorID, s32 partIndex, f32 rate)
Definition at line 47 of file code_190B20.c.
Referenced by SetAnimationRate().
func_8011B7C0()
void func_8011B7C0 (u16 arg0, s32 arg1, s32 arg2)
Definition at line 260 of file code_a5dd0_len_114e0.c.
Referenced by SetGroupEnabled().
get_anim_mesh()
AnimatedMesh* get_anim_mesh (s32 arg0)
Definition at line 59 of file code_B4580.c.
Referenced by func_802CD348(), func_802CD3C0(), func_802CD418(), and func_802E46BC().
func_80137D88()
void func_80137D88 (s32 arg0, f32 arg1)
Definition at line 5 of file code_cd180_len_38f0.c.
Referenced by func_8004304C(), func_802D4D14(), func_802D4D88(), init_demo_data(), and intro_logos_update_fade().
func_80137DA4()
void func_80137DA4 (s32 arg0, f32 arg1)
Definition at line 7 of file code_cd180_len_38f0.c.
Referenced by begin_state_intro(), func_802405EC_E1EA4C(), func_802D4BDC(), func_802D4C4C(), func_802D4CC4(), func_802D7BA4(), and UnkFunc1().
func_80137DC0()
void func_80137DC0 (s32 arg0, f32 * arg1, f32 * arg2)
Definition at line 9 of file code_cd180_len_38f0.c.
Referenced by func_802537C0(), and func_802D7BA4().
func_80137E10()
s32 func_80137E10 (s32 arg0, u8 arg1, u8 arg2, u8 arg3)
Definition at line 11 of file code_cd180_len_38f0.c.
Referenced by begin_state_intro(), func_8004304C(), func_802405EC_E1EA4C(), and intro_logos_update_fade().
func_80137E4C()
void func_80137E4C (s32 arg0, s32 arg1, s32 arg2, s32 arg3)
Definition at line 13 of file code_cd180_len_38f0.c.
Referenced by func_802D4D14(), and func_802D7BA4().
rand_int()
s32 rand_int (s32 arg0)
Definition at line 232 of file code_42e0_len_1f60.c.
Referenced by func_80260DD8(), get_coin_drop_amount(), OnFleeBattleDrops(), RandInt(), and UnkNpcAIFunc1().
sort_items()
void sort_items (void)
Definition at line 172 of file code_80850_len_3060.c.
Referenced by add_item(), remove_consumable(), RemoveItem(), and RemoveItemAt().
is_ability_active()
s32 is_ability_active (s32 arg0)
Referenced by enforce_hpfp_limits(), func_802A1000_7345A0(), func_802A1050_7345F0(), get_coin_drop_amount(), heroes_is_ability_active(), is_actor_hp_bar_visible(), is_actortype_hpbar_visible(), and update_locomotion_state().
update_lerp()
f32 update_lerp (Easing easing, f32 start, f32 end, s32 elapsed, s32 duration)
Definition at line 349 of file code_42e0_len_1f60.c.
Referenced by UpdateLerp().
make_item_entity()
s32 make_item_entity (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 facingAngleSign, s32 pickupVar)
Definition at line 43 of file code_C50A0.c.
Referenced by func_802E88EC(), make_item_entity_delayed(), and make_item_entity_nodelay().
make_item_entity_delayed()
s32 make_item_entity_delayed (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 pickupVar)
Definition at line 49 of file code_C50A0.c.
Referenced by OnFleeBattleDrops().
set_item_entity_position()
void set_item_entity_position (s32 itemEntityIndex, f32 x, f32 y, f32 z)
Definition at line 109 of file code_C50A0.c.
Referenced by Bandit_DropCoin().
get_item_entity()
ItemEntity* get_item_entity (s32 itemEntityIndex)
Definition at line 26 of file code_C50A0.c.
Referenced by func_802D721C(), func_802E3650(), SetItemFlags(), SetItemPos(), ShowGotItem(), and SomeItemEntityFunc().
make_item_entity_nodelay()
s32 make_item_entity_nodelay (s32 itemID, f32 x, f32 y, f32 z, ItemSpawnMode itemSpawnMode, s32 pickupVar)
Definition at line 45 of file code_C50A0.c.
Referenced by DropItemEntity(), DropItemEntityB(), func_802E38D8(), and MakeItemEntity().
set_item_entity_flags()
void set_item_entity_flags (s32 itemEntityIndex, s32 flag)
Definition at line 77 of file code_C50A0.c.
Referenced by DropItemEntityB(), func_80240000_800880(), and func_80240044_8008C4().
set_cam_viewport()
void set_cam_viewport (s16 id, s16 x, s16 y, s16 width, s16 height)
Definition at line 15 of file code_8560.c.
Referenced by SetCamViewport().
disable_player_shadow()
void disable_player_shadow (void)
Definition at line 127 of file code_77480.c.
Referenced by HidePlayerShadow(), and player_enter_blue_pipe().
move_player()
void move_player (s32 duration, f32 heading, f32 speed)
Definition at line 17 of file code_7bb60_len_41b0.c.
get_npc_safe()
Npc* get_npc_safe (NpcId npcId)
Definition at line 66 of file code_13870_len_6980.c.
Referenced by AwaitPlayerNearNpc(), func_80240000_8C7F90(), func_80240814_97BE44(), func_802408B4_97BEE4(), GetNpcCollisionHeight(), GetNpcPointer(), play_sound_at_npc(), resolve_npc(), SetPartnerFlags20000(), SetPartnerFlags80000(), and SetPartnerFlagsA0000().
get_npc_unsafe()
Npc* get_npc_unsafe (NpcId npcId)
Definition at line 64 of file code_13870_len_6980.c.
Referenced by Bandit_DropCoin(), CheckPartnerFlags1000(), DeleteNpc(), DoNpcDefeat(), func_8003F018(), func_8003F084(), func_80045580(), func_80045900(), func_800E6860(), func_80240060_BFA100(), func_802401B0_8C8140(), func_80240530_8AC4C0(), func_80240A70_9B2200(), func_80240BD8_8ACB68(), func_80283908(), get_npc_pos(), GetNpcUnsafeOwner2(), GetPartnerPos(), NpcJumpFunc(), NpcJumpFunc2(), NpcJumpFunc3(), OnDefeatEnemy(), set_script_owner_npc_anim(), set_script_owner_npc_col_height(), SetSelfRotation(), TeleportPartnerToPlayer(), UnkDurationCheck(), UnkMovePartner(), UnkNpcAIFunc1(), UnkNpcAIFunc10(), UnkNpcAIFunc11(), UnkNpcAIFunc12(), UnkNpcAIFunc2(), UnkNpcAIFunc3(), UnkNpcAIFunc4(), UnkNpcAIFunc5(), UnkNpcAIFunc6(), UnkNpcAIFunc7(), UnkNpcAIFunc8(), UnkNpcAIFunc9(), UnkNpcDurationFlagFunc(), UnkRotatePartner(), UnkSetDurationFunc(), and UnkYawFunc().
resolve_npc()
Npc* resolve_npc (ScriptInstance * script, NpcId npcIdOrPtr)
Definition at line 4 of file code_f2470_len_27f0.c.
Referenced by ClearPartnerMoveHistory(), EnableNpcBlur(), EnableNpcShadow(), func_80045838(), func_802CDE68(), func_802CF1B4(), func_802CF208(), func_802CFD30(), func_802CFE2C(), func_802CFE80(), func_802CFEEC(), func_802CFFC0(), func_802D0244(), GetAngleBetweenNPCs(), GetAngleToNPC(), GetAngleToPlayer(), GetNpcAnimation(), GetNpcPos(), GetNpcYaw(), NpcSetHomePosToCurrent(), PlaySoundAtNpc(), SetNpcAnimation(), SetNpcAnimationSpeed(), SetNpcCollisionSize(), SetNpcEffect(), SetNpcFlagBits(), SetNpcJumpscale(), SetNpcPos(), SetNpcRotation(), SetNpcScale(), SetNpcSpeed(), and SetNpcYaw().
set_npc_yaw()
void set_npc_yaw (Npc * npcPtr, f32 angle)
Definition at line 111 of file code_13870_len_6980.c.
Referenced by func_80240000_8C7F90(), SetNpcYaw(), TeleportPartnerToPlayer(), and UnkNpcAIFunc4().
npc_move_heading()
void npc_move_heading (Npc * npc, f32 speed, f32 yaw)
Definition at line 55 of file code_13870_len_6980.c.
Referenced by UnkNpcAIFunc11(), and UnkNpcAIFunc12().
disable_npc_blur()
void disable_npc_blur (Npc * npc)
Definition at line 76 of file code_13870_len_6980.c.
Referenced by EnableNpcBlur(), and world_goombario_pre_battle().
dist2D()
f32 dist2D (f32 ax, f32 ay, f32 bx, f32 by)
Definition at line 284 of file code_42e0_len_1f60.c.
Referenced by AwaitPlayerApproach(), AwaitPlayerLeave(), AwaitPlayerNearNpc(), func_800E0088(), get_dpad_input_radial(), GetDist2D(), is_point_within_region(), IsPlayerWithin(), PlayerMoveTo(), and UnkMusicFunc().
dist3D()
f32 dist3D (f32 ax, f32 ay, f32 az, f32 bx, f32 by, f32 bz)
Definition at line 291 of file code_42e0_len_1f60.c.
add_vec2D_polar()
void add_vec2D_polar (f32 * x, f32 * y, f32 r, f32 theta)
Definition at line 299 of file code_42e0_len_1f60.c.
Referenced by AddVectorPolar(), func_80283908(), SomeXYZFunc2(), and UnkYawFunc().
func_801499EC()
s32 func_801499EC (s32 soundID, s32 arg1, f32 arg2, f32 arg3, f32 arg4)
Definition at line 28 of file code_DF950.c.
Referenced by func_80240060_BFA100().
play_sound_at_position()
s32 play_sound_at_position (s32 soundID, s32 value2, f32 posX, f32 posY, f32 posZ)
Definition at line 57 of file code_DF950.c.
Referenced by calc_item_check_hit(), func_80240BD8_8ACB68(), func_802D7520(), func_802D75D8(), func_802E2EB0(), func_802E3BA4(), play_sound_at_npc(), play_sound_at_player(), PlayLoopingSoundAtActor(), PlaySoundAt(), PlaySoundAtActor(), PlaySoundAtCollider(), PlaySoundAtF(), PlaySoundAtModel(), PlaySoundAtNpc(), and PlaySoundAtPart().
set_music_track()
s32 set_music_track (s32 playerIndex, s32 songID, s32 variation, s32 fadeOutTime, s16 volume)
Definition at line 93 of file code_e0b30_len_b80.c.
Referenced by FadeOutMusic(), func_8014AC08(), func_8014ADF8(), func_8014AEF8(), and SetMusicTrack().
func_8014AA54()
s32 func_8014AA54 (s32 playerIndex, s32 arg1, s16 arg2)
Definition at line 135 of file code_e0b30_len_b80.c.
Referenced by func_802D5F28(), and UnkMusicFunc().
player_create_target_list()
void player_create_target_list (Actor * actor)
Definition at line 5 of file code_190B20.c.
Referenced by count_targets(), func_80218644_6DE404(), func_802186E0_6DE4A0(), func_80218770_6DE530(), func_802187F0_6DE5B0(), and PlayerCreateTargetList().
enemy_create_target_list()
void enemy_create_target_list (Actor * actor)
Definition at line 9 of file code_190B20.c.
Referenced by EnemyCreateTargetList().
set_actor_yaw()
void set_actor_yaw (ActorID actorID, s32 yaw)
Definition at line 49 of file code_190B20.c.
Referenced by SetActorYaw().
set_part_yaw()
void set_part_yaw (ActorID actorID, s32 partIndex, s32 value)
Definition at line 53 of file code_190B20.c.
Referenced by SetPartYaw().
add_part_decoration()
void add_part_decoration (ActorPart * part, s32 decorationIndex, DecorationId decorationType)
Definition at line 279 of file code_190B20.c.
Referenced by add_actor_decoration().
add_actor_decoration()
void add_actor_decoration (Actor * actor, s32 decorationIndex, DecorationId decorationType)
Definition at line 291 of file code_190B20.c.
remove_part_decoration()
void remove_part_decoration (ActorPart * part, s32 decorationIndex)
Definition at line 300 of file code_190B20.c.
Referenced by remove_actor_decoration().
remove_actor_decoration()
void remove_actor_decoration (Actor * actor, s32 decorationIndex)
Definition at line 304 of file code_190B20.c.
Referenced by delete_player_actor().
heroes_is_ability_active()
s32 heroes_is_ability_active (Actor * actor, Ability ability)
Definition at line 313 of file code_190B20.c.
create_part_shadow()
void create_part_shadow (ActorID actorID, s32 partIndex)
Definition at line 331 of file code_190B20.c.
remove_part_shadow()
void remove_part_shadow (ActorID actorID, s32 partIndex)
Definition at line 339 of file code_190B20.c.
create_part_shadow_by_ref()
void create_part_shadow_by_ref (s32 arg0, ActorPart * part)
Definition at line 346 of file code_190B20.c.
get_script_by_index()
ScriptInstance* get_script_by_index (s32 index)
Definition at line 727 of file code_e79b0_len_1920.c.
Referenced by dispatch_event_actor(), and func_802C73B8().
suspend_all_group()
void suspend_all_group (s32 groupFlags)
Definition at line 679 of file code_e79b0_len_1920.c.
Referenced by func_802C3390(), and si_handle_suspend_all().
kill_script()
void kill_script (ScriptInstance * instanceToKill)
Definition at line 444 of file code_e79b0_len_1920.c.
Referenced by DoNpcDefeat(), func_802C3C10(), kill_all_scripts(), kill_script_by_ID(), si_handle_end_parallel_thread(), si_handle_end_spawn_thread(), and si_handle_return().
exec_entity_updatecmd()
void exec_entity_updatecmd (Entity * entity)
Definition at line 11 of file code_a5dd0_len_114e0.c.
Referenced by func_80240444_8CAD44(), func_802E1204(), func_802E1270(), func_802E1328(), func_802E1350(), func_802E1400(), func_802E1460(), func_802E14D8(), func_802E1614(), func_802E1660(), func_802E1740(), func_802E17A8(), func_802E1EDC(), func_802E3728(), func_802E37E4(), func_802E3A48(), func_802E3BA4(), func_802E4154(), func_802E54CC(), func_802E555C(), func_802E8858(), func_802E89B0(), func_802E89F8(), func_802E8A58(), func_802E8ADC(), func_802E8C94(), and func_802E8D74().
func_802D7460()
void func_802D7460 (f32 x, f32 y, f32 z, s32 arg3)
Definition at line 3 of file code_FBE10.c.
Referenced by func_802D7520(), and UnkBattleFunc2().
func_802D74C0()
void func_802D74C0 (f32 x, f32 y, f32 z, s32 arg3)
Definition at line 5 of file code_FBE10.c.
Referenced by func_802D75D8(), and UnkBattleFunc2_2().