include/map.h File Reference - Paper Mario Documentation
map.h File Reference
Data Structures
struct MapConfig
Fields other than main, entryList, entryCount, background, and tattle are initialised when the map loads.
struct Map
struct Area
struct NpcAISettings
struct NpcSettings
struct ItemDrop
struct StatDrop
Describes heart/flower drop chances after defeating an Npc in the overworld.
struct StaticNpc
struct Enemy
struct NpcGroupList
Zero-terminated.
Macros
#define ENTRY_COUNT(entryList) (sizeof(entryList) / sizeof(Vec4f))
#define MAP_ID_MAX_LEN 7
"xxx_yyy" excluding null terminator.
#define NO_DROPS { F16(100), F16(0), 0, F16(0) }
#define STANDARD_HEART_DROPS(attempts)
#define GENEROUS_HEART_DROPS(attempts)
#define GENEROUS_WHEN_LOW_HEART_DROPS(attempts)
#define STANDARD_FLOWER_DROPS(attempts)
#define GENEROUS_WHEN_LOW_FLOWER_DROPS(attempts)
#define REDUCED_FLOWER_DROPS(attempts)
#define OVERRIDE_MOVEMENT_SPEED(speed) (speed * 32767)
#define NO_OVERRIDE_MOVEMENT_SPEED OVERRIDE_MOVEMENT_SPEED(-1)
#define NPC_GROUP(npcs, battle) { sizeof(npcs) / sizeof(StaticNpc), &npcs, battle }
Typedefs
typedef Vec4f EntryList[0]
typedef s32(* MapInit) (void)
Functions
Enemy * get_enemy (NpcId npcId)
MapConfig * get_current_map_header (void)
s32 func_800490B4 (s32 arg0, Enemy *arg1, f32 arg2, s32 arg3, s32 arg4)
Variables
Area gAreas [29]
Zero-terminated.
SongID gSongsUsingVariationFlag [6]
s16 D_8014F738
Macro Definition Documentation
ENTRY_COUNT
#define ENTRY_COUNT (entryList) (sizeof(entryList) / sizeof(Vec4f))
Definition at line 10 of file map.h.
MAP_ID_MAX_LEN
#define MAP_ID_MAX_LEN 7
"xxx_yyy" excluding null terminator.
Definition at line 36 of file map.h.
NO_DROPS
#define NO_DROPS { F16(100), F16(0), 0, F16(0) }
Definition at line 115 of file map.h.
STANDARD_HEART_DROPS
#define STANDARD_HEART_DROPS (attempts)
Definition at line 117 of file map.h.
GENEROUS_HEART_DROPS
#define GENEROUS_HEART_DROPS (attempts)
Definition at line 125 of file map.h.
GENEROUS_WHEN_LOW_HEART_DROPS
#define GENEROUS_WHEN_LOW_HEART_DROPS (attempts)
Definition at line 133 of file map.h.
STANDARD_FLOWER_DROPS
#define STANDARD_FLOWER_DROPS (attempts)
Definition at line 141 of file map.h.
GENEROUS_WHEN_LOW_FLOWER_DROPS
#define GENEROUS_WHEN_LOW_FLOWER_DROPS (attempts)
Definition at line 149 of file map.h.
REDUCED_FLOWER_DROPS
#define REDUCED_FLOWER_DROPS (attempts)
Definition at line 157 of file map.h.
OVERRIDE_MOVEMENT_SPEED
#define OVERRIDE_MOVEMENT_SPEED (speed) (speed * 32767)
Definition at line 165 of file map.h.
NO_OVERRIDE_MOVEMENT_SPEED
#define NO_OVERRIDE_MOVEMENT_SPEED OVERRIDE_MOVEMENT_SPEED(-1)
Definition at line 166 of file map.h.
NPC_GROUP
#define NPC_GROUP (npcs, battle) { sizeof(npcs) / sizeof(StaticNpc), &npcs, battle }
Definition at line 245 of file map.h.
Typedef Documentation
EntryList
typedef Vec4f EntryList[0]
Definition at line 12 of file map.h.
MapInit
typedef s32(* MapInit) (void)
Definition at line 34 of file map.h.
Function Documentation
get_enemy()
Enemy* get_enemy (NpcId npcId)
Definition at line 253 of file code_13870_len_6980.c.
Referenced by BindNpcAux(), BindNpcDefeat(), BindNpcHit(), BindNpcIdle(), BindNpcInteract(), EnableNpcAI(), EnableNpcAux(), func_80240060_BFA100(), GetNpcVar(), RestartNpcAI(), RestartNpcAux(), set_npc_animation(), SetEnemyFlagBits(), SetNpcVar(), SetTattleString(), and UnkNpcAIFunc9().
get_current_map_header()
MapConfig* get_current_map_header (void)
Definition at line 29 of file world.c.
func_800490B4()
s32 func_800490B4 (s32 arg0, Enemy * arg1, f32 arg2, s32 arg3, s32 arg4)
Definition at line 187 of file code_20ec0_len_5040.c.
Referenced by UnkNpcAIFunc11().
Variable Documentation
gAreas
Area gAreas[29]
Zero-terminated.
Definition at line 253 of file map.h.
gSongsUsingVariationFlag
SongID gSongsUsingVariationFlag[6] extern
Lists the songs that are forced to use the variation determined by map.songVariation & 1.
See also
get_song_variation_override_for_cur_map
Referenced by get_song_variation_override_for_cur_map().
D_8014F738
s16 D_8014F738 extern