src/os/nusys/nuSched.c File Reference - Paper Mario Documentation
nuSched.c File Reference
Functions
void nuScEventHandler (void)
void nuScExecuteAudio (void)
void nuScExecuteGraphics (void)
void nuScCreateScheduler (u8 videoMode, u8 numFields)
void nuScAddClient (NUScClient *c, OSMesgQueue *mq, NUScMsg msgType)
void nuScRemoveClient (NUScClient *client)
void nuScResetClientMesgType (NUScClient *client, NUScMsg msgType)
OSMesgQueue * nuScGetGfxMQ (void)
OSMesgQueue * nuScGetAudioMQ (void)
void nuScSetFrameBufferNum (u8 frameBufferNum)
s32 nuScGetFrameRate (void)
void nuScEventBroadcast (NUScMsg *msg)
void nuScWaitTaskReady ()
Variables
u8 D_8009A5B0
u64 nuScStack [NU_SC_STACK_SIZE/sizeof(u64)]
u64 nuScAudioStack [NU_SC_STACK_SIZE/sizeof(u64)]
u64 nuScGraphicsStack [NU_SC_STACK_SIZE/sizeof(u64)]
Function Documentation
nuScEventHandler()
void nuScEventHandler (void)
Definition at line 149 of file nuSched.c.
Referenced by nuScCreateScheduler().
nuScExecuteAudio()
void nuScExecuteAudio (void)
Definition at line 62 of file nuSched.c.
Referenced by nuScCreateScheduler().
nuScExecuteGraphics()
void nuScExecuteGraphics (void)
Definition at line 64 of file nuSched.c.
Referenced by nuScCreateScheduler().
nuScCreateScheduler()
void nuScCreateScheduler (u8 videoMode, u8 numFields)
Definition at line 14 of file nuSched.c.
Referenced by boot_idle().
nuScAddClient()
void nuScAddClient (NUScClient * c, OSMesgQueue * mq, NUScMsg msgType)
Definition at line 66 of file nuSched.c.
nuScRemoveClient()
void nuScRemoveClient (NUScClient * client)
Definition at line 84 of file nuSched.c.
nuScResetClientMesgType()
void nuScResetClientMesgType (NUScClient * client, NUScMsg msgType)
Definition at line 105 of file nuSched.c.
nuScGetGfxMQ()
OSMesgQueue* nuScGetGfxMQ (void)
Definition at line 115 of file nuSched.c.
nuScGetAudioMQ()
OSMesgQueue* nuScGetAudioMQ (void)
Definition at line 124 of file nuSched.c.
nuScSetFrameBufferNum()
void nuScSetFrameBufferNum (u8 frameBufferNum)
Definition at line 133 of file nuSched.c.
nuScGetFrameRate()
s32 nuScGetFrameRate (void)
Definition at line 142 of file nuSched.c.
nuScEventBroadcast()
void nuScEventBroadcast (NUScMsg * msg)
Definition at line 151 of file nuSched.c.
nuScWaitTaskReady()
void nuScWaitTaskReady ()
Definition at line 162 of file nuSched.c.
Variable Documentation
D_8009A5B0
u8 D_8009A5B0 extern
Referenced by nuScAddClient(), and nuScCreateScheduler().
nuScStack
u64 nuScStack[NU_SC_STACK_SIZE/sizeof(u64)] extern
Referenced by nuScCreateScheduler().
nuScAudioStack
u64 nuScAudioStack[NU_SC_STACK_SIZE/sizeof(u64)] extern
Referenced by nuScCreateScheduler().
nuScGraphicsStack
u64 nuScGraphicsStack[NU_SC_STACK_SIZE/sizeof(u64)] extern
Referenced by nuScCreateScheduler().