src/os/nusys/nuSiMgr.c File Reference - Paper Mario Documentation
nuSiMgr.c File Reference
Functions
u8 nuSiMgrInit ()
s32 nuSiSendMesg (NUScMsg mesg, void *dataPtr)
void nuSiMgrStop (void)
void nuSiMgrRestart ()
s32 nuSiMgrThread ()
Function Documentation
nuSiMgrInit()
u8 nuSiMgrInit ()
Definition at line 4 of file nuSiMgr.c.
Referenced by nuContInit().
nuSiSendMesg()
s32 nuSiSendMesg (NUScMsg mesg, void * dataPtr)
Definition at line 6 of file nuSiMgr.c.
Referenced by nuContRmbCheck(), nuContRmbStart(), and nuSiMgrStop().
nuSiMgrStop()
void nuSiMgrStop (void)
Definition at line 8 of file nuSiMgr.c.
nuSiMgrRestart()
void nuSiMgrRestart ()
Definition at line 12 of file nuSiMgr.c.
nuSiMgrThread()
s32 nuSiMgrThread ()
Definition at line 14 of file nuSiMgr.c.