src/os/osCreateThread.c File Reference - Paper Mario Documentation
osCreateThread.c File Reference
Functions
void osCreateThread (OSThread *thread, OSId id, void(*entrypoint)(void *), void *unk1, void *unk2, OSPri pri)
Function Documentation
osCreateThread()
void osCreateThread (OSThread * thread, OSId id, void(*)(void *) entrypoint, void * unk1, void * unk2, OSPri pri)
Definition at line 5 of file osCreateThread.c.
Referenced by boot_idle(), nuBoot(), and nuScCreateScheduler().