include/script_api/common.h File Reference - Paper Mario Documentation
common.h File Reference
Typedefs
typedef Bytecode Script[0]
Functions
ApiStatus FadeBackgroundToBlack (ScriptInstance *script, s32 isInitialCall)
ApiStatus UnfadeBackgroundFromBlack (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCamLookAtObjVector (ScriptInstance *script, s32 isInitialCall)
ApiStatus HasMerleeCasts (ScriptInstance *script, s32 isInitialCall)
ApiStatus OnDefeatEnemy (ScriptInstance *script, s32 isInitialCall)
ApiStatus OnFleeBattleDrops (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetEncounterStatusFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus LoadDemoBattle (ScriptInstance *script, s32 isInitialCall)
ApiStatus RemoveNpc (ScriptInstance *script, s32 isInitialCall)
ApiStatus RemoveEncounter (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetBattleOutcome (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetOwnerEncounterTrigger (ScriptInstance *script, s32 isInitialCall)
ApiStatus DoNpcDefeat (ScriptInstance *script, s32 isInitialCall)
ApiStatus StartBattle (ScriptInstance *script, s32 isInitialCall)
ApiStatus StartBattleWith (ScriptInstance *script, s32 isInitialCall)
ApiStatus StartBossBattle (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetBattleMusic (ScriptInstance *script, s32 isInitialCall)
ApiStatus BindNpcAI (ScriptInstance *script, s32 isInitialCall)
ApiStatus BindNpcIdle (ScriptInstance *script, s32 isInitialCall)
ApiStatus RestartNpcAI (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableNpcAI (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcAux (ScriptInstance *script, s32 isInitialCall)
ApiStatus BindNpcAux (ScriptInstance *script, s32 isInitialCall)
ApiStatus RestartNpcAux (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableNpcAux (ScriptInstance *script, s32 isInitialCall)
ApiStatus BindNpcInteract (ScriptInstance *script, s32 isInitialCall)
ApiStatus BindNpcHit (ScriptInstance *script, s32 isInitialCall)
ApiStatus BindNpcDefeat (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetSelfVar (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetSelfVar (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcVar (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetNpcVar (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetSelfRotation (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetSelfEnemyFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetSelfEnemyFlagBits (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetSelfNpcID (ScriptInstance *script, s32 isInitialCall)
ApiStatus ClearDefeatedEnemies (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetEnemyFlagBits (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetSelfAnimationFromTable (ScriptInstance *script, s32 isInitialCall)
ApiStatus ShowCoinCounter (ScriptInstance *script, s32 isInitialCall)
ApiStatus MakeEntity (ScriptInstance *script, s32 isInitialCall)
ApiStatus AssignScript (ScriptInstance *script, s32 isInitialCall)
ApiStatus AssignAreaFlag (ScriptInstance *script, s32 isInitialCall)
ApiStatus AssignFlag (ScriptInstance *script, s32 isInitialCall)
ApiStatus AssignBlockFlag (ScriptInstance *script, s32 isInitialCall)
ApiStatus AssignPanelFlag (ScriptInstance *script, s32 isInitialCall)
ApiStatus AssignCrateFlag (ScriptInstance *script, s32 isInitialCall)
ApiStatus DeleteTrigger (ScriptInstance *script, s32 isInitialCall)
ApiStatus TranslateModel (ScriptInstance *script, s32 isInitialCall)
ApiStatus RotateModel (ScriptInstance *script, s32 isInitialCall)
ApiStatus ScaleModel (ScriptInstance *script, s32 isInitialCall)
ApiStatus CloneModel (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetModelIndex (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetModelCenter (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetTexPanner (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetModelFlag10 (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableTexPanning (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableModel (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetGroupEnabled (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetTexPanOffset (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetModelFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus TranslateGroup (ScriptInstance *script, s32 isInitialCall)
ApiStatus RotateGroup (ScriptInstance *script, s32 isInitialCall)
ApiStatus ScaleGroup (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableGroup (ScriptInstance *script, s32 isInitialCall)
ApiStatus ModifyColliderFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetColliderCenter (ScriptInstance *script, s32 isInitialCall)
ApiStatus ParentColliderToModel (ScriptInstance *script, s32 isInitialCall)
ApiStatus UpdateColliderTransform (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetZoneEnabled (ScriptInstance *script, s32 isInitialCall)
ApiStatus GotoMap (ScriptInstance *script, s32 isInitialCall)
ApiStatus GotoMapSpecial (ScriptInstance *script, s32 isInitialCall)
ApiStatus GotoMapByID (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetEntryID (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetMapID (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetLoadType (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetRenderMode (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlaySoundAtModel (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlaySoundAtCollider (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamEnabled (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamFlag80 (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamPerspective (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamViewport (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamBGColor (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamTarget (ScriptInstance *script, s32 isInitialCall)
ApiStatus ShakeCam (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamLeadPlayer (ScriptInstance *script, s32 isInitialCall)
ApiStatus PanToTarget (ScriptInstance *script, s32 isInitialCall)
ApiStatus UseSettingsFrom (ScriptInstance *script, s32 isInitialCall)
ApiStatus LoadSettings (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamType (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamPitch (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamDistance (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamPosA (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamPosB (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamPosC (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPanTarget (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamSpeed (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCamType (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCamPitch (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCamDistance (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCamPosA (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCamPosB (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCamPosC (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCamPosition (ScriptInstance *script, s32 isInitialCall)
ApiStatus WaitForCam (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetCamProperties (ScriptInstance *script, s32 isInitialCall)
ApiStatus AdjustCam (ScriptInstance *script, s32 isInitialCall)
ApiStatus ResetCam (ScriptInstance *script, s32 isInitialCall)
ApiStatus LoadModelAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlayModelAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus ChangeModelAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus DeleteNpc (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetNpcPointer (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcRotation (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcScale (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcCollisionSize (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcSpeed (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcJumpscale (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetNpcAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus NpcMoveTo (ScriptInstance *script, s32 isInitialCall)
ApiStatus NpcJump0 (ScriptInstance *script, s32 isInitialCall)
ApiStatus NpcJump1 (ScriptInstance *script, s32 isInitialCall)
ApiStatus NpcFlyTo (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetNpcYaw (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcYaw (ScriptInstance *script, s32 isInitialCall)
ApiStatus InterpNpcYaw (ScriptInstance *script, s32 isInitialCall)
ApiStatus NpcFacePlayer (ScriptInstance *script, s32 isInitialCall)
ApiStatus NpcFaceNpc (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcFlagBits (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetNpcPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableNpcShadow (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableNpcBlur (ScriptInstance *script, s32 isInitialCall)
ApiStatus ClearPartnerMoveHistory (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPartnerPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus DisablePartnerAI (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnablePartnerAI (ScriptInstance *script, s32 isInitialCall)
ApiStatus BringPartnerOut (ScriptInstance *script, s32 isInitialCall)
ApiStatus PutPartnerAway (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCurrentPartnerID (ScriptInstance *script, s32 isInitialCall)
ApiStatus IsCurrentPartnerFlying (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetNpcEffect (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlaySoundAtNpc (ScriptInstance *script, s32 isInitialCall)
ApiStatus SpeakToPlayer (ScriptInstance *script, s32 isInitialCall)
ApiStatus EndSpeech (ScriptInstance *script, s32 isInitialCall)
ApiStatus ContinueSpeech (ScriptInstance *script, s32 isInitialCall)
ApiStatus SpeakToNpc (ScriptInstance *script, s32 isInitialCall)
ApiStatus ShowMessageAtScreenPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus ShowMessageAtWorldPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus CloseMessage (ScriptInstance *script, s32 isInitialCall)
ApiStatus SwitchMessage (ScriptInstance *script, s32 isInitialCall)
ApiStatus ShowChoice (ScriptInstance *script, s32 isInitialCall)
ApiStatus CloseChoice (ScriptInstance *script, s32 isInitialCall)
ApiStatus CancelMessage (ScriptInstance *script, s32 isInitialCall)
ApiStatus CancelMessageAndBlock (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetMessageImages (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetMessageString (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetMessageValue (ScriptInstance *script, s32 isInitialCall)
ApiStatus HidePlayerShadow (ScriptInstance *script, s32 isInitialCall)
ApiStatus DisablePlayerPhysics (ScriptInstance *script, s32 isInitialCall)
ApiStatus DisablePlayerInput (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerCollisionSize (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerSpeed (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerJumpscale (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerActionState (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlayerMoveTo (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlayerJump (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlayerJump1 (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlayerJump2 (ScriptInstance *script, s32 isInitialCall)
ApiStatus InterpPlayerYaw (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlayerFaceNpc (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPlayerTargetYaw (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetPlayerFlagBits (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPlayerActionState (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPlayerPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetPlayerAnimation (ScriptInstance *script, s32 isInitialCall)
ApiStatus FullyRestoreHPandFP (ScriptInstance *script, s32 isInitialCall)
ApiStatus FullyRestoreSP (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnablePartner (ScriptInstance *script, s32 isInitialCall)
ApiStatus DisablePartner (ScriptInstance *script, s32 isInitialCall)
ApiStatus UseEntryHeading (ScriptInstance *script, s32 isInitialCall)
ApiStatus UseExitHeading (ScriptInstance *script, s32 isInitialCall)
ApiStatus DisablePulseStone (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetCurrentPartner (ScriptInstance *script, s32 isInitialCall)
ApiStatus Disable8bitMario (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlaySoundAtPlayer (ScriptInstance *script, s32 isInitialCall)
ApiStatus MakeLerp (ScriptInstance *script, s32 isInitialCall)
ApiStatus UpdateLerp (ScriptInstance *script, s32 isInitialCall)
ApiStatus RandInt (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetAngleBetweenNPCs (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetAngleToNPC (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetAngleToPlayer (ScriptInstance *script, s32 isInitialCall)
ApiStatus AwaitPlayerApproach (ScriptInstance *script, s32 isInitialCall)
ApiStatus IsPlayerWithin (ScriptInstance *script, s32 isInitialCall)
ApiStatus AwaitPlayerLeave (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddVectorPolar (ScriptInstance *script, s32 isInitialCall)
ApiStatus LoadPath (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetNextPathPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetDist2D (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetValueByRef (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetValueByRef (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableStatusMenu (ScriptInstance *script, s32 isInitialCall)
ApiStatus ShowStatusMenu (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetGameMode (ScriptInstance *script, s32 isInitialCall)
ApiStatus ClampAngleInt (ScriptInstance *script, s32 isInitialCall)
ApiStatus ClampAngleFloat (ScriptInstance *script, s32 isInitialCall)
ApiStatus FadeOutMusic (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetMusicTrack (ScriptInstance *script, s32 isInitialCall)
ApiStatus FadeInMusic (ScriptInstance *script, s32 isInitialCall)
ApiStatus ClearAmbientSounds (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlayAmbientSounds (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlaySound (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlaySoundAt (ScriptInstance *script, s32 isInitialCall)
ApiStatus StopSound (ScriptInstance *script, s32 isInitialCall)
ApiStatus UseDoorSounds (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlaySoundAtF (ScriptInstance *script, s32 isInitialCall)
ApiStatus RemoveKeyItemAt (ScriptInstance *script, s32 isInitialCall)
ApiStatus RemoveItemAt (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddKeyItem (ScriptInstance *script, s32 isInitialCall)
ApiStatus HasKeyItem (ScriptInstance *script, s32 isInitialCall)
ApiStatus FindKeyItem (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddItem (ScriptInstance *script, s32 isInitialCall)
ApiStatus FindItem (ScriptInstance *script, s32 isInitialCall)
ApiStatus RemoveItem (ScriptInstance *script, s32 isInitialCall)
ApiStatus CountFortessKeys (ScriptInstance *script, s32 isInitialCall)
ApiStatus RemoveFortressKeys (ScriptInstance *script, s32 isInitialCall)
ApiStatus MakeItemEntity (ScriptInstance *script, s32 isInitialCall)
ApiStatus DropItemEntity (ScriptInstance *script, s32 isInitialCall)
ApiStatus DropItemEntityB (ScriptInstance *script, s32 isInitialCall)
ApiStatus RemoveItemEntity (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddBadge (ScriptInstance *script, s32 isInitialCall)
ApiStatus RemoveBadge (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetItemPos (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetItemFlags (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddCoin (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddStarPoints (ScriptInstance *script, s32 isInitialCall)
ApiStatus AddStarPieces (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetItemPower (ScriptInstance *script, s32 isInitialCall)
ApiStatus ShowGotItem (ScriptInstance *script, s32 isInitialCall)
ApiStatus ShowEmote (ScriptInstance *script, s32 isInitialCall)
ApiStatus ShowSleepBubble (ScriptInstance *script, s32 isInitialCall)
ApiStatus RemoveEffect (ScriptInstance *script, s32 isInitialCall)
ApiStatus PlayEffect (ScriptInstance *script, s32 isInitialCall)
ApiStatus SetSpriteShading (ScriptInstance *script, s32 isInitialCall)
ApiStatus EnableSpriteShading (ScriptInstance *script, s32 isInitialCall)
ApiStatus GetDemoState (ScriptInstance *script, s32 isInitialCall)
ApiStatus DemoPressButton (ScriptInstance *script, s32 isInitialCall)
ApiStatus DemoReleaseButton (ScriptInstance *script, s32 isInitialCall)
ApiStatus DemoSetButtons (ScriptInstance *script, s32 isInitialCall)
ApiStatus DemoJoystickRadial (ScriptInstance *script, s32 isInitialCall)
ApiStatus DemoJoystickXY (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CFE2C (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802CFD30 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_800441F0 (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802D5830 (ScriptInstance *script, s32 isInitialCall)
Variables
Script EnemyNpcHit
Script EnemyNpcDefeat
Typedef Documentation
Script
typedef Bytecode Script[0]
Definition at line 7 of file common.h.
Function Documentation
FadeBackgroundToBlack()
ApiStatus FadeBackgroundToBlack (ScriptInstance * script, s32 isInitialCall)
Definition at line 48 of file code_1a1f0_len_5390.c.
UnfadeBackgroundFromBlack()
ApiStatus UnfadeBackgroundFromBlack (ScriptInstance * script, s32 isInitialCall)
Definition at line 62 of file code_1a1f0_len_5390.c.
GetCamLookAtObjVector()
ApiStatus GetCamLookAtObjVector (ScriptInstance * script, s32 isInitialCall)
Definition at line 114 of file code_1a1f0_len_5390.c.
HasMerleeCasts()
ApiStatus HasMerleeCasts (ScriptInstance * script, s32 isInitialCall)
Definition at line 122 of file code_1a1f0_len_5390.c.
OnDefeatEnemy()
ApiStatus OnDefeatEnemy (ScriptInstance * script, s32 isInitialCall)
Definition at line 151 of file code_1a1f0_len_5390.c.
OnFleeBattleDrops()
ApiStatus OnFleeBattleDrops (ScriptInstance * script, s32 isInitialCall)
Definition at line 190 of file code_1a1f0_len_5390.c.
SetEncounterStatusFlags()
ApiStatus SetEncounterStatusFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 4 of file code_1f580_len_1940.c.
LoadDemoBattle()
ApiStatus LoadDemoBattle (ScriptInstance * script, s32 isInitialCall)
Definition at line 31 of file code_1f580_len_1940.c.
RemoveNpc()
ApiStatus RemoveNpc (ScriptInstance * script, s32 isInitialCall)
Definition at line 61 of file code_1f580_len_1940.c.
RemoveEncounter()
ApiStatus RemoveEncounter (ScriptInstance * script, s32 isInitialCall)
Definition at line 63 of file code_1f580_len_1940.c.
GetBattleOutcome()
ApiStatus GetBattleOutcome (ScriptInstance * script, s32 isInitialCall)
Definition at line 65 of file code_1f580_len_1940.c.
GetOwnerEncounterTrigger()
ApiStatus GetOwnerEncounterTrigger (ScriptInstance * script, s32 isInitialCall)
Definition at line 80 of file code_1f580_len_1940.c.
Referenced by N().
DoNpcDefeat()
ApiStatus DoNpcDefeat (ScriptInstance * script, s32 isInitialCall)
Definition at line 85 of file code_1f580_len_1940.c.
StartBattle()
ApiStatus StartBattle (ScriptInstance * script, s32 isInitialCall)
Definition at line 104 of file code_1f580_len_1940.c.
StartBattleWith()
ApiStatus StartBattleWith (ScriptInstance * script, s32 isInitialCall)
Definition at line 109 of file code_1f580_len_1940.c.
StartBossBattle()
ApiStatus StartBossBattle (ScriptInstance * script, s32 isInitialCall)
Definition at line 114 of file code_1f580_len_1940.c.
SetBattleMusic()
ApiStatus SetBattleMusic (ScriptInstance * script, s32 isInitialCall)
Definition at line 116 of file code_1f580_len_1940.c.
BindNpcAI()
ApiStatus BindNpcAI (ScriptInstance * script, s32 isInitialCall)
Definition at line 126 of file code_1f580_len_1940.c.
Referenced by N().
BindNpcIdle()
ApiStatus BindNpcIdle (ScriptInstance * script, s32 isInitialCall)
Definition at line 128 of file code_1f580_len_1940.c.
Referenced by N().
RestartNpcAI()
ApiStatus RestartNpcAI (ScriptInstance * script, s32 isInitialCall)
Definition at line 144 of file code_1f580_len_1940.c.
EnableNpcAI()
ApiStatus EnableNpcAI (ScriptInstance * script, s32 isInitialCall)
Definition at line 178 of file code_1f580_len_1940.c.
Referenced by N().
SetNpcAux()
ApiStatus SetNpcAux (ScriptInstance * script, s32 isInitialCall)
Definition at line 201 of file code_1f580_len_1940.c.
Referenced by N().
BindNpcAux()
ApiStatus BindNpcAux (ScriptInstance * script, s32 isInitialCall)
Definition at line 203 of file code_1f580_len_1940.c.
Referenced by N().
RestartNpcAux()
ApiStatus RestartNpcAux (ScriptInstance * script, s32 isInitialCall)
Definition at line 219 of file code_1f580_len_1940.c.
EnableNpcAux()
ApiStatus EnableNpcAux (ScriptInstance * script, s32 isInitialCall)
Definition at line 252 of file code_1f580_len_1940.c.
BindNpcInteract()
ApiStatus BindNpcInteract (ScriptInstance * script, s32 isInitialCall)
Definition at line 275 of file code_1f580_len_1940.c.
BindNpcHit()
ApiStatus BindNpcHit (ScriptInstance * script, s32 isInitialCall)
Definition at line 295 of file code_1f580_len_1940.c.
Referenced by N().
BindNpcDefeat()
ApiStatus BindNpcDefeat (ScriptInstance * script, s32 isInitialCall)
Definition at line 315 of file code_1f580_len_1940.c.
SetSelfVar()
ApiStatus SetSelfVar (ScriptInstance * script, s32 isInitialCall)
Definition at line 331 of file code_1f580_len_1940.c.
Referenced by N().
GetSelfVar()
ApiStatus GetSelfVar (ScriptInstance * script, s32 isInitialCall)
Definition at line 341 of file code_1f580_len_1940.c.
Referenced by N().
SetNpcVar()
ApiStatus SetNpcVar (ScriptInstance * script, s32 isInitialCall)
Definition at line 348 of file code_1f580_len_1940.c.
Referenced by N().
GetNpcVar()
ApiStatus GetNpcVar (ScriptInstance * script, s32 isInitialCall)
Definition at line 365 of file code_1f580_len_1940.c.
Referenced by N().
SetSelfRotation()
ApiStatus SetSelfRotation (ScriptInstance * script, s32 isInitialCall)
Definition at line 382 of file code_1f580_len_1940.c.
SetSelfEnemyFlags()
ApiStatus SetSelfEnemyFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 396 of file code_1f580_len_1940.c.
SetSelfEnemyFlagBits()
ApiStatus SetSelfEnemyFlagBits (ScriptInstance * script, s32 isInitialCall)
Definition at line 401 of file code_1f580_len_1940.c.
Referenced by N().
GetSelfNpcID()
ApiStatus GetSelfNpcID (ScriptInstance * script, s32 isInitialCall)
Definition at line 427 of file code_1f580_len_1940.c.
ClearDefeatedEnemies()
ApiStatus ClearDefeatedEnemies (ScriptInstance * script, s32 isInitialCall)
Definition at line 432 of file code_1f580_len_1940.c.
Referenced by N().
SetEnemyFlagBits()
ApiStatus SetEnemyFlagBits (ScriptInstance * script, s32 isInitialCall)
Definition at line 445 of file code_1f580_len_1940.c.
GetSelfAnimationFromTable()
ApiStatus GetSelfAnimationFromTable (ScriptInstance * script, s32 isInitialCall)
Definition at line 471 of file code_1f580_len_1940.c.
ShowCoinCounter()
ApiStatus ShowCoinCounter (ScriptInstance * script, s32 isInitialCall)
Definition at line 508 of file code_80850_len_3060.c.
MakeEntity()
ApiStatus MakeEntity (ScriptInstance * script, s32 isInitialCall)
Definition at line 119 of file code_a5dd0_len_114e0.c.
Referenced by N().
AssignScript()
ApiStatus AssignScript (ScriptInstance * script, s32 isInitialCall)
Definition at line 125 of file code_a5dd0_len_114e0.c.
Referenced by N().
AssignAreaFlag()
ApiStatus AssignAreaFlag (ScriptInstance * script, s32 isInitialCall)
Definition at line 127 of file code_a5dd0_len_114e0.c.
AssignFlag()
ApiStatus AssignFlag (ScriptInstance * script, s32 isInitialCall)
Definition at line 131 of file code_a5dd0_len_114e0.c.
AssignBlockFlag()
ApiStatus AssignBlockFlag (ScriptInstance * script, s32 isInitialCall)
Definition at line 129 of file code_a5dd0_len_114e0.c.
Referenced by N().
AssignPanelFlag()
ApiStatus AssignPanelFlag (ScriptInstance * script, s32 isInitialCall)
Definition at line 144 of file code_a5dd0_len_114e0.c.
AssignCrateFlag()
ApiStatus AssignCrateFlag (ScriptInstance * script, s32 isInitialCall)
Definition at line 146 of file code_a5dd0_len_114e0.c.
DeleteTrigger()
ApiStatus DeleteTrigger (ScriptInstance * script, s32 isInitialCall)
Definition at line 1022 of file si.c.
TranslateModel()
ApiStatus TranslateModel (ScriptInstance * script, s32 isInitialCall)
Definition at line 5 of file code_ED510.c.
Referenced by N().
RotateModel()
ApiStatus RotateModel (ScriptInstance * script, s32 isInitialCall)
Definition at line 30 of file code_ED510.c.
ScaleModel()
ApiStatus ScaleModel (ScriptInstance * script, s32 isInitialCall)
Definition at line 55 of file code_ED510.c.
CloneModel()
ApiStatus CloneModel (ScriptInstance * script, s32 isInitialCall)
Definition at line 98 of file code_ED510.c.
GetModelIndex()
ApiStatus GetModelIndex (ScriptInstance * script, s32 isInitialCall)
Definition at line 80 of file code_ED510.c.
GetModelCenter()
ApiStatus GetModelCenter (ScriptInstance * script, s32 isInitialCall)
Definition at line 107 of file code_ED510.c.
SetTexPanner()
ApiStatus SetTexPanner (ScriptInstance * script, s32 isInitialCall)
Definition at line 124 of file code_ED510.c.
SetModelFlag10()
ApiStatus SetModelFlag10 (ScriptInstance * script, s32 isInitialCall)
Definition at line 135 of file code_ED510.c.
EnableTexPanning()
ApiStatus EnableTexPanning (ScriptInstance * script, s32 isInitialCall)
Definition at line 176 of file code_ED510.c.
EnableModel()
ApiStatus EnableModel (ScriptInstance * script, s32 isInitialCall)
Definition at line 190 of file code_ED510.c.
SetGroupEnabled()
ApiStatus SetGroupEnabled (ScriptInstance * script, s32 isInitialCall)
Definition at line 204 of file code_ED510.c.
SetTexPanOffset()
ApiStatus SetTexPanOffset (ScriptInstance * script, s32 isInitialCall)
Definition at line 213 of file code_ED510.c.
SetModelFlags()
ApiStatus SetModelFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 252 of file code_ED510.c.
TranslateGroup()
ApiStatus TranslateGroup (ScriptInstance * script, s32 isInitialCall)
Definition at line 292 of file code_ED510.c.
RotateGroup()
ApiStatus RotateGroup (ScriptInstance * script, s32 isInitialCall)
Definition at line 294 of file code_ED510.c.
ScaleGroup()
ApiStatus ScaleGroup (ScriptInstance * script, s32 isInitialCall)
Definition at line 296 of file code_ED510.c.
EnableGroup()
ApiStatus EnableGroup (ScriptInstance * script, s32 isInitialCall)
Definition at line 307 of file code_ED510.c.
ModifyColliderFlags()
ApiStatus ModifyColliderFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 321 of file code_ED510.c.
Referenced by N().
GetColliderCenter()
ApiStatus GetColliderCenter (ScriptInstance * script, s32 isInitialCall)
Definition at line 327 of file code_ED510.c.
ParentColliderToModel()
ApiStatus ParentColliderToModel (ScriptInstance * script, s32 isInitialCall)
Definition at line 339 of file code_ED510.c.
UpdateColliderTransform()
ApiStatus UpdateColliderTransform (ScriptInstance * script, s32 isInitialCall)
Definition at line 349 of file code_ED510.c.
SetZoneEnabled()
ApiStatus SetZoneEnabled (ScriptInstance * script, s32 isInitialCall)
GotoMap()
ApiStatus GotoMap (ScriptInstance * script, s32 isInitialCall)
Definition at line 360 of file code_ED510.c.
Referenced by N().
GotoMapSpecial()
ApiStatus GotoMapSpecial (ScriptInstance * script, s32 isInitialCall)
Definition at line 365 of file code_ED510.c.
GotoMapByID()
ApiStatus GotoMapByID (ScriptInstance * script, s32 isInitialCall)
Definition at line 370 of file code_ED510.c.
GetEntryID()
ApiStatus GetEntryID (ScriptInstance * script, s32 isInitialCall)
Definition at line 375 of file code_ED510.c.
Referenced by N().
GetMapID()
ApiStatus GetMapID (ScriptInstance * script, s32 isInitialCall)
Definition at line 380 of file code_ED510.c.
GetLoadType()
ApiStatus GetLoadType (ScriptInstance * script, s32 isInitialCall)
Definition at line 385 of file code_ED510.c.
SetRenderMode()
ApiStatus SetRenderMode (ScriptInstance * script, s32 isInitialCall)
Definition at line 390 of file code_ED510.c.
PlaySoundAtModel()
ApiStatus PlaySoundAtModel (ScriptInstance * script, s32 isInitialCall)
Definition at line 400 of file code_ED510.c.
Referenced by N().
PlaySoundAtCollider()
ApiStatus PlaySoundAtCollider (ScriptInstance * script, s32 isInitialCall)
Definition at line 414 of file code_ED510.c.
SetCamEnabled()
ApiStatus SetCamEnabled (ScriptInstance * script, s32 isInitialCall)
Definition at line 3 of file code_ef070_len_3400.c.
Referenced by N().
SetCamFlag80()
ApiStatus SetCamFlag80 (ScriptInstance * script, s32 isInitialCall)
Definition at line 16 of file code_ef070_len_3400.c.
SetCamPerspective()
ApiStatus SetCamPerspective (ScriptInstance * script, s32 isInitialCall)
Definition at line 29 of file code_ef070_len_3400.c.
Referenced by N().
SetCamViewport()
ApiStatus SetCamViewport (ScriptInstance * script, s32 isInitialCall)
Definition at line 91 of file code_ef070_len_3400.c.
SetCamBGColor()
ApiStatus SetCamBGColor (ScriptInstance * script, s32 isInitialCall)
Definition at line 137 of file code_ef070_len_3400.c.
Referenced by N().
SetCamTarget()
ApiStatus SetCamTarget (ScriptInstance * script, s32 isInitialCall)
Definition at line 167 of file code_ef070_len_3400.c.
Referenced by N().
ShakeCam()
ApiStatus ShakeCam (ScriptInstance * script, s32 isInitialCall)
Definition at line 184 of file code_ef070_len_3400.c.
SetCamLeadPlayer()
ApiStatus SetCamLeadPlayer (ScriptInstance * script, s32 isInitialCall)
Definition at line 205 of file code_ef070_len_3400.c.
Referenced by N().
PanToTarget()
ApiStatus PanToTarget (ScriptInstance * script, s32 isInitialCall)
Definition at line 231 of file code_ef070_len_3400.c.
Referenced by N().
UseSettingsFrom()
ApiStatus UseSettingsFrom (ScriptInstance * script, s32 isInitialCall)
Definition at line 251 of file code_ef070_len_3400.c.
Referenced by N().
LoadSettings()
ApiStatus LoadSettings (ScriptInstance * script, s32 isInitialCall)
Definition at line 253 of file code_ef070_len_3400.c.
SetCamType()
ApiStatus SetCamType (ScriptInstance * script, s32 isInitialCall)
Definition at line 255 of file code_ef070_len_3400.c.
SetCamPitch()
ApiStatus SetCamPitch (ScriptInstance * script, s32 isInitialCall)
Definition at line 268 of file code_ef070_len_3400.c.
Referenced by N().
SetCamDistance()
ApiStatus SetCamDistance (ScriptInstance * script, s32 isInitialCall)
Definition at line 281 of file code_ef070_len_3400.c.
Referenced by N().
SetCamPosA()
ApiStatus SetCamPosA (ScriptInstance * script, s32 isInitialCall)
Definition at line 292 of file code_ef070_len_3400.c.
SetCamPosB()
ApiStatus SetCamPosB (ScriptInstance * script, s32 isInitialCall)
Definition at line 305 of file code_ef070_len_3400.c.
SetCamPosC()
ApiStatus SetCamPosC (ScriptInstance * script, s32 isInitialCall)
Definition at line 318 of file code_ef070_len_3400.c.
SetPanTarget()
ApiStatus SetPanTarget (ScriptInstance * script, s32 isInitialCall)
Definition at line 331 of file code_ef070_len_3400.c.
Referenced by N().
SetCamSpeed()
ApiStatus SetCamSpeed (ScriptInstance * script, s32 isInitialCall)
Definition at line 347 of file code_ef070_len_3400.c.
Referenced by N().
GetCamType()
ApiStatus GetCamType (ScriptInstance * script, s32 isInitialCall)
Definition at line 358 of file code_ef070_len_3400.c.
GetCamPitch()
ApiStatus GetCamPitch (ScriptInstance * script, s32 isInitialCall)
Definition at line 371 of file code_ef070_len_3400.c.
GetCamDistance()
ApiStatus GetCamDistance (ScriptInstance * script, s32 isInitialCall)
Definition at line 384 of file code_ef070_len_3400.c.
GetCamPosA()
ApiStatus GetCamPosA (ScriptInstance * script, s32 isInitialCall)
Definition at line 395 of file code_ef070_len_3400.c.
GetCamPosB()
ApiStatus GetCamPosB (ScriptInstance * script, s32 isInitialCall)
Definition at line 408 of file code_ef070_len_3400.c.
GetCamPosC()
ApiStatus GetCamPosC (ScriptInstance * script, s32 isInitialCall)
Definition at line 421 of file code_ef070_len_3400.c.
GetCamPosition()
ApiStatus GetCamPosition (ScriptInstance * script, s32 isInitialCall)
Definition at line 434 of file code_ef070_len_3400.c.
WaitForCam()
ApiStatus WaitForCam (ScriptInstance * script, s32 isInitialCall)
Definition at line 449 of file code_ef070_len_3400.c.
Referenced by N().
SetCamProperties()
ApiStatus SetCamProperties (ScriptInstance * script, s32 isInitialCall)
Definition at line 462 of file code_ef070_len_3400.c.
AdjustCam()
ApiStatus AdjustCam (ScriptInstance * script, s32 isInitialCall)
Definition at line 464 of file code_ef070_len_3400.c.
ResetCam()
ApiStatus ResetCam (ScriptInstance * script, s32 isInitialCall)
Definition at line 466 of file code_ef070_len_3400.c.
LoadModelAnimation()
ApiStatus LoadModelAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 492 of file code_ef070_len_3400.c.
PlayModelAnimation()
ApiStatus PlayModelAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 540 of file code_ef070_len_3400.c.
ChangeModelAnimation()
ApiStatus ChangeModelAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 565 of file code_ef070_len_3400.c.
DeleteNpc()
ApiStatus DeleteNpc (ScriptInstance * script, s32 isInitialCall)
Definition at line 28 of file code_f2470_len_27f0.c.
GetNpcPointer()
ApiStatus GetNpcPointer (ScriptInstance * script, s32 isInitialCall)
Definition at line 40 of file code_f2470_len_27f0.c.
SetNpcPos()
ApiStatus SetNpcPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 49 of file code_f2470_len_27f0.c.
Referenced by N().
SetNpcRotation()
ApiStatus SetNpcRotation (ScriptInstance * script, s32 isInitialCall)
Definition at line 72 of file code_f2470_len_27f0.c.
Referenced by N().
SetNpcScale()
ApiStatus SetNpcScale (ScriptInstance * script, s32 isInitialCall)
Definition at line 105 of file code_f2470_len_27f0.c.
SetNpcCollisionSize()
ApiStatus SetNpcCollisionSize (ScriptInstance * script, s32 isInitialCall)
Definition at line 123 of file code_f2470_len_27f0.c.
SetNpcSpeed()
ApiStatus SetNpcSpeed (ScriptInstance * script, s32 isInitialCall)
Definition at line 139 of file code_f2470_len_27f0.c.
Referenced by N().
SetNpcJumpscale()
ApiStatus SetNpcJumpscale (ScriptInstance * script, s32 isInitialCall)
Definition at line 153 of file code_f2470_len_27f0.c.
Referenced by N().
SetNpcAnimation()
ApiStatus SetNpcAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 167 of file code_f2470_len_27f0.c.
Referenced by N().
GetNpcAnimation()
ApiStatus GetNpcAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 181 of file code_f2470_len_27f0.c.
NpcMoveTo()
ApiStatus NpcMoveTo (ScriptInstance * script, s32 isInitialCall)
Definition at line 209 of file code_f2470_len_27f0.c.
Referenced by N().
NpcJump0()
ApiStatus NpcJump0 (ScriptInstance * script, s32 isInitialCall)
Definition at line 213 of file code_f2470_len_27f0.c.
Referenced by N().
NpcJump1()
ApiStatus NpcJump1 (ScriptInstance * script, s32 isInitialCall)
Definition at line 217 of file code_f2470_len_27f0.c.
NpcFlyTo()
ApiStatus NpcFlyTo (ScriptInstance * script, s32 isInitialCall)
Definition at line 221 of file code_f2470_len_27f0.c.
GetNpcYaw()
ApiStatus GetNpcYaw (ScriptInstance * script, s32 isInitialCall)
Definition at line 223 of file code_f2470_len_27f0.c.
SetNpcYaw()
ApiStatus SetNpcYaw (ScriptInstance * script, s32 isInitialCall)
Definition at line 237 of file code_f2470_len_27f0.c.
InterpNpcYaw()
ApiStatus InterpNpcYaw (ScriptInstance * script, s32 isInitialCall)
Definition at line 250 of file code_f2470_len_27f0.c.
Referenced by N().
NpcFacePlayer()
ApiStatus NpcFacePlayer (ScriptInstance * script, s32 isInitialCall)
Definition at line 252 of file code_f2470_len_27f0.c.
Referenced by N().
NpcFaceNpc()
ApiStatus NpcFaceNpc (ScriptInstance * script, s32 isInitialCall)
Definition at line 254 of file code_f2470_len_27f0.c.
SetNpcFlagBits()
ApiStatus SetNpcFlagBits (ScriptInstance * script, s32 isInitialCall)
Definition at line 256 of file code_f2470_len_27f0.c.
Referenced by N().
GetNpcPos()
ApiStatus GetNpcPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 276 of file code_f2470_len_27f0.c.
Referenced by N().
EnableNpcShadow()
ApiStatus EnableNpcShadow (ScriptInstance * script, s32 isInitialCall)
Definition at line 322 of file code_f2470_len_27f0.c.
Referenced by N().
EnableNpcBlur()
ApiStatus EnableNpcBlur (ScriptInstance * script, s32 isInitialCall)
Definition at line 340 of file code_f2470_len_27f0.c.
ClearPartnerMoveHistory()
ApiStatus ClearPartnerMoveHistory (ScriptInstance * script, s32 isInitialCall)
Definition at line 358 of file code_f2470_len_27f0.c.
GetPartnerPos()
ApiStatus GetPartnerPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 384 of file code_f2470_len_27f0.c.
DisablePartnerAI()
ApiStatus DisablePartnerAI (ScriptInstance * script, s32 isInitialCall)
Definition at line 401 of file code_f2470_len_27f0.c.
EnablePartnerAI()
ApiStatus EnablePartnerAI (ScriptInstance * script, s32 isInitialCall)
Definition at line 412 of file code_f2470_len_27f0.c.
Referenced by N().
BringPartnerOut()
ApiStatus BringPartnerOut (ScriptInstance * script, s32 isInitialCall)
Definition at line 434 of file code_f2470_len_27f0.c.
PutPartnerAway()
ApiStatus PutPartnerAway (ScriptInstance * script, s32 isInitialCall)
Definition at line 436 of file code_f2470_len_27f0.c.
GetCurrentPartnerID()
ApiStatus GetCurrentPartnerID (ScriptInstance * script, s32 isInitialCall)
Definition at line 438 of file code_f2470_len_27f0.c.
IsCurrentPartnerFlying()
ApiStatus IsCurrentPartnerFlying (ScriptInstance * script, s32 isInitialCall)
SetNpcEffect()
ApiStatus SetNpcEffect (ScriptInstance * script, s32 isInitialCall)
Definition at line 542 of file code_f2470_len_27f0.c.
PlaySoundAtNpc()
ApiStatus PlaySoundAtNpc (ScriptInstance * script, s32 isInitialCall)
Definition at line 557 of file code_f2470_len_27f0.c.
Referenced by N().
SpeakToPlayer()
ApiStatus SpeakToPlayer (ScriptInstance * script, s32 isInitialCall)
Definition at line 5 of file code_f4c60_len_4300.c.
Referenced by N().
EndSpeech()
ApiStatus EndSpeech (ScriptInstance * script, s32 isInitialCall)
Definition at line 9 of file code_f4c60_len_4300.c.
ContinueSpeech()
ApiStatus ContinueSpeech (ScriptInstance * script, s32 isInitialCall)
Definition at line 13 of file code_f4c60_len_4300.c.
SpeakToNpc()
ApiStatus SpeakToNpc (ScriptInstance * script, s32 isInitialCall)
Definition at line 17 of file code_f4c60_len_4300.c.
ShowMessageAtScreenPos()
ApiStatus ShowMessageAtScreenPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 23 of file code_f4c60_len_4300.c.
Referenced by N().
ShowMessageAtWorldPos()
ApiStatus ShowMessageAtWorldPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 25 of file code_f4c60_len_4300.c.
CloseMessage()
ApiStatus CloseMessage (ScriptInstance * script, s32 isInitialCall)
Definition at line 27 of file code_f4c60_len_4300.c.
SwitchMessage()
ApiStatus SwitchMessage (ScriptInstance * script, s32 isInitialCall)
Definition at line 42 of file code_f4c60_len_4300.c.
ShowChoice()
ApiStatus ShowChoice (ScriptInstance * script, s32 isInitialCall)
Definition at line 59 of file code_f4c60_len_4300.c.
CloseChoice()
ApiStatus CloseChoice (ScriptInstance * script, s32 isInitialCall)
Definition at line 61 of file code_f4c60_len_4300.c.
CancelMessage()
ApiStatus CancelMessage (ScriptInstance * script, s32 isInitialCall)
Definition at line 66 of file code_f4c60_len_4300.c.
CancelMessageAndBlock()
ApiStatus CancelMessageAndBlock (ScriptInstance * script, s32 isInitialCall)
Definition at line 71 of file code_f4c60_len_4300.c.
Referenced by world_goombario_pre_battle().
SetMessageImages()
ApiStatus SetMessageImages (ScriptInstance * script, s32 isInitialCall)
Definition at line 76 of file code_f4c60_len_4300.c.
SetMessageString()
ApiStatus SetMessageString (ScriptInstance * script, s32 isInitialCall)
Definition at line 90 of file code_f4c60_len_4300.c.
SetMessageValue()
ApiStatus SetMessageValue (ScriptInstance * script, s32 isInitialCall)
Definition at line 99 of file code_f4c60_len_4300.c.
HidePlayerShadow()
ApiStatus HidePlayerShadow (ScriptInstance * script, s32 isInitialCall)
Definition at line 3 of file code_F5750.c.
Referenced by N().
DisablePlayerPhysics()
ApiStatus DisablePlayerPhysics (ScriptInstance * script, s32 isInitialCall)
Definition at line 15 of file code_F5750.c.
Referenced by N().
DisablePlayerInput()
ApiStatus DisablePlayerInput (ScriptInstance * script, s32 isInitialCall)
Definition at line 27 of file code_F5750.c.
Referenced by N().
SetPlayerPos()
ApiStatus SetPlayerPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 51 of file code_F5750.c.
Referenced by N().
SetPlayerCollisionSize()
ApiStatus SetPlayerCollisionSize (ScriptInstance * script, s32 isInitialCall)
Definition at line 69 of file code_F5750.c.
SetPlayerSpeed()
ApiStatus SetPlayerSpeed (ScriptInstance * script, s32 isInitialCall)
Definition at line 85 of file code_F5750.c.
Referenced by N().
SetPlayerJumpscale()
ApiStatus SetPlayerJumpscale (ScriptInstance * script, s32 isInitialCall)
Definition at line 90 of file code_F5750.c.
Referenced by N().
SetPlayerAnimation()
ApiStatus SetPlayerAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 96 of file code_F5750.c.
Referenced by N().
SetPlayerActionState()
ApiStatus SetPlayerActionState (ScriptInstance * script, s32 isInitialCall)
Definition at line 115 of file code_F5750.c.
PlayerMoveTo()
ApiStatus PlayerMoveTo (ScriptInstance * script, s32 isInitialCall)
Definition at line 125 of file code_F5750.c.
Referenced by N().
PlayerJump()
ApiStatus PlayerJump (ScriptInstance * script, s32 isInitialCall)
Definition at line 158 of file code_F5750.c.
Referenced by N().
PlayerJump1()
ApiStatus PlayerJump1 (ScriptInstance * script, s32 isInitialCall)
Definition at line 162 of file code_F5750.c.
PlayerJump2()
ApiStatus PlayerJump2 (ScriptInstance * script, s32 isInitialCall)
Definition at line 166 of file code_F5750.c.
InterpPlayerYaw()
ApiStatus InterpPlayerYaw (ScriptInstance * script, s32 isInitialCall)
Definition at line 170 of file code_F5750.c.
Referenced by N().
PlayerFaceNpc()
ApiStatus PlayerFaceNpc (ScriptInstance * script, s32 isInitialCall)
Definition at line 214 of file code_F5750.c.
Referenced by N().
GetPlayerTargetYaw()
ApiStatus GetPlayerTargetYaw (ScriptInstance * script, s32 isInitialCall)
Definition at line 216 of file code_F5750.c.
SetPlayerFlagBits()
ApiStatus SetPlayerFlagBits (ScriptInstance * script, s32 isInitialCall)
Definition at line 221 of file code_F5750.c.
GetPlayerActionState()
ApiStatus GetPlayerActionState (ScriptInstance * script, s32 isInitialCall)
Definition at line 237 of file code_F5750.c.
GetPlayerPos()
ApiStatus GetPlayerPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 243 of file code_F5750.c.
Referenced by N().
GetPlayerAnimation()
ApiStatus GetPlayerAnimation (ScriptInstance * script, s32 isInitialCall)
Definition at line 256 of file code_F5750.c.
FullyRestoreHPandFP()
ApiStatus FullyRestoreHPandFP (ScriptInstance * script, s32 isInitialCall)
Definition at line 263 of file code_F5750.c.
FullyRestoreSP()
ApiStatus FullyRestoreSP (ScriptInstance * script, s32 isInitialCall)
Definition at line 271 of file code_F5750.c.
EnablePartner()
ApiStatus EnablePartner (ScriptInstance * script, s32 isInitialCall)
Definition at line 278 of file code_F5750.c.
DisablePartner()
ApiStatus DisablePartner (ScriptInstance * script, s32 isInitialCall)
Definition at line 286 of file code_F5750.c.
UseEntryHeading()
ApiStatus UseEntryHeading (ScriptInstance * script, s32 isInitialCall)
UseExitHeading()
ApiStatus UseExitHeading (ScriptInstance * script, s32 isInitialCall)
DisablePulseStone()
ApiStatus DisablePulseStone (ScriptInstance * script, s32 isInitialCall)
Definition at line 329 of file code_F5750.c.
GetCurrentPartner()
ApiStatus GetCurrentPartner (ScriptInstance * script, s32 isInitialCall)
Definition at line 342 of file code_F5750.c.
Disable8bitMario()
ApiStatus Disable8bitMario (ScriptInstance * script, s32 isInitialCall)
Definition at line 360 of file code_F5750.c.
PlaySoundAtPlayer()
ApiStatus PlaySoundAtPlayer (ScriptInstance * script, s32 isInitialCall)
Definition at line 382 of file code_F5750.c.
Referenced by N().
MakeLerp()
ApiStatus MakeLerp (ScriptInstance * script, s32 isInitialCall)
Definition at line 3 of file code_f8f60_len_1560.c.
UpdateLerp()
ApiStatus UpdateLerp (ScriptInstance * script, s32 isInitialCall)
Definition at line 15 of file code_f8f60_len_1560.c.
RandInt()
ApiStatus RandInt (ScriptInstance * script, s32 isInitialCall)
Definition at line 34 of file code_f8f60_len_1560.c.
GetAngleBetweenNPCs()
ApiStatus GetAngleBetweenNPCs (ScriptInstance * script, s32 isInitialCall)
Definition at line 45 of file code_f8f60_len_1560.c.
GetAngleToNPC()
ApiStatus GetAngleToNPC (ScriptInstance * script, s32 isInitialCall)
Definition at line 59 of file code_f8f60_len_1560.c.
GetAngleToPlayer()
ApiStatus GetAngleToPlayer (ScriptInstance * script, s32 isInitialCall)
Definition at line 72 of file code_f8f60_len_1560.c.
Referenced by N().
AwaitPlayerApproach()
ApiStatus AwaitPlayerApproach (ScriptInstance * script, s32 isInitialCall)
Definition at line 85 of file code_f8f60_len_1560.c.
IsPlayerWithin()
ApiStatus IsPlayerWithin (ScriptInstance * script, s32 isInitialCall)
Definition at line 113 of file code_f8f60_len_1560.c.
AwaitPlayerLeave()
ApiStatus AwaitPlayerLeave (ScriptInstance * script, s32 isInitialCall)
Definition at line 144 of file code_f8f60_len_1560.c.
Referenced by N().
AddVectorPolar()
ApiStatus AddVectorPolar (ScriptInstance * script, s32 isInitialCall)
Definition at line 172 of file code_f8f60_len_1560.c.
Referenced by N().
LoadPath()
ApiStatus LoadPath (ScriptInstance * script, s32 isInitialCall)
Definition at line 354 of file code_f8f60_len_1560.c.
GetNextPathPos()
ApiStatus GetNextPathPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 376 of file code_f8f60_len_1560.c.
GetDist2D()
ApiStatus GetDist2D (ScriptInstance * script, s32 isInitialCall)
Definition at line 378 of file code_f8f60_len_1560.c.
SetValueByRef()
ApiStatus SetValueByRef (ScriptInstance * script, s32 isInitialCall)
Definition at line 413 of file code_f8f60_len_1560.c.
Referenced by N().
GetValueByRef()
ApiStatus GetValueByRef (ScriptInstance * script, s32 isInitialCall)
Definition at line 423 of file code_f8f60_len_1560.c.
Referenced by N().
EnableStatusMenu()
ApiStatus EnableStatusMenu (ScriptInstance * script, s32 isInitialCall)
Definition at line 434 of file code_f8f60_len_1560.c.
ShowStatusMenu()
ApiStatus ShowStatusMenu (ScriptInstance * script, s32 isInitialCall)
Definition at line 444 of file code_f8f60_len_1560.c.
SetGameMode()
ApiStatus SetGameMode (ScriptInstance * script, s32 isInitialCall)
Definition at line 455 of file code_f8f60_len_1560.c.
ClampAngleInt()
ApiStatus ClampAngleInt (ScriptInstance * script, s32 isInitialCall)
Definition at line 463 of file code_f8f60_len_1560.c.
ClampAngleFloat()
ApiStatus ClampAngleFloat (ScriptInstance * script, s32 isInitialCall)
Definition at line 471 of file code_f8f60_len_1560.c.
FadeOutMusic()
ApiStatus FadeOutMusic (ScriptInstance * script, s32 isInitialCall)
Definition at line 7 of file code_fa4c0_len_3bf0.c.
SetMusicTrack()
ApiStatus SetMusicTrack (ScriptInstance * script, s32 isInitialCall)
Definition at line 15 of file code_fa4c0_len_3bf0.c.
Referenced by N().
FadeInMusic()
ApiStatus FadeInMusic (ScriptInstance * script, s32 isInitialCall)
Definition at line 25 of file code_fa4c0_len_3bf0.c.
ClearAmbientSounds()
ApiStatus ClearAmbientSounds (ScriptInstance * script, s32 isInitialCall)
Definition at line 86 of file code_fa4c0_len_3bf0.c.
PlayAmbientSounds()
ApiStatus PlayAmbientSounds (ScriptInstance * script, s32 isInitialCall)
Definition at line 93 of file code_fa4c0_len_3bf0.c.
PlaySound()
ApiStatus PlaySound (ScriptInstance * script, s32 isInitialCall)
Definition at line 100 of file code_fa4c0_len_3bf0.c.
Referenced by N().
PlaySoundAt()
ApiStatus PlaySoundAt (ScriptInstance * script, s32 isInitialCall)
Definition at line 117 of file code_fa4c0_len_3bf0.c.
StopSound()
ApiStatus StopSound (ScriptInstance * script, s32 isInitialCall)
Definition at line 129 of file code_fa4c0_len_3bf0.c.
UseDoorSounds()
ApiStatus UseDoorSounds (ScriptInstance * script, s32 isInitialCall)
Definition at line 143 of file code_fa4c0_len_3bf0.c.
PlaySoundAtF()
ApiStatus PlaySoundAtF (ScriptInstance * script, s32 isInitialCall)
Definition at line 157 of file code_fa4c0_len_3bf0.c.
RemoveKeyItemAt()
ApiStatus RemoveKeyItemAt (ScriptInstance * script, s32 isInitialCall)
Definition at line 173 of file code_fa4c0_len_3bf0.c.
RemoveItemAt()
ApiStatus RemoveItemAt (ScriptInstance * script, s32 isInitialCall)
Definition at line 182 of file code_fa4c0_len_3bf0.c.
AddKeyItem()
ApiStatus AddKeyItem (ScriptInstance * script, s32 isInitialCall)
Definition at line 192 of file code_fa4c0_len_3bf0.c.
HasKeyItem()
ApiStatus HasKeyItem (ScriptInstance * script, s32 isInitialCall)
Definition at line 224 of file code_fa4c0_len_3bf0.c.
FindKeyItem()
ApiStatus FindKeyItem (ScriptInstance * script, s32 isInitialCall)
Definition at line 240 of file code_fa4c0_len_3bf0.c.
AddItem()
ApiStatus AddItem (ScriptInstance * script, s32 isInitialCall)
Definition at line 263 of file code_fa4c0_len_3bf0.c.
FindItem()
ApiStatus FindItem (ScriptInstance * script, s32 isInitialCall)
Definition at line 277 of file code_fa4c0_len_3bf0.c.
RemoveItem()
ApiStatus RemoveItem (ScriptInstance * script, s32 isInitialCall)
Definition at line 300 of file code_fa4c0_len_3bf0.c.
CountFortessKeys()
ApiStatus CountFortessKeys (ScriptInstance * script, s32 isInitialCall)
RemoveFortressKeys()
ApiStatus RemoveFortressKeys (ScriptInstance * script, s32 isInitialCall)
Definition at line 337 of file code_fa4c0_len_3bf0.c.
MakeItemEntity()
ApiStatus MakeItemEntity (ScriptInstance * script, s32 isInitialCall)
Definition at line 344 of file code_fa4c0_len_3bf0.c.
Referenced by N().
DropItemEntity()
ApiStatus DropItemEntity (ScriptInstance * script, s32 isInitialCall)
Definition at line 357 of file code_fa4c0_len_3bf0.c.
Referenced by N().
DropItemEntityB()
ApiStatus DropItemEntityB (ScriptInstance * script, s32 isInitialCall)
Definition at line 370 of file code_fa4c0_len_3bf0.c.
RemoveItemEntity()
ApiStatus RemoveItemEntity (ScriptInstance * script, s32 isInitialCall)
Definition at line 384 of file code_fa4c0_len_3bf0.c.
AddBadge()
ApiStatus AddBadge (ScriptInstance * script, s32 isInitialCall)
Definition at line 392 of file code_fa4c0_len_3bf0.c.
RemoveBadge()
ApiStatus RemoveBadge (ScriptInstance * script, s32 isInitialCall)
Definition at line 401 of file code_fa4c0_len_3bf0.c.
SetItemPos()
ApiStatus SetItemPos (ScriptInstance * script, s32 isInitialCall)
Definition at line 421 of file code_fa4c0_len_3bf0.c.
SetItemFlags()
ApiStatus SetItemFlags (ScriptInstance * script, s32 isInitialCall)
Definition at line 439 of file code_fa4c0_len_3bf0.c.
AddCoin()
ApiStatus AddCoin (ScriptInstance * script, s32 isInitialCall)
Definition at line 464 of file code_fa4c0_len_3bf0.c.
AddStarPoints()
ApiStatus AddStarPoints (ScriptInstance * script, s32 isInitialCall)
Definition at line 469 of file code_fa4c0_len_3bf0.c.
AddStarPieces()
ApiStatus AddStarPieces (ScriptInstance * script, s32 isInitialCall)
Definition at line 474 of file code_fa4c0_len_3bf0.c.
GetItemPower()
ApiStatus GetItemPower (ScriptInstance * script, s32 isInitialCall)
Definition at line 479 of file code_fa4c0_len_3bf0.c.
ShowGotItem()
ApiStatus ShowGotItem (ScriptInstance * script, s32 isInitialCall)
Definition at line 490 of file code_fa4c0_len_3bf0.c.
ShowEmote()
ApiStatus ShowEmote (ScriptInstance * script, s32 isInitialCall)
Definition at line 31 of file code_FBE10.c.
Referenced by N().
ShowSleepBubble()
ApiStatus ShowSleepBubble (ScriptInstance * script, s32 isInitialCall)
RemoveEffect()
ApiStatus RemoveEffect (ScriptInstance * script, s32 isInitialCall)
Definition at line 33 of file code_FBE10.c.
PlayEffect()
ApiStatus PlayEffect (ScriptInstance * script, s32 isInitialCall)
SetSpriteShading()
ApiStatus SetSpriteShading (ScriptInstance * script, s32 isInitialCall)
EnableSpriteShading()
ApiStatus EnableSpriteShading (ScriptInstance * script, s32 isInitialCall)
Definition at line 5 of file code_fe0b0_len_5a0.c.
GetDemoState()
ApiStatus GetDemoState (ScriptInstance * script, s32 isInitialCall)
DemoPressButton()
ApiStatus DemoPressButton (ScriptInstance * script, s32 isInitialCall)
Definition at line 19 of file code_fe0b0_len_5a0.c.
DemoReleaseButton()
ApiStatus DemoReleaseButton (ScriptInstance * script, s32 isInitialCall)
Definition at line 24 of file code_fe0b0_len_5a0.c.
DemoSetButtons()
ApiStatus DemoSetButtons (ScriptInstance * script, s32 isInitialCall)
Definition at line 29 of file code_fe0b0_len_5a0.c.
DemoJoystickRadial()
ApiStatus DemoJoystickRadial (ScriptInstance * script, s32 isInitialCall)
Definition at line 34 of file code_fe0b0_len_5a0.c.
DemoJoystickXY()
ApiStatus DemoJoystickXY (ScriptInstance * script, s32 isInitialCall)
Definition at line 48 of file code_fe0b0_len_5a0.c.
func_802CFE2C()
ApiStatus func_802CFE2C (ScriptInstance * script, s32 isInitialCall)
Definition at line 475 of file code_f2470_len_27f0.c.
Referenced by N().
func_802CFD30()
ApiStatus func_802CFD30 (ScriptInstance * script, s32 isInitialCall)
Definition at line 457 of file code_f2470_len_27f0.c.
Referenced by N().
func_800441F0()
ApiStatus func_800441F0 (ScriptInstance * script, s32 isInitialCall)
Definition at line 19 of file code_1f580_len_1940.c.
Referenced by N().
func_802D5830()
ApiStatus func_802D5830 (ScriptInstance * script, s32 isInitialCall)
Definition at line 392 of file code_f8f60_len_1560.c.
Referenced by N().
Variable Documentation
EnemyNpcHit
Script EnemyNpcHit extern
Referenced by N().
EnemyNpcDefeat
Script EnemyNpcDefeat extern
Referenced by N().