src/si.c File Reference - Paper Mario Documentation
si.c File Reference
Functions
Bytecode * si_find_label (ScriptInstance *script, s32 arg1)
Bytecode * si_skip_if (ScriptInstance *script)
Bytecode * si_skip_else (ScriptInstance *script)
Bytecode * si_goto_end_case (ScriptInstance *script)
Bytecode * si_goto_next_case (ScriptInstance *script)
Bytecode * si_goto_end_loop (ScriptInstance *script)
s32 get_variable_index (ScriptInstance *script, s32 var)
f32 fixed_var_to_float (Bytecode scriptVar)
Bytecode float_to_fixed_var (f32 value)
ApiStatus si_handle_return (ScriptInstance *script)
ApiStatus si_handle_label (ScriptInstance *script)
ApiStatus si_handle_goto (ScriptInstance *script)
ApiStatus si_handle_loop (ScriptInstance *script)
ApiStatus si_handle_end_loop (ScriptInstance *script)
ApiStatus si_handle_break_loop (ScriptInstance *script)
ApiStatus si_handle_sleep_frames (ScriptInstance *script)
ApiStatus si_handle_sleep_seconds (ScriptInstance *script)
ApiStatus si_handle_if_equal (ScriptInstance *script)
ApiStatus si_handle_if_not_equal (ScriptInstance *script)
ApiStatus si_handle_if_less (ScriptInstance *script)
ApiStatus si_handle_if_greater (ScriptInstance *script)
ApiStatus si_handle_if_less_equal (ScriptInstance *script)
ApiStatus si_handle_if_greater_equal (ScriptInstance *script)
ApiStatus si_handle_if_flag (ScriptInstance *script)
ApiStatus si_handle_if_not_flag (ScriptInstance *script)
ApiStatus si_handle_else (ScriptInstance *script)
ApiStatus si_handle_end_if (ScriptInstance *script)
ApiStatus si_handle_match (ScriptInstance *script)
ApiStatus si_handle_match_const (ScriptInstance *script)
ApiStatus si_handle_case_equal (ScriptInstance *script)
ApiStatus si_handle_case_not_equal (ScriptInstance *script)
ApiStatus si_handle_case_less (ScriptInstance *script)
ApiStatus si_handle_case_less_equal (ScriptInstance *script)
ApiStatus si_handle_case_greater (ScriptInstance *script)
ApiStatus si_handle_case_greater_equal (ScriptInstance *script)
ApiStatus si_handle_case_range (ScriptInstance *script)
ApiStatus si_handle_case_else (ScriptInstance *script)
ApiStatus si_handle_case_flag (ScriptInstance *script)
ApiStatus si_handle_case_multi_or_equal (ScriptInstance *script)
ApiStatus si_handle_case_multi_and_equal (ScriptInstance *script)
ApiStatus si_handle_end_case_multi (ScriptInstance *script)
ApiStatus si_handle_break_match (ScriptInstance *script)
ApiStatus si_handle_end_match (ScriptInstance *script)
ApiStatus si_handle_set_var (ScriptInstance *script)
ApiStatus si_handle_set_const (ScriptInstance *script)
ApiStatus si_handle_set_float (ScriptInstance *script)
ApiStatus si_handle_add (ScriptInstance *script)
ApiStatus si_handle_subtract (ScriptInstance *script)
ApiStatus si_handle_multiply (ScriptInstance *script)
ApiStatus si_handle_divide (ScriptInstance *script)
ApiStatus si_handle_mod (ScriptInstance *script)
ApiStatus si_handle_addF (ScriptInstance *script)
ApiStatus si_handle_subtractF (ScriptInstance *script)
ApiStatus si_handle_multiplyF (ScriptInstance *script)
ApiStatus si_handle_divideF (ScriptInstance *script)
ApiStatus si_handle_set_int_buffer_ptr (ScriptInstance *script)
ApiStatus si_handle_set_float_buffer_ptr (ScriptInstance *script)
ApiStatus si_handle_get_1_word (ScriptInstance *script)
ApiStatus si_handle_get_2_word (ScriptInstance *script)
ApiStatus si_handle_get_3_word (ScriptInstance *script)
ApiStatus si_handle_get_4_word (ScriptInstance *script)
ApiStatus si_handle_get_Nth_word (ScriptInstance *script)
ApiStatus si_handle_get_1_float (ScriptInstance *script)
ApiStatus si_handle_get_2_float (ScriptInstance *script)
ApiStatus si_handle_get_3_float (ScriptInstance *script)
ApiStatus si_handle_get_4_float (ScriptInstance *script)
ApiStatus si_handle_get_Nth_float (ScriptInstance *script)
ApiStatus si_handle_set_array (ScriptInstance *script)
ApiStatus si_handle_set_flag_array (ScriptInstance *script)
ApiStatus si_handle_allocate_array (ScriptInstance *script)
ApiStatus si_handle_AND (ScriptInstance *script)
ApiStatus si_handle_AND_const (ScriptInstance *script)
ApiStatus si_handle_OR (ScriptInstance *script)
ApiStatus si_handle_OR_const (ScriptInstance *script)
ApiStatus si_handle_call (ScriptInstance *script)
ApiStatus si_handle_spawn_script (ScriptInstance *script)
ApiStatus si_handle_spawn_script_get_id (ScriptInstance *script)
ApiStatus si_handle_await_script (ScriptInstance *script)
ApiStatus si_handle_jump (ScriptInstance *script)
s32 _bound_script_trigger_handler (Trigger *trigger)
ApiStatus si_handle_bind_trigger (ScriptInstance *script)
ApiStatus DeleteTrigger (ScriptInstance *script, s32 isInitialCall)
ApiStatus si_handle_unbind (ScriptInstance *script)
ApiStatus si_handle_kill_script (ScriptInstance *script)
ApiStatus si_handle_set_priority (ScriptInstance *script)
ApiStatus si_handle_set_timescale (ScriptInstance *script)
ApiStatus si_handle_set_group (ScriptInstance *script)
ApiStatus si_handle_suspend_all (ScriptInstance *script)
ApiStatus si_handle_resume_all (ScriptInstance *script)
ApiStatus si_handle_suspend_others (ScriptInstance *script)
ApiStatus si_handle_resume_others (ScriptInstance *script)
ApiStatus si_handle_suspend_script (ScriptInstance *script)
ApiStatus si_handle_resume_script (ScriptInstance *script)
ApiStatus si_handle_does_script_exist (ScriptInstance *script)
void si_standard_trigger_executor (Trigger *trigger)
ApiStatus si_handle_bind_lock (ScriptInstance *script)
s32 si_handle_spawn_thread (ScriptInstance *script, s32 isInitialCall)
ApiStatus si_handle_end_spawn_thread (ScriptInstance *script)
s32 si_handle_parallel_thread (ScriptInstance *script, s32 isInitialCall)
ApiStatus si_handle_end_parallel_thread (ScriptInstance *script)
ApiStatus func_802C6E14 (ScriptInstance *script)
s32 si_handle_print_debug_var (ScriptInstance *script, s32 isInitialCall)
ApiStatus func_802C739C (ScriptInstance *script)
ApiStatus func_802C73B0 (ScriptInstance *script)
s32 func_802C73B8 (ScriptInstance *script)
s32 si_execute_next_command ()
s32 get_variable (ScriptInstance *script, Bytecode var)
s32 get_variable_index_alt (s32 var)
s32 set_variable (ScriptInstance *script, Bytecode var, s32 value)
f32 get_float_variable (ScriptInstance *script, Bytecode var)
f32 set_float_variable (ScriptInstance *script, Bytecode var, f32 value)
Function Documentation
si_find_label()
Bytecode * si_find_label (ScriptInstance * script, s32 arg1)
Definition at line 1379 of file si.c.
Referenced by si_handle_goto().
si_skip_if()
Bytecode * si_skip_if (ScriptInstance * script)
Definition at line 1398 of file si.c.
Referenced by si_handle_if_equal(), si_handle_if_flag(), si_handle_if_greater(), si_handle_if_greater_equal(), si_handle_if_less(), si_handle_if_less_equal(), si_handle_if_not_equal(), and si_handle_if_not_flag().
si_skip_else()
Bytecode * si_skip_else (ScriptInstance * script)
Definition at line 1438 of file si.c.
Referenced by si_handle_else().
si_goto_end_case()
Bytecode * si_goto_end_case (ScriptInstance * script)
Definition at line 1474 of file si.c.
Referenced by si_handle_break_match(), si_handle_case_else(), si_handle_case_equal(), si_handle_case_flag(), si_handle_case_greater(), si_handle_case_greater_equal(), si_handle_case_less(), si_handle_case_less_equal(), si_handle_case_multi_and_equal(), si_handle_case_multi_or_equal(), si_handle_case_not_equal(), si_handle_case_range(), and si_handle_end_case_multi().
si_goto_next_case()
Bytecode * si_goto_next_case (ScriptInstance * script)
Definition at line 1476 of file si.c.
Referenced by si_handle_case_equal(), si_handle_case_flag(), si_handle_case_greater(), si_handle_case_greater_equal(), si_handle_case_less(), si_handle_case_less_equal(), si_handle_case_multi_and_equal(), si_handle_case_multi_or_equal(), si_handle_case_not_equal(), si_handle_case_range(), and si_handle_end_case_multi().
si_goto_end_loop()
Bytecode * si_goto_end_loop (ScriptInstance * script)
Definition at line 1478 of file si.c.
Referenced by si_handle_break_loop().
get_variable_index()
s32 get_variable_index (ScriptInstance * script, s32 var)
Definition at line 1239 of file si.c.
Referenced by AssignFlag(), DropItemEntityB(), MakeItemEntity(), si_handle_bind_lock(), and si_handle_bind_trigger().
fixed_var_to_float()
f32 fixed_var_to_float (Bytecode scriptVar)
Definition at line 11 of file si.c.
Referenced by get_float_variable(), and get_variable().
float_to_fixed_var()
Bytecode float_to_fixed_var (f32 value)
Definition at line 19 of file si.c.
si_handle_return()
ApiStatus si_handle_return (ScriptInstance * script)
Definition at line 23 of file si.c.
si_handle_label()
ApiStatus si_handle_label (ScriptInstance * script)
Definition at line 28 of file si.c.
si_handle_goto()
ApiStatus si_handle_goto (ScriptInstance * script)
Definition at line 32 of file si.c.
si_handle_loop()
ApiStatus si_handle_loop (ScriptInstance * script)
Definition at line 37 of file si.c.
si_handle_end_loop()
ApiStatus si_handle_end_loop (ScriptInstance * script)
Definition at line 50 of file si.c.
si_handle_break_loop()
ApiStatus si_handle_break_loop (ScriptInstance * script)
Definition at line 80 of file si.c.
si_handle_sleep_frames()
ApiStatus si_handle_sleep_frames (ScriptInstance * script)
Definition at line 87 of file si.c.
si_handle_sleep_seconds()
ApiStatus si_handle_sleep_seconds (ScriptInstance * script)
Definition at line 103 of file si.c.
si_handle_if_equal()
ApiStatus si_handle_if_equal (ScriptInstance * script)
Definition at line 119 of file si.c.
si_handle_if_not_equal()
ApiStatus si_handle_if_not_equal (ScriptInstance * script)
Definition at line 129 of file si.c.
si_handle_if_less()
ApiStatus si_handle_if_less (ScriptInstance * script)
Definition at line 139 of file si.c.
si_handle_if_greater()
ApiStatus si_handle_if_greater (ScriptInstance * script)
Definition at line 149 of file si.c.
si_handle_if_less_equal()
ApiStatus si_handle_if_less_equal (ScriptInstance * script)
Definition at line 159 of file si.c.
si_handle_if_greater_equal()
ApiStatus si_handle_if_greater_equal (ScriptInstance * script)
Definition at line 169 of file si.c.
si_handle_if_flag()
ApiStatus si_handle_if_flag (ScriptInstance * script)
Definition at line 179 of file si.c.
si_handle_if_not_flag()
ApiStatus si_handle_if_not_flag (ScriptInstance * script)
Definition at line 190 of file si.c.
si_handle_else()
ApiStatus si_handle_else (ScriptInstance * script)
Definition at line 201 of file si.c.
si_handle_end_if()
ApiStatus si_handle_end_if (ScriptInstance * script)
Definition at line 206 of file si.c.
si_handle_match()
ApiStatus si_handle_match (ScriptInstance * script)
Definition at line 210 of file si.c.
si_handle_match_const()
ApiStatus si_handle_match_const (ScriptInstance * script)
Definition at line 222 of file si.c.
si_handle_case_equal()
ApiStatus si_handle_case_equal (ScriptInstance * script)
Definition at line 234 of file si.c.
si_handle_case_not_equal()
ApiStatus si_handle_case_not_equal (ScriptInstance * script)
Definition at line 257 of file si.c.
si_handle_case_less()
ApiStatus si_handle_case_less (ScriptInstance * script)
Definition at line 280 of file si.c.
si_handle_case_less_equal()
ApiStatus si_handle_case_less_equal (ScriptInstance * script)
Definition at line 303 of file si.c.
si_handle_case_greater()
ApiStatus si_handle_case_greater (ScriptInstance * script)
Definition at line 326 of file si.c.
si_handle_case_greater_equal()
ApiStatus si_handle_case_greater_equal (ScriptInstance * script)
Definition at line 349 of file si.c.
si_handle_case_range()
ApiStatus si_handle_case_range (ScriptInstance * script)
Definition at line 372 of file si.c.
si_handle_case_else()
ApiStatus si_handle_case_else (ScriptInstance * script)
Definition at line 398 of file si.c.
si_handle_case_flag()
ApiStatus si_handle_case_flag (ScriptInstance * script)
Definition at line 413 of file si.c.
si_handle_case_multi_or_equal()
ApiStatus si_handle_case_multi_or_equal (ScriptInstance * script)
Definition at line 438 of file si.c.
si_handle_case_multi_and_equal()
ApiStatus si_handle_case_multi_and_equal (ScriptInstance * script)
Definition at line 463 of file si.c.
si_handle_end_case_multi()
ApiStatus si_handle_end_case_multi (ScriptInstance * script)
Definition at line 491 of file si.c.
si_handle_break_match()
ApiStatus si_handle_break_match (ScriptInstance * script)
Definition at line 508 of file si.c.
si_handle_end_match()
ApiStatus si_handle_end_match (ScriptInstance * script)
Definition at line 514 of file si.c.
si_handle_set_var()
ApiStatus si_handle_set_var (ScriptInstance * script)
Definition at line 525 of file si.c.
si_handle_set_const()
ApiStatus si_handle_set_const (ScriptInstance * script)
Definition at line 533 of file si.c.
si_handle_set_float()
ApiStatus si_handle_set_float (ScriptInstance * script)
Definition at line 538 of file si.c.
si_handle_add()
ApiStatus si_handle_add (ScriptInstance * script)
Definition at line 546 of file si.c.
si_handle_subtract()
ApiStatus si_handle_subtract (ScriptInstance * script)
Definition at line 558 of file si.c.
si_handle_multiply()
ApiStatus si_handle_multiply (ScriptInstance * script)
Definition at line 570 of file si.c.
si_handle_divide()
ApiStatus si_handle_divide (ScriptInstance * script)
Definition at line 582 of file si.c.
si_handle_mod()
ApiStatus si_handle_mod (ScriptInstance * script)
Definition at line 594 of file si.c.
si_handle_addF()
ApiStatus si_handle_addF (ScriptInstance * script)
Definition at line 606 of file si.c.
si_handle_subtractF()
ApiStatus si_handle_subtractF (ScriptInstance * script)
Definition at line 618 of file si.c.
si_handle_multiplyF()
ApiStatus si_handle_multiplyF (ScriptInstance * script)
Definition at line 630 of file si.c.
si_handle_divideF()
ApiStatus si_handle_divideF (ScriptInstance * script)
Definition at line 642 of file si.c.
si_handle_set_int_buffer_ptr()
ApiStatus si_handle_set_int_buffer_ptr (ScriptInstance * script)
Definition at line 654 of file si.c.
si_handle_set_float_buffer_ptr()
ApiStatus si_handle_set_float_buffer_ptr (ScriptInstance * script)
Definition at line 659 of file si.c.
si_handle_get_1_word()
ApiStatus si_handle_get_1_word (ScriptInstance * script)
Definition at line 664 of file si.c.
si_handle_get_2_word()
ApiStatus si_handle_get_2_word (ScriptInstance * script)
Definition at line 674 of file si.c.
si_handle_get_3_word()
ApiStatus si_handle_get_3_word (ScriptInstance * script)
Definition at line 688 of file si.c.
si_handle_get_4_word()
ApiStatus si_handle_get_4_word (ScriptInstance * script)
Definition at line 706 of file si.c.
si_handle_get_Nth_word()
ApiStatus si_handle_get_Nth_word (ScriptInstance * script)
Definition at line 728 of file si.c.
si_handle_get_1_float()
ApiStatus si_handle_get_1_float (ScriptInstance * script)
Definition at line 738 of file si.c.
si_handle_get_2_float()
ApiStatus si_handle_get_2_float (ScriptInstance * script)
Definition at line 748 of file si.c.
si_handle_get_3_float()
ApiStatus si_handle_get_3_float (ScriptInstance * script)
Definition at line 762 of file si.c.
si_handle_get_4_float()
ApiStatus si_handle_get_4_float (ScriptInstance * script)
Definition at line 780 of file si.c.
si_handle_get_Nth_float()
ApiStatus si_handle_get_Nth_float (ScriptInstance * script)
Definition at line 802 of file si.c.
si_handle_set_array()
ApiStatus si_handle_set_array (ScriptInstance * script)
Definition at line 812 of file si.c.
si_handle_set_flag_array()
ApiStatus si_handle_set_flag_array (ScriptInstance * script)
Definition at line 817 of file si.c.
si_handle_allocate_array()
ApiStatus si_handle_allocate_array (ScriptInstance * script)
Definition at line 822 of file si.c.
si_handle_AND()
ApiStatus si_handle_AND (ScriptInstance * script)
Definition at line 832 of file si.c.
si_handle_AND_const()
ApiStatus si_handle_AND_const (ScriptInstance * script)
Definition at line 841 of file si.c.
si_handle_OR()
ApiStatus si_handle_OR (ScriptInstance * script)
Definition at line 853 of file si.c.
si_handle_OR_const()
ApiStatus si_handle_OR_const (ScriptInstance * script)
Definition at line 862 of file si.c.
si_handle_call()
ApiStatus si_handle_call (ScriptInstance * script)
Definition at line 874 of file si.c.
si_handle_spawn_script()
ApiStatus si_handle_spawn_script (ScriptInstance * script)
Definition at line 897 of file si.c.
si_handle_spawn_script_get_id()
ApiStatus si_handle_spawn_script_get_id (ScriptInstance * script)
Definition at line 923 of file si.c.
si_handle_await_script()
ApiStatus si_handle_await_script (ScriptInstance * script)
Definition at line 951 of file si.c.
si_handle_jump()
ApiStatus si_handle_jump (ScriptInstance * script)
Definition at line 957 of file si.c.
_bound_script_trigger_handler()
s32 _bound_script_trigger_handler (Trigger * trigger)
Definition at line 963 of file si.c.
Referenced by bind_trigger(), and si_handle_bind_trigger().
si_handle_bind_trigger()
ApiStatus si_handle_bind_trigger (ScriptInstance * script)
Definition at line 990 of file si.c.
DeleteTrigger()
ApiStatus DeleteTrigger (ScriptInstance * script, s32 isInitialCall)
Definition at line 1022 of file si.c.
si_handle_unbind()
ApiStatus si_handle_unbind (ScriptInstance * script)
Definition at line 1027 of file si.c.
si_handle_kill_script()
ApiStatus si_handle_kill_script (ScriptInstance * script)
Definition at line 1032 of file si.c.
si_handle_set_priority()
ApiStatus si_handle_set_priority (ScriptInstance * script)
Definition at line 1037 of file si.c.
si_handle_set_timescale()
ApiStatus si_handle_set_timescale (ScriptInstance * script)
Definition at line 1042 of file si.c.
si_handle_set_group()
ApiStatus si_handle_set_group (ScriptInstance * script)
Definition at line 1047 of file si.c.
si_handle_suspend_all()
ApiStatus si_handle_suspend_all (ScriptInstance * script)
Definition at line 1052 of file si.c.
si_handle_resume_all()
ApiStatus si_handle_resume_all (ScriptInstance * script)
Definition at line 1057 of file si.c.
si_handle_suspend_others()
ApiStatus si_handle_suspend_others (ScriptInstance * script)
Definition at line 1062 of file si.c.
si_handle_resume_others()
ApiStatus si_handle_resume_others (ScriptInstance * script)
Definition at line 1067 of file si.c.
si_handle_suspend_script()
ApiStatus si_handle_suspend_script (ScriptInstance * script)
Definition at line 1072 of file si.c.
si_handle_resume_script()
ApiStatus si_handle_resume_script (ScriptInstance * script)
Definition at line 1077 of file si.c.
si_handle_does_script_exist()
ApiStatus si_handle_does_script_exist (ScriptInstance * script)
Definition at line 1082 of file si.c.
si_standard_trigger_executor()
void si_standard_trigger_executor (Trigger * trigger)
Definition at line 1091 of file si.c.
Referenced by si_handle_bind_lock().
si_handle_bind_lock()
ApiStatus si_handle_bind_lock (ScriptInstance * script)
Definition at line 1108 of file si.c.
si_handle_spawn_thread()
s32 si_handle_spawn_thread (ScriptInstance * script, s32 isInitialCall)
Definition at line 1138 of file si.c.
si_handle_end_spawn_thread()
ApiStatus si_handle_end_spawn_thread (ScriptInstance * script)
Definition at line 1140 of file si.c.
si_handle_parallel_thread()
s32 si_handle_parallel_thread (ScriptInstance * script, s32 isInitialCall)
Definition at line 1145 of file si.c.
si_handle_end_parallel_thread()
ApiStatus si_handle_end_parallel_thread (ScriptInstance * script)
Definition at line 1147 of file si.c.
func_802C6E14()
ApiStatus func_802C6E14 (ScriptInstance * script)
Definition at line 1152 of file si.c.
si_handle_print_debug_var()
s32 si_handle_print_debug_var (ScriptInstance * script, s32 isInitialCall)
Definition at line 1156 of file si.c.
func_802C739C()
ApiStatus func_802C739C (ScriptInstance * script)
Definition at line 1158 of file si.c.
func_802C73B0()
ApiStatus func_802C73B0 (ScriptInstance * script)
Definition at line 1163 of file si.c.
func_802C73B8()
s32 func_802C73B8 (ScriptInstance * script)
Definition at line 1167 of file si.c.
si_execute_next_command()
s32 si_execute_next_command ()
Definition at line 1178 of file si.c.
get_variable()
s32 get_variable (ScriptInstance * script, Bytecode var)
Definition at line 1182 of file si.c.
Referenced by ActorExists(), ActorSpeak(), AddActorPos(), AddActorVar(), AddAnimModelPosition(), AddBadge(), AddCoin(), AddGoalPos(), AddItem(), AddKeyItem(), AddPartDispOffset(), AddPartMovementVar(), AddStarPieces(), AddStarPoints(), AfflictActor(), ApplyShrinkFromOwner(), AwaitPlayerApproach(), AwaitPlayerLeave(), AwaitScriptComplete(), Bandit_DropCoin(), BindHandleEvent(), BindIdle(), BindNextTurn(), BindNpcAux(), BindNpcDefeat(), BindNpcHit(), BindNpcIdle(), BindNpcInteract(), BindTakeTurn(), Call800EB168(), ChangeModelAnimation(), CheckItemFlags40(), ClampAngleInt(), ClearAmbientSounds(), ClearPartnerMoveHistory(), ClearStatusEffects(), CloneModel(), CopyStatusEffects(), CountPlayerTargets(), DeleteNpc(), DeleteTrigger(), DemoPressButton(), DemoReleaseButton(), DemoSetButtons(), Disable8bitMario(), DisablePartner(), DisablePartnerAI(), DisablePlayerInput(), DisablePlayerPhysics(), DisablePulseStone(), DispatchDamageEvent(), DispatchEvent(), DropItemEntity(), DropItemEntityB(), EnableActorBlur(), EnableActorGlow(), EnableIdleScript(), EnableModel(), EnableNpcAI(), EnableNpcAux(), EnableNpcBlur(), EnableNpcShadow(), EnablePartner(), EnableSpriteShading(), EnableStatusMenu(), EnableTexPanning(), FadeInMusic(), FadeOutMusic(), FindItem(), FindKeyItem(), ForceHomePos(), func_8003F414(), func_8003F4CC(), func_80044238(), func_80045580(), func_80045798(), func_800457C4(), func_80045838(), func_80045900(), func_80218618_4FF068(), func_80240000_800880(), func_80240000_8C7F90(), func_80240044_8008C4(), func_802402BC_8D878C(), func_80240304_8D87D4(), func_802403B8_8AC348(), func_80240530_8AC4C0(), func_802405EC_7EB2FC(), func_80240A6C_8D482C(), func_80240BD8_8ACB68(), func_80241CC8_8D31D8(), func_80252B3C(), func_802535B4(), func_802536A8(), func_80253734(), func_80253B30(), func_8026919C(), func_802692EC(), func_80269550(), func_802695D4(), func_8026962C(), func_8026BF48(), func_8026D51C(), func_8026D5A4(), func_8026D8EC(), func_8026D940(), func_8026DA94(), func_8026DEF0(), func_8026DF88(), func_8026E16C(), func_8026F60C(), func_80276F1C(), func_8027CC10(), func_8027D2D8(), func_8027D32C(), func_8027D434(), func_8027D4C8(), func_8027D628(), func_8027D75C(), func_80281C20(), func_80282338(), func_80283BD0(), func_802BD100_3251D0(), func_802BD1AC_3251D0(), func_802BD26C(), func_802BD32C(), func_802BD388(), func_802BD458(), func_802C8EE4(), func_802C90FC(), func_802C91A4(), func_802C9428(), func_802C94A0(), func_802C971C(), func_802C9748(), func_802C9B40(), func_802C9C70(), func_802CA90C(), func_802CA988(), func_802CABE8(), func_802CACC0(), func_802CAE50(), func_802CB710(), func_802CCDAC(), func_802CCEDC(), func_802CD348(), func_802CD3C0(), func_802CD418(), func_802CDE68(), func_802CF1B4(), func_802CF208(), func_802CF56C(), func_802CFD30(), func_802CFE2C(), func_802CFE80(), func_802CFEEC(), func_802CFFC0(), func_802D0244(), func_802D0C94(), func_802D4CC4(), func_802D5830(), func_802D585C(), func_802D5EE0(), func_802D5F28(), func_802D5FA4(), func_802D5FF8(), func_802D6090(), func_802D617C(), func_802D62E4(), func_802D6340(), func_802D721C(), func_802D7520(), func_802D75D8(), func_802D7B10(), func_802D7B44(), func_802D7B74(), get_spirits_rescued(), GetActorFlags(), GetActorHP(), GetActorLevel(), GetActorPos(), GetActorRotation(), GetActorScale(), GetActorSize(), GetActorVar(), GetActorYaw(), GetAngleBetweenNPCs(), GetAngleToNPC(), GetAngleToPlayer(), GetAnimation(), GetAnimModelPosition(), GetCamDistance(), GetCamPitch(), GetCamPosA(), GetCamPosB(), GetCamPosC(), GetCamPosition(), GetCamType(), GetCamVfov(), GetColliderCenter(), GetCurrentActorType(), GetEnemyMaxHP(), GetEntityPosition(), GetEntryPos(), GetGoalPos(), GetHomePos(), GetIdleGoal(), GetIndexFromHome(), GetIndexFromPos(), GetItemName(), GetItemPower(), GetLastDamage(), GetLastEvent(), GetModelCenter(), GetModelIndex(), GetNpcAnimation(), GetNpcCollisionHeight(), GetNpcPointer(), GetNpcPos(), GetNpcVar(), GetNpcYaw(), GetOriginalActorType(), GetPartDispOffset(), GetPartEventFlags(), GetPartFlags(), GetPartMovementVar(), GetPartOffset(), GetPartPos(), GetPartRotation(), GetPartScale(), GetPartTarget(), GetPartTargetFlags(), GetPartYaw(), GetSelfAnimationFromTable(), GetSelfVar(), GetValueByRef(), HasKeyItem(), HidePlayerShadow(), HPBarToCurrent(), HPBarToHome(), InterpPlayerYaw(), IsPlayerWithin(), IsSaveVar123(), ItemAfflictEnemy(), ItemCheckHit(), ItemDamageEnemy(), load_map_bg(), LoadDemoBattle(), LoadModelAnimation(), LoadPath(), MakeItemEntity(), MakeLerp(), MakeNpcs(), MakeShopOwner(), MakeStatusField(), NpcSetHomePosToCurrent(), OverrideBattleDmaDest(), PanToTarget(), ParentColliderToModel(), PauseTakeTurn(), PlayAmbientSounds(), PlayerMoveTo(), PlayLoopingSoundAtActor(), PlayModelAnimation(), PlaySound(), PlaySoundAt(), PlaySoundAtActor(), PlaySoundAtCollider(), PlaySoundAtF(), PlaySoundAtModel(), PlaySoundAtNpc(), PlaySoundAtPart(), PlaySoundAtPlayer(), RandInt(), RemoveBadge(), RemoveEffect(), RemoveFortressKeys(), RemoveItem(), RemoveItemAt(), RemoveItemEntity(), RemoveKeyItemAt(), ResetAllActorSounds(), RestartNpcAI(), RestartNpcAux(), ResumeTakeTurn(), RotateModel(), ScaleModel(), SetActionSuccess(), SetActorDispOffset(), SetActorFlagBits(), SetActorFlags(), SetActorIdleJumpGravity(), SetActorIdleSpeed(), SetActorJumpGravity(), SetActorPos(), SetActorRotation(), SetActorRotationOffset(), SetActorScale(), SetActorScaleModifier(), SetActorSize(), SetActorSpeed(), SetActorVar(), SetActorYaw(), SetAnimation(), SetAnimationRate(), SetAnimModelPosition(), SetAnimModelRotation(), SetAnimModelScale(), SetBattleFlagBits(), SetBattleFlagBits2(), SetBattleMusic(), SetCamBGColor(), SetCamDistance(), SetCamEnabled(), SetCamFlag80(), SetCamLeadPlayer(), SetCamPerspective(), SetCamPitch(), SetCamPosA(), SetCamPosB(), SetCamPosC(), SetCamSpeed(), SetCamTarget(), SetCamType(), SetCamVfov(), SetCamViewport(), SetDefenseTable(), SetEncounterStatusFlags(), SetEnemyFlagBits(), SetEnemyHP(), SetEnemyTargetOffset(), SetEntityPosition(), SetForegroundModelsVisible(), SetForegroundModelsVisibleUnsafe(), SetGameMode(), SetGoalPos(), SetGoalToFirstTarget(), SetGoalToHome(), SetGoalToTarget(), SetGroupEnabled(), SetHomePos(), SetIdleAnimations(), SetIdleGoal(), SetIdleGoalToHome(), SetItemFlags(), SetItemPos(), SetJumpAnimations(), SetManyVars(), SetMessageString(), SetMessageValue(), SetModelFlag10(), SetModelFlags(), SetMusicTrack(), SetNpcAnimation(), SetNpcAnimationSpeed(), SetNpcCollisionSize(), SetNpcEffect(), SetNpcFlagBits(), SetNpcJumpscale(), SetNpcPos(), SetNpcRotation(), SetNpcScale(), SetNpcSpeed(), SetNpcVar(), SetNpcYaw(), SetOwnerID(), SetPanTarget(), SetPartDispOffset(), SetPartEventBits(), SetPartEventFlags(), SetPartFlagBits(), SetPartFlags(), SetPartGoalToTarget(), SetPartJumpGravity(), SetPartMovementVar(), SetPartMoveSpeed(), SetPartPos(), SetPartRotation(), SetPartRotationOffset(), SetPartScale(), SetPartTargetFlagBits(), SetPartTargetFlags(), SetPartYaw(), SetPlayerActionState(), SetPlayerAnimation(), SetPlayerCollisionSize(), SetPlayerFlagBits(), SetPlayerPos(), SetRenderMode(), SetSelfEnemyFlagBits(), SetSelfRotation(), SetSelfVar(), SetStatusTable(), SetTargetActor(), SetTargetOffset(), SetTattleString(), SetTexPanner(), SetTexPanOffset(), SetValueByRef(), ShowBattleChoice(), ShowCoinCounter(), ShowGotItem(), ShowShockEffect(), ShowStatusMenu(), si_handle_add(), si_handle_allocate_array(), si_handle_AND(), si_handle_AND_const(), si_handle_await_script(), si_handle_bind_lock(), si_handle_bind_trigger(), si_handle_call(), si_handle_case_equal(), si_handle_case_greater(), si_handle_case_greater_equal(), si_handle_case_less(), si_handle_case_less_equal(), si_handle_case_multi_and_equal(), si_handle_case_multi_or_equal(), si_handle_case_not_equal(), si_handle_case_range(), si_handle_divide(), si_handle_does_script_exist(), si_handle_end_loop(), si_handle_get_Nth_float(), si_handle_get_Nth_word(), si_handle_goto(), si_handle_if_equal(), si_handle_if_flag(), si_handle_if_greater(), si_handle_if_greater_equal(), si_handle_if_less(), si_handle_if_less_equal(), si_handle_if_not_equal(), si_handle_if_not_flag(), si_handle_jump(), si_handle_kill_script(), si_handle_match(), si_handle_mod(), si_handle_multiply(), si_handle_OR(), si_handle_OR_const(), si_handle_resume_all(), si_handle_resume_others(), si_handle_resume_script(), si_handle_set_array(), si_handle_set_flag_array(), si_handle_set_float_buffer_ptr(), si_handle_set_group(), si_handle_set_int_buffer_ptr(), si_handle_set_priority(), si_handle_set_var(), si_handle_sleep_frames(), si_handle_spawn_script(), si_handle_spawn_script_get_id(), si_handle_subtract(), si_handle_suspend_all(), si_handle_suspend_others(), si_handle_suspend_script(), SomeMatrixOperation2(), SomeXYZFuncTodoRename(), Spawn802D9D50(), StartBattleWith(), StartRumble(), StartRumbleWithParams(), StopLoopingSoundAtActor(), StopSound(), SwitchMessage(), TranslateModel(), UnkBattleFunc1(), UnkBattleFunc2(), UnkBattleFunc2_2(), UnkCameraFunc(), UnkFloatFunc(), UnkMusicFunc(), UnkPositionFunc(), UnkYawFunc(), UpdateColliderTransform(), UseDoorSounds(), WaitForCam(), and WasStatusInflicted().
get_variable_index_alt()
s32 get_variable_index_alt (s32 var)
Definition at line 1282 of file si.c.
set_variable()
s32 set_variable (ScriptInstance * script, Bytecode var, s32 value)
Definition at line 1325 of file si.c.
Referenced by ActorExists(), AddBadge(), AddItem(), ApplyShrinkFromOwner(), CheckActionState(), CheckButtonDown(), CheckButtonHeld(), CheckButtonPress(), ClampAngleInt(), CountFortressKeys(), CountPlayerTargets(), exec_ShakeCamX(), FindItem(), FindKeyItem(), func_80035E54(), func_800441F0(), func_800445A8(), func_800445D4(), func_8004580C(), func_800458CC(), func_80240000_9A4650(), func_80240044_8008C4(), func_80241CC8_8D31D8(), func_80252B3C(), func_802537C0(), func_80253B30(), func_80269318(), func_80269524(), func_802695A8(), func_80269600(), func_80269E80(), func_8026DEF0(), func_8026DF88(), func_8027D75C(), func_802C9B40(), func_802CA988(), func_802D249C(), func_802D6AF0(), GetActionSuccess(), GetActionSuccessCopy(), GetActorFlags(), GetActorHP(), GetActorLevel(), GetActorPos(), GetActorRotation(), GetActorSize(), GetActorVar(), GetActorYaw(), GetAngleBetweenNPCs(), GetAngleToNPC(), GetAngleToPlayer(), GetAnimation(), GetAttackerActorID(), GetBattleFlags(), GetBattleFlags2(), GetBattleOutcome(), GetBattlePhase(), GetBattleState(), GetBlockResult(), GetCamType(), GetCamVfov(), GetCurrentActorType(), GetCurrentPartner(), GetCurrentPartnerID(), GetDemoState(), GetEncounterEnemyIsOwner(), GetEncounterState(), GetEnemyMaxHP(), GetEntityPosition(), GetEntryID(), GetEntryPos(), GetFrameCounter(), GetGameStatus75(), GetGoalPos(), GetHomePos(), GetIdleGoal(), GetIndexFromHome(), GetIndexFromPos(), GetItemName(), GetItemPower(), GetLastDamage(), GetLastElement(), GetLastEvent(), GetLoadType(), GetMapID(), GetModelIndex(), GetNpcAnimation(), GetNpcCollisionHeight(), GetNpcPointer(), GetNpcPos(), GetNpcVar(), GetNpcYaw(), GetOriginalActorType(), GetOwnerEncounterTrigger(), GetOwnerID(), GetPartDispOffset(), GetPartEventFlags(), GetPartFlags(), GetPartMovementVar(), GetPartnerCall800EB168(), GetPartnerPos(), GetPartOffset(), GetPartPos(), GetPartTarget(), GetPartTargetFlags(), GetPartYaw(), GetPlayerActionState(), GetPlayerAnimation(), GetPlayerHP(), GetPlayerPos(), GetPlayerTargetYaw(), GetSelectedMoveID(), GetSelfAnimationFromTable(), GetSelfNpcID(), GetSelfVar(), GetTargetListLength(), GetValueByRef(), HasKeyItem(), IsMessageBoxDisplayed(), IsPlayerWithin(), ItemAfflictEnemy(), ItemCheckHit(), ItemDamageEnemy(), MakeStatusField(), PartnerCanUseAbility(), PartnerIsFlying(), RandInt(), RemoveItem(), SetValueByRef(), si_handle_add(), si_handle_allocate_array(), si_handle_AND(), si_handle_AND_const(), si_handle_bind_trigger(), si_handle_divide(), si_handle_does_script_exist(), si_handle_end_loop(), si_handle_get_1_word(), si_handle_get_2_word(), si_handle_get_3_word(), si_handle_get_4_word(), si_handle_get_Nth_word(), si_handle_mod(), si_handle_multiply(), si_handle_OR(), si_handle_OR_const(), si_handle_set_const(), si_handle_set_var(), si_handle_spawn_script_get_id(), si_handle_subtract(), SomeXYZFuncTodoRename(), UnkCameraFunc(), UnkFloatFunc(), UnkYawFunc(), and WasStatusInflicted().
get_float_variable()
f32 get_float_variable (ScriptInstance * script, Bytecode var)
Definition at line 1329 of file si.c.
Referenced by AddActorPos(), AddAnimModelPosition(), AddGoalPos(), AddPartDispOffset(), AddVectorPolar(), CheckActionState(), ClampAngleFloat(), DemoJoystickRadial(), DemoJoystickXY(), func_80282594(), func_802CD348(), func_802CDE68(), func_802D4D14(), func_802D7520(), func_802D75D8(), GetDist2D(), InterpPlayerYaw(), MultiplyByActorScale(), MultiplyVec2ByActorScale(), MultiplyVec3yActorScale(), PanToTarget(), PlaySoundAtF(), RotateModel(), ScaleModel(), SetActorDispOffset(), SetActorIdleJumpGravity(), SetActorIdleSpeed(), SetActorJumpGravity(), SetActorRotation(), SetActorRotationOffset(), SetActorScale(), SetActorScaleModifier(), SetActorSpeed(), SetAnimationRate(), SetAnimModelPosition(), SetAnimModelRotation(), SetAnimModelScale(), SetCamDistance(), SetCamPerspective(), SetCamPitch(), SetCamPosA(), SetCamPosB(), SetCamPosC(), SetCamSpeed(), SetCamVfov(), SetNpcAnimationSpeed(), SetNpcJumpscale(), SetNpcRotation(), SetNpcScale(), SetNpcSpeed(), SetPanTarget(), SetPartDispOffset(), SetPartJumpGravity(), SetPartMoveSpeed(), SetPartRotation(), SetPartRotationOffset(), SetPartScale(), SetPlayerAnimationSpeed(), SetPlayerJumpscale(), SetPlayerSpeed(), si_handle_addF(), si_handle_divideF(), si_handle_get_1_float(), si_handle_get_2_float(), si_handle_get_3_float(), si_handle_get_4_float(), si_handle_multiplyF(), si_handle_set_float(), si_handle_set_timescale(), si_handle_sleep_seconds(), si_handle_subtractF(), SomeMatrixOperation2(), SomeXYZFunc2(), TranslateModel(), UnkFloatFunc(), UnkMovePartner(), and WaitForCam().
set_float_variable()
f32 set_float_variable (ScriptInstance * script, Bytecode var, f32 value)
Definition at line 1377 of file si.c.
Referenced by AddVectorPolar(), ClampAngleFloat(), exec_ShakeCamX(), GetActorScale(), GetAnimModelPosition(), GetCamDistance(), GetCamPitch(), GetCamPosA(), GetCamPosB(), GetCamPosC(), GetCamPosition(), GetDist2D(), GetPartRotation(), GetPartScale(), MultiplyByActorScale(), MultiplyVec2ByActorScale(), MultiplyVec3yActorScale(), si_handle_addF(), si_handle_divideF(), si_handle_get_1_float(), si_handle_get_2_float(), si_handle_get_3_float(), si_handle_get_4_float(), si_handle_get_Nth_float(), si_handle_multiplyF(), si_handle_set_float(), si_handle_subtractF(), SomeXYZFunc2(), and UnkFloatFunc().