EffectBlueprint Struct Reference - Paper Mario Documentation
EffectBlueprint Struct Reference
Data Fields
s32 unk_00
s32 effectIndex
void(* init)(EffectInstance *effectInst)
void(* update)(EffectInstance *effectInst)
void(* renderWorld)(EffectInstance *effectInst)
void(* unk_14)(EffectInstance *effectInst)
Detailed Description
Definition at line 790 of file common_structs.h.
Field Documentation
unk_00
s32 EffectBlueprint::unk_00
Definition at line 791 of file common_structs.h.
effectIndex
s32 EffectBlueprint::effectIndex
Definition at line 792 of file common_structs.h.
Referenced by func_8005A2BC().
init
void(* EffectBlueprint::init) (EffectInstance *effectInst)
Definition at line 793 of file common_structs.h.
Referenced by func_8005A2BC().
update
void(* EffectBlueprint::update) (EffectInstance *effectInst)
Definition at line 794 of file common_structs.h.
Referenced by func_8005A2BC().
renderWorld
void(* EffectBlueprint::renderWorld) (EffectInstance *effectInst)
Definition at line 795 of file common_structs.h.
Referenced by func_8005A2BC().
unk_14
void(* EffectBlueprint::unk_14) (EffectInstance *effectInst)
Definition at line 796 of file common_structs.h.
Referenced by func_8005A2BC().
The documentation for this struct was generated from the following file:
include/common_structs.h