Effect Struct Reference - Paper Mario Documentation
Effect Struct Reference
Data Fields
s32 flags
s32 effectIndex
s32 instanceCounter
s32 unk_0C
void(* update)(EffectInstance *effectInst)
void(* renderWorld)(EffectInstance *effectInst)
void(* unk_18)(EffectInstance *effectInst)
void * unk_1C
Detailed Description
Definition at line 799 of file common_structs.h.
Field Documentation
flags
s32 Effect::flags
Definition at line 800 of file common_structs.h.
Referenced by func_8005A2BC(), and play_effect().
effectIndex
s32 Effect::effectIndex
Definition at line 801 of file common_structs.h.
Referenced by func_8005A2BC(), and play_effect().
instanceCounter
s32 Effect::instanceCounter
Definition at line 802 of file common_structs.h.
Referenced by func_8005A2BC(), and play_effect().
unk_0C
s32 Effect::unk_0C
Definition at line 803 of file common_structs.h.
update
void(* Effect::update) (EffectInstance *effectInst)
Definition at line 804 of file common_structs.h.
Referenced by func_8005A2BC().
renderWorld
void(* Effect::renderWorld) (EffectInstance *effectInst)
Definition at line 805 of file common_structs.h.
Referenced by func_8005A2BC(), and render_effects().
unk_18
void(* Effect::unk_18) (EffectInstance *effectInst)
Definition at line 806 of file common_structs.h.
Referenced by func_8005A2BC().
unk_1C
void* Effect::unk_1C
Definition at line 807 of file common_structs.h.
Referenced by play_effect().
The documentation for this struct was generated from the following file:
include/common_structs.h