src/world/world.c File Reference - Paper Mario Documentation
world.c File Reference
Macros
#define AREA(area, jp_name) { ARRAY_COUNT(area##_maps), area##_maps, "area_" #area, jp_name }
#define MAP(map)
#define MAP_UNSPLIT(map, configVRAM)
Functions
void load_world_script_api (void)
s32 load_map_by_IDs ()
s32 get_current_map_config ()
MapConfig * get_current_map_header ()
s32 get_map_IDs_by_name ()
void * load_asset_by_name (char *name, s32 *decompressedSize)
s32 get_asset_offset ()
Variables
static const s32 rodata_73DA0 []
static const char D_80098A10 [] = "%s_shape"
static const char D_80098A1C [] = "%s_hit"
static const char D_80098A24 [] = "%s_tex"
static Map mac_maps []
Toad Town.
static Map tik_maps []
Toad Town Tunnels.
static Map kgr_maps []
Inside the Whale.
MapConfig kmr_12_config
Goomba Region.
static Map kmr_maps []
static Map iwa_maps []
Mt. Rugged.
static Map dro_maps []
Dry Dry Outpost.
static Map sbk_maps []
Dry Dry Desert.
static Map isk_maps []
Dry Dry Ruins.
static Map trd_maps []
Koopa Bros. Fortress.
static Map nok_maps []
Koopa Region.
static Map hos_maps []
Star Region.
static Map kpa_maps []
Bowser's Castle.
static Map osr_maps []
Peach's Castle Grounds.
static Map kkj_maps []
static Map jan_maps []
Jade Jungle.
static Map mim_maps []
Forever Forest.
static Map obk_maps []
Boo's Mansion.
static Map arn_maps []
Gusty Gulch.
static Map dgb_maps []
Tubba Blubba's Castle.
static Map kzn_maps []
Mt. Lavalava.
static Map flo_maps []
Flower Fields.
static Map sam_maps []
Shiver Region.
static Map pra_maps []
Crystal Palace.
static Map omo_maps []
Shy Guy's Toy Box.
static Map tst_maps []
Debug.
static Map end_maps []
Credits.
static Map mgm_maps []
Toad Town Playroom.
static Map gv_maps []
Game Over.
Area gAreas []
Macro Definition Documentation
AREA
#define AREA (area, jp_name) { ARRAY_COUNT(area##_maps), area##_maps, "area_" #area, jp_name }
Definition at line 37 of file world.c.
MAP
#define MAP (map)
Definition at line 39 of file world.c.
MAP_UNSPLIT
#define MAP_UNSPLIT (map, configVRAM)
Definition at line 47 of file world.c.
Function Documentation
load_world_script_api()
void load_world_script_api (void)
Definition at line 5 of file world.c.
load_map_by_IDs()
s32 load_map_by_IDs ()
Definition at line 25 of file world.c.
get_current_map_config()
s32 get_current_map_config ()
Definition at line 27 of file world.c.
get_current_map_header()
MapConfig* get_current_map_header (void)
Definition at line 29 of file world.c.
Referenced by func_802E8BC0(), and GetEntryPos().
get_map_IDs_by_name()
s32 get_map_IDs_by_name ()
Definition at line 31 of file world.c.
load_asset_by_name()
void* load_asset_by_name (char * name, s32 * decompressedSize)
Definition at line 33 of file world.c.
Referenced by load_map_bg().
get_asset_offset()
s32 get_asset_offset ()
Definition at line 35 of file world.c.
Variable Documentation
rodata_73DA0
const s32 rodata_73DA0[] static
Definition at line 10 of file world.c.
D_80098A10
const char D_80098A10[] = "%s_shape" static
Definition at line 21 of file world.c.
D_80098A1C
const char D_80098A1C[] = "%s_hit" static
Definition at line 22 of file world.c.
D_80098A24
const char D_80098A24[] = "%s_tex" static
Definition at line 23 of file world.c.
mac_maps
Map mac_maps[] static
Toad Town.
Definition at line 55 of file world.c.
tik_maps
Map tik_maps[] static
Toad Town Tunnels.
Definition at line 67 of file world.c.
kgr_maps
Map kgr_maps[] static
Inside the Whale.
Definition at line 93 of file world.c.
kmr_12_config
MapConfig kmr_12_config
Goomba Region.
Definition at line 99 of file world.c.
kmr_maps
Map kmr_maps[] static
Definition at line 100 of file world.c.
iwa_maps
Map iwa_maps[] static
Mt. Rugged.
Definition at line 121 of file world.c.
dro_maps
Map dro_maps[] static
Dry Dry Outpost.
Definition at line 132 of file world.c.
sbk_maps
Map sbk_maps[] static
Dry Dry Desert.
Definition at line 138 of file world.c.
isk_maps
Map isk_maps[] static
Dry Dry Ruins.
Definition at line 192 of file world.c.
trd_maps
Map trd_maps[] static
Koopa Bros. Fortress.
Definition at line 213 of file world.c.
nok_maps
Map nok_maps[] static
Koopa Region.
Definition at line 228 of file world.c.
hos_maps
Map hos_maps[] static
Star Region.
Definition at line 241 of file world.c.
kpa_maps
Map kpa_maps[] static
Bowser's Castle.
Definition at line 254 of file world.c.
osr_maps
Map osr_maps[] static
Peach's Castle Grounds.
Definition at line 308 of file world.c.
kkj_maps
Map kkj_maps[] static
Peach's Castle
Bug:
There are two entries for kkj_26; the latter is unreachable.
Definition at line 318 of file world.c.
jan_maps
Map jan_maps[] static
Jade Jungle.
Definition at line 347 of file world.c.
mim_maps
Map mim_maps[] static
Forever Forest.
Definition at line 373 of file world.c.
obk_maps
Map obk_maps[] static
Boo's Mansion.
Definition at line 389 of file world.c.
arn_maps
Map arn_maps[] static
Gusty Gulch.
Definition at line 402 of file world.c.
dgb_maps
Map dgb_maps[] static
Tubba Blubba's Castle.
Definition at line 417 of file world.c.
kzn_maps
Map kzn_maps[] static
Mt. Lavalava.
Definition at line 440 of file world.c.
flo_maps
Map flo_maps[] static
Flower Fields.
Definition at line 461 of file world.c.
sam_maps
Map sam_maps[] static
Shiver Region.
Definition at line 485 of file world.c.
pra_maps
Map pra_maps[] static
Crystal Palace.
Definition at line 501 of file world.c.
omo_maps
Map omo_maps[] static
Shy Guy's Toy Box.
Definition at line 537 of file world.c.
tst_maps
Map tst_maps[] static
Debug.
Definition at line 558 of file world.c.
end_maps
Map end_maps[] static
Credits.
Definition at line 571 of file world.c.
mgm_maps
Map mgm_maps[] static
Toad Town Playroom.
Definition at line 577 of file world.c.
gv_maps
Map gv_maps[] static
Game Over.
Definition at line 585 of file world.c.
gAreas
Area gAreas[]
Definition at line 589 of file world.c.
Referenced by get_song_variation_override_for_cur_map().